### ISSUE TITLE
[Urgent] features needed to not get banned.

### ISSUE THREAD

**Issue by daproject85** [NoxxDev/NecroBot#100]
hey, to all the devs thanks for your work. A few features that i have been seeing that other bots (which basically bit off of necro, ) utlize and users are saying they are not getting banned. 

- BIgger speed variant
- Walking in streets (humanized walking)
- Max pokemon catch limit (this bans you for sure)
- max pokestop limit (this also bans you for sure)

**Comment by EricFaler** [comment]
With current 0.9.0 setup it took me 25 hours to be banned.
So something still needs to be changed, or we need to only bot in 9 hour timeslots.

(just a warning in case anyone else is continuously botting)

**Comment by daproject85** [comment]
1) Always moving in a straight line (no matter the pathing), no GPS fuckery **We need to fix this to go through streets, other bots are doing this**
2) Going in a straight line between stops. **this will get you banned, i was banned with no snipping moving at 15km and 6 seconds dealys, they detect this**
4) Constant running, no breaks. **mustbe implemented**
5) Inhuman xp/hr. **someone needs to bench mark this**
6) Constant speed with no fluctuations. **we have this, maybe a bigger variance**
7) Constant altitude. **this will fuck us in the ass if we dont fix it**
8) Constant excellent curve-balls. **not sure if this is implemented** 

@Na1w @NoxxDev @Chaaaaaaaaarlie @magicparty

**Comment by JoNMii** [comment]
It isnt problem. The problem is what is sending to niantic. A lot of harcoded data. ATM only connecting with the bot is a posibble permaban.

**Comment by Chaaaaaaaaarlie** [comment]
The hell?
Why did I get mentioned? :o 
I'm not a dev, just someone who knows how to read :x

**Comment by daproject85** [comment]
trying to grab attention and create community brah @Chaaaaaaaaarlie idk who works on this

**Comment by Chaaaaaaaaarlie** [comment]
Well ain't got no problem with this xD
I'm just here from time to time to help with easy to solve by reading issues :p

**Comment by gysi** [comment]
Going on streets isnt necessary, just adding some variance and not going a
perfect straight line will be enough

**Comment by daproject85** [comment]
who will do it ?

**Comment by PoppaCoder** [comment]
There's no freaking way in hell they're going to calculate how straight or not you're walking, that would take google's computing power to scale to all users, just think about all the math involved and cpu time., So I don't think that's needed, it's a cool feature but it's certainly not needed.
I've been running bots for days now but only below 5km/h

**Comment by daproject85** [comment]
@PoppaCoder you do realize they are owned by google? also coming from someone who has 4 friends that are devs at google and compaines google has aquired, accessing technology like that isn't a problem for them. Spinning up server to calculate things is nothing for google

**Comment by daproject85** [comment]
also @PoppaCoder, maybe you should brush up on annomaly and abnormality detection software. Dying companies like Hewlett Packard have them. You set a threshold or a baseline for anything and you see what falls out of that. So if a dead company like HP can develop that, you think it takes much for google to have it and spin up servers to do it? They run the internet, you really think compute power to mine data from a game is anything to them? You also do realize they actually already have this data

**Comment by PoppaCoder** [comment]
@daproject85 More questions?

**Comment by EricFaler** [comment]
They definitely use actions per seconds to calculate, so just dont log on
to your account from your phone while youre botting, gps on or not

**Comment by DmitrySilchenko** [comment]
i think the only way to use bot and avoid permabans is to make bot send all the same data like real application.... to be as close during all time of botting to what real app data looks like. the timings, the probability of perfect ball throw, speeds, pauses in movement, maximum variations in everything that has a number: intervals between actions (like from 5 to 15 seconds, RANDOM every time, random every action), item limits RANDOM, sometimes throw stuff at 16 items, sometimes at 21, sometimes at 7,  not always "120 potions limit" and 100 pokeballs limit, like freakin math application :D

**Comment by DmitrySilchenko** [comment]
it has to be max random in aaaalll what can be randomized.  only seeing a value of "120 pokeballs" exactly rotating up to 120 again and again for me if i would be their developer = 100% i caught a bot. so their algorithms will not try hard to calculate your walking paths and speeds much (btw some guys from my job catch pokemons while driving on a bug from work home, and do it DAILY since game came out, nobody was banned. and THE BUS is a pattern of SAME ROUTE every day, but they're not getting banned not for the movement speed which i guess is at around 50-60kmph avg, and not for capturing plenty pokemon on their way :) . why? because their ALL OTHER patterns are human... the random walks here and there, req\responses frequency with the servers, random actions, random item amounts)

**Comment by DmitrySilchenko** [comment]
also many of them never turn off the application at all, so it moves with them 24/7 all around.  but they go to sleep so the app "stants still" sometimes for all night, it adds to the "human proof" for niantic algorithms

**Comment by DmitrySilchenko** [comment]
i think we should record daily actions of regular player through MITM proxy, and try to replicate very similar behavior with the bot

**Comment by DmitrySilchenko** [comment]
also constant speed during all day of bot activity is obviously a flag for ban i think.. this needs to be randomized urgently

**Comment by daproject85** [comment]
@DmitrySilchenko i agree 100%

**Comment by gysi** [comment]
You won't get banned by things a human can do. And this will NEVER change.

So limiting pokeballs at 120 for example is completely fine

**Comment by DmitrySilchenko** [comment]
@gysi  but a human will never watch his exact number of pokeballs every second to be sure it never reaches 120+ to recycle them...

**Comment by DmitrySilchenko** [comment]
its ok but don't have to be a CONSTANT for the lifetime of account. coz its suspicious.

**Comment by daproject85** [comment]
i mean are any devs controbuting to this? or is @NoxxDev only person?

**Comment by EricFaler** [comment]
"Just another quick update, we have discovered that users utilizing MITM
techniques may be getting flagged by Niantic servers. Please note read-only
MITM is not affected by this flagging. We've confirmed this to the best of
our joint abilities"

https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

back when pogo api was updated

**Comment by NoxxDev** [comment]
Features added
