### ISSUE TITLE
Looking for incense Pokemon...

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#105]
Hi!

I find these lines constantly in the logs.

```
Looking for Pokemon...
Looking for incense Pokemon...
```

As far as I know incense Pokemon are only spawned for the player using incense.
Can we check if incense is active and only then look 30 minutes for pokemon in the surrounding area? This would half these requests the to the servers.

**Comment by ausscheider** [comment]
The same by me
