### ISSUE TITLE
[Request] Set an option for the bot to miss pokeball throw.

### ISSUE THREAD

**Issue by carlos0202** [NoxxDev/NecroBot#108]
It would be great if we add more and more logic to the bot to avoid the ban hammer radar. One could be to make it miss pokeball throws under random conditions. It's weird if you have never missed a single pokeball over 1000 throws. Thanks in advance for your help.

**Comment by Tokariew** [comment]
you have options
  "EnableMissedThrows": false,
  "ThrowMissPercentage": 25,

change to true, and to desire miss chance in %

**Comment by carlos0202** [comment]
ok, thanks.My bad. The only missed otpion is now to stop Jesus mode of the bot. Because he walks over the water. Something must be done to make the bot follow roads.

**Comment by carlos0202** [comment]
And also an option to allow the bot stop when he founds more than 2 pokestops close each other and all of them with lures. to Stay there for a while walking and catching pokemons. Like a human.
