### ISSUE TITLE
TransferDuplicatePokemonOnCapture doesn't respect DelayBetweenPlayerActions

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#111]
### Expected Behavior
Wait the value specified in DelayBetweenPlayerActions before transfering duplicate Pokemon.

### Actual Behavior
```
[01:23:22] (CatchSuccess) | (Normal) Paras Lvl: 19 CP: (453/497) IV: 63.00% [..]
[01:23:24] Paras	- CP: 453  IV: 63.02%   [Best CP: 279  IV: 87.75%] (Candies: 130)
```

### Your config.json
```
  "DelayBetweenPlayerActions": 29264,
  "TransferDuplicatePokemonOnCapture": true,
```

### Other Information
Version: 0.9.0
Windows Version: 8.1 64bit
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
catch, transfer, waiting time

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the repository owner and I feel like I'm wasting my time, is not worth my effort if my commits are not being pushed. I'll be making a discord channel today for that new repo I forked and got some devs coming over to help me there.

I will compile a new version in about 3 hours, this will be one of the changes. Necro 0.9.1

Please and thanks.
