### ISSUE TITLE
[Request] random location at 1st start bot

### ISSUE THREAD

**Issue by gxa12di43yr56** [NoxxDev/NecroBot#116]
something like this..

 "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }

then bot will random choose location what we set at 1st start.. so didnt need change location every time

**Comment by plgonzalezrx8** [comment]
This is dangerous and most likely will get you banned pretty fast.

**Comment by gxa12di43yr56** [comment]
why is it dangerous ? you need to know border between location.. not like one location in the United States and one location in mexico.. maybe 2nd location just  5km/10km/20km far from 1st location... btw ppl always moving.. not just catching on one spot

maybe a option for those who want to use something like this . this good for who using rotation script for bot

**Comment by plgonzalezrx8** [comment]
My reply was based on the locations you put, they are very far apart.

Also, If you are using a rotation script, you can make a main folder, then create several instances of the necrobot for the same account with different locations (and different settings overall) and rotate between them, there are tools out already to do that compatible with necrobot. 

I will be hard to implement safely, unless another hardcore coder wants to work on this, not me.

Lets say you have different locations, 5km, 10km, 20km, 30km from the initial point, and the scripts randomly goes from the 1st, to the last one, that is 30km traveled instantly and it can get you banned, or if the script crashes, the way it currently handles error, can teleport you to an unwanted location instantly and will get you banned. I'll rather not deal with the aftermath of a bug with that feature.

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the repository owner and I feel like I'm wasting my time, is not worth my effort if my commits are not being pushed. I'll be making a discord channel today for that new repo I forked and got some devs coming over to help me there.

I will compile a new version in about 3 hours, . Necro 0.9.1

I will implement a form of this allowing the user to customize it to the likings, but will stay within the close area.

**Comment by smoothrunnings** [comment]
I think what also might work is taking the "LAST" coordinates and using them as the starting point. Worse case adding a degree to them, or making some lock that randomly changes the values keeping it in the same area; letting people decide what that area range is. So think of this way, using the last coords and randomly adding a degree or two within a 2km radius. Both options could added to the config so the farmer can adjust them to their liking.
