### ISSUE TITLE
 create perma ban tool or code

### ISSUE THREAD

**Issue by luigidanield2** [NoxxDev/NecroBot#117]
can we create a tool or code for remove a permaban in necrobot? is a good idea maybe..... thanks

**Comment by plgonzalezrx8** [comment]
This is not possible since the ban is server side.

**Comment by luigidanield2** [comment]
ci sarà una falla sul server loro!??basta trovarla ed entrarci dentro.....

**Comment by luigidanield2** [comment]
is there a bug in your server no????

**Comment by plgonzalezrx8** [comment]
Huh?

**Comment by SmilingSword** [comment]
you cant remove perma ban unless you have access to servers side and hijacked all and unlocked all the account lol

**Comment by abh4di** [comment]
LOL ..

**Comment by Koshyy** [comment]
Maybe angry Anon members can help you lol

**Comment by smoothrunnings** [comment]
@luigidanield2 Regarding the server, they don't mean the Necrobot which is an application and not a server, they (the others here) are referring to the game server that Pokemon Go lives on. Only the game maker can set and or remove the bans. If you got banned you'll have to take it up with them.

**Comment by luigidanield2** [comment]
I tell that !!!need hack your server and create a tool for unban perm

**Comment by luigidanield2** [comment]
I tell that !!!need hack their server and create a tool for unban perm

**Comment by smoothrunnings** [comment]
@luigidanield2 Ask the Chinese they can maybe help you with that. :P  No one in North America would be that silly, the risk is too high for so little gain.
