### ISSUE TITLE
Failed to Get Data from the server

### ISSUE THREAD

**Issue by xcuts1** [NoxxDev/NecroBot#118]
i keep on receiving this error on my Google accounts, i already created new account and this keeps on showing up. i have tried 5 accounts. but PTC works fine.

**Comment by dbw-holic** [comment]
It most likely is a permanent ban.

**Comment by bestsuto** [comment]
You got permanent ban dude.

**Comment by xcuts1** [comment]
even those newly created accounts?

**Comment by bestsuto** [comment]
Yup

**Comment by plgonzalezrx8** [comment]
Failed to Get Data from the server ? Where are you seeing this, on the phone client or the bot?

**Comment by xcuts1** [comment]
on the phone sir

**Comment by plgonzalezrx8** [comment]
That means your account has been permabanned.

**Comment by xcuts1** [comment]
i also logged in my newly created account and got the same error. how about that?

**Comment by plgonzalezrx8** [comment]
Your device has been flagged and all the accounts used by the device will be banned.

**Comment by plgonzalezrx8** [comment]
Uninstall the Pokemon Go app, and reinstall, if you have an iPhone, look up the instructions on how to change your UDID (Technically, your Advert ID #)

**Comment by xcuts1** [comment]
im using undroid sir

**Comment by plgonzalezrx8** [comment]
Then do this.

Google Settings > Ads > Reset advertising ID.

**Comment by plgonzalezrx8** [comment]
Do no use any of your banned accounts again with your phone to avoid it getting flagged

**Comment by xcuts1** [comment]
ok thanks. any ways to retrieve my accounts?

**Comment by SmilingSword** [comment]
there is no way unless you have the access to the server side and hijacked the locked account to be unlocked :)

**Comment by xcuts1** [comment]
lol. i havent used my banned account since softbans are out. (like 4 days ago). But why the eff my account got banned

**Comment by SmilingSword** [comment]
what do you mean?

**Comment by xcuts1** [comment]
i did not use bot on my banned account 4 days ago. then all of a sudden this morning when logging in it, this error popped out

**Comment by SmilingSword** [comment]
yes because niantic already scan every account on their server. they will read the time frame of each catch or poke stop.

**Comment by xcuts1** [comment]
what if i log in with different device and ip?

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the repository owner and I feel like I'm wasting my time, is not worth my effort if my commits are not being pushed. I'll be making a discord channel today for that new repo I forked and got some devs coming over to help me there.

I will compile a new version in about 3 hours, this will be one of the changes. Necro 0.9.

THank you, will follow up over there, leaving this fork so we can actually get things working.

**Comment by xcuts1** [comment]
whats with this

**Comment by plgonzalezrx8** [comment]
@xcuts1 I'm a developer, and I'm not getting response for the developer here, this is a fork I made that I will keep updated constantly and I have 3 other developer friends come and help me.

**Comment by xcuts1** [comment]
what is the difference of yours with the noxxdev?

**Comment by plgonzalezrx8** [comment]
Right now they are the same, except that I added options to randomize walking speed even more, and I will be adding new features that are here in the issues list.

The difference will be that changes will actually be happening. The owner of this repository apparently is missing in action and no changes are happening right now.
