### ISSUE TITLE
Rename Pokemon does not respect delay between actions

### ISSUE THREAD

**Issue by Heraisu** [NoxxDev/NecroBot#119]
Renaming Pokemon (Pokename_IV) renames 2-3 Pokemon PER SECOND despite any action delay setting. Renaming different Pokemon would never be this fast and results in detection.

### Expected Behavior
Rename would delay based on DelayBetweenPlayerActions, or even better, a new RenamePokemonDelay parameter since that process takes longer than a typical action.

### Actual Behavior
Pokemon are renamed in under 500ms in quick succession.

### Steps to Reproduce
1. Turn on rename (or change the criteria to include more Pokemon in the rename process).
2, Start App.
3. Notice the rapid renaming of the Pokemon.
4. Probably get banned later that day.

### Other Information
Version: 0.9.0
Windows Version: Windows 10 x64
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
Renaming Pokemon

**Comment by plgonzalezrx8** [comment]
I think I found the problem, will be conducting some tests and will submit a pull request once I got it working.

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the repository owner and I feel like I'm wasting my time, is not worth my effort if my commits are not being pushed. I'll be making a discord channel today for that new repo I forked and got some devs coming over to help me there.

I will compile a new version in about 3 hours, this will be one of the changes. Necro 0.9.1
