### ISSUE TITLE
Evolving Pokemon has a random delay between actions?

### ISSUE THREAD

**Issue by Heraisu** [NoxxDev/NecroBot#120]
Evolving Pokemon (Pokename_IV) renames a Pokemon every (what seems to be) random interval between 1 and 15 seconds despite any action delay setting. Evolving different Pokemon is well known to take at least 30 seconds and results in detection. I was banned shortly after this happened.

Expected Behavior

Evolve would delay based on the minimum time between evolution animations + human offset (30s+)

Actual Behavior

Pokemon are evolved in quick succession.

Steps to Reproduce

1. Set up Pokemon inventory to Evolve Pokemon
2, Reach the required Inventory point at which evolving will begin (90.0% at default)
3. Notice the rapid evolving of the Pokemon.
Probably get banned later that day.

Other Information
Version: 0.9.0
Windows Version: Windows 10 x64
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
Evolving Pokemon

**Comment by plgonzalezrx8** [comment]
I just evolved 25 pokemon, and all of them evolved but only 17 notifications showed on the screen.

The problems seems to be with the display of the text and not with the action itself, I will look into it.

**Comment by r-pearce** [comment]
I had logged evolutions, some with 1 second between them. Average around 7
seconds. Expected the 60 to take a half hour and instead it took minutes. I
was banned shortly after.

**Comment by plgonzalezrx8** [comment]
Okay, Will look into it.

Does anyone know NoxxDev?? He hasn't been approving or making any feedback on pull requests and I'm about to start a fork and find some active collaborators to keep the project going.

**Comment by vipery** [comment]
Proper evolution 30sec per pokemon. 60 evolutions with LuckyEggs = 30 min. Must be add ASAP

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the repository owner and I feel like I'm wasting my time, is not worth my effort if my commits are not being pushed. I'll be making a discord channel today for that new repo I forked and got some devs coming over to help me there.

I will compile a new version in about 3 hours, this will be one of the changes. Necro 0.9.1

**Comment by NoxxDev** [comment]
Yes, necrobot has delays DelayBetweenPlayerActions
