### ISSUE TITLE
Add new task asap EvolveKeptPokemonsAtPotentialEvolution = "60"

### ISSUE THREAD

**Issue by vipery** [NoxxDev/NecroBot#122]
Must be:
EvolveKeptPokemonsAtPotentialEvolution = "60"
EvolveKeptPokemonsOperator = "or"
DelayEvolvePokemon = "30000"

Already exist:
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,

60 evolutions (30 sec per evolve) with LuckyEggs (30min) its proper and humanity behavoir.

Like please who understand this is big improve

**Comment by plgonzalezrx8** [comment]
Let me get this straight, I think I can make this change very easily;

So you want these options in the config:

"EvolveKeptPokemonsAtPotentialEvolution" = 60
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
"EvolveKeptPokemonsOperator" = "or"
"DelayEvolvePokemon" = 30000

And the result you expect is to start the evolution sequence when you have 60 evolvable pokemon OR 90% pokemon capacity? And then 30 seconds delay between evolutions? While also making it customizable?

**Comment by vipery** [comment]
U right. Since ive read reddit. Someone who have faster phone can bypass time and do 90 evolve per 20 sec. So yeah, settings must be costumizable.

With new ban filters, evolve is true way to leveling. U collect 60 pokemons, evolve them with LuckyEggs, profit is 30k EXTRA xp.

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the owner.

**Comment by mlebrasseur** [comment]
^^ We need this!!!
