### ISSUE TITLE
Restart Bot on first softban

### ISSUE THREAD

**Issue by AmazingGamerBoy** [NoxxDev/NecroBot#123]
Can someone please make an option in the bot to restart on the first sight of a softban if enabled? When I see a softban, i restart the bot, and immediately it helps. If someone could also be able to help me implement a short bit of code where it needs to go?

**Comment by plgonzalezrx8** [comment]
Why are you getting a softban though? Care to post your current config.json? If you are getting softbans, you are boting wrong right now.

**Comment by AmazingGamerBoy** [comment]
I have 2 bot configs, one that is really safe, another that is maxed out dangerous. I was banned on my safe account because i had left the bot overnight and woke up to see that the soft bans had been going on for hours. The restart of the bot helped me with the extremely dangerous config.

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the repository owner and I feel like I'm wasting my time, is not worth my effort if my commits are not being pushed. I'll be making a discord channel today for that new repo I forked and got some devs coming over to help me there.

I will compile a new version in about 3 hours, this will be one of the changes. Necro 0.9.1

**Comment by AmazingGamerBoy** [comment]
@plgonzalezrx8 Yeah sure man, thank you very much for the feature, i'm coming right away!

**Comment by AmazingGamerBoy** [comment]
@plgonzalezrx8 what happened with your bot page?
