### ISSUE TITLE
How to set amount of specific ball to keep

### ISSUE THREAD

**Issue by Asriandy** [NoxxDev/NecroBot#124]
Can i set amounts of specific ball to keep?
For example i want to keep 100 pokeballs, 100 greatballs and 100 ultraballs.
How i set in config file?
Thank u

**Comment by plgonzalezrx8** [comment]
Do you mind opening this same issue here? https://github.com/plgonzalezrx8/MagicPoGoBot

I'm leaving this fork, not receiving replies or any feedback from the repository owner and I feel like I'm wasting my time, is not worth my effort if my commits are not being pushed. I'll be making a discord channel today for that new repo I forked and got some devs coming over to help me there.

I will compile a new version in about 3 hours, Necro 0.9.1

I will look into adding this option, however, by default it is optimized to give priority to ultraballs. so all you have to do is change it to the amount of pokeballs you want.

**Comment by Asriandy** [comment]
Please add that features in the new version.
Thank u

**Comment by TLBM** [comment]
```
  "TotalAmountOfPokeballsToKeep": 300,
  "ItemRecycleFilter": [
    {
      "Key": "itemPokeBall",
      "Value": 100
    },
    {
      "Key": "itemGreatBall",
      "Value": 100
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    }
]
```

**Comment by Asriandy** [comment]
I give it try...
Thank u @TLBM
