### ISSUE TITLE
worked then cant find spots

### ISSUE THREAD

**Issue by zinba** [NoxxDev/NecroBot#13]
the program was working perfectly for about 30+ mins 
had to shut off because of storm

now it cant find any pokestops.
any help?
![poke](https://cloud.githubusercontent.com/assets/21026674/17652115/921dba36-6242-11e6-9792-b1183bd4fcfc.png)

**Comment by GioBregs** [comment]
Same with me

![untitled](https://cloud.githubusercontent.com/assets/21030261/17657476/43bc9650-62f6-11e6-820d-ecc386585bcc.png)

**Comment by NoxxDev** [comment]
Probably softban ip

**Comment by eicool** [comment]
I changed so many times and still no think, can you suggest what ip changer to download ?

**Comment by zinba** [comment]
I had a ip banned for an hour. Looking into vpn
