### ISSUE TITLE
Dont let open bot without changing device id

### ISSUE THREAD

**Issue by JoNMii** [NoxxDev/NecroBot#130]
Title says all,

**Comment by Koshyy** [comment]
Why?

**Comment by HOUDX1** [comment]
cuz many users using the same info of device that gonna make niantic read as multiple

**Comment by noppGithub** [comment]
Can i generate my own UNIQUE code for each of my bots ?

**Comment by Koshyy** [comment]
can it be random numbers and letters?

**Comment by jaschoo1988** [comment]
how to generate a device id?

**Comment by zzzz9999** [comment]
I think every time you run config wizard, new device data is generated, right @NoxxDev ?
