### ISSUE TITLE
No Pokestops found

### ISSUE THREAD

**Issue by mhicarl** [NoxxDev/NecroBot#133]
Hi.. its my first time to ask here.. i look at all other issue but i didnt see similar issue but not 100% sure if there's none. Im having trouble with this error "No Pokestops Found" my first problem is the softban then i saw solution about this by turning false the snipe thing.. Then after doing this no pokestops found. Please help.. Thanks

**Comment by mhicarl** [comment]
help pls :(

**Comment by jimkaya** [comment]
caused due the softban... this should end in a few hours... just stop the bot for the next few hours.
stop sniping, maybe permban will follow

**Comment by mhicarl** [comment]
awww.. is there anything i can do about this? im planning to create a new one. i see others they didnt get softbans and they say to those who get this doing bot wrong. :(

**Comment by HOUDX1** [comment]
ur IP got ban use a VPN and take a look again at ur config 99% of bans because of config setting this one gonna help you https://github.com/NoxxDev/NecroBot/issues/127 ow i have seen ur comment 
look go at Config Folder > config file > right click then open with a notepad 
but for more easy download the config from the link and replace it
but the most important u have to edit ur location lat and long cuz bot gonna open ur trainer in a different place
or give me ur location lat & long and i will upload ur config

**Comment by mhicarl** [comment]
oh thank u thank u for your response.. but im now a techie dont know how to use VPN but i will check it on google.. Im from the Phil. but this is the lat and long i used to farm 48.851438, 2.357557  its from France.

**Comment by HOUDX1** [comment]
is there a lot of pokemons? :D google cyberghost vpn and use it as france 
copy this then go to config Ctrl+A then Ctrl+V then save
for more safe change device info at auth file too  
{
  "TranslationLanguageCode": "en",
  "CheckForUpdates": true,
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": true,
  "WebSocketPort": 14251,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "TelegramPassword": "12345",
  "StartupWelcomeDelay": true,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": true,
  "CatchPokemon": true,
  "MaxBerriesToUsePerPokemon": 4,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": false,
  "UseLevelUpList": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 0,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 0.0,
  "UpgradePokemonIvMinimum": 98.1,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 48.851438,
  "DefaultLongitude": 2.357557,
  "WalkingSpeedInKilometerPerHour": 7.0,
  "UseWalkingSpeedVariant": true,
  "RandomlyPauseAtStops": true,
  "ShowVariantWalking": true,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 3000,
  "DelayBetweenPokemonCatch": 1000,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 2.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 95.0,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1150,
  "KeepMinIvPercentage": 80.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": true,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": true,
  "UseEggIncubators": false,
  "UseEggIncubatorMinKm": 2,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 20,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 50,
  "UseBerriesMinIv": 0.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "GetSniperInfoFromSkiplagged": false,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 50,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 5,
  "MaxTravelDistanceInMeters": 5000,
  "TotalAmountOfPokeballsToKeep": 250,
  "TotalAmountOfPotionsToKeep": 5,
  "TotalAmountOfRevivesToKeep": 5,
  "TotalAmountOfBerriesToKeep": 5,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 2500,
  "UseGreatBallAboveIv": 80.0,
  "UseUltraBallAboveIv": 89.0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "EnableHumanizedThrows": true,
  "EnableMissedThrows": true,
  "ThrowMissPercentage": 10,
  "NiceThrowChance": 20,
  "GreatThrowChance": 40,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 90.0,
  "AutoFavoritePokemon": true,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "mewtwo",
    "dragonite",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonair",
    "dragonite",
    "aerodactyl",
    "venusaur",
    "charizard",
    "blastoise",
    "mewtwo",
    "vaporeon",
    "jolteon",
    "flareon",
    "exeggutor",
    "gyarados",
    "lapras",
    "ditto",
    "arcanine",
    "slowbro",
    "dratini",
    "magikarp",
    "eevee",
    "ditto",
    "articuno",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo",
    "metapod",
    "butterfree",
    "kakuna",
    "beedrill",
    "pidgeotto",
    "pidgeot",
    "raticate",
    "fearow",
    "ekans",
    "arbok",
    "nidorina",
    "nidoqueen",
    "nidorino",
    "nidoking",
    "jigglypuff",
    "wigglytuff",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "paras",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "meowth",
    "persian",
    "psyduck",
    "golduck",
    "mankey",
    "primeape",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "machop",
    "machoke",
    "machamp",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "magnemite",
    "magneton",
    "dodrio",
    "seel",
    "shellder",
    "drowzee",
    "krabby",
    "voltorb",
    "cubone",
    "rhyhorn",
    "horsea",
    "goldeen",
    "staryu",
    "ditto",
    "omanyte",
    "kabuto"
  ],
  "PokemonsToLevelUp": null,
  "PokemonsToIgnore": [
    "zubat",
    "golbat"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 84.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Hypno": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 93.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 98.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Slowbro": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 91.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dratini": {
      "KeepMinCp": 1300,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 99.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 37.747536,
        "Longitude": -122.389374
      },
      {
        "Latitude": 37.75468,
        "Longitude": -122.383175
      },
      {
        "Latitude": 37.764149,
        "Longitude": -122.386327
      },
      {
        "Latitude": 37.773284,
        "Longitude": -122.386117
      },
      {
        "Latitude": 37.785076,
        "Longitude": -122.388218
      },
      {
        "Latitude": 37.794535,
        "Longitude": -122.392343
      },
      {
        "Latitude": 37.798755,
        "Longitude": -122.396457
      },
      {
        "Latitude": 37.803546,
        "Longitude": -122.401076
      },
      {
        "Latitude": 37.806967,
        "Longitude": -122.405478
      },
      {
        "Latitude": 37.809134,
        "Longitude": -122.413851
      },
      {
        "Latitude": 37.808564,
        "Longitude": -122.419192
      },
      {
        "Latitude": 37.807089,
        "Longitude": -122.424528
      },
      {
        "Latitude": 37.805948,
        "Longitude": -122.439974
      },
      {
        "Latitude": 37.804216,
        "Longitude": -122.447704
      },
      {
        "Latitude": -37.764537,
        "Longitude": 145.357286
      },
      {
        "Latitude": -37.763517,
        "Longitude": 145.354768
      },
      {
        "Latitude": -37.763038,
        "Longitude": 145.352128
      },
      {
        "Latitude": -37.764657,
        "Longitude": 145.349457
      },
      {
        "Latitude": -37.766012,
        "Longitude": 145.350656
      },
      {
        "Latitude": -37.76809,
        "Longitude": 145.350435
      },
      {
        "Latitude": -37.769745,
        "Longitude": 145.350708
      },
      {
        "Latitude": -37.770561,
        "Longitude": 145.353014
      },
      {
        "Latitude": -37.769265,
        "Longitude": 145.354865
      },
      {
        "Latitude": -37.769049,
        "Longitude": 145.357262
      },
      {
        "Latitude": -37.769985,
        "Longitude": 145.358598
      },
      {
        "Latitude": -37.76797,
        "Longitude": 145.359933
      },
      {
        "Latitude": -37.766699,
        "Longitude": 145.358901
      },
      {
        "Latitude": 48.849957,
        "Longitude": 2.359276
      },
      {
        "Latitude": 48.850423,
        "Longitude": 2.358203
      },
      {
        "Latitude": 48.850901,
        "Longitude": 2.356532
      },
      {
        "Latitude": 48.851289,
        "Longitude": 2.355588
      },
      {
        "Latitude": 48.851678,
        "Longitude": 2.354257
      },
      {
        "Latitude": 48.852256,
        "Longitude": 2.353657
      },
      {
        "Latitude": 48.852934,
        "Longitude": 2.353292
      },
      {
        "Latitude": 48.853386,
        "Longitude": 2.353217
      },
      {
        "Latitude": 48.853428,
        "Longitude": 2.354075
      },
      {
        "Latitude": 48.853075,
        "Longitude": 2.355169
      },
      {
        "Latitude": 48.852821,
        "Longitude": 2.356006
      },
      {
        "Latitude": 48.852518,
        "Longitude": 2.356961
      },
      {
        "Latitude": 59.90014,
        "Longitude": 10.755197
      },
      {
        "Latitude": 59.906256,
        "Longitude": 10.75955
      },
      {
        "Latitude": 59.904917,
        "Longitude": 10.752632
      },
      {
        "Latitude": 59.908204,
        "Longitude": 10.752389
      },
      {
        "Latitude": 59.906135,
        "Longitude": 10.746684
      },
      {
        "Latitude": 59.902604,
        "Longitude": 10.743771
      },
      {
        "Latitude": 59.90437,
        "Longitude": 10.737944
      },
      {
        "Latitude": 59.906682,
        "Longitude": 10.734424
      },
      {
        "Latitude": 59.910091,
        "Longitude": 10.733696
      },
      {
        "Latitude": 59.910273,
        "Longitude": 10.730054
      },
      {
        "Latitude": 59.909299,
        "Longitude": 10.7235
      },
      {
        "Latitude": 59.908387,
        "Longitude": 10.718766
      },
      {
        "Latitude": 59.906743,
        "Longitude": 10.713061
      },
      {
        "Latitude": 59.908326,
        "Longitude": 10.708812
      },
      {
        "Latitude": 59.911977,
        "Longitude": 10.7025
      },
      {
        "Latitude": 33.736842,
        "Longitude": -118.101057
      },
      {
        "Latitude": 33.738163,
        "Longitude": -118.104018
      },
      {
        "Latitude": 33.739876,
        "Longitude": -118.107623
      },
      {
        "Latitude": 33.740411,
        "Longitude": -118.109168
      },
      {
        "Latitude": 33.740875,
        "Longitude": -118.110455
      },
      {
        "Latitude": 33.741731,
        "Longitude": -118.112172
      },
      {
        "Latitude": 33.742838,
        "Longitude": -118.114361
      },
      {
        "Latitude": 33.745229,
        "Longitude": -118.112945
      },
      {
        "Latitude": 33.747512,
        "Longitude": -118.111571
      },
      {
        "Latitude": 33.749154,
        "Longitude": -118.108739
      },
      {
        "Latitude": 39.285967,
        "Longitude": -76.608897
      },
      {
        "Latitude": 39.285932,
        "Longitude": -76.610142
      },
      {
        "Latitude": 39.285709,
        "Longitude": -76.611674
      },
      {
        "Latitude": 39.284746,
        "Longitude": -76.611977
      },
      {
        "Latitude": 39.282679,
        "Longitude": -76.611886
      },
      {
        "Latitude": 39.281904,
        "Longitude": -76.611613
      },
      {
        "Latitude": 39.281751,
        "Longitude": -76.610081
      },
      {
        "Latitude": 39.281857,
        "Longitude": -76.608579
      },
      {
        "Latitude": 39.281868,
        "Longitude": -76.607638
      },
      {
        "Latitude": 39.281528,
        "Longitude": -76.606576
      },
      {
        "Latitude": 39.280882,
        "Longitude": -76.605817
      },
      {
        "Latitude": 39.280318,
        "Longitude": -76.605377
      },
      {
        "Latitude": 39.27932,
        "Longitude": -76.605878
      },
      {
        "Latitude": 39.278632,
        "Longitude": -76.605629
      },
      {
        "Latitude": 41.021727456054904,
        "Longitude": 28.974664807319641
      },
      {
        "Latitude": 41.021686983614593,
        "Longitude": 28.974841833114624
      },
      {
        "Latitude": 41.021557471638516,
        "Longitude": 28.975163698196411
      },
      {
        "Latitude": 41.021642463901557,
        "Longitude": 28.975732326507568
      },
      {
        "Latitude": 41.021771975710486,
        "Longitude": 28.976660370826721
      },
      {
        "Latitude": 41.022298114815477,
        "Longitude": 28.977813720703125
      },
      {
        "Latitude": 22.296065137950858,
        "Longitude": 114.17695999145508
      },
      {
        "Latitude": 22.295370267016203,
        "Longitude": 114.17655229568481
      },
      {
        "Latitude": 22.294298173652926,
        "Longitude": 114.17612314224243
      },
      {
        "Latitude": 22.293920953661537,
        "Longitude": 114.17558670043945
      },
      {
        "Latitude": 22.293543732651891,
        "Longitude": 114.17442798614502
      },
      {
        "Latitude": 22.293762123886843,
        "Longitude": 114.17301177978516
      },
      {
        "Latitude": 22.294238612669361,
        "Longitude": 114.17221784591675
      },
      {
        "Latitude": 22.293603293931632,
        "Longitude": 114.17140245437622
      },
      {
        "Latitude": 22.2940400758741,
        "Longitude": 114.17000770568848
      },
      {
        "Latitude": 22.294258466333368,
        "Longitude": 114.16837692260742
      },
      {
        "Latitude": 22.295251145937577,
        "Longitude": 114.1680121421814
      },
      {
        "Latitude": 22.297514429066013,
        "Longitude": 114.16784048080444
      },
      {
        "Latitude": 22.299321058583679,
        "Longitude": 114.1673469543457
      },
      {
        "Latitude": 22.300730610444251,
        "Longitude": 114.16702508926392
      },
      {
        "Latitude": 40.707287092735527,
        "Longitude": -74.000215530395508
      },
      {
        "Latitude": 40.7066689811733,
        "Longitude": -74.0013313293457
      },
      {
        "Latitude": 40.706018331225707,
        "Longitude": -74.002768993377686
      },
      {
        "Latitude": 40.705172476790494,
        "Longitude": -74.004077911376953
      },
      {
        "Latitude": 40.704310344869079,
        "Longitude": -74.005537033081055
      },
      {
        "Latitude": 40.7036759387806,
        "Longitude": -74.006803035736084
      },
      {
        "Latitude": 40.702830054596006,
        "Longitude": -74.008305072784424
      },
      {
        "Latitude": 40.70141480126501,
        "Longitude": -74.011673927307129
      },
      {
        "Latitude": 40.700633958968886,
        "Longitude": -74.013111591339111
      },
      {
        "Latitude": 40.700991846157528,
        "Longitude": -74.015192985534668
      },
      {
        "Latitude": 40.702781253257584,
        "Longitude": -74.0170168876648
      },
      {
        "Latitude": 40.704668212304441,
        "Longitude": -74.017167091369629
      },
      {
        "Latitude": 40.704814612064688,
        "Longitude": -74.017682075500488
      },
      {
        "Latitude": 40.70489594512577,
        "Longitude": -74.018948078155518
      },
      {
        "Latitude": 40.70627859196756,
        "Longitude": -74.019098281860352
      },
      {
        "Latitude": 40.70705936809059,
        "Longitude": -74.018733501434326
      },
      {
        "Latitude": 40.707628678242877,
        "Longitude": -74.0182614326477
      },
      {
        "Latitude": -33.8564820606244,
        "Longitude": 151.21579885482788
      },
      {
        "Latitude": -33.85630386827517,
        "Longitude": 151.21461868286133
      },
      {
        "Latitude": -33.8571591881608,
        "Longitude": 151.2143611907959
      },
      {
        "Latitude": -33.858157050534182,
        "Longitude": 151.21382474899292
      },
      {
        "Latitude": -33.858798527331587,
        "Longitude": 151.21320247650147
      },
      {
        "Latitude": -33.859422180709466,
        "Longitude": 151.21275186538696
      },
      {
        "Latitude": -33.860188377195747,
        "Longitude": 151.21273040771484
      },
      {
        "Latitude": -33.860936748522356,
        "Longitude": 151.21266603469849
      },
      {
        "Latitude": -33.861275295301176,
        "Longitude": 151.21195793151856
      },
      {
        "Latitude": -33.861310931726138,
        "Longitude": 151.21152877807617
      },
      {
        "Latitude": -33.8610792946981,
        "Longitude": 151.21086359024048
      },
      {
        "Latitude": -33.861097112953331,
        "Longitude": 151.21019840240479
      },
      {
        "Latitude": -33.861008021639968,
        "Longitude": 151.20964050292969
      },
      {
        "Latitude": -33.860544745312112,
        "Longitude": 151.20938301086426
      },
      {
        "Latitude": -33.859618185116148,
        "Longitude": 151.20957612991333
      },
      {
        "Latitude": -33.859208357207272,
        "Longitude": 151.20991945266724
      },
      {
        "Latitude": -33.858673796109471,
        "Longitude": 151.21006965637207
      },
      {
        "Latitude": -33.858174869399171,
        "Longitude": 151.2102198600769
      },
      {
        "Latitude": -33.857533387917158,
        "Longitude": 151.21011257171631
      },
      {
        "Latitude": -33.857194826303477,
        "Longitude": 151.20983362197876
      },
      {
        "Latitude": -33.85667807177915,
        "Longitude": 151.20938301086426
      },
      {
        "Latitude": -33.856090036965327,
        "Longitude": 151.20916843414307
      },
      {
        "Latitude": -33.855751469629858,
        "Longitude": 151.20974779129028
      },
      {
        "Latitude": -33.855698011506824,
        "Longitude": 151.21019840240479
      },
      {
        "Latitude": -33.854949594271112,
        "Longitude": 151.2102198600769
      },
      {
        "Latitude": -33.854325908231658,
        "Longitude": 151.20966196060181
      },
      {
        "Latitude": -33.854005153637992,
        "Longitude": 151.20914697647095
      },
      {
        "Latitude": -33.853809136348893,
        "Longitude": 151.20882511138916
      },
      {
        "Latitude": -33.853809136348893,
        "Longitude": 151.2083101272583
      },
      {
        "Latitude": -33.8541655310854,
        "Longitude": 151.20788097381592
      },
      {
        "Latitude": -33.855591095160392,
        "Longitude": 151.20710849761963
      },
      {
        "Latitude": -33.855804927719419,
        "Longitude": 151.20637893676758
      },
      {
        "Latitude": -33.85651769904964,
        "Longitude": 151.20577812194824
      },
      {
        "Latitude": -33.85651769904964,
        "Longitude": 151.20515584945679
      },
      {
        "Latitude": -33.856588975855495,
        "Longitude": 151.20436191558838
      },
      {
        "Latitude": -33.855377262066007,
        "Longitude": 151.20352506637573
      },
      {
        "Latitude": -33.856588975855495,
        "Longitude": 151.20354652404785
      },
      {
        "Latitude": -33.8564820606244,
        "Longitude": 151.20290279388428
      },
      {
        "Latitude": -33.855858385775527,
        "Longitude": 151.20245218276978
      },
      {
        "Latitude": -33.856446422184312,
        "Longitude": 151.202130317688
      },
      {
        "Latitude": -33.857996680581948,
        "Longitude": 151.20165824890137
      },
      {
        "Latitude": -33.858620339815644,
        "Longitude": 151.20178699493408
      },
      {
        "Latitude": -33.859190538557925,
        "Longitude": 151.20200157165527
      },
      {
        "Latitude": -33.859600366552314,
        "Longitude": 151.2013578414917
      },
      {
        "Latitude": -33.860063648003653,
        "Longitude": 151.20049953460693
      }
    ],
    "Pokemon": [
      "charizard",
      "blastoise",
      "raichu",
      "cloyster",
      "gyarados",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "dragonair",
      "dratini"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by mhicarl** [comment]
Thank you so much i really appreciate this..

**Comment by HOUDX1** [comment]
stop using it atm and wait the new Release visit here [](https://github.com/NoxxDev/NecroBot/issues/138)

**Comment by mhicarl** [comment]
ohh okey.. thank you so much

**Comment by mhicarl** [comment]
sorry to ask this but where i can find the new release?

**Comment by HOUDX1** [comment]
it's okay https://github.com/NoxxDev/NecroBot/releases

**Comment by mhicarl** [comment]
thank you so much HOUDX1 i really appreciate this.. this is a really big help to me

**Comment by mhicarl** [comment]
Hi.. another question.. sorry for so many questions i've asked.. If ever i want to switch places, like from france to philippines, i will just change my VPN or i need to wait and not bot for some several days to change locations?

**Comment by Unentertained** [comment]
It seems like jumping countries will still get you flagged. The VPN/IP Address you use will not make your account appear in that area. You have to change the coordinates in your config.json manually.

There are a lot of opinions and misinformation going around lately (Like the fact that we still do not know for a fact* what causes a ban), so play it safe.

*Through my own personal research

**Comment by mhicarl** [comment]
thanks @Unentertained  i think sudden change of locations might trigger softbans base on my experience.
