### ISSUE TITLE
Release 9.1 easily gets softbanned

### ISSUE THREAD

**Issue by likeness123** [NoxxDev/NecroBot#135]
Hey I tried usign the new release I keep getting softbanned. All my snipe functions are set to false. Walking is at 5.0 km. Enable missed throws true. Is it true that when you get softbanned you should stop playing for 1 week?

**Comment by smoothrunnings** [comment]
They will perm ban you if you play 24hours a day for a week as no human plays like this, it's just not possible. Plus they also log everything on their servers, so if they haven't banned you yet, they will soon.
