### ISSUE TITLE
Bot isn't following GPX pathing.

### ISSUE THREAD

**Issue by CHRNY** [NoxxDev/NecroBot#136]
### Expected Behavior
Bot follows GPX pathing file in a loop.

### Actual Behavior
Bot followed GPX file for 1 loop then strayed and walked around as if the GPX pathing file wasn't there.

### Your config.json
```
http://pastebin.com/pyTf0Nn9
```

### Steps to Reproduce
Updated to Necrobot 0.9.0 from previous version.

### Other Information
Version: Necrobot 0.9.0
Windows Version: Windows 10, 64 Bit
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): GPX pathing

EDIT: In case it was unclear, GPX pathing worked 100% BEFORE 0.9.0, but after updating the bot stopped following the pathing file. Not sure if one time incident or not.

**Comment by mo0ojava** [comment]
Tested the gpx-tracker just now and it works just as before. As far as I can see there has been no changes to the code that would make the bot stop after just one revolution. Unless more people can reproduce your findings chances are you have a rare case on your hand. Have you validated/doublechecked the file?

**Comment by CHRNY** [comment]
I've validated my config.json file and it's okay. What I have observed so far is that if I restart the bot, it runs normally following the GPX file for a few hours before changing course. At which point I need to restart the bot again to get it on the pathing that I want.

Could this be because MaxSpawnLocationOffset is messing with the pathing?

**Comment by NoxxDev** [comment]
Fixed
