### ISSUE TITLE
Autoexit after "x" hours

### ISSUE THREAD

**Issue by jimkaya** [NoxxDev/NecroBot#137]
Hi,
it would be nice if you can add a option to autoexit the bot after "x" min or hours.
would it be possible?

**Comment by hcarrega** [comment]
Auto stop and auto loggin

**Comment by jimkaya** [comment]
nice idea! a timer that will delay the login when start the bot.

**Comment by hcarrega** [comment]
Pokefarmer a paid bot as that option...he stops at pokestops for a while and on lured ones..after x time e stops and try to loggin later

**Comment by Kongen8800** [comment]
Use my tool/extension https://discord.gg/SVFvc it does exacty what you want.
More options are being added to it soon (Random start/close the bot(looping) ,start from last position, and more)
Its support NecroBot and PokeMobBot.

**Comment by hcarrega** [comment]
Im already on that discord... rocketbot...gonna try

**Comment by felipetmartini** [comment]
@Kongen8800 can you post  a new invite code? this one have expired

**Comment by Kongen8800** [comment]
Sure, this one won't expire: https://discord.gg/ZdetZug

**Comment by felipetmartini** [comment]
ty

**Comment by Skolzack** [comment]
I'm doing that using the Task Scheduler of Windows. I made two .bats that one opens Necrobot and the other closes it, it'so easy..

1 - Open a notepad
2 - this command open necrobot: @echo off

start C:\Users\XxXx\Desktop\0.8.8\NecroBot.exe

end

3 - name it "something.bat" don't forget to put .bat in the end and save it.

4 - To close necrobot: @echo off

taskkill /IM NecroBot.exe

5 - Do the same of the step 3.

6 - After that just go to Task Scheduler of Windows and configure as you wish.

**Comment by jimkaya** [comment]
i use currently the same function
but implementation in the bot would be nice
