### ISSUE TITLE
1000 pokemon / 2000 pokestop limit please

### ISSUE THREAD

**Issue by SmartHacker** [NoxxDev/NecroBot#141]
It has been confirmed that the softbans are cause by something as simple as this, but I am yet to see any other bot to get it implemented besides PokeFarmer, the commercialized bot.

https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/

I have 5 bot accounts and get countless softbans. I realized that all of them is caused by exceeding the limits. I have tried setting walkingspeed to 100km/h, pure sniping(without catching pokemon normally), getting over 300k XP/h for 3 days. Even under these extreme conditions, I didn't get a single softban as long as I keep the total pokemon/pokestop count in 24 hours within the limit. At this stage, Niantic simply doesn't have to rely on any fancy and high-cost data mining and pattern recognition technique to catch botters while a no-brainer as simple as this all ready work like charm. I recommend devs to focus energy on what we already confirmed than rootless humanizations that does nothing but make bot inefficient and unstable.

It's not all that hard to implement the limit check, by the way. We simply needs to create a file to log the pokemon/pokestop count for each of the last 24 hours and write it back to a file every hour. Then we can check if the limit has been reached during 25 hours (to be on the safe side since user can restart the bot in the middle of an hour). I am yet to see if any developer is able to take the challenge.

**Comment by noppGithub** [comment]
I think your idea is good, these values might show on the bar as real-time short summary or even auto log-off if one condition is being reached.

However, I have some note about botting
2 acc: Default config + snipping = Can't get data from server(i think it's ban).
1 acc: Default config + no snipe = Working fine

As far as i know, dev or someone write in the manual that SNIP = easy big flag on your acc.

**Comment by HOUDX1** [comment]
can u share with us a config working fine without sniping and any cause of bans?

**Comment by likeness123** [comment]
What is the limit of pokestops within 24 hours?

**Comment by SmartHacker** [comment]
@noppGithub There is no source confirming sniping is the cause of permaban. I have done heavy sniping on all of my account, only 1 of them got banned, and I suspect it's due to too many softbans in a single day (at that time I am not aware of the 24 hr limit thing). Can you confirm that you have no softbans on the account you lost that you suspect is due to sniping?

The majority of botters are going beyond the limit at some time point and get flagged and latter perm-banned. Then they correlates it with whatever random thing that comes into their mind and claim it to be the cause. That's my speculation. So far, only the 24 hour limit thing is deterministically reproducible.

**Comment by mhicarl** [comment]
Hi yesterday ive got 3 softbans in my account and thats the total number that account received since i bot it. and when i wake up today i cant access that account its says "failed getting game data".. just want to share this info. but i dont know what cause of this.

**Comment by smoothrunnings** [comment]
@SmartHacker They are going to shut you down next. :)

They log everything now, anything that looks suspicious means you are a bot and they won't give you a warning and will ban your account. Because they haven't done it yet doesn't mean it won't happen, after mass bans started happening it took them 3 days to finally get to my accounts and shut them down. You have understand there are millions of people playing this game now, it banning all the bots takes time.

**Comment by noppGithub** [comment]
@SmartHacker You may right, both of the banned IDs are got soft banned because I use the same machine to do botting(even one of them is in VM).

I think the external IP is bring soft-ban to both of them(even only 1 softban, can't get game data 1 day after).

The quote from 0.8.6 version in GUI config, i think this word wrote by devs. and i think we should follow the Devs instructions(strictly)
"WARNING: Sniping is extremely risky and easy to detect, using snipping.....you have been warned!!!"

Sorry if i'm wrong

**Comment by patade** [comment]
What we can do now is make dump account and experiment the bot before use the bot on real account.

**Comment by Skolzack** [comment]
If you get so much softbans in the same day you will be permabanned for sure! I was using 50km/h with humanizedwalk = false and was getting much softbans in a day, 3 of my 4 accounts is permabanned because of this. Now I'm with my last one with no softbans playing 14hours per day in the limit of 1k pokemons and 2k pokestops, everything is fine until now.

**Comment by AgainstTheCurrent** [comment]
@smoothrunnings  We will wait and see. But I feel they will definitely screen accounts with softbans first. As long as you keep within the specified limits there is no softbans. My point is, the accounts that use ridiculous walking speed (100km/h) and no humanization at all but keep within the limits is safer than account that use every humanization and slow as crap but don't abide by the limits. So why would devs waste time on rootless things such as pathing and more sophisticated humanzation, while even the basic and confirmed ban reasons haven't been fixed. If Niantic were to datamine the user logs, there are way much more efficient patterns to recognize than the humanization thing devs are trying to achieve here.
As of now, the correct botting strategy is to use no humanization at all and bot with sniping as fast as possible to complete 1000 catches/2000 pokestops within 2 hours and then rest for 22 hours. I'm not saying it will not be hard banned. But according to my limited experiment, it's at least as safe as accounts that use slow and complicated settings and accidentally exceeds the 1000/2000 limit.

**Comment by SmartHacker** [comment]
We will wait and see. But I feel they will definitely screen accounts with softbans first. As long as you keep within the specified limits there is no softbans. My point is, the accounts that use ridiculous walking speed (100km/h) and no humanization at all but keep within the limits is safer than account that use every humanization and slow as crap but don't abide by the limits. So why would devs waste time on rootless things such as pathing and more sophisticated humanzation, while even the basic and confirmed ban reasons haven't been fixed. If Niantic were to datamine the user logs, there are way much more efficient patterns to recognize than the humanization thing devs are trying to achieve here.
As of now, the correct botting strategy is to use no humanization at all and bot with sniping as fast as possible to complete 1000 catches/2000 pokestops within 2 hours and then rest for 22 hours. I'm not saying it will not be hard banned. But according to my limited experiment, it's at least as safe as accounts that use slow and complicated settings and accidentally exceeds the 1000/2000 limit.

**Comment by Hyperhk** [comment]
@SmartHacker Do you mind sharing your setting for the 300XP/h pure sniping and not catching pokemon normally? I have read the config but not really familiar with what to change since some of them are similar. Thanks!

**Comment by SmartHacker** [comment]
Why closed?
