### ISSUE TITLE
Problem with filter pokemons by move

### ISSUE THREAD

**Issue by wuaito4** [NoxxDev/NecroBot#142]
Hi I'm from Argentina (sorry for my English). I want filter pokemon by moves in Config.json but I can't. The bot gives an error message. I tried a lot of combinations but I give up.

The "error message":

JSON Exception: Error converting value "Blizzard" to type ´System.Collections.Generic.List`1[POGOProtos.Enums.PokemonMove]´. Path ´PokemonsTransferFilter.Ditto.Moves[0]´, line 1793, position 26.

This happens when in my "Config.json" I changed the value in LAPRAS, for example.

This is my configuration for LAPRAS:
},
    "Lapras": {
      "KeepMinCp": 1300,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "and"
    },

When i add the names of moves, the bot gives that error message.

If u can tell me how configure to filter pokemons by moves I would be very grateful. Sorry for my basic English and poor programming knowledge. Thank you!

I've the last version of NecroBot. I've windows 10 x64.

**Comment by f3l1p1nh07** [comment]
},
    "Jolteon": {
      "KeepMinCp": 0,
      "KeepMinLvl": 21,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [
        [
          "thunderShock",
          "thunder"
        ]
      ],
      "DeprecatedMoves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "and"
    },

this is correct. add [ ] for move1 + move2 par.

**Comment by wuaito4** [comment]
Thank You! F3l1p1nh07
