### ISSUE TITLE
update pogoprotos

### ISSUE THREAD

**Issue by thekjohn** [NoxxDev/NecroBot#146]
https://github.com/johnduhart/POGOProtos-dotnet

this includes a new field, called unknown25

            sig.Unknown25 = BitConverter.ToInt64(new System.Data.HashFunction.xxHash(64, 0x88533787).ComputeHash(System.Text.Encoding.ASCII.GetBytes("\"b8fa9757195897aae92c53dbcf8a60fb3d86d745\"")), 0);

source: https://github.com/AeonLucid/POGOProtos/commit/b65d4b56f02a1182bd81572bcee3a32944c47885

also unknown22 is renamed to SessionHash
(which shouldn't be constant, but randomized in my opinion)

**Comment by vfuyong** [comment]
This is urgent!

**Comment by NoxxDev** [comment]
Updated https://github.com/NoxxDev/NecroBot-Rocket-API/commit/6bc1672760921b5aed812b2bd799936aa23726f6
