### ISSUE TITLE
Someone working on the telegram support?

### ISSUE THREAD

**Issue by developnoop** [NoxxDev/NecroBot#147]
Since 0.8.5 Telegram bot functionallity is not working anymore.
This would be a nice feature add :-)

Maybe Describe the telegram bot usage incl. the password part in the wiki page 
a little bit better :-)

### Expected Behavior
- configure telegram in the config.json 
- setting the usage of the telegram api to true
- start the Necrobot
- Telegram function works and reacts to the telegram bot commands

### Actual Behavior
telegram function does not start.

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by jk94** [comment]
Hey @developnoop 

I have to disagree. I'm using the 0.9.0 version of the bot and the telegram bot usage is fully functioning.
You can enable the function in the config.json

**Comment by Dreker** [comment]
@jk94  what is "TelegramPassword": "12345",
?

**Comment by caio-pinho** [comment]
Mine is working too.
@Dreker don't know what is it, but you don't need to change it.

**Comment by butilities** [comment]
I fix it on this [commit](https://github.com/NoxxDev/NecroBot/commit/e28c73cb7781981a4a2f8aa617232450769bd7d2), the password is for 2 factor authentication but it has not been implemented. You might leave it blank or just leave it as it is.

**Comment by developnoop** [comment]
Hmm, still "unknown telegram error" on my side with 0.9.0 and yes i checked more then 3 times the botfather answer with the token to be the same i had in the config.
Hmm, so maybe a little bit of looking at the error code may be helpful. Till now it is a "one catches all errors".

**Comment by rigardo09** [comment]
hai can u guys give me link to instal the telegram? i cant find it
thanks

**Comment by NoxxDev** [comment]
https://github.com/NoxxDev/NecroBot/commit/5a37606e6bb9a747afa7bf414ddea6b67781e1dc
