### ISSUE TITLE
May be BAN !

### ISSUE THREAD

**Issue by HYZO** [NoxxDev/NecroBot#15]
I donn't know why but i have this... (show the screen)
This afternoon the bot working correctly and now... and i can't log me on the app : "
Error reading data from the server"

SOME HELP ? i was ban ? someone have the same ?
![bot pokemon go](https://cloud.githubusercontent.com/assets/21027699/17652479/94ed8e2c-627d-11e6-9d89-62e6bb6b9ab3.png)

The config is the basic config with lat and long changed, good pass and good username all is workign this afternoon

**Comment by EyesReye** [comment]
Permba banned.... like me...

**Comment by NoxxDev** [comment]
Config default start in new york

If you used the default location and after bot closes it opened on your Smartphone, you should probably be another country, it is very likely that the ban

**Comment by HYZO** [comment]
yeah i just wait 5-6h to reconnect me in an orther counter or on my smartphone...
SO ITS PERMA BANN ???????? :'(

**Comment by GioBregs** [comment]
Neva heard of a perm ban give it a day and try again

**Comment by Retalyx** [comment]
Yes, it's a permaban :/ I have the same on my account 3 days ago, and i still can't loggin
