### ISSUE TITLE
what is the average bot xp/hour should be without getting softban?? please advise

### ISSUE THREAD

**Issue by inclouis** [NoxxDev/NecroBot#154]
what are the average bot xp/hour should be without getting softban?? please advise

my bot now is like 10k xp/hour. is that too slow?

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by bulubebek** [comment]
some said max. 100k exp/day. so keep below it.

**Comment by inclouis** [comment]
Thanks bud !
