### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by siangs** [NoxxDev/NecroBot#158]
hi...what is the line for disable auto snipe at the config.json?

**Comment by narutomxc** [comment]
--> "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
-->  "GetSniperInfoFromPokezz": false,
-->  "GetOnlyVerifiedSniperInfoFromPokezz": false,
-->  "GetSniperInfoFromPokeSnipers": false,
-->  "GetSniperInfoFromPokeWatchers": false,
-->  "GetSniperInfoFromSkiplagged": false,
