### ISSUE TITLE
Now i cant use it because i have windows vista

### ISSUE THREAD

**Issue by samuel4707** [NoxxDev/NecroBot#16]
Cant i use necrobot while being an windows vista user?

## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version: Vista
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by NoxxDev** [comment]
Yes, it should work for Windows Vista

Download and install
[Net Framework 4.6.2] (https://www.microsoft.com/en-us/download/details.aspx?id=53345)
[Visual C++ Redistributable for Visual Studio 2015] (https://www.microsoft.com/en-US/download/details.aspx?id=48145)
