### ISSUE TITLE
Idea on range of snipe

### ISSUE THREAD

**Issue by samtch999** [NoxxDev/NecroBot#160]
Considering sniping far apart from your current location could result in banning, could we just add a function on calculating distance before teleporting to the sniping destination? Let say, I am in Hong Kong, I am not supposed to catch pokemon out of Hong Kong. So I am just sniping Pokemon in range around 22.3 , 114.2
Should be an easy calculation.

**Comment by NoxxDev** [comment]
Use HumanSnipeWalki v0.9.5 or upper
