### ISSUE TITLE
Add new task asap EvolveKeptPokemonsAtPotentialEvolution = "60"

### ISSUE THREAD

**Issue by vipery** [NoxxDev/NecroBot#162]
Must be:
EvolveKeptPokemonsAtPotentialEvolution = "60"
EvolveKeptPokemonsOperator = "or"
DelayEvolvePokemon = "30000"

Already exist:
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,

60 evolutions (30 sec per evolve) with LuckyEggs (30min) its proper and humanity behavoir.
Since ive read reddit. Someone who have faster phone can bypass time and do 90 evolve per 20 sec each. So yeah, settings must be costumizable.

With new ban filters, evolve is true way to leveling. U collect 60 pokemons, evolve them with LuckyEggs, profit is 30k EXTRA xp.

Already exist too:
"UseLuckyEggsMinPokemonAmount": 30,
"UseLuckyEggsWhileEvolving": true,

Need only add

"EvolveKeptPokemonsAtPotentialEvolution" = 60
"EvolveKeptPokemonsOperator" = "or"
"DelayEvolvePokemon" = 30000

**Comment by samtch999** [comment]
I have tried manual evolved 73 pokemon in 1 lucky egg

**Comment by vipery** [comment]
Sure u can change value to 90 for exmaple. But operator absolutely must have when leveling with lucky eggs becuse u dont know when and how much will evolve with EvolveKeptPokemonsAtStorageUsagePercentage
