### ISSUE TITLE
There is no Necro Bot Config.exe anymore since last update

### ISSUE THREAD

**Issue by Throrozan** [NoxxDev/NecroBot#165]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by jimkaya** [comment]
read the changelog!
that was only experimentally and is no longer available

**Comment by Throrozan** [comment]
Where can I read it?

Von meinem iPhone gesendet

**Comment by jimkaya** [comment]
https://github.com/NoxxDev/NecroBot/releases

NecroBot Forked v0.9.0

Removed:
configGUI

-----------
you already written a comment there ;)

**Comment by likeness123** [comment]
I am using the 9.1. I downloaded it immediately. So far no softban. It has easier config.json file.

**Comment by rayeswt** [comment]
Is the config.json in the translation folder? I have a bunch of other languages but none in english @jimkaya

**Comment by rayeswt** [comment]
@jimkaya no worries mate, solved it. It's not in the 0.9.0 release pack but it works if you download 0.89 and lets the software update itself. thanks!
