### ISSUE TITLE
Softban problem

### ISSUE THREAD

**Issue by tonigino2** [NoxxDev/NecroBot#166]
Hi everyone!
I bot from like 4 days and it was all good, now the bot can't remove me softbans and i don't know why, i upload a screen
![immagine](https://cloud.githubusercontent.com/assets/21101446/17770540/a9fa6010-653e-11e6-8976-23427b1d8832.png)

**Comment by DavideRaggi** [comment]
I've got the same problem

**Comment by smoothrunnings** [comment]
@tonigino2  Did you just bot the 4 days straight? You know you have to think like a Pokemon Go player, if you bot constantly they will eventually softban/permban you because no human Pokemon Go player plays constantly. Also keep in mind they log everything.

**Comment by galopuong** [comment]
I got softban, and close the bot, i reopen it after an hours and get it: "system null reference exception object reference not set to an instance of an object" any idea guys?

**Comment by harryhalim05** [comment]
You are going too fast man.

**Comment by albysprx** [comment]
@galopuong it's the permaban

**Comment by galopuong** [comment]
@albysprx I can open the acc in my phone is my ip get permaban?

**Comment by albysprx** [comment]
@galopuong i got the same message when my account got permabanned but it doesn't work in my phone too, maybe it's another problem, try with another account and see if it works

**Comment by jimkaya** [comment]
for the future, change "WalkingSpeedInKilometerPerHour"
45 km/h is too much
