### ISSUE TITLE
GPX Path not following road curve (going straight line point to point)

### ISSUE THREAD

**Issue by Josp1337** [NoxxDev/NecroBot#168]
### Expected Behavior
GPX path will be followed with more precision.

### Actual Behavior
GPX path doing straight line from point to point. I mean its not curving(following road turn) its cutting straight angle in go straight line to the other point.

### Steps to Reproduce
GPX created with : http://www.justgoride.co.uk/
or 
https://www.plotaroute.com

### Other Information
Version: 0.9.0
Windows Version: Microsoft Windows 10 X64 Professional Build 10586

What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): GPX Path

**Comment by NoxxDev** [comment]
create your GPX using this site http://www.yournavigation.org
it creates enough points

**Comment by Josp1337** [comment]
Ok i will try and give you a feedback ! BTW thanks for the quick reply ! its appreciated !

**Comment by Josp1337** [comment]
Cool site but cannot create offroad track. Thx again i will try finding a better GPX creator.

**Comment by kalamera** [comment]
try this one: http://www.gpsies.com/createTrack.do
just select the "shoe" and check the "follow roads" option.
after you set the track points you need to export the track to GPX file below the map.
in the export options use the "middle" track simplification.

**Comment by Josp1337** [comment]
thanks !!! I will try this one ! i'll give you feedback after trying !
