### ISSUE TITLE
New banning from Niantic: Pokemon flee

### ISSUE THREAD

**Issue by YouGamePlayHD** [NoxxDev/NecroBot#169]
I have a suggestion about softban removal.
They deal two kinds of softbans:
1) The normal one (no interaction) which gets detected and removed by the bot. CHECKED
2) The "Pokemon-Flee-Ban" which can't be detected. You can still collect PokeStops, but there is a major problem with encountering wild pokemon (sniped pokemon): They all flee. The bot is detecting softbans by looting PokeStops successfully or not, That's why the ban cannot be detected. My suggestion is to add a feature that can remove this new ban. I'd suggest creating a new possibility for detecting softbans in the config:

`softban-pokemon-flee-streak: 8`
That would mean that the bot tries to remove the ban after 8 pokemon have fled in a row.
 

Thank you for continuing this awesome bot! ;D

**Comment by CHRNY** [comment]
You can't remove catchflee unless you stop the bot and take a break from botting for a few hours. The reason you are getting the catchflee errors is because you are probably botting for too long, catching too many pokemon or looting too many pokestops.

**Comment by YouGamePlayHD** [comment]
So you shouldie activate the killswitch?

**Comment by NoxxDev** [comment]
Fix
