### ISSUE TITLE
9.1 Release 

### ISSUE THREAD

**Issue by likeness123** [NoxxDev/NecroBot#170]
Currently I am using the 9.1 release. I downloaded it immediately last time. It is has the easiest code in config.json

**Comment by YouGamePlayHD** [comment]
How do u get it? I only see 0.9 release?

**Comment by likeness123** [comment]
I downloaded once it was out after about a couple of hours they took it down due to many issues. But I used it so far it is okay.

**Comment by gxa12di43yr56** [comment]
can share 0.91 release?
