### ISSUE TITLE
Login Pokemon go while necrobot running on PC at home

### ISSUE THREAD

**Issue by inclouis** [NoxxDev/NecroBot#174]
Hi all, may I know what will happen if I login my Pokemon go from my mobile phone while my bot is running on my PC at home? What will happen? Will niantic detect anything and ban me for it? Is it safe to do this? Anyone please advise thank you.

**Comment by kalamera** [comment]
just do not do that.
the bot can mimic your phone if you input all the parameters in auth.json.
you can get those parameters from AIDA64 for example.
"DevicePackageName" should be "custom" in that case.
And when you disable the GPS on your phone, you can start the PoGo app, but I would still not consider that to be safe.
