### ISSUE TITLE
building the source code and some errors

### ISSUE THREAD

**Issue by vaca1** [NoxxDev/NecroBot#175]
hi 
i download the source code and use vs2015 express
i try to build this project
but some error happened
did i miss anything?
thanks .. ( i am a beginner of vs2015) 
![1](https://cloud.githubusercontent.com/assets/21092136/17776273/5613b35c-658e-11e6-80ea-9c5b48eedf75.png)
![2](https://cloud.githubusercontent.com/assets/21092136/17776274/59abd99a-658e-11e6-87b3-53932a51f822.png)

**Comment by smoothrunnings** [comment]
@vaca1 Did you use GitHub to download the source?

**Comment by vaca1** [comment]
@smoothrunnings 
yes
git clone https://github.com/NoxxDev/NecroBot necrobot

**Comment by NoxxDev** [comment]
git clone https://github.com/NoxxDev/NecroBot.git
cd NecroBot
git submodule update --init --recursive
