### ISSUE TITLE
Delay of transfer pokemon

### ISSUE THREAD

**Issue by helpmeplease1** [NoxxDev/NecroBot#176]
Hi, 

Just want to ask any place to configure delay transfer pokemon? Cause i fell the transfer for pokemon was too fast. It capture the pokemon and transfer immediately within 1 second. I fell too fast on it.

Any place to setup this?

Thank you.

**Comment by jimkaya** [comment]
it's realy necessary?
On the phone, after catching, you can transfer the pokemon immediately on the next screen.

Maybe there is a 1 second delay in the code, but not in the config, no option to configure this.

**Comment by helpmeplease1** [comment]
I already have 3 account ban, abit scare already

**Comment by TLBM** [comment]
DelayBetweenPlayerActions in config.json seems to influence it.
