### ISSUE TITLE
New banning from Niantic: Checking for GPS altitude. 

### ISSUE THREAD

**Issue by smoothrunnings** [NoxxDev/NecroBot#177]
Niantic is checking for GPS Altitude. If the data is empty you are instantly considered to be a BOT and you are banned.

**Comment by Dreker** [comment]
https://mapzen.com/ Elevation API can fix that

**Comment by TLBM** [comment]
Prior versions had a "DefaultAltitude" option in the config.json
Would NecroBot read the <ele></ele> parts of a .gpx?
I use http://www.routeconverter.de/ for the tracks and that has the option to add the proper altitude to the trackpoints.

**Comment by ANR2ME** [comment]
Are you sure altitude causes ban? because people who plays inside a tall building may have different altitude on each floor.

**Comment by smoothrunnings** [comment]
@ANR2ME Yeap I am sure. People you play in a building are still ending Altitude data to the server, while Necrobot and other bots send no data.

**Comment by TLBM** [comment]
And the altitude in a building is alway higher than the ground level on this position.
So one could check if the altitude is much lower and asume there is no GPS in basements. -> Red Flag

**Comment by lanadelrey92** [comment]
That's the reason why i have been banned right now! My bot was set VERY good, i was at level 12 so.. not so many pokestops and pokemons but, i got permaban (can't get data from servers), This is a very HIGH PRIORITY issue

**Comment by monkeyastronaut** [comment]
Can someone please confirm and/ or fix this please? I think this should be a high priority issue

**Comment by Ev0luti0n2016** [comment]
PLEASE add an elevation option to necro and if possible, allow the settings to adjust for random values that the user can input.

Example:
    Say I live in a region where the elevation changes between 100-120. It would be nice if we can add the values of "100" and "120" so it can adjust accordingly. 


On another note....Please allow for a delay option when an egg hatches and another one is put in the incubator. If one hatches at 1:20 and another one is put in instantly, then it makes it look suspect. 

I like the option for random values to be used here as well, so it can't be detected that we all wait 90 seconds to put an egg in each and every time.

**Comment by psicrest** [comment]
To emulate a humanlike behavior, the altitude needs to deviate randomly.

**Comment by vlalo001** [comment]
Dev here, just cloned this fork.

First, I need to confirm if 0.9.1 is actually sending a null value for altitude.

If it is, I think best long-term solution is to implement some API that returns altitude based on current latitude / longitude.

However, easiest solution of course is to just generate and store a random altitude value in a float (with restrictions on the value that is generated, of course - we don't want to be 30,000 ft. in the air one moment, then in the center of the earth the next).

Anyways, will begin to research and work on this issue tonight.

**Comment by psicrest** [comment]
I was thinking that Necrobot might be leaking some unique request header from ferox api (probably need to run wireshark to confirm). Because I experimented on two different pokemon bot. One compiled in java and necro running at the same time on two seperate vps, with the same gps position, same config specially walkspeed and turned off sniping. Necrobot got banned after 24 hours while the bot compiled in Java is still running. Another difference also was the java version is randomly changing its altitude with -5/+5 meters.

**Comment by NoxxDev** [comment]
altitude is random set 

`await session.Navigation.Move(new GeoCoordinate(pokeStop.Latitude, pokeStop.Longitude,
                        LocationUtils.getElevation(pokeStop.Latitude, pokeStop.Longitude)),`

`public static double getElevation(double lat, double lon)
        {
            Random random = new Random();
            double maximum = 11.0f;
            double minimum = 8.6f;
            double return1 = random.NextDouble() * (maximum - minimum) + minimum;

            return return1;
        }`

**Comment by TLBM** [comment]
Getting a Navigation API Key I noticed there is also a Google Maps Elevation API which we could possibly use.

**Comment by cuongomega** [comment]
does this new v0.9.2 fixed this problem ? i has it running for like 1 hrs and it still working and it does walk more like a human now.

**Comment by ANR2ME** [comment]
double maximum = 11.0f;
double minimum = 8.6f;

These values should at least be user defined instead of hardcoded if the bot didn't get altitude from API, right? since different regions may have different minimum altitude.

PS: I can run the bot more than 24 hours without getting any issue, not even softban, so i don't think altitude causes a ban (yet) at the moment. 
Running bot 24 hours/day without breaks time might have a higher chance to get banned than altitude.

**Comment by dayshake** [comment]
@ANR2ME Just wait. It will happen eventually. No matter how careful you are.

**Comment by Eightbitlife** [comment]
@psicrest which java bot are you using?

**Comment by psicrest** [comment]
​@Eigthbitlife - Pokebot ninja i think, just look for it on ownedcore its
the only bot with "ninja" on it hahaha. Its still running as we speak.​
