### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by tonigino2** [NoxxDev/NecroBot#178]
Hi, i have a question, how can i bot more accounts contemporary without getting ip banned?

**Comment by ausscheider** [comment]
use proxy

**Comment by tonigino2** [comment]
How?

**Comment by smoothrunnings** [comment]
@tonigino2 1 bot per IP. So you will need use a proxy or vpn if you want to use multiple bots.

**Comment by tonigino2** [comment]
@smoothrunnings Oh okay but how can i activate the proxy?Is there a tutorial on internet?
