### ISSUE TITLE
Evolve doesn't stop if "EvolveKeptPokemonsAtStorageUsagePercentage" is changed to lower value and Bot restarted

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#181]
### Expected Behavior
Check "EvolveKeptPokemonsAtStorageUsagePercentage" on startup.

### Actual Behavior
"EvolveKeptPokemonsAtStorageUsagePercentage" on startup ignored if evoling already is running.

### Other Information
Version: 0.9.0

Also, where does the Bot note that evolving was started?

**Comment by NoxxDev** [comment]
check v0.9.6
