### ISSUE TITLE
Adding MinPokemonsCatched delay for sniping.

### ISSUE THREAD

**Issue by fedyay** [NoxxDev/NecroBot#184]
There are thoughts that Ninatic could probably be checking distance between X last caught pokemons spots. So I think it might be a good idea to delay next snipe before Y pokemons are caught near your starting location.

**Comment by smoothrunnings** [comment]
@fedyay They are probably checking everything. Ninatic has years of development in people using bots on their games. So Ninatic isn't some new company that hasn't any experience when it comes to cheaters. lol
