### ISSUE TITLE
Language update for Bahasa "id"

### ISSUE THREAD

**Issue by iwean** [NoxxDev/NecroBot#186]
Hi, I'm updating language for Bahasa "id"

Thx

[translation.id.zip](https://github.com/NoxxDev/NecroBot/files/425856/translation.id.zip)

**Comment by wakrad** [comment]
you can use PR

**Comment by iwean** [comment]
PR? What do you mean by that?

**Comment by iwean** [comment]
Done! Please check my PR. Thx...
