### ISSUE TITLE
After run 0.9.1 

### ISSUE THREAD

**Issue by ausscheider** [NoxxDev/NecroBot#187]
[22:25:26] Pokemon Servers might be offline / unstable. Trying again...
[22:25:27] Error: System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.Sockets.SocketException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 144.76.224.55:80
   bei System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.HttpWebRequest.GetResponse()
   bei System.Xml.XmlDownloadManager.GetNonFileStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   bei System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   bei System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   bei System.Xml.XmlTextReaderImpl.FinishInitUriString()
   bei System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   bei System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   bei System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
   bei System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   bei PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(GeoCoordinate start, GeoCoordinate dest) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:Zeile 24.
   bei PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:Zeile 17.
   bei PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:Zeile 33.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:Zeile 68.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 56.

**Comment by ausscheider** [comment]
v.0.9.0 works perfect

**Comment by Shadow-MasterTf** [comment]
Im getting the same. First the auto update failed then i manually installed v0.9.1 and got the same error

**Comment by RavenHome1** [comment]
same here, it says requesting human distance for pokestop then goes on a loop again

**Comment by NoxxDev** [comment]
Delete folder bot and download

**Comment by RavenHome1** [comment]
@NoxxDev just downloaded a clean copy with a new config, still getting the issue

**Comment by naor173** [comment]
what is the password?

**Comment by Dexter145** [comment]
Exact same here, clean copy.

**Comment by Shadow-MasterTf** [comment]
Yep same here.

**Comment by YouGamePlayHD** [comment]
Same. Sometimes it seems to work. But it takes ages to load one pokestop?

**Comment by iDeadSmack** [comment]
Same thing, clean copy, changed default location 3 times. Error still there.

**Comment by destructi6n** [comment]
Same, worked for a couple pokemon and get the web socket exception. Possible to rollback to 9.0 til 9.1 issues are fixed/stable? If you need help let me know.

**Comment by YouGamePlayHD** [comment]
There is a major error in the code, I suppose...

**Comment by Dexter145** [comment]
Now i'm getting this error: "[22:48:11] (ERROR) Pokemon Servers might be offline / unstable. Trying again..." before the requesting human distance.

**Comment by frax20** [comment]
Just download again the 9.0 follow the process as a new configuration.
After you put the lat and long fast close before it start to search for an update.
Go to config.json open it with notes and put false on checkforupdates and autoupdate.

**Comment by Josp1337** [comment]
same error here too with a fresh configured copy of 9.1 .....

**Comment by ausscheider** [comment]
@frax20 this is not the problem

i think i have the problem. the yournavigation.org is to slow. show at my log: 
.............. Error: System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.Sockets.SocketException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 144.76.224.55:80 ..................

**Comment by frax20** [comment]
@ausscheider we can't fix the problem of the 9.1 version by ourself so i explained how to go back to 9.0 .

**Comment by YouGamePlayHD** [comment]
So the hoster is too slow?

**Comment by ausscheider** [comment]
@frax20 ahh sorry, i read to fast and not the best english from me ;)
@YouGamePlayHD  i think so

**Comment by Dexter145** [comment]
There are two errors, one with a connection to 144.76.224.55 before Request human distance of pokestops... and a different one after Request human distance of pokestops...

**Comment by YouGamePlayHD** [comment]
Both having the same logs..

**Comment by YouGamePlayHD** [comment]
It looks like the servers are overwhelmed xD

**Comment by frax20** [comment]
@YouGamePlayHD you mean "Necrobot" servers or "Niantic" one?

**Comment by YouGamePlayHD** [comment]
Necrobot

**Comment by YouGamePlayHD** [comment]
too many people trying the new release :D

**Comment by frax20** [comment]
@YouGamePlayHD Not possible, i'm using the 9.0 version and it working fine.

**Comment by iDeadSmack** [comment]
nah, if it was so, it would happen on the other releases too. Don't you think?

**Comment by ausscheider** [comment]
144.76.224.55 <--- i think this is not necrobot ;)

**Comment by YouGamePlayHD** [comment]
yeah with me too...

**Comment by YouGamePlayHD** [comment]
what happens if you open this on browser?

**Comment by YouGamePlayHD** [comment]
YourNavigation?!?!

**Comment by YouGamePlayHD** [comment]
great, so 0.9.1 uses a new system: YourNavigation...

**Comment by ausscheider** [comment]
this is a IP from germany:

http://144.76.224.55.ipaddress.com/

**Comment by Sayton** [comment]
Same issue :/

**Comment by iwean** [comment]
[04:28:30] Pokemon Servers might be offline / unstable. Trying again...
[04:28:31] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(GeoCoordinate start, GeoCoordinate dest) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 24
   at PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 17
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56

**Comment by iDeadSmack** [comment]
they have fixed it. Is it working? or it will be released a new version?

**Comment by ridalarry** [comment]
I think the dev is working on it you can see by his latest commits

**Comment by iDeadSmack** [comment]
it's working again guys. have fun

**Comment by NoxxDev** [comment]
Errors fixed in release v0.9.2

**Comment by YouGamePlayHD** [comment]
Thx man
