### ISSUE TITLE
0.9.1 update not working

### ISSUE THREAD

**Issue by pogodpi** [NoxxDev/NecroBot#188]
after config and auth on fresh download, the bot keeps showing "request human distance of pokestops" and not making anyother process further.. any idea??

**Comment by userix** [comment]
same

**Comment by wakrad** [comment]
use 9.0 and set auto update to false until 9.1 fixed

**Comment by Kimmz** [comment]
I got this error only once, now after that I get this

http://imgur.com/a/lYkVH

**Comment by Dexter145** [comment]
https://github.com/NoxxDev/NecroBot/issues/187

**Comment by CHRNY** [comment]
0.9.1 is working. Just download the 0.9.1 release and MANUALLY copy your old config.json / auth.json settings into the new 0.9.1 config.

When I say manually, I mean go through each setting one by one with your old config and replace the values.

**Comment by zzzz9999** [comment]
Also 0.9.1 having problems.
And it renamed 99%of the files to .old (not only .json but also .dll's, xml's) ...

**Comment by Kimmz** [comment]
@CHRNY 
Or just use 0.90 with extremely little effort.

**Comment by CHRNY** [comment]
@Kimmz 
Well some people might have use for the killswitch options implemented in 0.9.1. The config.json file has also been reorganized for easier use. But whatever floats your boat I guess.

**Comment by yukun257** [comment]
how do you disable the auto update?

**Comment by CHRNY** [comment]
@yukun257 Release > Config > config.json > "AutoUpdate": false

**Comment by kw12xx** [comment]
I edited every value by hand after letting NB generate a default config/auth. I get the same error. If i go through the step-by-step in the bot itself, i still get the same issue. 

Have not been able to get .91 to work.

**Comment by inkal12** [comment]
hey guys, whats the best config to avoid the ban? can you help me?

**Comment by frax20** [comment]
# HOW TO GO BACK TO 9.0 VERSION TILL 9.1 WILL BE STABLE

Just download again the 9.0 version;
Open it and follow the process as a new configuration;
Put the Latitude and Longitude desidered press ok and fast close Necrobot before it start to search for an updated version;
Go to Config folder then open with Notes "config.json" file and put false on "checkforupdates" and "autoupdate".

PS: sorry for my english

**Comment by yukun257** [comment]
I got it running, but it doesnt seem to be catching anything

**Comment by NoxxDev** [comment]
Errors fixed in release v0.9.2
