### ISSUE TITLE
Release v0.9.1 - after extract there are missing files

### ISSUE THREAD

**Issue by zzzz9999** [NoxxDev/NecroBot#189]
In Release dir, only cert.pfx, NecroBot.exe and NecroBot.exe.config

**Comment by iwean** [comment]
All compile to exe file ..... I guest

**Comment by zzzz9999** [comment]
don't think so. what about the dependencies? RocketAPI, etc ...

**Comment by frax20** [comment]
# HOW TO GO BACK TO 9.0 VERSION TILL 9.1 WILL BE STABLE

Just download again the 9.0 version;
Open it and follow the process as a new configuration;
Put the Latitude and Longitude desidered press ok and fast close Necrobot before it start to search for an updated version;
Go to Config folder then open with Notes "config.json" file and put false on "checkforupdates" and "autoupdate".

PS: sorry for my english

**Comment by NoxxDev** [comment]
Errors fixed in release v0.9.2
