### ISSUE TITLE
Can't start bot.

### ISSUE THREAD

**Issue by FacuM** [NoxxDev/NecroBot#19]
**Expected Behavior**

Successful bot startup.

**Actual Behavior**

Bot not starting.

**config.json**

http://pastebin.com/cdG1GBvU

**Steps to Reproduce**

Download the bot latest release, unpack it and try to start it up after setting it up using NecroConfig.exe .

### Other Information
Version: 0.8.8
Windows Version: Windows 7 Ultimate x64
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Everything.

**Comment by NoxxDev** [comment]
What exactly happens?
