### ISSUE TITLE
v.0.9.1 not recommend

### ISSUE THREAD

**Issue by lautpelaut** [NoxxDev/NecroBot#193]
to much bug and script error

**Comment by vlalo001** [comment]
Which bug? Which script error? Post details and screenshots to help us fix. Thanks

**Comment by de81815** [comment]
08:06:42] Potential Evolutions: 0
[08:06:42] Incubator status update: 5.05km left
[08:06:44] Amount of Pokemon Seen: 110/151, Amount of Pokemon Caught: 110/151
[08:07:29] Pokemon Servers might be offline / unstable. Trying again...
[08:07:30] Error: System.Xml.XmlException: 遺漏根元素。
   於 System.Xml.XmlTextReaderImpl.Throw(Exception e)
   於 System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   於 System.Xml.XmlTextReaderImpl.Read()
   於 System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   於 System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   於 PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(GeoCoordinate start, GeoCoordinate dest) 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs: 行 24
   於 PoGo.NecroBot.Logic.Utils.LocationUtils.RequestDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs: 行 17
   於 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass5_0.<GetPokeStops>b__1(FortData i) 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: 行 274
   於 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   於 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   於 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   於 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<GetPokeStops>d__5.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: 行 271
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   於 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: 行 62
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   於 PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs: 行 68
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 於 E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs: 行 56

**Comment by ridalarry** [comment]
I am having the same issue

**Comment by midascodebreaker** [comment]
same issue

**Comment by lautpelaut** [comment]
yup same issue like @de81815

**Comment by NoxxDev** [comment]
New release fix errors
