### ISSUE TITLE
Does the Bot move on while catching is in progress?

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#196]
### Expected Behavior
stop moving, throw, catch, move again

### Actual Behavior
 throw, catch (, miss, catch, ...), jump to new location (in Pokemon Bot Visualiser 1.0.8)

Does the Bot really move on while catching is in progress or does the websocket just don't get the location-info in the meantime?

Have noticed it yesterday in v0.9.0 and today in 0.9.1 on a gpx-path. Had no visualiser before.

    "DelayBetweenPlayerActions": 20000,
    "WalkingSpeedInKilometerPerHour": 3.94,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,

**Comment by NoxxDev** [comment]
Fixed in release [v0.9.2] (https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.2)

**Comment by TLBM** [comment]
Thank you!
Just tried v0.9.2 and the location cursor still jumps (to the next waypoint after) some catches in a row. :(
