### ISSUE TITLE
StartupWelcomeDelay not working anymore since 0.9.2

### ISSUE THREAD

**Issue by Dexter145** [NoxxDev/NecroBot#197]
### Expected Behavior
Bot pauses after showing the location

### Actual Behavior
Bot just keep going further.

### Your config.json
"StartupWelcomeDelay": true,

### Other Information
Version: 0.9.2
Windows Version: Windows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by NoxxDev** [comment]
Fixed in new release
