### ISSUE TITLE
force google api key?

### ISSUE THREAD

**Issue by kaijajan** [NoxxDev/NecroBot#198]
built latest version just pulled from github. the following message showed up after fresh setup using ptc account. the latest version forbidden to run ptc account. weird!

You need to configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key

**Comment by NoxxDev** [comment]
Yes, mandatory for the bot trace routes

**Comment by augustowas** [comment]
how to make?

**Comment by NoxxDev** [comment]
https://github.com/NoxxDev/NecroBot/wiki/Config#googleapikey-value

**Comment by AJAmz** [comment]
I have made one what now ?

**Comment by robzork** [comment]
what to do when i made one ?

**Comment by antfuentes87** [comment]
@NoxxDev If you want help closing these type of issues (that are not really issues), I will be more than happy to help. It gets old after awhile, seeing my inbox filled up with useless issues. When you clearly state everything in the wiki.

**Comment by AJAmz** [comment]
whenever i press a key it closes i tried with my key in and it didnt work

**Comment by rjcute123** [comment]
read the guide in the wiki... and it is very easy!

**Comment by AJAmz** [comment]
can you link the wiki i cannot seem to find it
