### ISSUE TITLE
After entering my Google API key I get the following error. 

### ISSUE THREAD

**Issue by smoothrunnings** [NoxxDev/NecroBot#201]
I am not sure what else I am missing, I clicked the Google link in the wiki and created a key, then copy and pasted it into my auth replacing the "null" and saved it. Then I launched 0.92 and got this error. 

![error](https://cloud.githubusercontent.com/assets/6445945/17796307/672f08ae-658d-11e6-8291-c7751a5da638.jpg)

**Comment by plasmasoul** [comment]
did you put the " " on the key?

**Comment by ridalarry** [comment]
I had the same error, and its fixed when I added the quotation marks like this "API KEY"

PS. Please close the issue if its solved.

**Comment by badumts** [comment]
ive got the same problem, addet " " on my API still not workin

**Comment by drakoinstheking** [comment]
I've also tried "" and whenever I hit enter, it exits everything

**Comment by male2961** [comment]
excuse me!!

ahm.. a little question bout api key!!

where should i put the key?? the api key i mean!!

thanks for helping..

**Comment by plasmasoul** [comment]
@male2961 Look for  "GoogleAPIKey" in the auth.json file

**Comment by male2961** [comment]
@plasmasoul  thanks men.. and its working!!

**Comment by sk8gp** [comment]
what is the google apy key?

**Comment by ridalarry** [comment]
https://github.com/NoxxDev/NecroBot/wiki/Config#googleapikey-value

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
View new release
