### ISSUE TITLE
Google Api Key - It's not necessary

### ISSUE THREAD

**Issue by Trankilis** [NoxxDev/NecroBot#202]
Hi,

Google Api key it's not necessary, because without it you'll have a free quota of 2500 requests and Google control it by IP.

In other words, just change IP for more 2500 requests.

**Comment by Kimmz** [comment]
and for the people who cannot change their IP
And dont want to use a VPN/Proxy?

**Comment by Trankilis** [comment]
But, don't worry yesterday I was workin on same Features of release 0.9.2.

I'll make a pull request. One of my changes is to make Cache from Google Directions service for more requests

**Comment by Trankilis** [comment]
@Kimmz for these people?

First of all Google Free API key has quota of 2500 request limit. 

If you don't has a Business plan and don't want to change your IP nor your VPN, just wait for my Pull request. 

In this cenario the bot will move in straight line, like was in release 0.9.0

**Comment by Skolzack** [comment]
Can't use 0.9.2, wtf are you guys doing? no one test it before release?

**Comment by bulubebek** [comment]
@Skolzack devs is working hard to make necro better. its released as-is - without any guarantee it will work or not. you used it with your own risks. so stop blaming them for this.

**Comment by Kimmz** [comment]
https://gyazo.com/6f7c7503d9a5eba6a0c436bc4709b1fb

0.9.2 FINE FOR ME

**Comment by thomatbu** [comment]
@Skolzack  Don't blame devs, you can't use the bot because you're stupid or retarded. Everyone can run the bot except you. You idiot!

**Comment by NoxxDev** [comment]
It is not necessary to have the google API, if you do not want to use the dimension, just disable google routes in json.
