### ISSUE TITLE
[Request] Make human walking not 100% straight line

### ISSUE THREAD

**Issue by ridalarry** [NoxxDev/NecroBot#203]
[Request] Make human walking not 100% straight line

**Comment by AndikaTanpaH** [comment]
I'm agree @ridalarry 
look this, if the pointer cannot reach the pokestop.... and try to softban.... but its not a sofban, just cannot reach the pokestop (there is no way to go there)
![routeerror](https://cloud.githubusercontent.com/assets/15794749/17796416/84a5864e-65ea-11e6-90a5-3573e0b80a2d.jpg)
@NoxxDev please see my screenshot, may can you help this issue?

**Comment by ridalarry** [comment]
I didn't mean that as it won't change much, but maybe use it to not be flagged as a bot walking.

**Comment by ridalarry** [comment]
more like this https://gyazo.com/8cd295fc26771d245681ed00e5b5588e
