### ISSUE TITLE
Suggestion. Please Read it guys.

### ISSUE THREAD

**Issue by iDeadSmack** [NoxxDev/NecroBot#205]
With the new update, i saw a BIG, HUGE problem with the Killswitch. The idea is great, and now we are more protected then ever. But, it's usless now... The Necrobot like it is now, probably is the worst out there, why?
 Because the Killswitch, close the Bot after the limite reached, and it doesn't open it in the next hour. So, if we aren't by our computer, the bot will just close, and never "botting" again, untill we manual open it.

My suggestion, make the range of time from kill switch to 8/12/16/24 hours, so the math should be:
if 8 hours set (1000/8 = 125 - set to 120 per hour) something like this, and, if the switch is activated, in the next hour turn the bot on again.

I know that this will be a BIG improvement, but it would make this feature perfect. Hope you guys like the idea. ^^

Ps: Sorry for my english, hope is good enough to make me clear, and my idea.

**Comment by YouGamePlayHD** [comment]
Great idea

**Comment by NoxxDev** [comment]
KillSwitch changed, check v0.9.5 or upper
