### ISSUE TITLE
[REQ] Catch delay interval

### ISSUE THREAD

**Issue by nutsky** [NoxxDev/NecroBot#206]
can we set it to catch pokemon like after 10-20 seconds every catch and a 5-10 seconds delay every missed/escape

**Comment by bulubebek** [comment]
`"DelayBetweenPokemonCatch": 10000,`

**Comment by nutsky** [comment]
@bulubebek thanks did not see it

**Comment by bulubebek** [comment]
@nutsky you are welcome. please close this issue. :)
