### ISSUE TITLE
 there I missed? Please help me

### ISSUE THREAD

**Issue by yahudaay** [NoxxDev/NecroBot#21]
![aassd](https://cloud.githubusercontent.com/assets/21029634/17654121/1c95c688-62d2-11e6-836f-6a1a92766453.png)

**Comment by GioBregs** [comment]
Same issue with me
![necrobot](https://cloud.githubusercontent.com/assets/21030261/17654539/b525adb0-62d6-11e6-8f2c-02b34c7b100a.png)

**Comment by Titansz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21030724/17655083/08558ed6-62d4-11e6-8131-cf05a670a5ca.jpg)

Have a same problem here. Is there anyone can share the setting of NecroConfig.exe?

Thanksz

**Comment by NoxxDev** [comment]
Missing dll
Download and install
[Net Framework 4.6.2] (https://www.microsoft.com/en-us/download/details.aspx?id=53345)
[Visual C++ Redistributable for Visual Studio 2015] (https://www.microsoft.com/en-US/download/details.aspx?id=48145)

**Comment by GioBregs** [comment]
Cheers installing them now will repost my results

**Comment by yahudaay** [comment]
Thanks Work....
