### ISSUE TITLE
Unable to do anything with v0.9.2

### ISSUE THREAD

**Issue by painfulessence** [NoxxDev/NecroBot#210]
The v0.9.2 update fixed the infinite loop issue i was having but now its created another one which is much more irritating than the first. With this update it wont catch pokemon or travel to pokestops. Does anyone else have this issue or know how to fix it?

![necrobot](https://cloud.githubusercontent.com/assets/21115612/17796857/f3454c8c-6591-11e6-85c3-d275024178db.png)

**Comment by knguyen0105** [comment]
Yes, I got the same issue. Now I'm back to 0.90 and everything works.

**Comment by drakoinstheking** [comment]
Whenever i try 9.0 it closes itself.

**Comment by Skolzack** [comment]
10 minutes using the 0.9.2 version with a new account and i'm softbanned using default configs.. These guys are destroying the real Necrobot :/

**Comment by smoothrunnings** [comment]
@Skolzack check the settings, the variable throwing was disabled, and one of the other important options was disabled too, can't think of it off the top of my head.

**Comment by Skolzack** [comment]
@smoothrunnings I don't know what to do anymore dude.. I was with my last account level 27 botting on necrobot 0.8.8 with 10km/h, inside of the limits of 1k pokemons and 2k pokestops with 0 softbans and suddenly it got permaban. I don't know how to bypass Niantic anymore, they are winning.

**Comment by Fr3akGam3r** [comment]
@Skolzack Where was your bot when you got Softbanned? it could be that the bot try to get a Pokestop what is out of range and he could not get in the near but try to collect this error would be like a softban but isn't one D: also i try the bot with standart config and my acc get not softbanned

**Comment by monkeyastronaut** [comment]
I also got softbanned with the new 0.9.2, can u guys fix this please? the previous version was more stable

And is GPS Altitude added?

**Comment by Skolzack** [comment]
@Fr3akGam3r Walking at 4.16km/h.. I'm sure that wasn't softban because of the speed.

**Comment by Fr3akGam3r** [comment]
@Skolzack i mean where did you bot (Centrel Park,Washington DC or some else) i know that it isn't the speed also with the permanently change of the speed the bot is save in this aspect i think ^^

**Comment by Skolzack** [comment]
@Fr3akGam3r I'm botting at the center of Rio de Janeiro. With the Olympic Games there is a good place to stay. I'm from Brazil btw.

**Comment by iamcmc** [comment]
same as first floor

**Comment by painfulessence** [comment]
How has everyone else gotten past the infinite loop issue ive been having? I tried v0.9 but that just crashes. I am using default config as well

**Comment by maxcamacho** [comment]
can someone help with the google api key situation?

**Comment by Skolzack** [comment]
@maxcamacho If you like or love your account, just don't use 0.9.1 nor 0.9.2 version.

**Comment by cuongomega** [comment]
i use v0.9.2 and it works properly. 
i got the same problem like the first post, but it continues working after that

**Comment by monkeyastronaut** [comment]
my 0.9.0 keeps updating to the latest version, is there a way to disable the update?

**Comment by cuongomega** [comment]
@monkeyastronaut open config.json
    "CheckForUpdates": false,
    "AutoUpdate": false,

**Comment by Fr3akGam3r** [comment]
@monkeyastronaut if you want to use the latest version create here a GoogleApiKey and paste them into your auth.json https://developers.google.com/maps/documentation/javascript/get-api-key
@Skolzack dont be so hard the Developer work hard and programming isn't that easy especial AI Programming is very hard :/

**Comment by gb410** [comment]
Had to go back to 9.0. With 9.2, I get a softban within 5 minutes. With 9.0 I can run around for hours at 100km/h and never get a single softban. With 9.2, softban in minutes even at 10km/h.

**Comment by painfulessence** [comment]
@gb410 how did you get 9.0 running? I download it and disable all updates, then enter my info but when I open it, it proceeds to auto update

**Comment by maxcamacho** [comment]
Not my personal account. I have the key just having issues placing it in the code.

**Comment by Fr3akGam3r** [comment]
@gb410 i dont know what you did in the config but my bot on 9.2 run 1 hour with no problem ^^ also you know when you run with 100km/h and they notice that you will get a perma ban instead of a softban? they give sometimes softbans because they dont sure if you are an bots or a normal dude and they dont want to ban a normal guy :) also they posted that on twitter http://pokemongolive.com/en/post/cheating-bans/

**Comment by cuongomega** [comment]
@gb410 i use it for roundly 2 hrs now, but still no problem occures. 
My config: speed: 10km, no sniping, etc

**Comment by gb410** [comment]
@painfulessence I just these settings and it stays on 9.0:

  "CheckForUpdates": false,
  "AutoUpdate": false,

**Comment by Fr3akGam3r** [comment]
@gb410 okay its your account it will probably not run more than 6 hours so

**Comment by gb410** [comment]
@Fr3akGam3r Time will tell, but I've been botting this account for 5 days now and it never had a problem until the softban from 9.2. If it gets perma-banned now, I won't know that it wasn't because it got flagged because of the 9.2 softban.

**Comment by Fr3akGam3r** [comment]
@gb410 thats right but you can test it if you run another bot on a other account with the same settings ^^

**Comment by AndikaTanpaH** [comment]
Look my screnshot.. its not sofban, but just cannot reach pokestop.. its no way to going there.. "Pokestp to far blabla" but the 0.9.2 read this as sofban. If you try restart the 0.9.2 can running again.
Need a new task to force the path/way if cannot reach pokestop.

![routeerror](https://cloud.githubusercontent.com/assets/15794749/17798171/40852a50-65f9-11e6-9038-ea3432721402.jpg)

**Comment by Fr3akGam3r** [comment]
@AndikaTanpaH i though that thats could happen can the bot not search for a other way when it cant reach a pokestop?

**Comment by cuongomega** [comment]
@AndikaTanpaH i think the problem is that pokestop has been spinned under 5 mins ago

**Comment by AndikaTanpaH** [comment]
@Fr3akGam3r yes, like that.. need to force another way or another near pokestop...

@cuongomega no 5 mins ago.. look route from the left.. the bot start from there..

**Comment by gb410** [comment]
@AndikaTanpaH I think this may be the problem I was having. The softban message is misleading. I think it's the new the "human route" thing that is messing up. Does anyone know if there's a way to turn that off?

**Comment by Fr3akGam3r** [comment]
@gb410 you can turn that off in your settings but !!!Warning!!! if you do that will force that your Character will walk straight cross Buildings and stuff that is very obvios a bot when it walk cross buildings xD

**Comment by cuongomega** [comment]
@AndikaTanpaH #381, may be thats the problem/ found a problem with 0.9.2, pokestop is too far away (from the road)

http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/572524-necrobot-fork-updated-26.html#post3566154

**Comment by nutsky** [comment]
@Fr3akGam3r is it also dangerous if i am botting inside a mall? the mall has an insane respawn rate of pokemon and i cant resist botting there. i can bot fine before this update

**Comment by HoangQuy1998** [comment]
so can anyone fix the issue in the first post

**Comment by painfulessence** [comment]
@HoangQuy1998 i deleted all the files and re-downloaded v0.9.2 and entered all my info back in. It's works fine for me again, and I didnt receive any bans either

**Comment by HoangQuy1998** [comment]
@painfulessence i redownload it over and over again but it still the same, do i need to change anything in the setting

**Comment by jimkaya** [comment]
you have to do a lot in the settings... for every new release... and i think thats the biggest problem because some people can not even find the config file.

**Comment by HoangQuy1998** [comment]
@jimkaya ok, thanks :))

**Comment by mo0ojava** [comment]
@AndikaTanpaH @cuongomega I'd recommend using custom gpx-files over "auto-intellgence". You have way more control over what's happening. Here's a really easy and quick place to create them: 
[wtracks](https://wtracks.appspot.com/)
Just make sure to check "don't save metadata" when saving your track and you're fine to go right away.

**Comment by dtnazry** [comment]
Running back on v.09..donwload v.09 zip..then key in all your details as usual until the longitude and latitude..before press the enter, please disable your internet connection..the systems will automatically make new conf files..open up the folder and change from true to false for the updates path.

cheers..

**Comment by jayomu** [comment]
This is not a forum.
