### ISSUE TITLE
using VMware to use multi bot

### ISSUE THREAD

**Issue by khairulpetrcech** [NoxxDev/NecroBot#215]
beside using proxy,can i use vmware to use multibot (in my PC and the virtual machine) and avoid IP ban?

**Comment by bulubebek** [comment]
as long as its NAT-ed or bridged to your current network with same IP address, you still can get IP ban.

**Comment by Fr3akGam3r** [comment]
@khairulpetrcech where did you get that lol if you using a Vm the VM yours your internet connection to get to the internet ether ... you can duplicate the bot but change the phone model than it look like it is in the same network but a other phone ^^

**Comment by bulubebek** [comment]
answered. please close this issue. :)

**Comment by khairulpetrcech** [comment]
>wahahaha thanks guys..didnt know that keke...for phone model change,,just change the phone model ? and others leave as it is ?

Cheers,
khai

**Comment by khairulpetrcech** [comment]
wahahaha thanks guys..didnt know that keke...for phone model change,,just change the phone model ? and others leave as it is ?
Cheers,
khai

**Comment by Fr3akGam3r** [comment]
@khairulpetrcech in your auth.json you got these settings ` "DeviceConfig": {
    "DevicePackageName": "lg-g4",
    "DeviceId": "ec3b2d68e3e1d9ea",
    "AndroidBoardName": "msm8992",
    "AndroidBootloader": "",
    "DeviceBrand": "lge",
    "DeviceModel": "VS986",
    "DeviceModelIdentifier": "p1_vzw",
    "DeviceModelBoot": "qcom",
    "HardwareManufacturer": "LGE",
    "HardwareModel": "VS986",
    "FirmwareBrand": "p1_vzw",
    "FirmwareTags": "release-keys",
    "FirmwareType": "user",
    "FirmwareFingerprint": "lge/p1_vzw/p1:5.1/LMY47D/151541507ff1b:user/release-keys"
  }
}` search for these information about a other phone than a lg-g4 and replace the lg-g4 information with the from the new phone

**Comment by khairulpetrcech** [comment]
thanks @Fr3akGam3r ..but i seem cant get certain info (ex ,boot,identifier etc) of my device,,for those value,,can i use info from the default value ? sorry for noob question..

cheers,
khai

**Comment by gabi92a** [comment]
You need to use a diferent proxy in every bot, is the safest way.

**Comment by khairulpetrcech** [comment]
> You need to use a diferent proxy in every bot, is the safest way.

yeah thinks so..will try use it..coz using 2 bot with differernt mobile settings even got me IP ban
