### ISSUE TITLE
How to reduce/avoid soft ban

### ISSUE THREAD

**Issue by male2961** [NoxxDev/NecroBot#217]
Good Day!!

i had some issue bout soft-ban can anyone teach me how to avoid this issue..

looking forward to anyone..

thanks for some future advices!!!

**Comment by Fr3akGam3r** [comment]
dont put the movementspeed to high also dont use pokesniper and you should not get one

**Comment by male2961** [comment]
ok.. can you please chech my config here it is and im not sniping..

"WalkingSpeedInKilometerPerHour": 4.16,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000

**Comment by daproject85** [comment]
+1  no sniping, getting softbanned

**Comment by Fr3akGam3r** [comment]
@male2961 Check this out it could be that your "Softban" is only a Software error try to delete your lastpos.ini in your Config folder and you should nice to go ^^ (because your config is fine)
https://puu.sh/qGvY2/435d552c97.jpg

**Comment by male2961** [comment]
i didnt do sniping.. look guys!!

SnipingSettings": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false

**Comment by male2961** [comment]
@Fr3akGam3r  i try what you said.. delete all the post.. ill update if the s-ban was gone!! thanks guys really appreaciate..

-hail intinct.. haha..

**Comment by male2961** [comment]
@daproject85 thanks too men

**Comment by male2961** [comment]
@Fr3akGam3r i delete and it work.. haha..

**Comment by Fr3akGam3r** [comment]
@male2961 i told you ^^ it is a software error not a softban :)

**Comment by male2961** [comment]
haha.. still S-ban haha.. ill do the delete-post and still S-ban..

**Comment by male2961** [comment]
@Fr3akGam3r what should the link/image/jpg you sent told to?? hahaha.. can imagine what does the tuts told to!! haha..

**Comment by Fr3akGam3r** [comment]
@male2961 oh if you are still softbanned than im sorry you are really soaft banned :/ and the image show s a other post what i was talking about (i add it this time here)
![ss 2016-08-19 at 05 55 57](https://cloud.githubusercontent.com/assets/20647088/17798666/8420c90c-65d3-11e6-8bc4-c3500708174a.jpg)

**Comment by male2961** [comment]
@Fr3akGam3r haha.. i guess your right.. i am S-ban. well thanks for the big help men..
i think S-ban cant avoid or reduced. 

are u familiar with ip changer??

**Comment by daproject85** [comment]
this is an issue with the bot, I had the previous versions running with the **exact same config**. Please seriously look into this and do not just pass it on as "you are just soft banned". 

I was not previously softbanned. With in 5 minutes of running this I got softbanned

**Comment by Fr3akGam3r** [comment]
@daproject85 but why is my bot running without a problem 2 hours ? i'm not sofbanned and im using 9.2 D:

**Comment by male2961** [comment]
@daproject85 i think so.. hahaha...

**Comment by Fr3akGam3r** [comment]
@male2961 IP changer will not help against a softbann it is a account and ip ban D:

**Comment by male2961** [comment]
@Fr3akGam3r  wow that was super!! how did you do that?? ive run it for bout 10mins and it got softban..

**Comment by daproject85** [comment]
I just saw 5 other people on the discord saying the same thing

**Comment by Fr3akGam3r** [comment]
idk really idk

**Comment by male2961** [comment]
@daproject85 well i think that the payments for those who uses bots.. well its ok to got s-ban than perma ban

**Comment by male2961** [comment]
@Fr3akGam3r wow.. i think your bot has a great hiding skill hahaha.. just kidding well that was good.. hope niantics didnt detect me for about hours.. haha.. hope so

**Comment by Fr3akGam3r** [comment]
well i use the normal config and the normal place (Central Park) and all work idk what to say D:

**Comment by male2961** [comment]
@Fr3akGam3r i see.. news and some survey says so many trainers at central park.. kind of

**Comment by nutsky** [comment]
i also have softban thing, after the bot collect items from the first pokestop. i cant collect items anymore saying:

"Looting Failes: posible softban............"

**Comment by male2961** [comment]
@nutsky yeah.. same here.. that thing cant be avoid unless if you had ip changer software

**Comment by nutsky** [comment]
@male2961 i can collect fine using my phone, i guess it is not actually a softban

**Comment by male2961** [comment]
@nutsky bro its a softban but you can call it ip ban.. they ban your ip to avoid getting some stuffs in pokestops and even catch a pokemon..

**Comment by nutsky** [comment]
@male2961 i am using same ip in both my bot and my phone.

**Comment by male2961** [comment]
@nutsky yeah just i told you men.. its an ip ban for a mean time only.. but as i told you if you had an ip hider or changer or else u can override the ban and play again.. but the prob is an ip hidder/changer to change the ip and play again

**Comment by YouGamePlayHD** [comment]
I use CyberGhost

**Comment by khairulpetrcech** [comment]
to lift IP ban,just restart your wifi router..AND dont EVER use same IP on multiple bots

**Comment by hardknoxni69a** [comment]
The 24 hour limit is the problem everyone u can only collect 1000 mon and 2000 stops per in 24 hour revolving door 24 hour limit needs implementing or make a script to somehow ready all your logs to stop bot once its reached
