### ISSUE TITLE
hello how do you remove the ban ?

### ISSUE THREAD

**Issue by zakij** [NoxxDev/NecroBot#218]
hello I had a permanent ban how do I remove it?
answer me please let 'm desperate.

**Comment by Fr3akGam3r** [comment]
you cant remove a permanent ban ^^

**Comment by zakij** [comment]
:c            
But if you created a second gmail account is an app that avoid the permanent ban ???

**Comment by developnoop** [comment]
There is till now not a proven way to avoid a permanent ban. Niantic is still banning and it takes them sometimes weeks to ban a account.

**Comment by zakij** [comment]
so the best choice is to wait for the Niantic think about other things like add a new pokemon and when they do I create a second account right ???

**Comment by smoothrunnings** [comment]
@zakij Niantic isn't new when it comes to people cheating playing their games, they tried to make another game that was like Pokemon Go but not as good. People cheated then too, so they have a lot of experience. If you think they are magically going to stop or turn a blind eye one day think again.
