### ISSUE TITLE
need help configuring

### ISSUE THREAD

**Issue by djlsoccer89** [NoxxDev/NecroBot#219]
Hey guys so im all new to this and was wondering if i could get some help. So every time i put in my information for the bot, it tells me that i need a GoogleAPIKey and i got one but every time i put it in and press ENTER, the necrobot window closes. I then tried to configure the auth.jason file just like i read in the other issue comments but every time i try to open the file, it automatically closes. So if i could get a short tutorial as how to properly do all this, then i'd greatly appreciate it.

**Comment by developnoop** [comment]
Try to open the auth.json with a text editor of your choice, but not WORD! Use the windows Text Editor or something like that. Or did you mean that your editor automatically closes itself?

**Comment by thomatbu** [comment]
"your key", remember this " and " between your api key

**Comment by djlsoccer89** [comment]
@thomatbu what do u mean exactly????

**Comment by djlsoccer89** [comment]
@developnoop how would i do that exactly because when i right click the file, i dont see anything that allows me to open it, i chose internet explorer to open it but it's not working, so i guess i need to know how to change the text editor

**Comment by thomatbu** [comment]
In auth.json:

You will see the 8th line

Google API key: null

- delete "null"

- Change to this: Google API key: "dfjhsjahfufishdf"

- Remember using " before and after your key that you put.

- Come back here and help everyone. :)))

**Comment by thomatbu** [comment]
btw, try to open auth.json by using Notepad

**Comment by developnoop** [comment]
If you don't know how to open the file with a text editor, then 
i try to tell you a other way: Open Windows Notepad then say open and go to the folder where you have the bot config. click on auth.json and it should open in Notepad.

**Comment by djlsoccer89** [comment]
@developnoop @thomatbu so once i open it on Notepad and put in the GoogleAPIKey instead of the null, whats the next step? do i just save the file to somewhere?? Sorry for being such a noob

**Comment by thomatbu** [comment]
Just press Ctrl+S and close. Open the bot. Done

**Comment by djlsoccer89** [comment]
so once i did what u said and it still pops up with the same message, should i just delete the Release file, redownload it, and do what u said again???
@thomatbu

**Comment by thomatbu** [comment]
get a new api key and try again
remember that you put " before and after your api key

**Comment by djlsoccer89** [comment]
i tried it again and it didnt work but ill continue to repeat

**Comment by Jk123214** [comment]
in my Auth.json there is no "googleapikey" on line 8 so what do i do?

**Comment by ridalarry** [comment]
https://github.com/NoxxDev/NecroBot/wiki/Config#googleapikey-value This should help you and please close the issue if its solved.

**Comment by thomatbu** [comment]
delete release folder and extract again

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
View release v0.9.3
