### ISSUE TITLE
Ideas for new features - Killswitch - Pokemon Tracker

### ISSUE THREAD

**Issue by gabi92a** [NoxxDev/NecroBot#22]
Pokemon/Pokestop tracker - All Pokemon catches and Pokestop visits are logged at the top status bar. Keep an eye out for the thresholds of 1,000 pokemon/2,000 pokestops per day!
Killswitch - Going to be away from your computer? Set a killswitch value to have the bot close once a certain number of Pokemon are caught or Pokestops are looted.

Thank you for your work.

**Comment by ridalarry** [comment]
This would be great idea to add which is already added in TuringBot

**Comment by NoxxDev** [comment]
Will be added
