### ISSUE TITLE
Help! I am stucked at the GoogleAPIKey configuration

### ISSUE THREAD

**Issue by Hyperhk** [NoxxDev/NecroBot#221]
I met this message below when i downloaded the latest version. 

**You need to configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key
Program will continue after the key press...**

I went to the site and get a key, but then the program didnt continue. I tried to look for googleapikey in the config but didnt see it except a telegramapi thing which doesnt look like so. What should i do to make it work?

Thanks!

**Comment by thomatbu** [comment]
"your key", remember this " and " between your api key

**Comment by thomatbu** [comment]
In auth.json:

You will see the 8th line

Google API key: null

    delete "null"

    Change to this: Google API key: "dfjhsjahfufishdf"

    Remember using " before and after your key that you put.

    Come back here and help everyone. :)))

**Comment by ridalarry** [comment]
https://github.com/NoxxDev/NecroBot/wiki/Config#googleapikey-value this should help you how to use it.

**Comment by Jk123214** [comment]
please help i finally got the right auth.JSON but when i put in the key just how you have said and how it said to on that website Rida post it still doesnt work

**Comment by thomatbu** [comment]
show me your screenshot

**Comment by Jk123214** [comment]
![20160819_011325](https://cloud.githubusercontent.com/assets/21118018/17800640/769dafda-65aa-11e6-9ae6-535bf4b24f31.jpg)

**Comment by thomatbu** [comment]
anh when you run the bot, whhat happened?

**Comment by Jk123214** [comment]
keeps saying "you need to configure "GoogleAPIKey", get API Key in Link: https://developers.google.com/maps/documentation/directions/get-api-key
program will continue after the key press..." when i press key the window closes and nothing happens

**Comment by thomatbu** [comment]
Try to get a new key and do it again.

**Comment by Jk123214** [comment]
i have :( 3 times now

**Comment by thomatbu** [comment]
no idea about this

**Comment by Jk123214** [comment]
i guess 5th times a charm it started working now

thanks so much for all your help thomatbu

**Comment by thomatbu** [comment]
lol, you're welcome

**Comment by Hyperhk** [comment]
@thomatbu Thanks a lot bro many i have got it now but think my account has got a perma ban when i got up this morning.

**Comment by thomatbu** [comment]
which error have you seen?

**Comment by Hyperhk** [comment]
it just say probably perma banned, i couldnt log in to that account at all

**Comment by thomatbu** [comment]
so, maybe you visoted too many pokestops

**Comment by Hyperhk** [comment]
seems so, that's why i am lowering my travelling speed in the new account. coz i heard someone using 100km/hr sniping for 3 days and didnt got a ban. wuth the kill assist now i hope this account would last longer while i use 19km/h now

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
