### ISSUE TITLE
[Request] More delays and more randomness

### ISSUE THREAD

**Issue by ridalarry** [NoxxDev/NecroBot#222]
These delay options are taken from PokeMobBot I they get added I know some of them are already added. Randomizers would make it harder to get caught also as its not possible to always do a specific thing on a specific timeframe everytime.
    "MinRandomizeDelayMilliseconds": 2141,
    "MaxRandomizeDelayMilliseconds": 6736,
    "ReRandomizeDelayOnStart": true,
    "DelayBetweenPlayerActions": 4842,
    "DelayPositionCheckState": 3880,
    "DelayPokestop": 2260,
    "DelayCatchPokemon": 5882,
    "DelayBetweenPokemonCatch": 5036,
    "DelayCatchNearbyPokemon": 3096,
    "DelayCatchLurePokemon": 4314,
    "DelayCatchIncensePokemon": 3317,
    "DelayEvolvePokemon": 24129,
    "DelayEvolveVariation": 0.3,
    "DelayTransferPokemon": 4842,
    "DelayDisplayPokemon": 6609,
    "DelayUseLuckyEgg": 3081,
    "DelaySoftbanRetry": 2622,
    "DelayRecyleItem": 3994,
    "DelaySnipePokemon": 2871,
    "MinDelayBetweenSnipes": 10000,
    "SnipingScanOffset": 0.003

Also maybe delay on renaming as you can't just rename 10 pokemons that fast. Another thing would be a random pause.

**Comment by YouGamePlayHD** [comment]
+1

**Comment by caradex** [comment]
I hope this gets implemented especially the delay between catch attempts and also the delay of catching a new pokemon. Also the delay for evolving pokemon. I supposed that's how these settings should work.
"DelayCatchPokemon": 5882,
"DelayBetweenPokemonCatch": 5036,
"DelayEvolvePokemon": 24129,

**Comment by NoxxDev** [comment]
NecroBot using global delay and randomize 
```
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 5000
  },
```
