### ISSUE TITLE
Reaching PokeStops takes incredibly long

### ISSUE THREAD

**Issue by YouGamePlayHD** [NoxxDev/NecroBot#226]
I have the problem that a PokeStop which displays 8 seconds to get to it, isn't reached even a minute later... Who else has this problem? Can anyone help me?

**Comment by YouGamePlayHD** [comment]
Wow, Now I get Softban-message...

**Comment by AmazingGamerBoy** [comment]
same here

**Comment by dswtech** [comment]
@YouGamePlayHD  I think because it use humanized route, which follow the road route instead taking straight route.

That why you use google maps IP when you first time running the bot

**Comment by AmazingGamerBoy** [comment]
just get the original 0.9.0 version, it fixed it for me

**Comment by YouGamePlayHD** [comment]
@dswtech This is servere. That would mean that no PokeStops which aren't on the roads can be loaded?!

**Comment by wilsondgonzales** [comment]
@YouGamePlayHD "can be looted" because the bot doesn't have a direct route and can't reach it without setting up an API. answer: setup an API

**Comment by AmazingGamerBoy** [comment]
I did, still same problem

**Comment by NoxxDev** [comment]
the time shown is approximate, will vary the delay the stops to catch, variation in speed ...
