### ISSUE TITLE
crashing. not running at all 

### ISSUE THREAD

**Issue by botlord** [NoxxDev/NecroBot#227]
okay. turned bot on, updated then just stopped working. prior to updating there was no trouble at all. All I get now is this 
http://prntscr.com/c7lznz

**Comment by devilmanza21** [comment]
i got same problem

**Comment by boXseven** [comment]
me2

**Comment by claudiogbr** [comment]
same here

**Comment by YouGamePlayHD** [comment]
Same problem with me. Auto-updating seems to be broken.. Just download a fresh copy and try again, this worked for me
