### ISSUE TITLE
Configure killswitch

### ISSUE THREAD

**Issue by luigidanield2** [NoxxDev/NecroBot#228]
How to set killswitch for not riceve a perm ban???thank you and great work  staff noxxdev

**Comment by YouGamePlayHD** [comment]
Killswitch is configured by default. You can change it in the config.json under "Softban-Settings".
But I would not recommend using 0.9.2 because there are still issues.

**Comment by luigidanield2** [comment]
Yes but if killerswitch defalut i can capture only 40 pokemon and then after go out....and then????can i start another time necrobot??

**Comment by khairulpetrcech** [comment]
> Yes but if killerswitch defalut i can capture only 40 pokemon and then after go out....and then????can i start another time necrobot??

u can change total pokemon u capture u know ? not necessary 40..yes close necrobot after reach total pokemon caught,then open back

**Comment by luigidanield2** [comment]
Ok but for not riceve the ban  how many set capture pokemon 1000 and 2000 pokestop???in one day???

**Comment by khairulpetrcech** [comment]
U can just estimate ur self..maybe set it from 40 pokemon per session to ,,idk,,300 ?

**Comment by NoxxDev** [comment]
KillSwith has been replaced https://github.com/NoxxDev/NecroBot/commit/bcf5022962f0b393ef936fe0a02edcbc05f40608
