### ISSUE TITLE
[request] new function to avoid banning

### ISSUE THREAD

**Issue by rohk2** [NoxxDev/NecroBot#229]
Some news announced that the new banning system would ban the player who catch over 1000 monster or go to over 2000 pokestop per day. So, in the upcoming update, would you mind to add a new function to stop botting if it reached the daily limit (set by player)? And only take the item from pokestop if it is needed? (e.g. poke ball under…)

**Comment by YouGamePlayHD** [comment]
+1

**Comment by kalamera** [comment]
man, just use the logs.

for pokestops:

`find /I /C "Name: " NecroBot-2016-08-19*.txt`

---------- NECROBOT-2016-08-19-07.TXT: 22
---------- NECROBOT-2016-08-19-08.TXT: 53
---------- NECROBOT-2016-08-19-09.TXT: 51
---------- NECROBOT-2016-08-19-10.TXT: 15

for pokemons:

`find /I /C "catchsuccess" NecroBot-2016-08-19*.txt`

---------- NECROBOT-2016-08-19-07.TXT: 0
---------- NECROBOT-2016-08-19-08.TXT: 13
---------- NECROBOT-2016-08-19-09.TXT: 13
---------- NECROBOT-2016-08-19-10.TXT: 7

**Comment by rohk2** [comment]
I found the log but how to use it??

**Comment by NoxxDev** [comment]
```
"UseCatchLimit": true,
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,
```
