### ISSUE TITLE
Fastsoftban dont work

### ISSUE THREAD

**Issue by luigidanield2** [NoxxDev/NecroBot#232]
Fastsoftban dont work in necrobot 0.9.2

**Comment by YouGamePlayHD** [comment]
Same... I get softbanned and NOT unbanned

**Comment by YouGamePlayHD** [comment]
Lol even in 0.9.0

**Comment by YouGamePlayHD** [comment]
lol Softban just faded by itself...

**Comment by NoxxDev** [comment]
This not softban, fix in v0.9.4 or upper
