### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by evo09** [NoxxDev/NecroBot#233]
![222](https://cloud.githubusercontent.com/assets/21119934/17802143/128a6b74-6621-11e6-805c-6d2bc045a6c4.png)

Web Exception: The remote server returned an error (404) Not Found.

**Comment by pk356142** [comment]
Why 0.9.2 is so easy getting softban? 
I have start botting for just 5mins and it's soft banned...I use the default config.json,  just change the Lat,Long

**Comment by wilsondgonzales** [comment]
it's likely a false positive. What i mean is the bot might not have the range to activate the pokestop. If you have a visualizer you can confirm by looking at the map if the pokestop is too far

**Comment by NoxxDev** [comment]
False/Positive fix in v0.9.4 or upper
