### ISSUE TITLE
API keys questions

### ISSUE THREAD

**Issue by petpetpetvm** [NoxxDev/NecroBot#234]
1. how many accounts that I can use for 1 key ? (not at the same time)
2. can i make use different keys from same account 1 time ?
Thanks

**Comment by smoothrunnings** [comment]
@petpetpetvm Looks like someone didn't read the info on Google's site.

**Comment by petpetpetvm** [comment]
@smoothrunnings im sorry but my english is not that good

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
View release v0.9.3
