### ISSUE TITLE
How do I make an API?

### ISSUE THREAD

**Issue by sunnybuoy** [NoxxDev/NecroBot#235]
I dont know where to ask, but how do I do this? I am so lost.
Thanks

**Comment by khairulpetrcech** [comment]
https://github.com/NoxxDev/NecroBot/wiki/Config#googleapikey-value

**Comment by iwean** [comment]
Go to Google API Key site..... https://developers.google.com/maps/documentation/directions/get-api-key

Click "Get Keys" than next next next..... than you have the KEY. .......YeaY !!!

Paste it on your auth.json file ..... don't forget with Quotation mark.

Good to go :)

**Comment by gesamurai24** [comment]
"GoogleAPIKey": null   Line8 For file auth.json
if you have    "GoogleAPIKey": "KEY"  END

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
View release v0.9.3
