### ISSUE TITLE
092 don't work with only ptc account

### ISSUE THREAD

**Issue by EdmondDantes0** [NoxxDev/NecroBot#240]
i tried 092 version, but don't work with my ptc account, the message is that i must compile googleuser and googlepassword in auth.json
but i use only a ptc account.
thanks

**Comment by Schweng** [comment]
Is

{
  "AuthConfig": {
    "AuthType": "ptc", 

?

**Comment by EdmondDantes0** [comment]
i've write this in auth.json, but don't work again

**Comment by Schweng** [comment]
Maybe show us your auth.json. But anonymize your login data.

**Comment by EdmondDantes0** [comment]
{
  "AuthType": "ptc",
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": "myuser",
  "PtcPassword": "mypass",
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "note3",
  "DeviceId": "4d5ddb545b6814a4",
  "AndroidBoardName": "MSM8974",
  "AndroidBootloader": "N900PVPUEOK2",
  "DeviceBrand": "samsung",
  "DeviceModel": "SM-N900P",
  "DeviceModelIdentifier": "cm_hltespr",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "samsung",
  "HardwareModel": "SM-N900P",
  "FirmwareBrand": "cm_hltespr",
  "FirmwareTags": "test-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "samsung/hltespr/hltespr:5.0/LRX21V/N900PVPUEOH1:user/release-keys"
}

**Comment by Schweng** [comment]
Sure, this is 0.9.2? Looks like an old one. In your auth.json is no Google API. Maybe a new download will help.

**Comment by iwean** [comment]
Try deleting auth.json and config.json file, than hit the exe file...

The bot will make that 2 file for you.... than edit it.

**Comment by wilsondgonzales** [comment]
the auto update is broken. download and run fresh

**Comment by mazzod** [comment]
Hi guys, I've downloaded and configured the new version 0.9.2, but when I start the bot with my ptc accounts appear this error, I can't understand where is the problem:

"[11:52:03] Pokemon Servers might be offline / unstable. Trying again...
[11:52:04] Error: System.ArgumentOutOfRangeException: Index non compreso nell'intervallo. Richiesto valore non negativo e minore della dimensione della raccolta.
Nome parametro: index
   in System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   in System.Collections.Generic.List`1.get_Item(Int32 index)
   in Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)
   in Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   in PoGo.NecroBot.Logic.Navigation.Route(ISession session, GeoCoordinate start, GeoCoordinate dest) in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:riga 126
   in PoGo.NecroBot.Logic.Navigation.<Move>d__11.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:riga 199
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:riga 101
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:riga 68
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:riga 56"

Am I missing something on the configurations?

**Comment by petpetpetvm** [comment]
Try new api

**Comment by petpetpetvm** [comment]
@mazzod : try new api

**Comment by mazzod** [comment]
@petpetpetvm thks so much, with new API is working! :+1:

**Comment by Laiiiff** [comment]
@petpetpetvm  What do you mean with "new api"? I'm also trying to log in with the ptc account and have the new pattern config of the 0.9.2 but it's always asking to configure "GoogleAPIKey" even if I did already put PTC data.

**Comment by mazzod** [comment]
@Laiiiff follow this guide and you will resolve. Maybe you have an old API:
https://github.com/NoxxDev/NecroBot/wiki/Config#googleapikey-value

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
View release v0.9.3
