### ISSUE TITLE
New update for walk along the road/street great but error

### ISSUE THREAD

**Issue by samuraitruong** [NoxxDev/NecroBot#241]
Thanks to bring the google map api to determine the humanize walk route, however, it just ignore all the pokestops in park, along the river.
![image](https://cloud.githubusercontent.com/assets/1183138/17805533/4d19a35a-6643-11e6-9a8b-1a2a22955765.png)

**Comment by samuraitruong** [comment]
See  screenshot ![image](https://cloud.githubusercontent.com/assets/1183138/17805500/28d96f48-6643-11e6-9e42-dd7cbe792f55.png)

**Comment by YouGamePlayHD** [comment]
Yep, that is an error because the bot seems to aim at ONE PokeStop and ignore all the others on its way. That's a good point
+1

**Comment by boXseven** [comment]
how do u get such a view?

**Comment by samuraitruong** [comment]
Boxseven, you can get source from here - >https://github.com/nicoschmitt/necrobotvisualizer

or if you are lazy to install nodejs, then you can get installer here https://pokelifehacks.com/necrobot-mobbot-visualizer-gui-pokemon-go-bot/

**Comment by vipery** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/12803617/17808455/fabb482c-6618-11e6-929d-a90abed3fc83.png)
lol

**Comment by vipery** [comment]
Logic lol
![screenshot_2](https://cloud.githubusercontent.com/assets/12803617/17808544/398fcfa0-6619-11e6-8647-0bd8438fa4ac.png)

**Comment by TLBM** [comment]
Have pointed hat out already in #212 

Maybe we can use the other Pokestops in MaxTravelDistanceInMeters as waypoints and let Google plot a complete optimized route. The API seems to support that with waypoints optimize:true.
