### ISSUE TITLE
Unknown Error - Never Seen This Before!

### ISSUE THREAD

**Issue by mikegrimmers** [NoxxDev/NecroBot#242]
Hi guys,

Anyone know what the below is for? I can't work it out, I even downloaded and used a fresh config file thinking I may have messed a value up but the same error occurs - tried two separate PTC accounts and still no luck, help would be massively appreciated!

Thank you.

![error](https://cloud.githubusercontent.com/assets/20826071/17806298/932ceea8-65fb-11e6-8804-2f3981be824f.png)

**Comment by YouGamePlayHD** [comment]
What is that I have never experienced this?!

**Comment by luigidanield2** [comment]
ban

**Comment by mikegrimmers** [comment]
It isn't logged in on my phone and Pokemon catches work.

**Comment by samuraitruong** [comment]
the config has been refactored complexly, you need delete old config file to generate the new one.

**Comment by thadeustr** [comment]
thats ban try to login with your mobile..

**Comment by Triippykiid** [comment]
Its not ban. I have the same problem and my account is perfectly fine.

**Comment by thoraine** [comment]
I'm getting this error even on a fresh level 1 and I've checked that I'm not banned yet.

**Comment by dodkhaled** [comment]
having same error cant find away to fix it yet

**Comment by harvey87** [comment]
I'm having this kind of error too. any solution yet?

**Comment by NoxxDev** [comment]
ban
