### ISSUE TITLE
Turn API off

### ISSUE THREAD

**Issue by petpetpetvm** [NoxxDev/NecroBot#243]
How can i turn the API off, i just want it to be like 0.9.0 (no walking along streets,....) but i would love the killswitch
Thanks

**Comment by YouGamePlayHD** [comment]
Disable-Human-Walking: true
But you'll be softbanned in an instant because Niantic has buffed their Anti-Cheat

**Comment by vipery** [comment]
logic terrible 

[http://prntscr.com/c7owun]

**Comment by NoxxDev** [comment]
Errors fixed in release v0.9.3
