### ISSUE TITLE
Question about monitoring

### ISSUE THREAD

**Issue by YouGamePlayHD** [NoxxDev/NecroBot#244]
Is there a way to watch the bot go through the streets and monitor its activity? If you log in from your mobile, it won't work and Niantic will immediately softban you.

If not, it'd be a huge improvement if the dev added some way to see this (e.g. a google map on which the position is marked somehow).

**Comment by kalamera** [comment]
you can use the "LastPos.ini" file to get the actual coordinates of the bot.
just replace the ":" with "," and search on maps.google.com

**Comment by Josp1337** [comment]
https://github.com/AndikaTanpaH/NecrobotJavanHawk/releases

**Comment by TLBM** [comment]
https://github.com/nicoschmitt/necrobotvisualizer/releases
Use this and activate websocket in config

**Comment by YouGamePlayHD** [comment]
Nice, thank you guys!
