### ISSUE TITLE
9.2 google Api issue

### ISSUE THREAD

**Issue by repelsteeltjehd** [NoxxDev/NecroBot#247]
Quick fix:

copy and paste this into the config.json

{
"AuthConfig": {
"AuthType": "google",
"GoogleUsername": "username here",
"GooglePassword": "password here",
"PtcUsername": null,
"PtcPassword": null,
"GoogleAPIKey": "google api here"

**Comment by Astifleure** [comment]
same here

**Comment by repelsteeltjehd** [comment]
fixed the issue by doing this

{
  "AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": "username here",
    "GooglePassword": "password here",
    "PtcUsername": null,
    "PtcPassword": null,
    "GoogleAPIKey": "google api here"

your welcome :)

**Comment by Astifleure** [comment]
how u get google api  ?where ?

**Comment by repelsteeltjehd** [comment]
nercobot will send you to the google api :)

**Comment by ridalarry** [comment]
actually you get the API yourself check the wiki this link for more info https://github.com/NoxxDev/NecroBot/commit/f5d1847afc2a00f6b9cb51f4bbd64ab02c62d8b7

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
View new release
