### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by thomatbu** [NoxxDev/NecroBot#249]
After using Necro 0.9.2, I think it will be cool if devs add these features:
- Auto run (killswitch is good, it will be perfect if we have schedule for the bot)
- Upgrade killswitch (ya, killswitch will stop the bot and doesn't start automatically, it's nice if devs add auto restart the bot after 1 hour usage)
- Manage Inventory (I love this feature a lot, I can transfer, upgrade and evolve pokemons without opening the game)
- Log report (report how many pokestops/pokemons I have traveled/caught in 1 hour, and report for each hour. And much more information about km walked)
- Change device simulator manually.
- Stay longer at lure pokestops
- Auto skip pokemons with low IV or CP
- Detect catch flee softban and stop catching pokemons, but still spin pokestops with time settings (save the balls, lol)

Devs please take a look and see if devs can add to the bot to make it more...crazy, haha. This is not a request, just my idea to improve devs' idea.=))))

**Comment by ridalarry** [comment]
I would agree with all of them, but not this one "Auto skip pokemons with low IV or CP" as it could make it easier to detect with niantic anti cheat, but you can make it transfer them on capture if they have low cp or iv which is already implemented.

**Comment by thomatbu** [comment]
Ya I know auto transfer low IV, I just thought we could skip pokemons with low IV that can save the balls for other pokemons.

**Comment by samuraitruong** [comment]
nop, you don't need save ball because you always have many ball when spin pokestop. just catch all of them then transfer.

**Comment by thomatbu** [comment]
Just an idea, lol, if it's impossible, that's fine. Because I think many people still need this feature than auto transfer.

**Comment by mosca90** [comment]
- Change device simulator manually.
Why?

It's not better to using your own **Device Info** always?
Either by phone and emulator?

**Comment by caradex** [comment]
I would really like to have this feature: Stay longer at lure pokestops.
and make the time configurable. Normally people tend to stop at pokestops if there are lures around especially those pokestops in cluster.

**Comment by thomatbu** [comment]
@mosca90 Because if you reset the bot, it will change device info too. I'm just scared that Niantic will be easier to ban.

**Comment by mosca90** [comment]
@thomatbu just use your personal device info, or backup before reset and here you go :)

**Comment by thomatbu** [comment]
Sometimes, I would like to stick with 1 device. But when I met permanent ban, I need to change to another device but I can't find device info manually. Randomly change device info could be easier to be banned.

**Comment by NoxxDev** [comment]
Almost all there is in the bot check v 0.9.6
