### ISSUE TITLE
0.8.8 do nothing

### ISSUE THREAD

**Issue by livedalzen22** [NoxxDev/NecroBot#25]
![image](https://cloud.githubusercontent.com/assets/11879916/17654889/74443d9e-62da-11e6-8c64-2b4703cb2da5.png)

why always catchflee or do nothing

**Comment by Eden-Sun** [comment]
Perhaps you got baned?

**Comment by NoxxDev** [comment]
Probably CatchFlee Softban

**Comment by ntatoo** [comment]
you just got softban , after 45 spin of pokestop 
you good to go
