### ISSUE TITLE
How to use multiple bot 

### ISSUE THREAD

**Issue by khairulpetrcech** [NoxxDev/NecroBot#251]
Hi.how to use multiple bot in 1 pc ? And obviously to avoid IP ban and softban also..

Someone say to use proxy..how do i do that?

Thanks.cheers,
khai.

**Comment by GummiBoat** [comment]
There's a section in the config called "Proxy". There are also lists on the internet, that will provide you with the necessary infos on a single proxy. To run the bot multiple times, copy paste the entire folder and rename it. Each folder = 1 Bot. 

For future questions, please go to the public discord.

**Comment by khairulpetrcech** [comment]
@GummiBoat sooryy noob question..what is public discord and could u provide the link?

cheers,
khai

**Comment by stjupiter** [comment]
https://discordapp.com/channels/209253611031625728/209253611031625728
