### ISSUE TITLE
Softbans solved.

### ISSUE THREAD

**Issue by repelsteeltjehd** [NoxxDev/NecroBot#253]
I found out that the killswitch gets me softbans..I turned it off and bam no more softbans :+1:

**Comment by likeness123** [comment]
So killswitch false?

**Comment by pk356142** [comment]
killswitch have two option "UseKillSwitchCatch" and "UseKillSwitchPokestops" , all set false?

**Comment by repelsteeltjehd** [comment]
yes killswitch to false, works for me

**Comment by pk356142** [comment]
OK, next time I'll try it. THX
