### ISSUE TITLE
wrong output at console (zh-*)

### ISSUE THREAD

**Issue by tonyder** [NoxxDev/NecroBot#254]
The Console.OutputEncoding is Encoding.UTF8 now, but the console can't work correctly at my PC (window 7, Chinese traditional)

![image](https://cloud.githubusercontent.com/assets/4448597/17809120/f1c23162-6646-11e6-95d7-a76792eecdf7.png)

after I change to Encoding.Unicode, the console work correctly

![image](https://cloud.githubusercontent.com/assets/4448597/17809245/c8dac286-6647-11e6-9363-814c0904863d.png)

I test the several language with zh-\*, ja-\*
maybe you can consider it.

**Comment by jam368** [comment]
How to change??

**Comment by tonyder** [comment]
you can change the Encoding.UTF8 to Encoding.Unicode in ConsoleLogger.cs, and rebuild the project
![image](https://cloud.githubusercontent.com/assets/4448597/17842132/4bdb1ce2-6852-11e6-849b-d7677d08be2c.png)
