### ISSUE TITLE
You need to configure the GoogleAPI Key

### ISSUE THREAD

**Issue by destructi6n** [NoxxDev/NecroBot#257]
### Expected Behavior
Should open your account after default location configuration and begin botting

### Actual Behavior
Asks me to configure the google api key that hasn't asked me to do so in previous versions

### Your config.json
"AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": "*****@gmail.com",
    "GooglePassword": "****",
    "PtcUsername": null,
    "PtcPassword": null,
    "GoogleAPIKey": null
  }
your config here
my config.json file hasn't been modified at all yet since the original setup
### Steps to Reproduce
simply followed the introductory configuration setup and doesn't work.

### Other Information
Version: 9.2
![capture](https://cloud.githubusercontent.com/assets/21111704/17810359/b5b2848a-65ea-11e6-881a-f52a79c787df.PNG)

Windows Version: Windows 10 Professional

**Comment by dayshake** [comment]
I have a question! does the maps api key solve altitude problem?

**Comment by Kleberstoff** [comment]
Pretty easy solution for this one, change following line
"GoogleAPIKey: null" to "GoogleAPIKey: "*" where * represent your GoogleAPIKey.

**Comment by uncannierelf** [comment]
I've configured the key, I still get this message on start up. It did this last night and adding the key fixed it, now it doesn't.

**Comment by ComputerApp1234** [comment]
same problem for me..

**Comment by Kleberstoff** [comment]
He updated the Bot just a bit ago, check in the config.json there is "GoogleWalkConfig" you can either set it to false to now use GoogleWalk or just simple enter your APIkey there.

**Comment by baomx888** [comment]
same issue on second bot on proxy

**Comment by inclouis** [comment]
guys, download the latest version NecroBot Forked v0.9.3.

GoogleAPIKey is in Config.json now

**Comment by ComputerApp1234** [comment]
I did , got my key and pasted it in the config.json.. The Bot is running, but i got this message :

"(INFO) Without a Google Api, you will have 2500 free quota limit, if
you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey",
 get API Key in link: https://developers.google.com/maps/documentation/direction
s/get-api-key"

**Comment by uncannierelf** [comment]
Set GoogleWalk to false. That fixed it for me so far.

**Comment by inclouis** [comment]
@ComputerApp1234 yes, that is (INFO), so if you had set your google API, you will not have quota limit.

**Comment by ComputerApp1234** [comment]
@inclouis Sorry, thought i did something wrong because it was the first message and it appeared in red :D

**Comment by siangs** [comment]
why i cannot find GoogleAPIKey is in Config.json?i only find it at auth.json

**Comment by uncannierelf** [comment]
@siangs Redownload the release. It should be in config.json in the new release.

**Comment by NoxxDev** [comment]
It is not necessary to have the google API
View release v0.9.3
