### ISSUE TITLE
Hard to encounter pokestop and pokemons?

### ISSUE THREAD

**Issue by inclouis** [NoxxDev/NecroBot#259]
My location settings is in the busiest park for pokemon and pokestop and yet I see nothing.

Please help:

[22:01:30] (INFO) Walking Speed: Has been changed, 7.17 Km/h to 7.17 Km/h
[22:01:37] (INFO) Walking Speed: Has been changed, 7.17 Km/h to 7.17 Km/h
[22:01:38] (INFO) Walking Speed: Has been changed, 7.17 Km/h to 7.21 Km/h
[22:01:39] (INFO) Walking Speed: Has been changed, 7.21 Km/h to 7.20 Km/h
[22:01:43] (INFO) Walking Speed: Has been changed, 7.20 Km/h to 7.20 Km/h
[22:01:52] (INFO) Walking Speed: Has been changed, 7.20 Km/h to 7.13 Km/h
[22:01:53] (INFO) Walking Speed: Has been changed, 7.13 Km/h to 7.13 Km/h
[22:01:57] (INFO) Walking Speed: Has been changed, 7.13 Km/h to 7.12 Km/h
[22:02:05] (INFO) Walking Speed: Has been changed, 7.12 Km/h to 7.05 Km/h
[22:02:08] (INFO) Walking Speed: Has been changed, 7.05 Km/h to 7.05 Km/h
[22:02:10] (INFO) Walking Speed: Has been changed, 7.05 Km/h to 10.10 Km/h
[22:02:10] (INFO) Walking Speed: Has been changed, 10.10 Km/h to 10.14 Km/
[22:02:12] (INFO) Walking Speed: Has been changed, 10.14 Km/h to 10.12 Km/
[22:02:15] (INFO) Walking Speed: Has been changed, 10.12 Km/h to 10.16 Km/
[22:02:20] (INFO) Walking Speed: Has been changed, 10.16 Km/h to 10.20 Km/
[22:02:26] (INFO) Walking Speed: Has been changed, 10.20 Km/h to 10.25 Km/
[22:02:31] (INFO) Walking Speed: Has been changed, 10.25 Km/h to 10.24 Km/
[22:02:37] (INFO) Walking Speed: Has been changed, 10.24 Km/h to 10.23 Km/
[22:02:45] (INFO) Walking Speed: Has been changed, 10.23 Km/h to 10.21 Km/
[22:02:51] (INFO) Walking Speed: Has been changed, 10.21 Km/h to 10.22 Km/
[22:02:52] (INFO) Walking Speed: Has been changed, 10.22 Km/h to 10.29 Km/
[22:02:55] (INFO) Walking Speed: Has been changed, 10.29 Km/h to 10.28 Km/
[22:02:58] (INFO) Walking Speed: Has been changed, 10.28 Km/h to 10.35 Km/
[22:02:59] (INFO) Walking Speed: Has been changed, 10.35 Km/h to 10.37 Km/
[22:03:02] (INFO) Walking Speed: Has been changed, 10.37 Km/h to 10.42 Km/
[22:03:03] (INFO) Walking Speed: Has been changed, 10.42 Km/h to 10.42 Km/
[22:03:09] (INFO) Walking Speed: Has been changed, 10.42 Km/h to 11.59 Km/
[22:03:11] (INFO) Walking Speed: Has been changed, 11.59 Km/h to 11.61 Km/
[22:03:13] (INFO) Walking Speed: Has been changed, 11.61 Km/h to 11.67 Km/
[22:03:14] (INFO) Walking Speed: Has been changed, 11.67 Km/h to 11.67 Km/
[22:03:18] (INFO) Walking Speed: Has been changed, 11.67 Km/h to 10.16 Km/
[22:03:18] (INFO) Walking Speed: Has been changed, 10.16 Km/h to 10.11 Km/
[22:03:20] (INFO) Walking Speed: Has been changed, 10.11 Km/h to 10.11 Km/
[22:03:34] (INFO) Walking Speed: Has been changed, 10.11 Km/h to 10.15 Km/
[22:03:37] (INFO) Walking Speed: Has been changed, 10.15 Km/h to 10.17 Km/
[22:03:40] (INFO) Walking Speed: Has been changed, 10.17 Km/h to 10.16 Km/
[22:03:42] (INFO) Walking Speed: Has been changed, 10.16 Km/h to 10.11 Km/
[22:03:47] (INFO) Walking Speed: Has been changed, 10.11 Km/h to 10.12 Km/
[22:03:52] (PKMN) (CatchEscape) | (Normal) Krabby Lvl: 11 CP: (215/249) IV
0% | Chance: 45.14% | 56.60m dist | with a PokeBall (1 left). | lat: 3.155
ng: 101.718350
[22:03:58] (PKMN) (CatchSuccess Attempt #2) | (Normal) Krabby Lvl: 11 CP:
49) IV: 48.00% | Chance: 45.14% | 56.60m dist | with a PokeBall (0 left).
EXP earned | Candies: 92 | lat: 3.155632 long: 101.718350
[22:04:00] (TRANSFERRED) Krabby - CP: 215  IV: 48.22%   [Best CP: 458  IV:
%] (Candies: 93)
[22:04:05] (INFO) Walking Speed: Has been changed, 10.12 Km/h to 10.14 Km/
[22:04:08] (INFO) Walking Speed: Has been changed, 10.14 Km/h to 10.18 Km/
[22:04:14] (INFO) Walking Speed: Has been changed, 10.18 Km/h to 10.17 Km/
[22:04:15] (INFO) Walking Speed: Has been changed, 10.17 Km/h to 10.13 Km/
[22:04:19] (INFO) Walking Speed: Has been changed, 10.13 Km/h to 6.47 Km/h
[22:04:28] (INFO) Walking Speed: Has been changed, 6.47 Km/h to 6.49 Km/h
[22:04:36] (INFO) Walking Speed: Has been changed, 6.49 Km/h to 6.43 Km/h
[22:04:39] (INFO) Walking Speed: Has been changed, 6.43 Km/h to 6.43 Km/h
[22:04:40] (INFO) Walking Speed: Has been changed, 6.43 Km/h to 6.50 Km/h
[22:04:42] (INFO) Walking Speed: Has been changed, 6.50 Km/h to 6.49 Km/h
[22:04:55] (INFO) Walking Speed: Has been changed, 6.49 Km/h to 6.49 Km/h
[22:04:57] (INFO) Walking Speed: Has been changed, 6.49 Km/h to 6.46 Km/h
[22:04:58] (INFO) Walking Speed: Has been changed, 6.46 Km/h to 6.43 Km/h
[22:05:01] (INFO) Walking Speed: Has been changed, 6.43 Km/h to 6.40 Km/h
[22:05:04] (INFO) Walking Speed: Has been changed, 6.40 Km/h to 6.47 Km/h
[22:05:07] (INFO) Walking Speed: Has been changed, 6.47 Km/h to 6.45 Km/h
[22:05:09] (INFO) Walking Speed: Has been changed, 6.45 Km/h to 6.52 Km/h
[22:05:22] (INFO) Walking Speed: Has been changed, 6.52 Km/h to 6.57 Km/h
[22:05:28] (INFO) Walking Speed: Has been changed, 6.57 Km/h to 6.57 Km/h
[22:05:37] (INFO) Walking Speed: Has been changed, 6.57 Km/h to 6.59 Km/h
[22:05:42] (INFO) Walking Speed: Has been changed, 6.59 Km/h to 6.58 Km/h
[22:06:00] (INFO) Walking Speed: Has been changed, 6.58 Km/h to 6.65 Km/h
[22:06:02] (INFO) Walking Speed: Has been changed, 6.65 Km/h to 6.70 Km/h

# **Here's my config :**

{
  "ConsoleSettings": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateSettings": {
    "CheckForUpdates": true,
    "AutoUpdate": true,
    "TransferConfigAndAuthOnUpdate": true
  },
  "WebsocketsSettings": {
    "UseWebsocket": false,
    "WebSocketPort": 14251
  },
  "LocationSettings": {
    "DisableHumanWalking": false,
    "DefaultLatitude": 3.1555,
    "DefaultLongitude": 101.7151,
    "WalkingSpeedInKilometerPerHour": 9.42,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 3.2,
    "ShowVariantWalking": true,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 2000
  },
  "TelegramSettings": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": "12345"
  },
  "GPXSettings": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipingSettings": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false
  },
  "PokemonSettings": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 1000,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseEggIncubatorMinKm": 2,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "UseBerriesMinCp": 800,
    "UseBerriesMinIv": 80.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 4,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{1}_{0}",
    "FavoriteMinIvPercentage": 90.0,
    "AutoFavoritePokemon": false,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 800,
    "UseUltraBallAboveCp": 1200,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": false,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": false,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": false,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false
  },
  "RecycleSettings": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "DelayBetweenRecycleActions": false,
    "TotalAmountOfPokeballsToKeep": 120,
    "TotalAmountOfPotionsToKeep": 80,
    "TotalAmountOfRevivesToKeep": 60,
    "TotalAmountOfBerriesToKeep": 80
  },
  "CustomCatchSettings": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 20,
    "NiceThrowChance": 40,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 10,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 90.0,
    "ForceGreatThrowOverCp": 1100,
    "ForceExcellentThrowOverCp": 1500
  },
  "PlayerSettings": {
    "DelayBetweenPlayerActions": 3000
  },
  "SoftBanSettings": {
    "FastSoftBanBypass": false,
    "UseKillSwitchCatch": false,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40,
    "UseKillSwitchPokestops": false,
    "AmountPokestops": 150
  },
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "aerodactyl",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew",
    "caterpie",
    "weedle",
    "pidgey"
  ],
  "PokemonsToEvolve": [
    "rattata"
  ],
  "PokemonsToLevelUp": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToIgnore": [
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 200,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 2000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

Please help.

**Comment by metalmouth** [comment]
The latest NecroBot has introduce google route which, I think, is enable by default. That means the bot uses road paths unlike before it walks over mountains and buildings (not sure haha).

**Comment by Dreker** [comment]
Same here

**Comment by inclouis** [comment]
most busy park and it wont catch pokemon or doesnt go to pokestop.. weird

**Comment by iwean** [comment]
Dev team disable snipe mode, I think... because snipe = banned

And Google API make our walking realistic... not get a short cut... more human.

Just IMHO

**Comment by inclouis** [comment]
Now is like won't go to pokestop. Walking realistic but there's alot of pokemons around, doesnt even have to walk much around this area. Maybe is my config something wrong?

**Comment by iwean** [comment]
Add this after softban setting:

  "SoftBanSettings": {
    "FastSoftBanBypass": false,
    "UseKillSwitchCatch": true,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40,
    "UseKillSwitchPokestops": true,
    "AmountPokestops": 80
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "Your KEY here",
    "Cache": true
  },
  "ItemRecycleFilter": [

**Comment by inclouis** [comment]
it is still same.. bot doesnt seem to catch pokemon, like catch only 1 pokemon every 15mins.

**Comment by iwean** [comment]
Set to "TRUE" :lol:

  "SnipingSettings": {
    "UseSnipeLocationServer": true,
