### ISSUE TITLE
snipe error EXPIRED and negative time. need HELP!

### ISSUE THREAD

**Issue by ramchris8484** [NoxxDev/NecroBot#263]
![error](https://cloud.githubusercontent.com/assets/21127581/17814751/1cd8f8ec-65e6-11e6-8f4a-66c7ca0b5c06.jpg)

Help i got it error since today.. yesterday its working fine..
after i update 9.2 that happens
i return to 9,0 and now still snipe always fail
can some1 got the same experience like this one?

Version: 9.2 9.0
Windows Version: win7 64bit
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):SNIPE

**Comment by ramchris8484** [comment]
kindly please help me about this :(

**Comment by YouGamePlayHD** [comment]
This means that the locations for spawning these pokemon have been changed by Niantic. What does happen if you let the sniping go on? Do you get "No pokemon found...."?

**Comment by ramchris8484** [comment]
all snipe fail  think its the error with time in my laptop.. i change it while ago because its wrong now i get back to backward time its working .. but i didnt know the exact time 
i need to fix my CMD to correct time in my necrobot.. how to do it?
