### ISSUE TITLE
    "UseGoogleWalk": true, ignore WalkingSpeedInKilometerPerHour?

### ISSUE THREAD

**Issue by vipery** [NoxxDev/NecroBot#264]
Noticed with google speed is avg 2.5

**Comment by GummiBoat** [comment]
I think you need to enter the corresponding traveling method too. e.g. bicycling. You can let the bot show you, how fast you are, under the walking settings in the configuration.

Notice, that you need the newest release 0.9.3 to do so.

**Comment by NoxxDev** [comment]
`UseGoogleWalk`, ability google trace routes of pokestop, view more in [wiki] (https://github.com/NoxxDev/NecroBot/wiki/Config#google-walk-config)
