### ISSUE TITLE
I want the kill switch to count total number of pokemon caught instead of pokemon caught per hour

### ISSUE THREAD

**Issue by iamhackhackami** [NoxxDev/NecroBot#266]
Like the title, and also pokestop

**Comment by antfuentes87** [comment]
This is not a issue, close this. And stop posting useless non-issues.

**Comment by zapahacks** [comment]
I might get your point... just set the switch for catch at 500 (all of the values, flees, scape, errors, etc), your speed to 20 km and delay between catchs to 2200. This way you will catch around 60 p/h and the bot will shut down around 8-9 hours (when 500 pokemons are caught). You can do the same with pokestops, just set it to 1000 and play with the delay settings...

**Comment by NoxxDev** [comment]
KillSwitch removed check version v0.9.5 or upper to new limits
