### ISSUE TITLE
Spammed soft bans

### ISSUE THREAD

**Issue by kassumi** [NoxxDev/NecroBot#268]
My account is botting since lvl 1, it was fine until like few hours ago, when i get soft ban for n-th time. It is basically softbanning me with EACH pokestop, it started randomly after 1 hour sesion, so it's not due to jumping, since my speed was like 10km/h. nothing seems to work, if i wait a while, it works again, catching few pokemons and then soft-ban spam over and over again. Anyone has got any kind of advice? is it over with this account? it's not a big deal creating another one tho.

**Comment by YouGamePlayHD** [comment]
I don't know if it's a softban. You can't collect PokeStops, right? But can you catch Pokemon?

**Comment by YouGamePlayHD** [comment]
It could also be the issue i've been having in 0.9.2 release. The bot aimed at activated stops - which version do you use?

**Comment by kassumi** [comment]
i use 9.0, no, i can not catch any pokemon. IF i wait like 30 minutes, necro will catch 2 or 3 pokemons, and aboutu 2 pokestops, then it softbanning me again. stops were not active, not after this time xd

**Comment by YouGamePlayHD** [comment]
Send your config.

**Comment by YouGamePlayHD** [comment]
I'm just sniping like crazy not even softbanned once!!

**Comment by YouGamePlayHD** [comment]
KillSwitch also prevents Niantic from CatchFlee-ban.
Why do you use 9.0? 9.3 is stable...

**Comment by YouGamePlayHD** [comment]
I mean...
![screenshot 3](https://cloud.githubusercontent.com/assets/12982238/17816583/244bff26-663a-11e6-9237-b1b3c3160e41.png)

**Comment by kassumi** [comment]
i use 9.0 by default xd.

btw, i just get random perma ban on my 3 bot accounts, one was on default setting that wouldn't let him be caught. fck me right? :D anyway, here is my config:

{
  "TranslationLanguageCode": "1",
  "CheckForUpdates": false,
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "TelegramPassword": "12345",
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": true,
  "CatchPokemon": true,
  "MaxBerriesToUsePerPokemon": 3,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 3000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 40.779014,
  "DefaultLongitude": -73.968447,
  "WalkingSpeedInKilometerPerHour": 10.0,
  "UseWalkingSpeedVariant": true,
  "RandomlyPauseAtStops": true,
  "ShowVariantWalking": false,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": true,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 3000,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "UseEggIncubatorMinKm": 2,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "GetSniperInfoFromSkiplagged": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 10,
  "MaxTravelDistanceInMeters": 1000,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.5,
  "UseUltraBallBelowCatchProbability": 0.25,
  "UseMasterBallBelowCatchProbability": 0.1,
  "EnableHumanizedThrows": true,
  "EnableMissedThrows": true,
  "ThrowMissPercentage": 10,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 15,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [

without rest, it's sensless to post it

**Comment by YouGamePlayHD** [comment]
Almost the exact same settings I run XD
If you get softban-spammed, just cool down your account.
And also switch off all stats that have "Snipe" infront of them.

Other than that I have no idea why you get softban-spammed.
Maybe an IP-Ban?

**Comment by kassumi** [comment]
WTF IS WRONG WITH NIANTIC? they banned my account that was not botting EVEN ONE SINGLE TIME, They banned my whole IP, wtf?!

**Comment by YouGamePlayHD** [comment]
My sister got banned without botting too lol
Write a ban appeal if you have played according to their laws...

**Comment by kassumi** [comment]
ok, thanks mate

**Comment by YouGamePlayHD** [comment]
No, IP-Ban can be bypassed easily ^^

**Comment by kassumi** [comment]
that's realy good to know :D for future: is there any guide or something? or just the appeal thing?

**Comment by YouGamePlayHD** [comment]
If it's a permaban, you will have to appeal...
IP-Ban and Softban can be removed.
CatchFlee will have to timeout.

**Comment by kassumi** [comment]
i can normally log in, there is just no pokestops and no pokemons. guess it's ip?

**Comment by YouGamePlayHD** [comment]
IP-ban. easy. just restart router and you're good

**Comment by kassumi** [comment]
ty

**Comment by YouGamePlayHD** [comment]
np

**Comment by khairulpetrcech** [comment]
@YouGamePlayHD if u generous,could u upload your config of 9.3 ? im keep getting softban =.=

**Comment by RavenHome1** [comment]
really niantic, what's with their ban system XD, tho they caught my old account level 25 with high iv and cp pokemon ;-; , i am very careful about sniping. i really don't understand why people are getting softbans a lot on the 9.3 build , been runing for an hour straight didn't get banned once. here is a suggestion go into task view on your smart phone and kill the game if it is running in the background on your smartphone.

**Comment by YouGamePlayHD** [comment]
Sorry, have been offline...
Here is my config @khairulpetrcech:
http://pastebin.com/zt28dJDp

**Comment by YouGamePlayHD** [comment]
The google walking really makes it difficult for Niantic. I don't think they will permaban any Necrobot 0.9.3 user because they can't define whether you use an bot or not...
Also setting "MissThrows" or so under Softban in the config to a decent amount will really reduce your chance to get CatchFlee-banned.

**Comment by RavenHome1** [comment]
@YouGamePlayHD i used to snipe a lot with my old account, 2 hours session everyday, i continued for about 3 days until eventually they killed my account, if it is not immediately then in time, i suggest you remain more careful and try to not raise the heat on your account

**Comment by YouGamePlayHD** [comment]
Doesn't Matter. That account is lvl 7 ^^

**Comment by khairulpetrcech** [comment]
thanks @YouGamePlayHD

**Comment by YouGamePlayHD** [comment]
Now I get the same issue. PokeStops can't be collected and unban doesn't work

**Comment by YouGamePlayHD** [comment]
But I get IPBan-Spammed

**Comment by YouGamePlayHD** [comment]
Ah! It's the bot always going the same routes!
Change the location. That solved it for me!
The softban will be bypassed.
