### ISSUE TITLE
API Key prolem!

### ISSUE THREAD

**Issue by tonigino2** [NoxxDev/NecroBot#269]
Hi!
I was botting like 5 minutes ago and then i closed and changed the walking speed on the config, then i opened up the bot it gives me the problem: 
You need to configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key

**Comment by kassumi** [comment]
what version?

**Comment by GummiBoat** [comment]
You only need a Google API Key, if you're using the Google Walk feature, which will let your character follow a google-maps-specified route. You can get one from the link you posted and enter it in the configuration. If you only get the red text on startup, that one is default. You don't need to have one, but it's recommended.

For future Questions please go to the public discord, since your problem has nothing to do with a malfunction of the bot.

**Comment by YouGamePlayHD** [comment]
I do have the same error, but the google walk still works?!

**Comment by nfettinger** [comment]
The public discord does not support Forked versions of NecroBOT.

**Comment by pipihaianh** [comment]
@tonigino2 
in config.json find 
"GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "GoogleHeuristic": "walking",
    **"GoogleAPIKey": " ",**
    "Cache": true
and add your Google API Key

**Comment by GummiBoat** [comment]
@nfettinger I'm terribly sorry if I caused any inconvenience. I thought there was, since the discord is linked on the main readme page. (I'm not using discord that often myself.)

**Comment by blackfabs** [comment]
I have the same problem... I set right and abilited Google api key...and when start necro there is a Red allert with that I not configurated the api at Google link...what can i do?

**Comment by jerrysceam** [comment]
Is it still open up the warning 
"You need to configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key"

when I key in my Google API key, and then the Necrobot work normally?

**Comment by n386345222** [comment]
0.9.2 confirmed,got it when i restart necrobot.
i already set an api key in auth condifg.

0.9.3 i cant find out "GoogleAPIKey",when i add it in auth config,it still output:
 (INFO) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key

**Comment by blackfabs** [comment]
i have problem, I've configured API KEY and after restart necrobot i have message "You need to configure your Google Api Key". What is wrong?

**Comment by Dexter145** [comment]
Have also the notification about missing key, I did enter the key in config.json.

I have read that the key isn't needed, but what is the different between using a key and not using one.

**Comment by YouGamePlayHD** [comment]
##  **The last time**
@blackfabs This is a default message! It will always be displayed, but the google walk will work!

**Comment by Rodny9** [comment]
@pipihaianh I can't find "Google" in config file. Maybe because of the auto-updated files?

**Comment by NoxxDev** [comment]
google api key not necessary
