### ISSUE TITLE
Not walking?

### ISSUE THREAD

**Issue by dhip123** [NoxxDev/NecroBot#270]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
Walk to the pokestops like it did yesterday 

### Actual Behavior
doesn't walk

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by YouGamePlayHD** [comment]
Not walking?

**Comment by dhip123** [comment]
yea like it will load up and everything say pokestop X is x meters away ect and then just sits there

**Comment by dhip123** [comment]
welp i fixed it, set show walk variant to true and use googlewalk to false

**Comment by YouGamePlayHD** [comment]
It doesn't sit but it walks on the streets. The time to PokeStop is wrong in this mode.
