### ISSUE TITLE
what does "RandomlyPauseAtStops" do if set to true?

### ISSUE THREAD

**Issue by raymonders** [NoxxDev/NecroBot#273]
Also, is there a way so that the bot walks to the nearest available pokestop possible? Mine always chooses stops that are 200m away, even though there are others closer nearby available (yes they are available, i checked the log and they werent accessed yet within the past 5 minutes)

**Comment by YouGamePlayHD** [comment]
RandomlyPauseAtStops is used for avoiding bans. It will make the bot stop at certain pokestops which are chosen randomly for a short time before continuing.
