### ISSUE TITLE
Anyone got a good config?

### ISSUE THREAD

**Issue by jskyjake2013** [NoxxDev/NecroBot#274]
I am looking for a config with around 200k exp per hour

**Comment by mosca90** [comment]
and ban after 2 days? :video_camera:

**Comment by jskyjake2013** [comment]
sure @mosca90

**Comment by jskyjake2013** [comment]
I'll just make the sniping locations near santa monica @mosca90

**Comment by YouGamePlayHD** [comment]
Enjoy ^^
http://pastebin.com/zt28dJDp

**Comment by mosca90** [comment]
With 200k exp per hour, u will not be banned like istant?

**Comment by YouGamePlayHD** [comment]
Oh yes, you will

**Comment by YouGamePlayHD** [comment]
Softban (Bypassed)
5 Minutes later:
IP-Ban -.-

I tried it out and lost my account for 24 hours (CatchFlee).
The config I've sent will make you bot safely even though you farm at a decent speed.

**Comment by jskyjake2013** [comment]
Thanks @YouGamePlayHD

**Comment by YouGamePlayHD** [comment]
np

**Comment by jskyjake2013** [comment]
@YouGamePlayHD Do you know why it says (ERROR) There are no usable pokestops in range, then keeps repeating that? It does this every so often!

**Comment by smoothrunnings** [comment]
@YouGamePlayHD You are walking too fast. No human can walk at 18.16kmph. On average people walk 3 ~ 5kmph. If you set it above 5kmph you will get banned!

**Comment by jskyjake2013** [comment]
@smoothrunnings Do you know why it says (ERROR) There are no usable pokestops in range, then keeps repeating that? It does this every so often!

**Comment by khairulpetrcech** [comment]
@jskyjake2013 its IP ban..what did u do ? use multiple bot in 1 pc ?

**Comment by samuraitruong** [comment]
poor for a newbie :)

**Comment by mosca90** [comment]
@smoothrunnings yeah, but u can ride a bike for example.. 8 +-2/3 km/h would be good probably
