### ISSUE TITLE
API Question - Discord is no help sorry

### ISSUE THREAD

**Issue by wilsondgonzales** [NoxxDev/NecroBot#275]
question in regards to API: 
I've created on to work with the bot and it works, but when i restart the bot, it asks me to configure an API key. Is there something I'm unaware off? like do these keys expire and do i have to create/enable them again whenever i run the bot?

**Comment by YouGamePlayHD** [comment]
That message is default. It will always display that even if it's working.
I get this message every boot and google walk is working fine :)

**Comment by wilsondgonzales** [comment]
oooo ty ty
