### ISSUE TITLE
0.9.3 waiting for Api key after some restarts

### ISSUE THREAD

**Issue by malfuncti0n** [NoxxDev/NecroBot#276]
After updating to 0.9.3 i was able to use the bot for many hours with the Api key that i got from google.

after a restart of the aplication, the second i think on version 0.9.3 its started  to ask for api key even if i can i see it in file and even if it worked for some hours.

**Comment by wilsondgonzales** [comment]
that's a default message eventhough it's setup
i asked the same thing earlier

**Comment by DavideRaggi** [comment]
It's an "info", not an error.
