### ISSUE TITLE
0.9.3 Telegram restart loop 

### ISSUE THREAD

**Issue by Danxor1** [NoxxDev/NecroBot#278]
After the /restart, the BOT don't start, he only restart.

If I disable telegram, it runs

**Comment by YouGamePlayHD** [comment]
The Bot doesn't start, he restart? 
What du you mean?

**Comment by Danxor1** [comment]
The BOT is restarts repeatedly after 5-10 second.

**Comment by NoxxDev** [comment]
Fixed
