### ISSUE TITLE
not team? WTF!? (levelup)

### ISSUE THREAD

**Issue by alexander171294** [NoxxDev/NecroBot#28]
### Actual Behavior
I can't choice team?

### Your config.json
my config.json is ok

### Steps to Reproduce
First, use a new google account, and not open the game, start the bot directly in the account. Then, the bot increase level from 0 to 6-7, now enter to your account, in this point, the game request nick, and avatar, then you are in lvl 6 without team, and isn't possible pick one.

### Other Information
Version: latest
Windows Version: win7
What is affected: levelup

**Comment by kevinpark1217** [comment]
Cancer. Close this issue, please. @NoxxDev

**Comment by koubie** [comment]
bruh.... you are using FREE bot, you know that you are lucky simply because it is FREE. if you dont appreciate it thats ok. dont WTF here man. FUCKING stay home and DEVELOP the bot for your FUCKING self.

**Comment by petpetpetvm** [comment]
get a gym so you can choice a team
