### ISSUE TITLE
Startup Delay is not working

### ISSUE THREAD

**Issue by singwong28** [NoxxDev/NecroBot#281]
On version 0.92/0.93, I find that StartupWelcomeDelay=true is not working
In previous version, i can confirm the location and press any key to continue. In this version,   it seems bypass this setting even StartupWelcomeDelay set to true.

**Comment by Dexter145** [comment]
Already mentioned it https://github.com/NoxxDev/NecroBot/issues/197

**Comment by NoxxDev** [comment]
Fix in v0.9.5 or upper
