### ISSUE TITLE
PERMANENT BAN

### ISSUE THREAD

**Issue by ronalbur** [NoxxDev/NecroBot#282]
Good afternoon guys,

After two hours using the bot I got a permanent ban. I don't know why. I had everything good.

**Comment by YouGamePlayHD** [comment]
PermaBan? No login with message:
Failed to get game info or so?

**Comment by YouGamePlayHD** [comment]
I use it since 8 hours now - no ban?

**Comment by czokalapik** [comment]
Just got perm ban too on one of my accounts. Bot suddenly shuts down, but before that, there is msg in console "Probably Permanent Ban". And after logging in to game on the phone i have "failed to get game data from the server".

I'm botting in San Fran but botting in Poland.
Now i'll try 2 new accounts, one in SF with SF proxy, second botting in my city. I'll let you know after a week (or untill ban) how that goes.

**Comment by ronalbur** [comment]
I'm gona try Hackemon.

**Comment by czokalapik** [comment]
actually, hackemon isn't best bot out there, there is one with really human behavior (but without GUI), can't remember whats it's called, i'll try to find it.

**Comment by smoothrunnings** [comment]
@ronalbur if you play like an idiot you'll get banned. MOST people don't spend more than 3 or 4 hours a day playing pokemon because they have to do more important things, like work, etc.

**Comment by ronalbur** [comment]
But two hours is not so much.

**Comment by czokalapik** [comment]
@smoothrunnings actually, my acc that just got banned was played with all safe guards on, 3-5 hours a day, always pretty same hours, speed from 4-9kmph, with mon/stops per hour limits.

**Comment by RavenHome1** [comment]
could ninatic be comparing ip adress to the location of the player?, that can be a give away to location faking

**Comment by ronalbur** [comment]
I'm fucked up.

**Comment by czokalapik** [comment]
@RavenHome1 that's what i'm thinking ;]

**Comment by avexus** [comment]
some legit players play like 10 hours a day. It's not how they put their criteria on banning people.

**Comment by RavenHome1** [comment]
@czokalapik if that is the case then F****

**Comment by kassumi** [comment]
How about average time required to catch a pokemon. It takes me like 10-30s while playing legally, but bot does it within 1-2s. That might be this

**Comment by atobolden** [comment]
30 minutes ago i got banned too :(

**Comment by djlsoccer89** [comment]
same i got banned too, im pissed

**Comment by RobertHue** [comment]
evolving takes about 30s, recycling needs about 10s and pokemon catches what kassumi says about 30s. With all that in the config the bot shouldn't be able to reach the 80 pokestops and 80 pokemons caught per hour anyways. And the total exp per hour doesn't exceed 10k with that.

I wonder what kind of config the guys had that got banned and how much exp/hour they had?
Teleporting around and sniping is too risky anyways.

**Comment by zapahacks** [comment]
I think all might be explained by issue #293...

**Comment by jimkaya** [comment]
got a ban, dont know why...
very save config, slow walking, high delays, max 8h per day running.

but with a new message:
"User credentials are invalid and login failed"

credentials cant be wrong... or my acc is hacked :D
