### ISSUE TITLE
Real speed by using GoogleApi?

### ISSUE THREAD

**Issue by vipery** [NoxxDev/NecroBot#284]
Serously im confused.
![0774fca5280348149a74198f6492d081](https://cloud.githubusercontent.com/assets/12803617/17824149/0b544562-6669-11e6-8842-27386ce43247.png)

**Comment by czokalapik** [comment]
basic walking speed is 5kmph, goes up to 9kmph, how fast d u think you are walking? sometimes slower, sometimes faster. that is randomness that can fake automatic recognizing of bots

**Comment by vipery** [comment]
took 150 sec instead 30 sec. As u see avg speed 5 kmph. Something wrong in calculating or walking speed

**Comment by kassumi** [comment]
"GoogleWalkConfig": {
    "UseGoogleWalk": true,  -> false
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "",
    "Cache": true

maybe this will work? o-o

**Comment by rjcute123** [comment]
the distance is measure by a straight line from point a to point b but when using google walk.. the bot will walk on the street like  a person walking... thats why the bot takes time to arrived the destination

**Comment by ValorRed** [comment]
How can I display the walking speed info?
