### ISSUE TITLE
Setup Google API key, but still alert

### ISSUE THREAD

**Issue by ValorRed** [NoxxDev/NecroBot#285]
![config](https://cloud.githubusercontent.com/assets/20829876/17824411/d8d38d70-662f-11e6-9d69-d5c8e5ae3ce4.png)
![alert](https://cloud.githubusercontent.com/assets/20829876/17824416/dd41ecf8-662f-11e6-9169-f3b7394846c6.PNG)

I basically use this URL: https://developers.google.com/maps/documentation/directions/get-api-key
press the "GET A KEY" blue button to generate the key, then put in config.json

Is it something I did wrong? Or is it just false alert?

**Comment by RavenHome1** [comment]
i am having the same i thing, i disabled google walk for now, i know that is  risky to do so but i am not running into any softbans doing so

**Comment by kassumi** [comment]
same problem here

**Comment by YouGamePlayHD** [comment]
Guys. I am telling this for the 5th time now:
It's just a default message, so google walk will work and there won't be any issues...

**Comment by theskyfuker** [comment]
same here
