### ISSUE TITLE
Someone fix the lucky egg evolve issue 

### ISSUE THREAD

**Issue by daproject85** [NoxxDev/NecroBot#287]
It's been going on for a lon time . The setting to use lucky egg for x number of evovles don't work. It says it will wait for X more but then right after your pokemons evovle

**Comment by therockers111** [comment]
my config:
    "UseLuckyEggsMinPokemonAmount": 60,
    "UseLuckyEggsWhileEvolving": true,
    "EvolveAllPokemonWithEnoughCandy": false,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 70.0,
    "KeepPokemonsThatCanEvolve": true,

**Comment by tutti13** [comment]
Setting "EvolveAllPokemonWithEnoughCandy": false still gives me the info that it will wait until i got x more pokemon (70% of inventory)...
