### ISSUE TITLE
Feature Request: Save GPX-Waypoint

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#288]
Hi Devs!

Could you please implement a function similiar to LastPos.ini to save the last visited waypoint of a gpx-path to resume this path after bot restart?
Thank you for all the good work!

**Comment by kassumi** [comment]
While on idea topic, adding commands would be nice, specially one like "Snipe" which would basically snipe one pokemon and then just go back farming. Also "ChangeSpeedTo x" and "KillSwitch on/off" would be great xd. Or just simply "ChangeValue ValueName Value" ex: "ChangeValue WalkingSpeedInKilometerPerHour 10.16"

**Comment by RavenHome1** [comment]
https://github.com/NoxxDev/NecroBot/issues/271

**Comment by NoxxDev** [comment]
check v0.9.6
