### ISSUE TITLE
No Google API Config

### ISSUE THREAD

**Issue by JaCGamingGuy** [NoxxDev/NecroBot#289]
Not sure why but I can't add the Google API to the auth.json file. Tried adding the code from a previous version but still no luck.

**Comment by RavenHome1** [comment]
google api configs exists in config.json not auth.json, also there was some changes in the config layout from 9.0 to 9.3 so that might explain it.

**Comment by JaCGamingGuy** [comment]
omg thank you lol

**Comment by RavenHome1** [comment]
you're welcome ;], don't forget to close the issue

**Comment by JaCGamingGuy** [comment]
wait one sec lol i cant find the section in the config file... is there a line missing?

**Comment by RavenHome1** [comment]
if you are using wordpad from windows do ctrl+f to open up search menu, other programs do have this feature if you happen to have any.

**Comment by JaCGamingGuy** [comment]
already did that... still can't find anything relating to the Google API

**Comment by JaCGamingGuy** [comment]
Could you post the code that you have or have used in this thread?

**Comment by RavenHome1** [comment]
huh....weird, maybe try to download a fresh copy of the bot, i am pretty sure the options are there

**Comment by JaCGamingGuy** [comment]
i've done that 3 times lol i'll do it again

**Comment by RavenHome1** [comment]
i am a bit confused are you trying to add the google api key or looking for the options for your google account?

**Comment by JaCGamingGuy** [comment]
I FOUND IT!!! i've downloaded it 3 times... the 4th is the charm XD thanks anyway

**Comment by RavenHome1** [comment]
ok then, that was weird but you're welcome XD, don't forget to close the issue.
