### ISSUE TITLE
(ERROR) Niantic Servers unstable, throttling API Calls.

### ISSUE THREAD

**Issue by zzzz9999** [NoxxDev/NecroBot#291]
What this means?

**Comment by JaCGamingGuy** [comment]
I think it's saying that there's too many people using the bot at the same time. But It's said that a few times for me but it would still work perfectly fine.

**Comment by mo0ojava** [comment]
It happens when strategy.HandleApiFailure decides to Abort the current attempt at communicating with the server. I'd would guess that includes irresponsive/congested servers along with a bunch of other possible reasons.
