### ISSUE TITLE
Bot doesn't work properly?

### ISSUE THREAD

**Issue by JaCGamingGuy** [NoxxDev/NecroBot#292]
I've set everything up correctly.. Google API and all... In previous versions, the bot would instantly start searching around specified coordinates, but now it just states "No usable PokeStops found in your area. Is your maximum distance too small?"

Any thoughts?
![botissue](https://cloud.githubusercontent.com/assets/14092298/17826477/249cbcf4-663f-11e6-9870-f299776be849.PNG)

**Comment by albysprx** [comment]
it's a softban, you can try to change your ip with a proxy

**Comment by petpetpetvm** [comment]
change ip or stop botting for about 1hr
