### ISSUE TITLE
[Issue] Fix protocol API. Or Niantic keeps banning users of 3rd party apps. Current public Rocket API is completely broken.

### ISSUE THREAD

**Issue by WinterMoxRZ** [NoxxDev/NecroBot#293]
Here's recap of what I wrote in issue "#265 [Issue] Fix protocol API. Current public Rocket API / FeroxDev is completely broken."

I give you a hint:

//static for now
sig.Unk22 = ByteString.CopyFrom(new byte[16] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F });

In issue "#146 update pogoprotos" thekjohn already brought this somewhat up but that's not all. There are others issues.

Most critical issue is broken low level protocol API and Unk22 or should I say SESSION_ID or SessionHash as others have named it is example of those issues.

Then there are also critical higher level protocol API issues but right now some of them can be handled with workarounds. None the less also these issues should be fixed on Rocket API. These issues include such things as configuring PoGO avatar, trainer naming, pop-up messages, collecting badges etc.

Right now adding such features as KillSwitch + CatchEscapeExceeded etc, yournavigation.org + Google Maps routing, Costura.Fody, etc is complete nonsense!

Niantic can and does identify every 3rd party application which uses BROKEN protocol API. Hence Niantic has and will identify every Google or PTC account used with these tools.

Niantic could ban every 3rd party user in few seconds or at most in minute or so. Why they don't do that? Well most of you already know the answer, because they don't want to give out how people end up in ban waves.

Right thing to do at the moment would be to dig in authentic PoGO client traffic either using MITM or other methods and rewrote Rocket API in away which emulates 100% accurately official PoGO client.

My 5c.

**Comment by WinterMoxRZ** [comment]
Now here is part two of my hints.

As some people may say "pics or it didn't happen" here's two pictures.

This is from official client X:

![01](https://cloud.githubusercontent.com/assets/21127256/17826688/1c467864-667c-11e6-9cef-bb20b41a059d.gif)

This is from public Rocket API:

![02](https://cloud.githubusercontent.com/assets/21127256/17826697/36ee27fc-667c-11e6-84d7-24a8a40d5b41.gif)

These are from same request, can you spot the difference?

Now this is my 10c.

**Comment by WinterMoxRZ** [comment]
So now it's time for third hint.

SESSION_ID isn't only static element in broken protocol API.

Here's another example, first part is copy/paste from public Rocket API C# code.

var downloadSettingsMessage = new DownloadSettingsMessage
{
    Hash = "05daf51635c82611d1aac95c0b051d3ec088a930"
};

This picture is from public Rocket API traffic dump:

![a01](https://cloud.githubusercontent.com/assets/21127256/17826766/c2de49ae-667c-11e6-8a77-5cda31c1a3c0.gif)

Yep once again static element for Niantic to catch users of public Rocket API.

Following two pictures are from official client:

![a02](https://cloud.githubusercontent.com/assets/21127256/17826794/0abd9a68-667d-11e6-9e5b-52637b154db6.gif)

![a03](https://cloud.githubusercontent.com/assets/21127256/17826801/123ab83e-667d-11e6-98a2-38403faf8af2.gif)

Traffic from official client doesn't look anything like what public Rocket API sends.

What I have shown to you here is just small part of what is broken in public Rocket API.

Niantic has long history of hunting botters and cheater so they already knew all this.

Let's hope that one of the root causes for major ban waves will be fixed.

W out.

**Comment by Skolzack** [comment]
Nice! These new versions of Necrobot is bugged as fuck dude

![screenshot_2](https://cloud.githubusercontent.com/assets/20953554/17826939/0f67b3c2-664c-11e6-935b-b9e1f65a043b.png)

**Comment by Sifu213** [comment]
Any private perfect API existe for now?

**Comment by Skolzack** [comment]
@Sifu213 I don't think so :/

**Comment by evs38** [comment]
We still don't know how these strings are generated.

**Comment by TemhAAhmeT** [comment]
Does Pokemongodev trying to figure it out? Shall we wait? Or everyone gave up after legal problems?

**Comment by RavenHome1** [comment]
well darn, there goes my second account on the next ban wave ;-;

**Comment by clash-votter** [comment]
Well then if Rocket API is broken/outdated as wonderfully pointed out here with technical detail, wouldn't it be an improvement to use this API ([available here](https://github.com/tejado/pgoapi))?

In the past a bot also using Rocket API got me permaban from logging too many softbans with it (pokesniper2, on autosniping mode). All the reason to be convinced that Rocket API is indeed broken.

v0.9.0 doesn't seem to be running into the softbans that its newer counterparts are facing (i.e. not seeing any objects on the map after some time: v0.9.1 and up). Maybe because v0.9.0 and earlier is not using RocketAPI?

**Comment by clash-votter** [comment]
On a related note with the API by tejado, this was posted when unkwn6 was solved
https://github.com/keyphact/pgoapi

**Comment by evs38** [comment]
It is not solved anywhere. tejado/keyphact API are also broken. There are no any ways to fully solve unknown6/unknown9 etc now because they are heavy encrypted.

**Comment by RavenHome1** [comment]
can anyone take a look at pokemobbot and what are they using?

**Comment by lanadelrey92** [comment]
Niantic could ban every 3rd party user in few seconds or at most in minute or so. Why they don't do that? Well most of you already know the answer, because they don't want to give out how people end up in ban waves. @WinterMoxRZ 
So... Soon or later, Permaban for all!

**Comment by Manelito** [comment]
NOX Emulator with real api can't give us perma ban? (sorry my english?)

**Comment by NoxxDev** [comment]
Fixed https://github.com/NoxxDev/NecroBot-Rocket-API/commit/6bc1672760921b5aed812b2bd799936aa23726f6

**Comment by disdain13** [comment]
looking at the new implementation, is there a reason the sig.Unknown25 is rehashed on every request iteration? I am not sure this is needed, and would just cause extra number crunching. My bot runs it like:

`            sig.SessionHash = ByteString.CopyFrom(new byte[16] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F });
            sig.Unknown25 = BitConverter.ToUInt32(new System.Data.HashFunction.xxHash(64, 0x88533787).ComputeHash(System.Text.Encoding.ASCII.GetBytes("\"b8fa9757195897aae92c53dbcf8a60fb3d86d745\"")), 0);

            foreach (var request in requestEnvelope.Requests)
            {
                sig.RequestHash.Add(
                    Utils.GenerateRequestHash(ticketBytes, request.ToByteArray())
                );
            }`

**Comment by sedder0205** [comment]
@Skolzack regarding ur post image also mne having that error but still it is continuing run now kindy tell me f my account that i bot now s gonna ban?
