### ISSUE TITLE
Never got softban but got perma ban immediately.

### ISSUE THREAD

**Issue by likeness123** [NoxxDev/NecroBot#294]
I used Necrobot 9.0 and everything went smoothly. When I used the 9.3 I never got softban either but after I used it once and used it again for the second time my account got permanent ban. What seems to be the problem?

**Comment by Skolzack** [comment]
No one knows.. I bet the RocketAPI was patched by Niantic and now they detect it easy.

**Comment by petpetpetvm** [comment]
they banned randomly, so nothing is a problem, i ran 10 accounts at same way and only 1 got ban in awhile

**Comment by likeness123** [comment]
@petpetpetvm  so probably perma ban is just temporary?

**Comment by aaegb** [comment]
my other account , last played 1 week behind... permaban..

**Comment by CharlesChung** [comment]
I got the same issue, the program auto update itself and changed the Config.json layout, the bot is throwing exceptions, after I fixed those issues and relaunch, it said that I got permanent ban already... =.=

**Comment by Dreker** [comment]
9.0 better than 9.3.

**Comment by tuxfrw** [comment]
9.3 running perfect for me.  :) Thx! Using default configuration with GoogleAPIKey and my coordenates from my City. Be playing all day can cause perma ban? I stop only at lunch and while I'm sleeping.

**Comment by Skolzack** [comment]
@tuxfrw Nothing is safe.. I was doing all things safety and suddenly permabanned.

**Comment by tuxfrw** [comment]
@Skolzack What was your level when it was banned?

**Comment by Skolzack** [comment]
@tuxfrw Level 27. I was using Necrobot 0.8.8 with 10km/h, 22k exp/h, 50 pokemons/h and always looking the limit of 1k pokemons and 2k pokestops 23~24hours, botting 10~13hours per day.. This account had no softbans, only one permaban lol

**Comment by likeness123** [comment]
@Skolzack I think they track every account and check if it is a bot. My friend is level 35 never got a softban his account is purely a bot since level 1.

**Comment by petpetpetvm** [comment]
@likeness123 per. ban

**Comment by NoxxDev** [comment]
v0.9.3 is false/positive softban, fix in v0.9.4
