### ISSUE TITLE
Program will continue after they key press

### ISSUE THREAD

**Issue by thuongtin** [NoxxDev/NecroBot#295]
<img width="555" alt="screen shot 2016-08-20 at 6 43 40 am" src="https://cloud.githubusercontent.com/assets/3460591/17827069/997c5f04-66a1-11e6-884c-8a9723746a60.png">

**Comment by AmazingGamerBoy** [comment]
Disable killswitch it config if u dont want to use it

**Comment by petpetpetvm** [comment]
many people said the number of people that you catch per day will make softban, per. ban, that's why there is killswitch came out this update, you can setting the limit of number of pkm that you catch, flee, whatever in config or you can disable it if you want
