### ISSUE TITLE
Slow walking bug!

### ISSUE THREAD

**Issue by Daniel99887** [NoxxDev/NecroBot#296]
It is taking very long to get to places https://i.gyazo.com/1cc53e988383484931976286dc3a3aa3.png

EDIT: I've just used necrobot visualiser and it looks like the bot is following the road any way to disable this?

**Comment by AmazingGamerBoy** [comment]
In config, set UseGoogleWalk to false. it fixed it for me

**Comment by thomatbu** [comment]
yep, because of Google Walking, just turn it off, and you'll fine

**Comment by NoxxDev** [comment]
This is not a bug, occurs because the bot calculates in a straight line from point A to point B, when googlewalki is enabled, uses human routes, increasing
