### ISSUE TITLE
When permaban get an email from Niantic? True or not?

### ISSUE THREAD

**Issue by likeness123** [NoxxDev/NecroBot#298]
I heard if you get permaban you should get an email signifying that your character is permanently banned. Is it this true cause if it is it is possible to log in perma ban characters after a week or a month.

**Comment by tr1p0z** [comment]
Not instant but you get the e-mail.

**Comment by Daniel99887** [comment]
I've never got it.

**Comment by tr1p0z** [comment]
![](https://i.gyazo.com/62cf4d6f47fb62fecb0388fc14ff3231.png)

**Comment by likeness123** [comment]
@tr1p0z I got banned a week ago but I never got the email

**Comment by coreproject2** [comment]
I've never got it.

**Comment by LeHartx** [comment]
Got banned 2 times, no email too

**Comment by czokalapik** [comment]
no emails on 2 banned accounts, one banned a week ago (name still available tho)

**Comment by ausscheider** [comment]
3 Acc banned
1 Email recieved

**Comment by Triky313** [comment]
2 banned and 2 Emails
