### ISSUE TITLE
add some times  try attack gym

### ISSUE THREAD

**Issue by mraksoll** [NoxxDev/NecroBot#300]
add some times attack gym ( optional - not a put pokemons only attack some times randomly not matter if it lose or win ) for it's be more how human

**Comment by mraksoll** [comment]
it's wlak on map - find gym attack them ( gym add how ataked end not attacks 30 min they again ( try attack it randomly times 1 - 3 ...

**Comment by mraksoll** [comment]
i think it's more detectable if bot 25 - 30 lvl's not attack gym's - human try attack it some times - no matter if they 1 or 30 lvl they try for see what it is, but bot's ingor the, always end niatic can see ( it's up 30 end only start attack gym end never attack them on low lvl's

**Comment by nutsky** [comment]
bots attacking gym will make niantic go all out war on bots.

**Comment by mraksoll** [comment]
how the people see who attack they gym if bot not add pokemons to deff  them ?
You up 30 lvl end no one times atack gym you not bot 100? it's stupid real people attack them some time - need only fact of attack - not mater lose o win they! Real people if they 3 lvl they try to atack gyms if they 1000% lose they try

**Comment by mraksoll** [comment]
if i bee neatic i firs see logs of people what up 25 - 30 end never atack gyms
2 i see logs people what attack gym's but never atack thme on low lvl's
or you think niatic dont undestand this ?  it's more simple detect

**Comment by mraksoll** [comment]
no try atack gym's on low lvl ? only exp end pick pokestops ? = 100% bot

**Comment by mraksoll** [comment]
all my bots what attack gym with hands on low lvl not banned

**Comment by mraksoll** [comment]
not need too deff them or pickup  only try attack end go away  every 20 - 30 min 1 - xx times
no mater lose or win ( only fact attack them )

**Comment by mraksoll** [comment]
About
"bots attacking gym will make niantic go all out war on bots. "
Now they not ban all bots?) I thik this write legits who scare the bot pick all gym's - but now all gym' piked by boots ! it's nosense. End thninkin about no add make easy no detects bot - end i think first bot what add this feature bee more undetectable , its feature not for pikup gym's bee only for try it atack not a pikup or add to deff.

**Comment by thomatbu** [comment]
Open Bluestacks and attack gyms by yourself. Auto attack gyms will ruin the game. Who plays the game that doesn't want to open the game? Bot just helps you about pokemons, not everything. You have hands or not?

**Comment by mysterykj** [comment]
@thomatbu nice answer.

**Comment by mraksoll** [comment]
You last idiot ? you read what i write ? I think no.
Read againg end mayby you undestand what i meen
If not it's diagnos ...

**Comment by thomatbu** [comment]
Cry more, trash.

**Comment by mraksoll** [comment]
You idiot...

**Comment by mraksoll** [comment]
if dont undstand how this can be detect , who whant pick up gym automat do this, but i saing not pick up them end no put in pokemons , i say about atack them some times ! for bot bee how human

**Comment by mraksoll** [comment]
or you dont understand sow simple thing ? if bot only exp 30 lvls + they see - its 100% bot. But stupid kid's say dont add - this ruin the game? Are you serios ? bot not ruin the game ? are you joke ? it's hard to how you say load no nox app player end simple make script for auto attack gym's ?
I say about this . bot exp ,exp up 5 lvl try atack gym, exp,exp end after 30 min try atack  etc. for its bee how human. i not say add auto pick gyms end add pokemons to them , only try attack , end meek it optional. who whant use they feature , who not.

**Comment by mraksoll** [comment]
I dond understand all people who copy past sources of bot's  so stupid end dont understand so simple thing ? Or you think niatic idiot's end they dont know - all bot's no atack gym...
