### ISSUE TITLE
Feature request - Walk to catch all pokemon nearby

### ISSUE THREAD

**Issue by samuraitruong** [NoxxDev/NecroBot#302]
Would love to have feature that pull data from Skiplagged or https://www.pokemonradargo.com then walk to catch all of them (or apply filter by pokemon, distance...)

Should combine to fort pokestop when walking

**Comment by iwean** [comment]
Set all snip setting on config.json file to "true" :)

**Comment by LeHartx** [comment]
Isn't it extremely risky to snipe pokemons

**Comment by samuraitruong** [comment]
Snip is risky, I finished draft has implemention for this already. It will walk to pokemon  just like walk to pokestop, catch all pokemon it found on the way, in testing right now
