### ISSUE TITLE
Help-me transfer pokemons with stats.

### ISSUE THREAD

**Issue by f3l1p1nh07** [NoxxDev/NecroBot#304]
As I put to the bot transfer all Pokemon that does not have the minimum requirement?

     "KeepPokemonsThatCanEvolve": true,
     "KeepMinCp": 0,
     "KeepMinIvPercentage": 90.0,
     "KeepMinLvl" 20
     "KeepMinOperator": "and"
     "UseKeepMinLvl": true,
     "PrioritizeIvOverCp": true,
     "KeepMinDuplicatePokemon": 2,

I thought putting these configurations, any pokemon that had any CP, but with IV above 90% and level above 20 had been in my inventory, but they are getting all the Pokemons, as do I get only Pokémon with LEVEL 20 and IV higher 90%?

**Comment by wilsondgonzales** [comment]
"UseKeepMinLvl": true, <<---- this needs to be false because it's using the pokemon level instead of CP or IV values to determine what to keep

**Comment by f3l1p1nh07** [comment]
but if I want to use the level in place of CP can not? example, want pokemon with LEVEL 20 but with IV 90%, do not have to?

**Comment by ShadXo** [comment]
Your missing commas also?
Maybe try with the commas?
     "KeepPokemonsThatCanEvolve": true,
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 20,
      "KeepMinOperator": "and",
      "UseKeepMinLvl": true,
      "PrioritizeIvOverCp": true,
      "KeepMinDuplicatePokemon": 2,

**Comment by wilsondgonzales** [comment]
@f3l1p1nh07 while it would make sense for the bot to use all those filters, I'm not 100% sure it would function in that way. I've always opted to not use level as a determining factor like the default config that gets generated on first run

**Comment by ShadXo** [comment]
@wilsondgonzales You maybe right, so "UseKeepMinLvl": true, disables KeepMinCp or KeepMinIvPercentage? that would be weird.

**Comment by f3l1p1nh07** [comment]
@wilsondgonzales then in fact, I do not want to use the CP to determine because the level automatically is connected to the CP attribute the higher the level the greater the CP, then you have Pokemon that will obviously not get CP 2000 but can get level 20, example. then I wanted to disable the CP and leave only the level and iv ... if you are level 20 and is greater than 90% leave in the inventory, if not transfer ...

**Comment by wilsondgonzales** [comment]
@f3l1p1nh07 

KeepMinOperator": "and" <<-- change to "OR" to only use IV as a determining factor for keeping prokemons by setting a high CP

As mentioned before, I'm not 100% confident the bot can use both. I understand what you want and looking at how to setup the config, technically it should be these parameters that would give you what you're trying to achieve

"KeepMinCp": 5000, <<--- set this to a ridiculous number so it always results as false however i believe                                 prioritizeIvOverCP` should technically bypass CP comparison.
"KeepMinIvPercentage": 90.0,
"KeepMinOperator": "or",
"PrioritizeIvOverCp": true,

"KeepMinLvl": 20,
"UseKeepMinLvl": true,

**Comment by f3l1p1nh07** [comment]
@wilsondgonzales and for serving this function ?

"TransferWeakPokemon": true
