### ISSUE TITLE
What Api do i need?

### ISSUE THREAD

**Issue by KuuuroNeko** [NoxxDev/NecroBot#306]
APIs de Google Maps

Google Maps Android API
Google Maps SDK for iOS
Google Maps JavaScript API
Google Places API for Android
Google Places API for iOS
Google Maps Roads API
Google Static Maps API
Google Street View Image API
Google Maps Embed API
Google Places API Web Service
Google Maps Geocoding API
Google Maps Directions API
Google Maps Distance Matrix API
Google Maps Geolocation API
Google Maps Elevation API
Google Maps Time Zone API

**Comment by Ev0luti0n2016** [comment]
https://developers.google.com/maps/documentation/directions/get-api-key

At the top right there is a box to click to "Get A Key"
