### ISSUE TITLE
what ?

### ISSUE THREAD

**Issue by ChenQiuming** [NoxxDev/NecroBot#308]
You need to configure "GoogleAPIKey", get API Key in link: https://developers.go
ogle.com/maps/documentation/directions/get-api-key

0.9.3

{
  "AuthConfig": {
    "AuthType": "Ptc",
    "GoogleUsername": null,
    "GooglePassword": null,
    "PtcUsername": "123123",
    "PtcPassword": "123qweqwe",
    "GoogleAPIKey": "AIzaSyD90PUQxpmbSC3BXUzlhRpNLY8s6AVPXv*"

**Comment by wilsondgonzales** [comment]
9.3 has the api key setting moved into config.json if you had the bot auto update, that might've caused the problem. Save your old config and delete the auth and config files to let the bot renegerate them

**Comment by thomatbu** [comment]
Just open and close the bot few times, it may fix your issue

**Comment by Kermel** [comment]
Actually it will not, the message is connected to two configuration parameters - one is the UsegoogleWalk and the other one is UseGPXPathing (I have not cheked why is that but unless you set UseGPXPathing to true, the message will be there, however the API key will be normally used if specified, only the message will appear).
(Bear in mind that if you set the UseGPXPathing to true then you of course must specify the GPX file as well :) )

**Comment by YouGamePlayHD** [comment]
The message is only there to remind you of the duty to have an API-Key configurated ;)

**Comment by NoxxDev** [comment]
google api key not necessary
