### ISSUE TITLE
Improvement idea: Pause bot till the hour passes and resume for the next

### ISSUE THREAD

**Issue by k0lev** [NoxxDev/NecroBot#309]
Currently, the bot directly stops working and expects manual action if it reaches a limit. Wouldn't it be awesome if that's just a pause function until the hour passes and then resets with the new limit for next hour? It resets the limit of 40 (let's say) each hour anyway, so it knows when the hour started and when it should end. Why not pause it to fulfill that quota?

**Comment by ShadXo** [comment]
I think best would be setting a limit like 1000 catches and 2000 pokestops a day?  (the limits of being banned?), and it will tranfer that to around 41 catches a hour or something like that.
 something like its done with the pokestop limit right now and than the next day it would continue till the limit is reached.

**Comment by k0lev** [comment]
Nah, it would look a lot more natural if the limit remains as is and spreads the 1000 limit (2000 for pokestops) throughout the day - 40 per hour pause and wait for next hour.

Be sure that Niantic arrived at the limit per day by monitoring the hourly activity. Probably it's based on 8 hours sleep and another 16 hours of active play witch 1000/16 = 62/h. The most natural way would be to limit 62/h for 16 hours, then pause the bot for 8 hours and start over.

But perhaps if you do the whole limit of 1000 for each module (rotate till the all get maxed) in 2-3 hours and kill the bot for the day, you might actually be safe... I can see it as two aproaches - hourly and steady growth and rush limit approach... I think the hourly is better with that 8 hour pause (be sure they will soon start banning 24/7 accounts).

**Comment by k0lev** [comment]
This is what I came up with:

`:loop
@echo off
@set /a x=0
@echo Starting 16 loops, one per hour, sit back...

:while

set /a result=%RANDOM%*3690/32768+3600

if %x% lss 16 (
	echo %x% times started out of 16, then 8-hour nap!
	set /a x+=1
	start "" "C:\Users\YOURUSERNAMEEEEEEEEEE\Desktop\Release\Necrobot.exe"

	echo The bot will be running for %result% seconds and then restarted
	timeout /t %result%	
	taskkill /f /im "Necrobot.exe"
	goto :while
)

@echo Having an 8-hour sleep... Piss off!
timeout /t 28800
goto loop`

What it does is makes sure that in case that we reach a limit in some hour, we restart it again every hour. The idea is to have it running with 16h limits, as already mentioned above, and then sleep for 6 hours. It works flawlessly, but still it will be stupid, since it might close/open the bot without it actually reaching a limit. Imagine if the bot pops an egg at 58 min, evolves 2 pokemons, and we close/open it and it starts from the beginning with transferring all...

**Comment by ShadXo** [comment]
Code looks nice, thats a start :), Thanks!
