### ISSUE TITLE
Free proxy server ?

### ISSUE THREAD

**Issue by khairulpetrcech** [NoxxDev/NecroBot#311]
Anybody know whre to get free proxy server that working ?

What i found not working,,eirther not working at all or being IP ban.

Thanks in advance !

**Comment by bulubebek** [comment]
most free proxy is sucks. you better setup your own proxy with auth support.

**Comment by YouGamePlayHD** [comment]
You mean for IP-Ban-Bypassing?
I use CyberGhost, free and can change your IP completely. Niantic has no chance to detect you and your IP-Ban is gone ;)

**Comment by NoxxDev** [comment]
Please, this not a forum
