### ISSUE TITLE
How Config For Snipe

### ISSUE THREAD

**Issue by TobBeContinous** [NoxxDev/NecroBot#316]
NecroBot 0.9.3
Hi My Friend
How Config Min Delay Of MinDelayBetweenSnipes , DelayBetweenPokemonCatch , DelayBetweenPlayerActions And WalkingSpeed for Necrobot Sniper Dratini Is Most Safety

**Comment by daarisieweer** [comment]
Im gues its better not to snipe for specific pokemon, adjust some changes in your ''config file'' about the catchdelay, movingspeed, catchsucces .                misstrow on 11%or some

Sniping of pokemon could lead for faster ban
