### ISSUE TITLE
how to set pokestop farming?

### ISSUE THREAD

**Issue by LobsterX** [NoxxDev/NecroBot#317]
i recently upgraded to .9.3 and the bot stoped tp farm pokestops.

i totally ran out of pokeballs

where is the setting to configure to farm pokestops?

**Comment by khairulpetrcech** [comment]
set catchpokemon to false..set all setting of sniping to false..there u go

**Comment by LobsterX** [comment]
it still didnt' work.... i wonder wht is wrong

**Comment by daarisieweer** [comment]
"SnipingSettings": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false
  },
  "PokemonSettings": {
    "CatchPokemon": true,

i have it on true, but if u change that True into false,

this should be the code-->>  "CatchPokemon": false,

it should work otherwise i guess, better wait till next version.

**Comment by YouGamePlayHD** [comment]
Is it displaying:
No pokestops found in .....?
That would indicate an IP-Ban
