### ISSUE TITLE
Help me ~~

### ISSUE THREAD

**Issue by harryhalim05** [NoxxDev/NecroBot#318]
![image](https://cloud.githubusercontent.com/assets/21101715/17831149/a51aae46-670b-11e6-8de2-1f71cbd68553.png)
Can someone tell me about this? i already wait for 3 days then i cant using BOT ==a v9.3  after i update

**Comment by thib3113** [comment]
the same error here : https://github.com/NoxxDev/NecroBot/issues/213#issuecomment-241013886

**Comment by harryhalim05** [comment]
How to fix this? @thib3113

**Comment by daarisieweer** [comment]
im not sure if im right, but in your map i see alot off files, i have less and bot is working.
maybe delete this map and download the new 0.9.3 version.

**Comment by harryhalim05** [comment]
let me try first @daarisieweer

**Comment by daarisieweer** [comment]
what i  also did, change some thing in the Config file, like walking speed, catchsucces, misstrow(i got it on 11%) dont make to big changes , just a little so not every user got the same ^^

**Comment by harryhalim05** [comment]
its work, ty @daarisieweer

**Comment by daarisieweer** [comment]
Good happy to hear my first post helped:D:D

i got like 5k-10k exp in a hour and that should be oke, takes some time but alot more riskfree

**Comment by YouGamePlayHD** [comment]
Close this issue if it's cleared.
