### ISSUE TITLE
0.8.8+ Suggest enable UseWebsocket by default

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#32]
UseWebsocket is the requirement for bot visualizer (which is extremely useful when boting)

Check out:
https://github.com/nicoschmitt/necrobotvisualizer

**Comment by GioBregs** [comment]
how do you even get visualizer to run

**Comment by neau** [comment]
@GioBregs 
You start the Necrobot with the following settings enabled:
```
  "UseWebsocket": true,
  "WebSocketPort": 14251,
```
Then you start the Necrobot Visualizer, from the bottom right click on the 'Settings' button and make sure the Vizualizer is using the websocket with the correct port from Necrobot's config.

Usually you should be able to connect both just by setting UseWebsocket to 'true'.

**Comment by GioBregs** [comment]
how do u start the visualizer

**Comment by neau** [comment]
Run NecrobotVisualizer.exe. There is nothing to config there.

**Comment by GioBregs** [comment]
ok now i get it u need to run the bot and visualizer at same time

thank you

**Comment by petpetpetvm** [comment]
not by default :), because there are many people (like me) bot on multiple accounts

**Comment by NoxxDev** [comment]
@petpetpetvm 
Responded this issue
