### ISSUE TITLE
I got the API Key but idk where to put it in

### ISSUE THREAD

**Issue by TheWaah** [NoxxDev/NecroBot#321]
Ive got the API Key from google but idk where to put it in. In Auth.json there isnt something like: API Key.
How do i put it in?

**Comment by ShadXo** [comment]
Download the newest release 0.9.3 and put your key in the config.json at the row  "GoogleAPIKey": "Your key",

**Comment by TheWaah** [comment]
I did, it says i have to put it in. And is it normal to have 9k exp/h?

**Comment by daarisieweer** [comment]
Yes its normal to have around 5-10k exp/h,  what ShadXo tell, i must work that way, but either wont work by my, still saying 2500 qotes ect...

**Comment by ShadXo** [comment]
@TheWaah It will work, the message is just to inform you, so you dont forget.

**Comment by Cyrus-Wong** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16282423/17832741/9db6a1ec-673c-11e6-96de-ef968ad7ca09.png)

which type of api should I choose?

**Comment by thomatbu** [comment]
Android
