### ISSUE TITLE
0.9.3 or 0.9.0

### ISSUE THREAD

**Issue by tuxfrw** [NoxxDev/NecroBot#322]
Hi all,

I see some people are complaining of banishment with the version 0.9.3 and advised to use the 0.9.0. I'm not having problems with the version 0.9.3, yet. You advise me to go back to the version 0.9.0?

Thx,

**Comment by clash-votter** [comment]
#293 #294 #297 #314 
Read all these issues and decide for yourself.

**Comment by likeness123** [comment]
9.0

**Comment by tuxfrw** [comment]
Ok running 0.9.0 without check updates and autoupdates.  :)

**Comment by peeveswozere** [comment]
How can I get the outdated version?

**Comment by p3monty** [comment]
https://github.com/NoxxDev/NecroBot/releases/

**Comment by boylondon** [comment]
0.9.3 is better for me,...
