### ISSUE TITLE
[HELP\BUG] Bot doesn't search lured pokemons with GPX path

### ISSUE THREAD

**Issue by morrrido** [NoxxDev/NecroBot#324]
I know a place near me where there are 5 pokestops that are very frequently lured.

I made a GPX path to run by them frequently. 
Using FastPokeMap I can see the pokemons spawned by the lured pokestops.
Using Visualiser I can see the bot passing correctly by those pokestops and using them but totally ignoring the pokemons spawned by the lures on them.

Bot doesn't catch lured pokemons?

**Comment by kassumi** [comment]
just a question from no-programmer, how do u make GPX like this?

**Comment by morrrido** [comment]
I use https://www.bikemap.net

**Comment by morrrido** [comment]
I have confirmed through the log file that in a 1 hour bot usage, it "activated" 34 pokestops passing multiple other times by them but they hadn't refreshed yet.

During that hour:
It has searched for pokemons 1338 times
It has searched for incense pokemons 1338 times
It has searched for lured pokemons 1 time!!

Why 1 time? How can I increase the search frequency for lured pokemons?

**Comment by YouGamePlayHD** [comment]
Have you maybe switched on any catching filter?
(PokemonNotToCatch, etc.)

**Comment by morrrido** [comment]
@YouGamePlayHD I believe you ment UsePokemonToNotCatchFilter which is set to false
"UsePokemonToNotCatchFilter": false
Here is my full config:
<a href=http://www.filedropper.com/config_22><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file storage online</a></div>

**Comment by morrrido** [comment]
Check the following screenshots..
![luredpokemons](https://cloud.githubusercontent.com/assets/20801587/17834398/840d7e6a-6736-11e6-83b2-d07e576be94c.png)
![luredpokemons2](https://cloud.githubusercontent.com/assets/20801587/17834399/85e47324-6736-11e6-8954-f1b0f4f74419.png)

**Comment by morrrido** [comment]
@NoxxDev in file FarmPokestopsGPXTask.cs
I found that the only place it calls CatchLurePokemonsTask is inside a While cycle which has the following comment:
// warning: this is never entered due to ps cooldowns from UseNearbyPokestopsTask 
If the while cycle is never entered, that explains why it wont search for lured pokemons.
Can you patch this?

**Comment by Capusjon** [comment]
I am not using any GPX file and I think I have the same problem. I'm having my bot in the middle of 7 lures walking radius of 275 meters. It's walking past all the stops but I very rarely see a lured pokemon caught. I've been watching de command window and visualizer for 2 hours straight.

**Comment by morrrido** [comment]
@Capusjon have you checked your log file?
Open in notepad and search for "Looking for lure Pokemon".
If you use notepad++ and use find all in current document it tells you how many times it found it..

**Comment by Capusjon** [comment]
3 times in 1 hour. Doesn't seem right.

**Comment by morrrido** [comment]
@Capusjon Indeed I don't think it seems right either, I'm not sure but I believe my sugestion would fix both cases since it would search for lured pokemons everytime it has a pokestop nearby...

**Comment by Capusjon** [comment]
Indeed, my bot now seems suspicious for not catching enough pokemon :-))

**Comment by Capusjon** [comment]
I'm going to try your fix. Only thing I need to do is clone the repository, edit UseNearbyPokestopsTask.cs. Then install from my repository?
Thats what I'm trying to do now at least..

**Comment by morrrido** [comment]
I don't really know how to test it. I'm new to this GitHub thingy.
I thought one would need visual studio installed in order to compile/build the files.
I don't have visual studio installed, tried to build/compile it from command line using MSBuild but it doesnt work. I'm waiting/hoping for @NoxxDev to try it and give some feedback.
@Capusjon If you manage to try it, please tell me if it works and how you managed to actually try it.

**Comment by Capusjon** [comment]
@NoxxDev @morrrido 

Been busy all night, tried to paste  if (pokeStop.LureInfo != null) { await CatchLurePokemonsTask.Execute(session, pokeStop, cancellationToken); } 
into different locations, didn't really work.
 
I did get some confirmation in the logs of searching for lures with your fix implemented. It did scan for Lured pokemon before looting some stops but it is not working consistently.

Also tried to make it the same as CatchIncensePokemonsTaks (deleting the pokestop reference) this resulted in compiling errors.

I'm now thinking about changing the CatchLurePokemonsTask.cs and making it more like CatchIncensePokemonsTaks.cs. I noticed in the log it is always searching for Incense and Normal pokemon, I hope to make CatchLurePokemonsTask.cs so it's always searching for lure pokemon even if there are no lures arround.

any insights?

**Comment by morrrido** [comment]
@Capusjon I've also been trying to implement it.
I tried what I said and it also didn't seem to work. 
Then I tried some other stuff that also did not work. 
Then I tried placing the code after the `if` cycle. (Before I said it was before the `if` cycle)
So it ended up looking like this
![patch](https://cloud.githubusercontent.com/assets/20801587/17854182/b11533ca-6868-11e6-9879-4122c63ec32a.png)
And it seemed to work. Give it a try and give some feedback.

**Comment by Capusjon** [comment]
I tried that one too, but for some reason it's not working every pokestop. Mabey I need to give it some more time to test.
Still I want it to look more for LurePokemons then once every pokestop.

**Comment by morrrido** [comment]
@Capusjon it will never look in all the pokestops unless all the pokestops are lured!
For example in my case I made a GPX path to walk around the same 12 pokestops, in which 5 of them are usually lured. It will only look for lured pokemons on those 5. 

You can't have lured pokemons on a pokestop that isn't lured. Therefore it's quite pointless to look for them.

Unless you are camping on the same pokestop (without moving) there should not be that much of a difference between searching for lured pokemons once for each pokestop and looking for lured pokemons many times for each pokestop.

**Comment by Capusjon** [comment]
@morrrido 
Your edit works consistently now then? Meaning its looking for lure pokemon at every lured stop?

I did see in the log that it looked 2 times for lured pokemon but didnt catch any. I'm still having a hard time to belief there were no Lure pokemons there.. But mabey I just need to run longer..

**Comment by morrrido** [comment]
@Capusjon In my case it worked..
I used fastpokemap.com and visualiser, and it caught 4 lured pokemons in 20 minutes (from 3 different lured pokestops). 
Previously it would catch 0!
I don't know if it's working 100%, but it sure is working better then before.

**Comment by Capusjon** [comment]
@morrrido 
If there are 4 pokestops in close proximity the bot doesn't always walk to al those stops. So if I look for Lurepokemon on a nonlure stop wich is located next to a lured stop it could be beneficial or am I wrong?

To let it search on every stop I assume I need to delete "if (pokeStop.LureInfo != null)" and only let it run " { await CatchLurePokemonsTask.Execute(session, pokeStop, cancellationToken); }" 

What do you think? I recognize your logic but I would like to test if it get's more Lurepokemons.

PS. Funny to see us 2 noobs at Git try to figure this shit out :-))

**Comment by morrrido** [comment]
@Capusjon yes, that would search for lured pokemons on every pokestop, independently if that pokestop is lured or not **BUT** if you notice the code 
`await CatchLurePokemonsTask.Execute(session, pokeStop, cancellationToken)`
you are passing in a parameter which pokeStop it will search lured pokemons from.

So I think that this doesn't work like normal\incense pokemons in which case it just looks at pokemons within a specific distance. 
CatchLurePokemonsTask seems to me that if you are in the middle of 4 (**A-B-C-D**) very close pokestops in which 1 (**D**) of them is lured would return:
**Non-lured pokestop A:** 0 pokemons
**Non-lured pokestop B:** 0 pokemons
**Non-lured pokestop C:** 0 pokemons
**lured pokestop D:** number of pokemons lured by itself

I'm just assuming thats how it works.
Like I said, you can always try to do what you said, if I am right it would search for pokemons and find none, but I don't see any harm in trying it.

**Comment by Capusjon** [comment]
Im going to run tonight with only your fix implemented. I did put in a 
" await CatchLurePokemonsTask.Execute(session, pokeStop, cancellationToken)" 
in the  	FarmPokestopsTask.cs above the CatchNormal and CatchInsensePokemon Line but I think it resulted in an error saying the lure event was over or something like that. I forgot to screenshot AND deleted logs ;( (did give me a lurepokemon on startup though..

I'm way to inexperienced to look at the code and see the problem. I believe it has something to do with how CatchLurePokemon.cs differs from CatchNormal or Incense.

**Comment by morrrido** [comment]
@Capusjon meanwhile i got another account banned.
Tell me how it works for you after you tried it.

**Comment by Brazuca87** [comment]
So I'm having a similar issue... Or maybe a different one altogether, but sounds to be the same...

Whenever I seem to encounter a lured pokemon (or bot tries to catch it) using GPX, I get error:
```
[19:51:26] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[19:51:27] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57
```
Now It seems like it may still be catching the Pokemons (as it transfer a pokemon I didnt seem to have), but it crashes and relogs every time this happens. Seem like a lot less Pokemons are popping now with this though... 0.9.4 is not very "gpx friendly", it seems...

**Comment by Capusjon** [comment]
@morrrido 
Test did work out with only your fix. I'm getting more lurepokemon and its consistently searching for them. So thanks a Lot ;-)

I would still like the bot to look more for lure pokemons but I can't seem to figure out where to put the command line, so this will have to do.

**Comment by Capusjon** [comment]
@tiggerite did an edit of some files and the usenearbypokestops.cs. He added the same line we did and some other stuff.

See for yourself at pull request #444

**Comment by morrrido** [comment]
@Capusjon yes, I reached out to him on one of his previous pull request :)

**Comment by Capusjon** [comment]
ah Nice, he did some more stuff today so I'm going to run it, view the logs and if it works out I assume we can close this issue..

**Comment by ranidentity** [comment]
Exp has been very low due to this problem T_T

**Comment by tiggerite** [comment]
Yeah, it's been fixed (I see lots of lured pokemon captured), just need to await the next release now, or compile it yourself from source.

**Comment by ranidentity** [comment]
Sorry, but mine still not looking for lured pokemon.

Using 0.9.5 now

**Comment by mo0ojava** [comment]
Agree. The new 0.9.6 doesn't catch lured Pokes either. Looking into it...

**Comment by mo0ojava** [comment]
Testing now. Let's see what the result is by tomorrow.

**Comment by morrrido** [comment]
@ranidentity @mo0ojava
I am still using the version that I patched myself. But I have checked 0.9.6 code and it appears ok. Are you sure your bot is passing by lured pokestops?
Check your logs to see if it searches for lured pokémons.

**Comment by ranidentity** [comment]
indeed, it didnt. 0 line for search for lured pokemon. i will try it again now, yesterday tested for 4 hours at my country hottest spot.

**Comment by mo0ojava** [comment]
Same thing. Tried the above patch during the night and now it's catching lured Pokemons again. Looks like we're back on track after/if the above Pull request is accepted. It's a bit convoluted why the original code isn't working. Someone mentioned cooldowns interfering. IF that's the case there's a possibility that this patch introduces the same effect vs the other catch-actions. That could theoretically lead to us missing a normal/incense Pokemon due to cooldown from CatchLurePoke. Couldn't find any evidence on that in the log though.

**Comment by ranidentity** [comment]
?? @mo0ojava you mean yours is working? mine still not. getting 4k exp/h

**Comment by NoxxDev** [comment]
Fix in PR https://github.com/NoxxDev/NecroBot/pull/592
Fix in next release
