### ISSUE TITLE
Google walk issue? System.invalidOperationException

### ISSUE THREAD

**Issue by alexbaas** [NoxxDev/NecroBot#326]
I was just opening the new 0.9.3 version and I got this error:
http://image.prntscr.com/image/3552d76b293246d797d2f2dd849e93d0.png
Anyone knows what this is and how to fix it?

### How to fix?
Thanks to @zurkoxxx 
seems to me that google API key is causing trouble.
I had to remove it completely from my config(leave "") to make the bot work again(even though i had the google walking set to false).

**Comment by ausscheider** [comment]
I have the Same

Unpack Release.zip
Start necrobot
When the ask Comes: do you want Start the setup
No
Then will install necrobot 
After this go to config folder and configure auth and config
Then Start necrobot

Sorry Forums english but i'm from gemany ;)

**Comment by YouGamePlayHD** [comment]
This is an error I've only been experiencing during AutoUpdate-mode. I don't know what is wrong with the code but something certainly is.
@ausscheider I'm german, too xD

**Comment by 357896** [comment]
I have the same problem, feels like there is a problem with .net or vc redist maybe?
saw similar errors when either is not installed.
reinstalled both, no difference.

**Comment by ausscheider** [comment]
;) dann bin ich ja nicht ganz alleine @YouGamePlayHD

**Comment by ausscheider** [comment]
@357896 Try the Second post

**Comment by zurkoxxx** [comment]
seems to me that google API key is causing trouble.
I had to remove it completely from my config to make the bot work again(even though i had the google walking set to false).

**Comment by alexbaas** [comment]
@zurkoxxx That helped me out, but now I don't have the Google walking :/

**Comment by 357896** [comment]
you can set google walking true but leave the api key null
