### ISSUE TITLE
Can't build !! missing file . 

### ISSUE THREAD

**Issue by muji2020** [NoxxDev/NecroBot#33]
I can't build this project , Missing file . 
"PermaBannedException.cs" and "SoftBanException.cs"

**Comment by butilities** [comment]
The latest commit [here](https://github.com/NoxxDev/NecroBot-Rocket-API/commit/46f6e268065e64a03c07acbdc5096d4fab3bf42c) fix this

**Comment by JoNMii** [comment]
thanks, i reverted some commits until this was fixed.

**Comment by NoxxDev** [comment]
Fixed

**Comment by muji2020** [comment]
thanks !
