### ISSUE TITLE
Issue in 0.9.3 version, function "ToNotCatchFilter"

### ISSUE THREAD

**Issue by ReganHo** [NoxxDev/NecroBot#331]
"PokemonSettings": {
    "CatchPokemon": true,
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": false,
    "KeepMinDuplicatePokemon": 4,
    **"UsePokemonToNotCatchFilter": false,**
    "UsePokemonSniperFilterOnly": true,
    "DumpPokemonStats": false

  "PokemonsToIgnore": [
    "magikarp",
    "caterpie",
    "weedle"
  ],

my config.json is here, but it can't catch like Pidgey, Rattata, ...etc, the setting looks connect with "SniperFilter", because when SniperFilter setting "false", the Pokemon like Pidgey, Rattata, ...etc it can be catch again, why ???

**Comment by YouGamePlayHD** [comment]
Hmmm. So you deactivate NotToCatch, but it still displays:
Skip Weedle....
And when you deactivate the SniperFilter everything works?!

Actually, the sniping should have nothing to do with the normal catching mode. After a certain amount of time and when the MinPokeBallsToSnipe is reached, the sniper should start sniping the pokemon that are on the sniping list all around the world...
 Styling with Markdown is supported
Comment

**Comment by ReganHo** [comment]
Yes!! i deactivate "NotToCatch" and it still displays Skip Weedle... then i deactivate the SniperFilter everything and it will work!!
i have try many times!!
