### ISSUE TITLE
xp per hour

### ISSUE THREAD

**Issue by HOUDX1** [NoxxDev/NecroBot#333]
what is the normally xp per hour i have to get? cuz i get 17k
i just want a confing working safe with good xp

**Comment by RavenHome1** [comment]
there is no safe xp per hour, xp per hour depends on the number of pokemon and pokestops in your area also if you are sniping or not.

**Comment by YouGamePlayHD** [comment]
Sniping can be very dangerous as it flags your account for PermBan

**Comment by Koshyy** [comment]
the guide is 1-2k pokestops and 1k pokemon per 24 hour period.

**Comment by HOUDX1** [comment]
i found a config i dunno from where i downloaded it give 85k per hour without sniping or lucky eggs
some one wanna take a look on it?
