### ISSUE TITLE
(Suggest) killswitch options

### ISSUE THREAD

**Issue by petpetpetvm** [NoxxDev/NecroBot#334]
I think it's would be better if you add some more options to the bot 
"RestartKillswtichperhour" (even that it's stopped already)
"Restartforcatchflee" (should be false all the time, the killswitch will restart for everything else except catch flee)
And when the bot stopped already, it should show : do you want to continue the bot (y/n)

It's my ideas
Thanks

**Comment by YouGamePlayHD** [comment]
There is a skript for restarting the bot every hour:
http://pastebin.com/xebsvvGk

Just change the position of the bot and you're good :)

**Comment by petpetpetvm** [comment]
@YouGamePlayHD i know there is, but what if you get catch flee softban and 1hr is not enough for stopping the bot, this way will make the account easier to get ban

**Comment by YouGamePlayHD** [comment]
CatchFlee? Just put it in the config to 15 or so, then the bot will shutdown in 5 minutes and will be restarted. Most CatchFlees are not longer than 1 hour.

**Comment by YouGamePlayHD** [comment]
Also, you won't get CatchFlee-Banned when you use good config settings.

**Comment by petpetpetvm** [comment]
I'm using a really fast config, that's why this bat won't work for me :)
Thanks thou.

**Comment by ShadXo** [comment]
@YouGamePlayHD the random in the script can make the script run for more than the 16 hours and make the sleep period more than a day.

**Comment by YouGamePlayHD** [comment]
I know

**Comment by NoxxDev** [comment]
KillSwitch has been removed
