### ISSUE TITLE
[Issue] Protocol API still broken. Niantic can still identify 3rd party app users.

### ISSUE THREAD

**Issue by WinterMoxRZ** [NoxxDev/NecroBot#336]
First of all I like to thank everybody who contributes to free opensource projects to make them better and not to break them. 

Including updated POGOProtos is a good thing.

Sad thing is that protocol API is still broken. There hasn't been a real actual fix.

Changing code from this:

//static for now
sig.Unk22 = ByteString.CopyFrom(new byte[16] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F });

To:

sig.SessionHash = ByteString.CopyFrom(new byte[16] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F });

Doesn't magically change the fact that SESSION_ID is still same static 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F. And removing "//static for now" comment fix the problem even less.

Also following code is still the same in those C# files where it was before previous issue was closed.

var downloadSettingsMessage = new DownloadSettingsMessage
{
   Hash = "05daf51635c82611d1aac95c0b051d3ec088a930"
};

If someone wants to look the pictures I posted earlier here's a link to closed issue.

"#293 [Issue] Fix protocol API. Or Niantic keeps banning users of 3rd party apps. Current public Rocket API is completely broken."

All the three example problems I presented earlier still exist. And as I said before there is more.

Good luck to everyone.

**Comment by RiberoD07** [comment]
so the issues are being closed without an actual fix being made?

**Comment by jdbaker82** [comment]
Sounds to me like we will never having a working bot in PoGO as the uk is heavily encrypted now. I don't understand why people keep making bots with all these new features that don't matter at all ... I got account banned by logging into bot and catching only 1 pokemon :/

**Comment by NoxxDev** [comment]
@WinterMoxRZ 
If you can check these commits, I believe it is now working properly
https://github.com/NoxxDev/NecroBot-Rocket-API/commit/6bc1672760921b5aed812b2bd799936aa23726f6
https://github.com/NoxxDev/NecroBot-Rocket-API/commit/6180e62a713092c45c4fa31bc6982329df9ec751

**Comment by ValorRed** [comment]
When can we have a release for this fix? Looking forward to it.

**Comment by bulubebek** [comment]
I hope its work properly. cant wait for new release. yay!

**Comment by bulubebek** [comment]
any confimation about API issue status? @WinterMoxRZ

**Comment by WinterMoxRZ** [comment]
@NoxxDev 

No comment about this right now. Haven't had enough time to dig in.
NoxxDev/NecroBot-Rocket-API@6bc1672

Next doesn't fix anything, if something it breaks things even more.
NoxxDev/NecroBot-Rocket-API@6180e62

Here is fast description of these two things.
RandomDevice.NextBytes(_sessionHash);
sig.SessionHash = ByteString.CopyFrom(_sessionHash);

This code generates new ID on every request. This isn't requestid it's sessionid so it should stay the same as long as session exist. In other words new sessionid should be generated when NecroBot logs in and be sent to /dev/null when NecroBot exits or logs in again because of connection problems.

I'm going to copy/paste none working pseudo code here which somewhat illustrates how sessionid generation could work.

        public void InitializePropertyDefaultValues(object obj)
        {
            .....

            var tmpRNG = new RNGCryptoServiceProvider();
            tmpRNG.GetBytes(AuthConfig.SessionHash);


        private Unknown6 GenerateSignature(IEnumerable<IMessage> requests)
        {
            .....

            sig.SessionHash = ByteString.CopyFrom(settings.SessionHash);

Now about Hash = "54b359c97e46900f87211ef6e6dd0b7f2a3ea1f5".

It's still static and sent in incorrect places and as @thekjohn brought up it was only changed in one place.

Things don't stop there, "05daf51635c82611d1aac95c0b051d3ec088a930" (the old static hash which wasn't changed in commit) is sent in authentication request. If you look traffic dump from official client there is no this kind of hash in authentication request.

NecroBot sends those hard coded hash's in incorrect requests.

If you look traffic dump from official client you will see that official client doesn't send this kind of hash until server returns this kind of hash in response. After that client starts to use hash sent by server.

So PLEASE who ever is coding protocol API "fixes" PLEASE look what happens in traffic between official client and server.

Then last thing about protocol API, there is more problems then I have presented here. Please please look it yourself.

Thanks fly to all developers and people who know how to code or reverse engineer.

**Comment by thekjohn** [comment]
I agree with you. The protocol most bots/APIs using is insanely bad, if you compare the requests made by 3rd party tools with the requests made by the game itself. Getting inventory data is just one thing (as you may know, the game queries the inventory only ONCE, and each subsequent request contains the last inventory result's timestamp so it will get only the diff since then). And this is just one example...

**Comment by ComputerApp1234** [comment]
If you are able to find and correct the problems, why you did not help the developer team?

**Comment by thekjohn** [comment]
Because there is no way they don't know their request pattern is bad. I am  sure they know that GetInventory requests get the lastTimestampMs pramater, which means Niantic is sending only diffs... This is not just a hint, this is an actual problem and the solution both...

**Comment by thekjohn** [comment]
I wonder if anybody has access to lots of dumped communication (with envelopes,  signatures!) between the app and the server - so we could improve LocationFix and Sensor data, also add GpsInfo, etc to Signature.
