### ISSUE TITLE
Favoritizing pokemons with too large pokemon.Id fails - unfixable unless Rocket API / POGO Protos are modified too

### ISSUE THREAD

**Issue by Kermel** [NoxxDev/NecroBot#338]
Favoritizing pokemon can rarely fail:
Class: FavoritePokemonTask
Line 32 (the one with "await session.Client.Inventory.SetFavoritePokemon(Convert.ToUInt32(pokemon.Id), true);" )

Can rarely fail if pokemon.Id is a large number (can happen from evolved pokemon as in my case).
It cannot be fixed in the bot itself as the value is used for message composing and leads to Rocket API and POGO Protos.
Does anyone have contact with Rocket API / POGO Protos devs and can ask them to fix the field data type? 
Then we can fix it also in the bot directly

**Comment by NoxxDev** [comment]
Fixed

https://github.com/NoxxDev/NecroBot/commit/fa02f2ebf30b521edab4f9523e961a6d6b9a68d8
https://github.com/NoxxDev/NecroBot/commit/5733d7bd539dfafa32725baeb57ec252f61fa111
