### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ridalarry** [NoxxDev/NecroBot#34]
1. _Kill switch option to close the bot when you reach a specific level, when you reach certain amount of poke stops or catch amount of pokemons, when you get certain amount of flees following each other, when you reach certain amount of times trying to unsoftban following each other, or when the bot reach x minutes running._
2. _Fix Telegram API by using same method as version 0.8.5._
3. _Speed randomizer to make it more human like walking._
4. Add all the working pull requests that was closed in the old version https://github.com/NECROBOTIO/NecroBot/pulls?page=1&q=is%3Apr+is%3Aclosed which were closed 3 days ago.
5. Gym battling if possible.
6. Use eggs in the gyms if possible.
7. GUI like NecrobotVisualizer and Necrobot.GUI
8. Ability to snipe with all PoGoLocationFeeder features.
9. Make the bot walk on the street instead of walking above buildings.
10. Organize the config to be easier to use.

**Comment by NoxxDev** [comment]
Item 2 and 3 made, gradually we're implementing new features 
Note, item 3 still needs improvements

**Comment by ridalarry** [comment]
Thank you so much and for "9" here is a pull request from the old version https://github.com/NECROBOTIO/NecroBot/pull/3766
