### ISSUE TITLE
(Request) Pokemon Go Monitor Track Exact Catches/Loots To The Second Master KillSwitch

### ISSUE THREAD

**Issue by hardknoxni69a** [NoxxDev/NecroBot#340]
Please Set The Bot To Have The Option For 24 Hour Counters Similar To TuringBot Fork
So Instead Of The Confusing 1 Hour Limits And Such Have It So A Player Can Load A Brand New Account And Have It Set So Once The 1000 Pokemon Limit Are Caught It Will Skip The Pokemon And Work Toward The 2000 Pokestop Limit Or Vice Versa To Maximize XP In Your 24 Hour Period (Once These Limits Are Met You Get The Soft Bans Loot Ban Or Catch Ban). Recommended Setting Would Be 975 Mon And 1975 Stops (Better Safe Than Sorry) Once These 2 Goals Are Met Bot Can Sign Out And Sign Back In Once The 24 Hour Limit Has Passed Or Even Better Just Have Bot Still Walk And Gain Kilometers On Your Eggs In Your Area Just Not Collecting Stops And Monsters. Now Say You Caught 50 Pokemon In The First Hour Or So So You Need It Set So You Can Only Catch 50 Pokemon Up To The Second So That The Ban Does Not Go Into Effect Because The Clock Is Revolving Constantly So At No Point Can You Have More Then The 1000 Mons Or The 2000 Stops Within The 24Hour Window Or You Will Immediately Get Flagged And Will Get Flee Or Be Unable To Loot Once This Happens Your Account Has Been Officially Flagged And So Many Strikes And You Are Out For The PermaBan. This Update Will Obviously Require A PlugIn To Read The Logs That Are Already Being Made So Shouldnt Be To Hard (For You Master Coders That Is Of Course). I've Run Necro For Over 24Hours And Never Got A Soft Ban Depending On Location But Every Time Your In A Good Location And You Hit That Limit Bam No Stops Until Your Counter Is Expired Or No Catches Until Your Allowed More But If We Set The Limits The Bot Can Run Till Right Before The Limit With No Bans. This Is A Very Good Idea Which I Believe Will Severly Limit The Amount Of Bans Being Given Out Please Master Coders Implement This True KillSwitch

**Comment by Trolha69** [comment]
My Brain Hurts. What Is Punctuation? And Why Do You Capitalize Every Single Word? That's Not How Typing Works.

**Comment by hardknoxni69a** [comment]
lol sorry bad habbit

**Comment by Koshyy** [comment]
I will summarise for those whose eyes hurt. So this isn't missed.

Add a setting for being able to set maximum pokemon/stops in a 24 hour period... not this one hour deal that it currently is. It also appears more legit because if you finish catching them all in 12 hours you log out for another 12... You could even add a randomizer... you relog in 25-27 hours... you catch 950 instead of 999 or 975... etc..

To me this seems like a no brainer...

**Comment by hardknoxni69a** [comment]
@NoxxDev Could we implement this or atleast make the killswitch maximize xp as it shuts down once one killswitch is activated not both so if we catch all pokemon it will stop catching and finish just the pokestops or vice versa thank you so much

**Comment by NoxxDev** [comment]
KillSwitch has been removed, check limits v0.9.5 or upper
