### ISSUE TITLE
bot more then 1 on same ip? proxy?

### ISSUE THREAD

**Issue by zinba** [NoxxDev/NecroBot#342]
how can i run more then 1 bot on my ip?

**Comment by samuraitruong** [comment]
use proxy
{code}

"ProxyConfig": {
    "UseProxy": true,
    "UseProxyHost": "175.182.xxx.xxx",
    "UseProxyPort": "8998",
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },

{code}
