### ISSUE TITLE
[Suggestion] More delays options

### ISSUE THREAD

**Issue by DavidSelem** [NoxxDev/NecroBot#343]
The bot lacks of delay options, right now I'm seeing how a pokemon is catched and transfered in the same second, the same when evolving.

**Comment by boylondon** [comment]
agree, i think that's good idea

**Comment by NoxxDev** [comment]
Bot using `DelayBetweenPlayerActions` and randomize value

`DelayingUtils.Delay(session.LogicSettings.DelayBetweenPlayerActions, 0);`

https://github.com/NoxxDev/NecroBot/blob/master/PoGo.NecroBot.Logic/Utils/DelayingUtils.cs#L15-L30

**Comment by DavidSelem** [comment]
I set 10s of delay with player actions, but the bot ignore that time
http://i.imgur.com/v9PqSVj.png

**Comment by NoxxDev** [comment]
delay is after the transfer
and random, based on setting
