### ISSUE TITLE
necrobot 0.9.4 necrobot instantly crashes

### ISSUE THREAD

**Issue by maboigorilla** [NoxxDev/NecroBot#345]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by spdragon** [comment]
i believe the problem is on the kill switch settings, but i have no idea how to fix

**Comment by knumchoke** [comment]
v094 dose not import all 093 killswitchsettings.
in v093
```
"SoftBanSettings": {
    "FastSoftBanBypass": false,
    "UseKillSwitchCatch": true,
    "CatchErrorPerHours": 40,
    "CatchEscapePerHours": 40,
    "CatchFleePerHours": 40,
    "CatchMissedPerHours": 40,
    "CatchSuccessPerHours": 40,
    "UseKillSwitchPokestops": true,
    "AmountPokestops": 80
  },
```

```
in094
"SoftBanSettings": {
    "FastSoftBanBypass": false
  },
"KillSwitchSettings": null,
```

all error appear after any action follow the KillSwitchSettings. try patch it up but not good.

**Comment by ausscheider** [comment]
--->> https://github.com/NoxxDev/NecroBot/issues/358
