### ISSUE TITLE
0.9.4 switch to another language??

### ISSUE THREAD

**Issue by Henry-Chung** [NoxxDev/NecroBot#347]
After updating to the new version, I can't swtich to another language.
like following pic.
![1](https://cloud.githubusercontent.com/assets/12480356/17835858/9486a9d0-67b1-11e6-926b-772e15a57d39.png)

**Comment by NoxxDev** [comment]
Delete folder bot and download
this error is conflict translation, delete bot and files and new download

**Comment by SDpower** [comment]
https://github.com/NoxxDev/NecroBot/commit/49feafd35e20e5549555b3929a01827d9cb905f2
commit fails!
json string fail! on end of line is two ""

**Comment by NoxxDev** [comment]
Errors after update v0.9.4 is caused for config.json and translations
Solution 
Delete you config.json and folder translation

config.json is recreate for bot
translation folder, request download release.zip and extract translation folder in your directory (NecroBot)\Config

https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.4

**Comment by SDpower** [comment]
https://github.com/NoxxDev/NecroBot/pull/348

**Comment by SDpower** [comment]
NO i am fix it.

**Comment by SDpower** [comment]
on/directions/get-api-key""   <~~~ is two ""

**Comment by NoxxDev** [comment]
Sorry Fixed

https://github.com/NoxxDev/NecroBot/releases/download/v0.9.4/Translations.zip

**Comment by Henry-Chung** [comment]
Thank you for your help :)
SDpower 謝啦
