### ISSUE TITLE
[Suggestion]Print the telegram exception on console

### ISSUE THREAD

**Issue by SnowyCoder** [NoxxDev/NecroBot#349]
All the times that a new update comes out something goes wrong with telegram and, due to the limited log information I always need to check all the config options and key....
If we add more log maybe the users will know where to search the error and they'll be able to fix it faster!
I'm not a c# developer but i think that is something like this:
In: NecroBot/blob/master/PoGo.NecroBot.Logic/Service/TelegramService.cs
Line: 45->48
`catch (Exception ex)
            {
                _session.EventDispatcher.Send(new ErrorEvent { Message = "Unkown Telegram Error occured. " + ex.stacktrace});
            }`

**Comment by developnoop** [comment]
I would like also to have a better error output, as i don't get telegram working for me.
