### ISSUE TITLE
Error when running 0.8.8

### ISSUE THREAD

**Issue by AmazingGamerBoy** [NoxxDev/NecroBot#35]
I have tried many of the bot versions. Installed .net 4.6.2 and visual c. Still not working. Here is the error:

![error](https://cloud.githubusercontent.com/assets/15712937/17659890/e881b996-6318-11e6-902b-a186ebb0c168.png)

**Comment by AmazingGamerBoy** [comment]
Not showing ip as well for some reason

**Comment by albysprx** [comment]
same here and I have latest .net framework

**Comment by AmazingGamerBoy** [comment]
btw it is windows 8.1

**Comment by albysprx** [comment]
Mine it's windows 7

**Comment by NoxxDev** [comment]
Probably Google Auth down

**Comment by NoxxDev** [comment]
Download [v0.9.0] (https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.0) and verify

**Comment by AmazingGamerBoy** [comment]
I will soon
