### ISSUE TITLE
Necrobot 0.9.4 Crash

### ISSUE THREAD

**Issue by 4ntani** [NoxxDev/NecroBot#351]
Hi everybody, 

![image](https://cloud.githubusercontent.com/assets/21153408/17836180/22c0aaf8-6789-11e6-8f17-f43c831b5c02.png)

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	NecroBot.exe
  Problem Signature 02:	0.9.4.0
  Problem Signature 03:	57b95ba6
  Problem Signature 04:	Pokemon.Go.Rocket.API
  Problem Signature 05:	1.0.0.0
  Problem Signature 06:	57b95b2e
  Problem Signature 07:	ca
  Problem Signature 08:	0
  Problem Signature 09:	System.TypeLoadException
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1040
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

this is my issue... Can anyone help me?

Thank's a lot

**Comment by inclouis** [comment]
same issue.. 

And I downloaded new download for v0.9.4, i did not auto update from v0.9.3.

Even with new download also having same crash. 

please help.

**Comment by clash-votter** [comment]
This error is confirmed to exist. See also
#346 9.4 Forced stop automatic??

**Comment by kosior98** [comment]
delete NecroBot.exe.config file 
for me now it works

**Comment by Koitah** [comment]
Someone ?

[10:54:45] (INFO) Walking Speed: Has been changed, 3.59 Km/h to 3.58 Km/h
[10:54:47] (INFO) Walking Speed: Has been changed, 3.58 Km/h to 3.57 Km/h
[10:54:49] (BERRY) Used Razz Berry | 15 remaining
[10:54:50] (PKMN) (CatchEscape) | (Normal) Nidorina Lvl: 21 CP: (761/842) IV: 49.00% | Chance: 16.34% | 56.92m dist | with a GreatBall (58 left). | lat: 41.147890 long: -8.674542
[10:54:57] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[10:54:58] (ERROR) Error: System.NullReferenceException: A referência de objecto não foi definida como uma instância de um objecto.
   em PoGo.NecroBot.Logic.Model.Settings.LogicSettings.get_UseKillSwitchCatch() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Model\Settings\LogicSettings.cs:line 109
   em PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 280
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 68
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass4_0.<<Execute>b__1>d.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 106
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__10.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:line 101
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 90
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 101
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 68
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() em E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 57

**Comment by 4ntani** [comment]
Me too, same problem.

**Comment by prostoman** [comment]
Me too, same problem.
walk, catch, error, relog, default location,

**Comment by amirrahzani** [comment]
For fix this problem just remove Necrobot.exe.config in subfolder ;-) enjoy

**Comment by 4ntani** [comment]
Removing Necrobot.exe.config it's not the solution... :(

**Comment by ausscheider** [comment]
look here ---> https://github.com/NoxxDev/NecroBot/issues/358

**Comment by iwean** [comment]
After catch 1 pokemon bot 9.4 crash..... :fallen_leaf:

**Comment by amirrahzani** [comment]
It's work i removed Necrobot.exe.config

[IMG]http://i64.tinypic.com/35a6f48.jpg[/IMG]

**Comment by ltf195** [comment]
Have same problem too, delete Necrobot.exe.config and it work! My question is, my bot running without Necrobot.exe.config, so, this file is not important? @NoxxDev

**Comment by clash-votter** [comment]
Good question. @ltf195 +1

**Comment by NoxxDev** [comment]
v0.9.7 release
