### ISSUE TITLE
how to make bot remain still in a spot?

### ISSUE THREAD

**Issue by mokkodog** [NoxxDev/NecroBot#352]
hi guys, how to make the bot stay in a spot (not moving) near pokestop with lure?

**Comment by LeHartx** [comment]
+1, would like to know as well

**Comment by vfuyong** [comment]
Set max distance to be 50.

**Comment by sniper85500** [comment]
setting travel distance down - maybe 50 or less (but not zero)

**Comment by LeHartx** [comment]
when i set it to 50 it doesnt catch anything at all.

**Comment by mokkodog** [comment]
error for me
