### ISSUE TITLE
Unkown Telegram Error occured. 

### ISSUE THREAD

**Issue by mitchelp** [NoxxDev/NecroBot#354]
I got trouble with Telegram, I created a new config file. And recopied the telegram API key.
Even created a new bot, but everytime when I start the bot I get the following:
```
Initializing NecroBot logger at time 8/21/2016 11:16:08 AM...
[11:16:10] Unkown Telegram Error occured. 
[11:16:10] Perfect! You already have the newest Version 0.9.4
[11:16:10] Logging in using Ptc
```
So I think there is something wrong with the last release 0.9.4 or troubles at Telegram?
Please check :)

**Comment by Dexter145** [comment]
Have the same error on 0.9.4.

**Comment by NoxxDev** [comment]
https://github.com/NoxxDev/NecroBot/commit/5a37606e6bb9a747afa7bf414ddea6b67781e1dc
