### ISSUE TITLE
Config location after update

### ISSUE THREAD

**Issue by d3l3t3r** [NoxxDev/NecroBot#356]
### Expected Behavior
To import my old config.json

### Actual Behavior
Created a new one with default location (not the same location where I farm.

### Your config.json
Dosen't matter

### Steps to Reproduce
-

### Other Information
Version: 9.3 to 9.4
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): I just closed my 0.9.3 bot, because I saw the update to 0.9.4. So I expected after update to import my config.json but instead the 0.9.4 came with the default one. Now I just teleported from LA to NYC. Will this ban me because of this bug???

**Comment by petpetpetvm** [comment]
Check your location next time, ALWAYS, at least after updating

**Comment by wilsondgonzales** [comment]
@d3l3t3r it's kinda not a bug only because since the time of necrobot, there were cases of autoupdates failing and people have gotten used to it heh. It might cause a ban or it might not :)
