### ISSUE TITLE
For all who have Problems since v.0.9.0 (v.0.9.1 - v.0.9.2 - v.0.9.3 v.0.9.4)

### ISSUE THREAD

**Issue by ausscheider** [NoxxDev/NecroBot#358]
Hello every one.

You have problems since v.0.9.0 after install with crash?
Make follow things for perfect works:

1. Download the latest release
2. unpack release.zip
3. start NecroBot.exe
4. By the Question: Would you like begin the setup? -->> No
5. Go to the Folder "Config"
6. open the file auth with notepad and make your personal settings
7. save the file
8. open the file config with notepad and make your personal settings
9. save the file
10. start NecroBot.exe
11. Have Fun
12. Remember 1 IP = 1 Bot

**Comment by ausscheider** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20948162/17836708/de62afd8-679b-11e6-8da7-f3882fa6feee.png)

It works perfect

**Comment by ShadXo** [comment]
@ausscheider How you got the Bisualizer to work? Never worked for me in config websocket is enabled, but keep saying: Connecting to the bot....
Can you help?

**Comment by wilsondgonzales** [comment]
@ShadXo confirm your settings and port # to match

"WebsocketsSettings": {
    "UseWebsocket": true,
    "WebSocketPort": 14251
  },

**Comment by ausscheider** [comment]
@ShadXo 

in Config from necrobot i have follow:

  },
  "WebsocketsSettings": {
    "UseWebsocket": true,
    "WebSocketPort": 14253

and by the visualizer 

Bot Websocket
wss://localhost:14253

**Comment by ShadXo** [comment]
@ausscheider @wilsondgonzales thanks for the help, was running is from a network drive saw someone on github having the same issue.

**Comment by likeness123** [comment]
@ausscheider where did you get the pokemonbot visualizers?

**Comment by LeHartx** [comment]
How to find out your port number?

**Comment by ausscheider** [comment]
@likeness123 
https://github.com/nicoschmitt/necrobotvisualizer

**Comment by vachzar** [comment]
did telegram API error in v.0.9.4 ? I got "(ERROR) Unkown Telegram Error occured."
