### ISSUE TITLE
When UseGoogleWalk is true, bot just walks.

### ISSUE THREAD

**Issue by clash-votter** [NoxxDev/NecroBot#359]
### Expected Behavior
Expected walking behaviour,
as well as spin pokestops, snipe, etc.

### Actual Behavior
Expected walking behaviour only.
No spin pokestop, snipe, etc.

Observed using [necrobotvisualizer](https://github.com/nicoschmitt/necrobotvisualizer).

### Steps to Reproduce
Set UseGoogleWalk to true.

### Other Information
If UseGoogleWalk to false, bot works as expected.

Version: 0.9.4
Windows Version: Windows 8 64-bit

**Comment by ausscheider** [comment]
i have UseGoogleWalk true and works fine

**Comment by clash-votter** [comment]
How about when catchpokemon false? Meaning bot only sniping? Same behaviour?

**Comment by ausscheider** [comment]
i don't know, because why should catchpokemon false? a human player catch all pokemon ;)
when you have false, i think the bot will only farm the pokestop
snipe = permban ;)

**Comment by clash-votter** [comment]
Catchpokemon false so the bot only sniping.

Since release of v0.9.0 still working :+1:  no signs of any sort of bans. Be assured sniping is safe.

**Comment by wilsondgonzales** [comment]
@clash-votter if you want to only snipe and do pokestops, you'll want to set this parameter

`"UsePokemonSniperFilterOnly": true,`

then specify the pokemons you'd want to catch under the pokemon list 

"PokemonToSnipe": {
"Locations": [
      {
        "Latitude": 35.6328964,
        "Longitude": 139.8803943
      }
],
"Pokemon": [
      "dratini",
      "dragonair",
      "dragonite",
]
},

**Comment by clash-votter** [comment]
My sniping config is just fine. Trust me.
![image](https://cloud.githubusercontent.com/assets/21138034/17836937/dc44ccc6-67e7-11e6-990c-2e369b67329a.png)

I'll try set UseGoogleWalk to true again and upload screenshots.

**Comment by clash-votter** [comment]
Here's a screenshot of the bot just walking. You can see 21.53 the bot just keeps walking, and is walking past the pokestops. It is walking in the expected fashion though.

I tried changing the UseGoogleWalk to false on the fly while the bot is running, at 21.58, but the bot continues to just walk.
![image](https://cloud.githubusercontent.com/assets/21138034/17837023/efe65f62-67ea-11e6-9a1b-9a6d7fa7e132.png)

**Comment by clash-votter** [comment]
Here's after I restart the bot, and when UseGoogleWalk is false. The bot doesn't miss any pokestops and works as expected.
![image](https://cloud.githubusercontent.com/assets/21138034/17837058/b9aee0bc-67eb-11e6-9881-80c7c0edf1fb.png)

**Comment by tutti13** [comment]
Same here. Bot targets a specific Pokestop and ignores all other Pokestops on its way to the targeted Pokestop.

**Comment by NooNW** [comment]
@clash-votter Hey man, could you share your snipe config please?

**Comment by noppGithub** [comment]
@clash-votter 
may I have your config + Pokemon Bot Visualizer ?
I want to compare EXP and result with my existing settings.

Thanks
