### ISSUE TITLE
0.8.8 transfer does not work

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#36]
It does not transfer captured ones.

**Comment by petpetpetvm** [comment]
can you share the config ?

**Comment by vfuyong** [comment]
"TranslationLanguageCode": "en",
  "CheckForUpdates": true,
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": true,
  "WebSocketPort": 14251,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "TelegramPassword": "12345",
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 20,
  "DetailedCountsBeforeRecycling": true,
  "CatchPokemon": true,
  "MaxBerriesToUsePerPokemon": 30,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 999999.0,
  "UpgradePokemonIvMinimum": 999999.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": -33.856784,
  "DefaultLongitude": 151.215296,
  "WalkingSpeedInKilometerPerHour": 10.0,
  "RandomlyPauseAtStops": true,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 8000,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 1,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "Sydney_CBD.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": true,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": true,
  "UseEggIncubators": true,
  "UseEggIncubatorMinKm": 2,
  "UseLuckyEggConstantly": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": true,
  "UseBerriesMinCp": 999999,
  "UseBerriesMinIv": 999999.0,
  "UseBerriesBelowCatchProbability": 0.4,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "GetSniperInfoFromSkiplagged": false,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 30000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{0}_{1}",
  "MaxPokeballsPerPokemon": 30,
  "MaxTravelDistanceInMeters": 300,
  "TotalAmountOfPokeballsToKeep": 200,
  "TotalAmountOfPotionsToKeep": 30,
  "TotalAmountOfRevivesToKeep": 30,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1500,
  "UseUltraBallAboveCp": 2000,
  "UseMasterBallAboveCp": 5000,
  "UseGreatBallAboveIv": 99.0,
  "UseUltraBallAboveIv": 100.0,
  "UseGreatBallBelowCatchProbability": 0.55,
  "UseUltraBallBelowCatchProbability": 0.35,
  "UseMasterBallBelowCatchProbability": 0.01,
  "EnableHumanizedThrows": true,
  "EnableMissedThrows": false,
  "ThrowMissPercentage": 0,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 95.0,
  "ForceExcellentThrowOverIv": 100.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,

**Comment by petpetpetvm** [comment]
"KeepMinCp": 1,
and 
"KeepMinOperator": "or",
so it keeps all pokemons that has cp over 1 cp

**Comment by petpetpetvm** [comment]
sorry, i never saw the notification about your config
