### ISSUE TITLE
"Pokemon Servers might be offline / unstable. Trying again..." Error Necrobot (v0.9.4)

### ISSUE THREAD

**Issue by alexbaas** [NoxxDev/NecroBot#361]
### Expected Behavior
To do actions like catching pokemons or looting pokestops without restarting the whole process and getting an error.

### Actual Behavior
Bot start-up is fine but after looting a pokestops, catching Pokemons, and all other actions, it gives this error (from log):

Error: System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij PoGo.NecroBot.Logic.Model.Settings.LogicSettings.get_UseKillSwitchPokestops() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Model\Settings\LogicSettings.cs:regel 115
   bij PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:regel 187
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:regel 68
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in E:\Projetos\CSharp\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:regel 57

Then after this error it just logs, then continues till another action and gets the error again. I tried to download the older version (0.9.3) which does work.

**Comment by ausscheider** [comment]
with v.0.9.3 works by you?

normaly this message "Pokemon Servers might be offline / unstable. Trying again..." comes when you are banned.

**Comment by alexbaas** [comment]
@ausscheider Yes it does work, it also does send info and receive info from the API so I can't be banned (it also does the action like catching a pokemon but after the action is done it gets the error)

**Comment by Jappi88** [comment]
no, its not because of a ban  cause i have the same thing, it catches pokemon, but whenever it tries to loot a pokestop it throws that error and resets the whole process...

**Comment by alexbaas** [comment]
@Jappi88 Exactly, and Im scared to get banned because of it relogging all the time. Would be very suspicious to Niantic when you log in every 30 seconds...

**Comment by alexbaas** [comment]
I think it's just an API related thing in the config of 0.9.4 causing the error, because 0.9.3 does work perfect.

**Comment by XneddyX** [comment]
remove config and generate a new one...

**Comment by ausscheider** [comment]
0.9.4 works by me perfect too

**Comment by ausscheider** [comment]
try this one : https://github.com/NoxxDev/NecroBot/issues/358

**Comment by maddisww** [comment]
Just delete "config.json", start the bot, press "N", press Enter and you are fine

**Comment by alexbaas** [comment]
Found the issue, used outdated config, in new config
    "FastSoftBanBypass": false,
    "UseKillSwitchCatch": false,
    "CatchErrorPerHours": 0,
    "CatchEscapePerHours": 0,
    "CatchFleePerHours": 0,
    "CatchMissedPerHours": 0,
    "CatchSuccessPerHours": 0,
    "UseKillSwitchPokestops": false,
    "AmountPokestops": 0

Which is not in old config, fk im stupid.
