### ISSUE TITLE
Snipe settings

### ISSUE THREAD

**Issue by Globuslele** [NoxxDev/NecroBot#363]
Hi, can u tell me how can i set my bot to snipe only
Slornax
Lapras
Dratini
Dragonair
Dragonite 

  "PokemonToSnipe": {
 "Slornax", ect dont work

**Comment by Usernameused** [comment]
Because is Snorlax

**Comment by Theo1996** [comment]
Isn't sniping a 100% giveaway and gets you banned or did noxx and the others fix it?

**Comment by Globuslele** [comment]
Ha ha ha,
Anyone can help me? when i sype Snorlax it doesnt work too

**Comment by ShadXo** [comment]
Because its more like:
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },

**Comment by Globuslele** [comment]
Thanks
