### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by vaine95** [NoxxDev/NecroBot#364]
![untitled](https://cloud.githubusercontent.com/assets/21127447/17837005/ad053580-67d9-11e6-85b9-50d500522880.png)

**Comment by albysprx** [comment]
I have the same problem, with 0.9.3 everything well, with 0.9.4 with a clean install too, I get this error every pokemon/pokestop

**Comment by repelsteeltjehd** [comment]
I have to same problem, I think it has something to do with the coding i'm searching the problem right now

**Comment by ausscheider** [comment]
try this one --> https://github.com/NoxxDev/NecroBot/issues/358

**Comment by vaine95** [comment]
same.. every pokestop this message keep repeating

**Comment by repelsteeltjehd** [comment]
Replacing a fresh nercobot for the old, does not help. I tried it.. So i guess there is a better solution going to Nercobot by neil :)

**Comment by vaine95** [comment]
https://github.com/NoxxDev/NecroBot/issues/361 try this one.. maybe will help

**Comment by albysprx** [comment]
I did a clean install so it's a new config

**Comment by LeHartx** [comment]
Tried every solution nothing works. Fresh installation etc all doesn't work too.

**Comment by imolesi** [comment]
Same here, I will revert to 0.9.3

**Comment by helpmeplease1** [comment]
this is what i do.
1) download a fresh release (0.94)
2) unzip it on destop
3) Delete Necrobot.exe.config
4) run NecroBot.exe 
5) Setup a new config like what we do in the past

Hope this help

**Comment by imolesi** [comment]
@helpmeplease1 it does not work for me :-(
I tried to revert to 0.9.3 but I can't login with ptc, always ask for google account, even with fresh install

**Comment by aaegb** [comment]
Still use 0.9.0.. it's perfect for me.. Tried 0.9.3.. permaban..

**Comment by imolesi** [comment]
EUREKA!

Reverting to english language code and disabling the web socket did the trick and now everything is working fine for me.
