### ISSUE TITLE
StartupWelcomeDelay still not working on 0.9.4

### ISSUE THREAD

**Issue by Dexter145** [NoxxDev/NecroBot#365]
### Expected Behavior
Pause after showing location

### Actual Behavior
[14:01:41] (ATTENTION) Program will continue after the key press...
But just continue without a key is pressed.

### Your config.json
"StartupWelcomeDelay": true,

### Steps to Reproduce
Created a new config.

### Other Information
Version: 0.9.4
Windows Version: Windows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by mo0ojava** [comment]
Found & fixed this. On the train atm but will make a commit later when I get home.

![positioncheckstate cs](https://cloud.githubusercontent.com/assets/20909700/17838257/16533c14-67c9-11e6-9442-16163cd798ab.png)

**Comment by NoxxDev** [comment]
Fix bc5f0a62dcd1b93e6ad6b6a17ab43faefc0103c0
