### ISSUE TITLE
For those who have issue on V0.9.4

### ISSUE THREAD

**Issue by helpmeplease1** [NoxxDev/NecroBot#369]
This is what i do. Now the bot wotk fine
1) download a fresh release (0.94)
2) unzip it on destop
3) Delete Necrobot.exe.config
4) run NecroBot.exe 
5) Setup a new config like what we do in the past

Hope this help

**Comment by imolesi** [comment]
Does not work for me

**Comment by ValorRed** [comment]
Recommend a tool: Beyond Compare. Use it to compare and merge the different configuration. You will make less mistake.

**Comment by ausscheider** [comment]
https://github.com/NoxxDev/NecroBot/issues/358

**Comment by lkhgamer** [comment]
it works well
