### ISSUE TITLE
LastPos.ini not working?

### ISSUE THREAD

**Issue by Kongen8800** [NoxxDev/NecroBot#37]
Shouldn't LastPos.ini not be the last position you were.
So when starting the bot, you will start at your last position, and not a the cordinates.
It's not working.

If this isen't the point, maybe it can be intergrated? I think it a good idea.

Necrobot 0.8.8

**Comment by wilsondgonzales** [comment]
afaik, the last pos is only used when the bot restarts when it encounters an error

**Comment by Kongen8800** [comment]
I see... but wouldn't it be better if it startede from the last position it where? Just a thought.

**Comment by ValorRed** [comment]
I vote for it start from last positiontoo. In cases I close the program, and accidentally start again. It jumped to the original coordinates. That could trigger suspicious.
