### ISSUE TITLE
Google API Key

### ISSUE THREAD

**Issue by LeshugaProh17** [NoxxDev/NecroBot#371]
## Help

"[09:36:52] (ATTENTION) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key"

What does it mean? What do I have to do to fix it?

### Other Information
Version: 0.9.4
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other: Google API Key

**Comment by MarceloDylton** [comment]
I just started a new cofiguration and its working fine. Go ahead and erase the config.json and the auth.json. start the program and set up a new configuration. It worked for me.

**Comment by ausscheider** [comment]
https://github.com/NoxxDev/NecroBot/issues/358

**Comment by god0911** [comment]
When I add GoogleAPIKey at config.json, it crash at the beginning.
When I keep GoogleAPIKey : "", it works well.
Any idea?

**Comment by iwean** [comment]
@NoxxDev said, for 9.4 it's not necessary to use API Key.
