### ISSUE TITLE
[Suggestion/Idea]The killswitches are good but add a Counter/24h.

### ISSUE THREAD

**Issue by Theo1996** [NoxxDev/NecroBot#372]
Since killswitches are a very good addition i wanted to make suggestion.

### Expected Behavior
Add a counter for pokestops and pokemons caught for the last 24h
Keep a log where you count every pokestop(2000) and pokemon(1000).
Delete anything older than 24 hours.Present it at the top of the console or inside.
Will make it easier to keep track of how many mon and stops you soun and caught thus keeping ou safe from softbans.
### Your config.json
```
example
UsePokestopCounter24=true;
UsePokemonCounter24=true;
```

### Steps to Reproduce
```
make a table for pokestop mons and their time stamp
read and count every timestamp for the last 24 hours
print
```

### Other Information
Version:0.9.4
Windows Version: win7 ultimate 64 bit sp 1 debotnet'd
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):catch,other

**Comment by ShadXo** [comment]
Look at #337

**Comment by Theo1996** [comment]
thx didnt see that,waiting it to be merged.
