### ISSUE TITLE
New version's GoogleWalk is definitely need more work

### ISSUE THREAD

**Issue by ValorRed** [NoxxDev/NecroBot#373]
1. It shall not need to walk to the exact point of Pokestop to spin, the Pokestop range shall be big enough for you to spin on the path.
2. It is missing a lot of Pokestops (the fix may relate to above issue)
3. Work with GPX: If default coordinates not the start of GPX, and GoogleWalk=true, it shall use GoogleWalk to walk to the poing of GPX start. Also, use GoogleWalk between GPX points.
4. If speed < 8, use pedestrian path, instead of walking on the road

Can I get a confirmation from Dev team that these will be considered?
Thanks and really appreciate your work!

**Comment by clash-votter** [comment]
This must be related to #359 (When UseGoogleWalk is true, bot just walks).
Like mentioned in the issue when UseGoogleWalk is false bot works as expected.
