### ISSUE TITLE
Help me fix this error v9.4

### ISSUE THREAD

**Issue by harryhalim05** [NoxxDev/NecroBot#377]
![image](https://cloud.githubusercontent.com/assets/21101715/17838313/e0eb1bba-67f4-11e6-85ed-18a8383db61c.png)

Can Someone tell me about this? im already download the new here -_-

**Comment by memiedeedy** [comment]
I believe this error come from config.json file
Have you try to validate your config.json?

Maybe you can try to d/l release.zip (0.94) that exact to new folder and start to run the bot then let bot create a config for you

Note: My problem was gone after i turn Telegram to false
Now work very smooth, Thank you for your hard work @NoxxDev , Luv you

Hope it help

**Comment by harryhalim05** [comment]
![image](https://cloud.githubusercontent.com/assets/21101715/17838349/85f26abe-67f5-11e6-90bb-a742da19628b.png)

no Config.json here -_-

**Comment by inclouis** [comment]
delete your necrobot.exe and start the bot again

**Comment by harryhalim05** [comment]
![image](https://cloud.githubusercontent.com/assets/21101715/17838397/099379de-67f7-11e6-9d3e-2f966900e67b.png)
I'm already fill it, but still cant lol -_-
@inclouis 
already delete my necrobo.exe

**Comment by harryhalim05** [comment]
its already work now, thanks @inclouis . im already make it work haha

**Comment by inclouis** [comment]
no worries buddy!
