### ISSUE TITLE
Unable to start bot

### ISSUE THREAD

**Issue by inoxas78** [NoxxDev/NecroBot#38]
As on screen shot: Missing DLL but DLL is at the right place.

![image](https://cloud.githubusercontent.com/assets/21035583/17661056/1bb6d4ea-62dd-11e6-9831-f6b6d6515f59.png)

Configured with necrobot.exe not necroconfig.exe
Same problem if configured with necroconfig

### Other Information
Version: 0.8.8
Windows Version: Win7 SP1 on VM - Parallels desktop last .NET  last Java etc etc (i'm on a mac) Older version worded fine on my "PC" (or other bots i've tried to check ban)
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Launching app

**Comment by smoothrunnings** [comment]
@inoxas78  install .NET 4.6.2

**Comment by RubenvdKolk** [comment]
@smoothrunnings i installed it and it still doesnt works

**Comment by NoxxDev** [comment]
Missing dll
Download and install
[Net Framework 4.6.2] (https://www.microsoft.com/en-us/download/details.aspx?id=53345)
[Visual C++ Redistributable for Visual Studio 2015] (https://www.microsoft.com/en-US/download/details.aspx?id=48145)

**Comment by inoxas78** [comment]
Problem was Visual C++ :) 
Thks a lot :)
