### ISSUE TITLE
TypeInitializationException? Please help me

### ISSUE THREAD

**Issue by Noreplic** [NoxxDev/NecroBot#381]
![image](https://cloud.githubusercontent.com/assets/21159287/17838755/42db41fe-67d4-11e6-88cd-e1fe6524d159.png)

I tried to run my bot today and it didn't work, so i downloaded it again and it still gave me this...
It does not even ask me at first to configure something and it doesn't create config.json or auth.json.
Can anybody help me?

**Comment by xhaoran06** [comment]
Delete the NecroBot.exe xml config

**Comment by ausscheider** [comment]
https://github.com/NoxxDev/NecroBot/issues/358

**Comment by Noreplic** [comment]
you are the best <3
