### ISSUE TITLE
encrypt.dll virus?

### ISSUE THREAD

**Issue by edmean** [NoxxDev/NecroBot#382]
![pk1](https://cloud.githubusercontent.com/assets/20985645/17838920/c2e7156c-680b-11e6-834b-43d35bbd1db6.jpg)

**Comment by illuminatiboss** [comment]
Yes , I've had this false positive

**Comment by Daniel99887** [comment]
It's because it's encrypted most crypted files come up as viruses.

**Comment by edmean** [comment]
Any tips to overcome/bypass this? 🤔🤔

**Comment by iwean** [comment]
Softban your antivirus :dancer:

**Comment by knumchoke** [comment]
Use excludes function in your AV to make it ignore the files.
