### ISSUE TITLE
Red Error text

### ISSUE THREAD

**Issue by Texiqq** [NoxxDev/NecroBot#39]
http://imgur.com/NGRypWk

Im not very good with understanding this, but I want to learn. What am I missing?

Version: 0.8.8
Windows Version: Server 2012 R2
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): It wont start

**Comment by NoxxDev** [comment]
Download and install
[Net Framework 4.6.2] (https://www.microsoft.com/en-us/download/details.aspx?id=53345)
[Visual C++ Redistributable for Visual Studio 2015] (https://www.microsoft.com/en-US/download/details.aspx?id=48145)

Delete all files in folder bot and [download] (https://github.com/NoxxDev/NecroBot/releases/tag/v0.8.8)

**Comment by Texiqq** [comment]
I still get the same message as before

**Comment by NoxxDev** [comment]
Dll removed in [v0.9.0] (https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.0)
