### ISSUE TITLE
0.9.4 bot restarts after every pokestop or pokemon catch

### ISSUE THREAD

**Issue by Daniel99887** [NoxxDev/NecroBot#392]
Pokemon servers might be offline error

**Comment by ComputerApp1234** [comment]
Pls read the other issues.

**Comment by nutsky** [comment]
check your killswitch settings if it is existing

**Comment by iwean** [comment]
don't forget update your framework & visual c++

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
