### ISSUE TITLE
Positioning not working correctly 0.9.4

### ISSUE THREAD

**Issue by Daniel99887** [NoxxDev/NecroBot#394]
I need to change my location and I changed the coords on the lastpos and config but I still go back to the same place

**Comment by wilsondgonzales** [comment]
u don't use lastpos.ini you have to change it in config.json. The ini file serves a different purpose

**Comment by Trankilis** [comment]
In next version the bot will read the lastpos from file again.

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
