### ISSUE TITLE
KillSwitch Settings

### ISSUE THREAD

**Issue by Cranki** [NoxxDev/NecroBot#397]
After I've seen this error on lot of ppl, I had to open this Issue
After I reached the KillSwitchSettings on Pokemon 37/37 and clsoed the bot, the
"KillSwitchSettings": null, has changed to null! When I reopen the Bot, I get this Error
http://img5.fotos-hochladen.net/uploads/fehlernqdsrk3oc1.jpg
So i have to paste the KillswitchSettings again in, to fitx it.

I hope you can fix it, and furthermor extend it so far, that the bot Complete KillSwitchPokemon and Pokestops. Because when i reach MaxPokemonPerHour but not MaxPokeStop the bot still stops.. So it would be cool if he keeps running until maxPokeStops also get to done. 
And one other thing, that the Bot Saves the Total Amount of Pokemon a Day, like the lastLog.ini file... just for totalamountPokemonaDay and totalamountpokestopsDay,,

thx for the super work and best regards

**Comment by ShadXo** [comment]
#337

**Comment by ShadXo** [comment]
Rename your config open, necrobot press n, and set your options in the config again.
In the new version a few options are added to the config.

**Comment by NoxxDev** [comment]
KillSwitch has been removed
