### ISSUE TITLE
is it happening all over again?

### ISSUE THREAD

**Issue by 245trioxin** [NoxxDev/NecroBot#4]
[17:02:05] Name: Bench of Home Help INFO: Looting failed, possible softban. Unban in: 44/45

no softban removal after this

then the dreaded no usable pokestops found!

only a matter of time i suppose

also my lvl 31 account is perm banned (cannot get data from server error) on start up

**Comment by draknyte1** [comment]
I've been botting for 34hr straight on a single account without that happen once. Bad configs will obviously get you (soft) banned quicker..

**Comment by 245trioxin** [comment]
same config ive been using for a while. mind sharing yours so i can see where ive possibly went wrong

**Comment by 245trioxin** [comment]
update! left the bot off for an hr and its back up and running so panic over. no changes to config and walking speed is 10 kph
