### ISSUE TITLE
Razz Spammed

### ISSUE THREAD

**Issue by AmyEscano** [NoxxDev/NecroBot#401]
I dont know if this can be detected by niantic.......

### Expected Behavior
Actual Game by Niantic does not allow additional use of razz after a missed throw if razz has already been used beforehand
1. Use Razz on Pokemon
2. Missed Throw
3. Not Able to Use another razz

additional info:
if pokeball hits but pokemon escapes right after using razz....additional use of razz is allowed

### Actual Behavior
Bot allows use of another razz right after missing a throw and razz already used beforehand
1. Use Razz on Pokemon
2. Missed Throw
3. Bot uses Another Razz (I think this should not be allowed)
4. Bot attempts another throw

### Steps to Reproduce
1. Set 
-MaxBerriesToUsePerPokemon value greater than 1
-EnableMissedThrows value true
-ThrowMissPercentage value 90 (to easily reproduce missed throw) (optional)
-UseBerriesMinCp value 10 (to easily reproduce use of berries) (optional)
-UseBerriesMinIv value 10.0 (to easily reproduce use of berries) (optional)
-UseBerriesBelowCatchProbability value 0.9 (to easily reproduce use of berries) (optional)

2. Run Bot, Wait for pokemon that is "hard" to catch

**Comment by masterpowers** [comment]
your bot by pass the ui and goes to the endpoint of throwing of berries , and its better i guess since berries can make the catching easier >;D

**Comment by AmyEscano** [comment]
1. You dont know for sure if multiple use of razz stacks
2. If niantic detects a "bypass" in ui, u get perma banned

i think its a risk

**Comment by ridalarry** [comment]
This is needed to be fixed ASAP as it could be the reason of some bans
