### ISSUE TITLE
Feature Request:Location setup through Telegram everytime bot restarts & remote bot restart through Telegram

### ISSUE THREAD

**Issue by grinmind** [NoxxDev/NecroBot#402]
Am I asking too much? If it is possible it would be a great feature of the bot especially for the people who are away from the computer all the time

**Comment by petpetpetvm** [comment]
you can use teamviewer lol

**Comment by langit7** [comment]
teamviewer or use websocket just setup tunnel  to your bot

**Comment by grinmind** [comment]
Internet connectivity is really slow at some point. Teamviewer is no good sometimes. How do you set up tunnel to the bot using websocket? Coz i mostly use my phone by telegram to see the status of the bot
