### ISSUE TITLE
[Feature Request] Can we have the mons' stats in the log file?

### ISSUE THREAD

**Issue by avexus** [NoxxDev/NecroBot#405]
Hi, I would like to post a feature. In the beginning of running the bot, I can see there is a summary of every bot's stats. Like iv, atk, defense, stamina, movesets.
Can these to appended to the log file?
That would be very nice to look at.
I tried to cut from the results, could not do so.
Also, in the config file, I would like an option to specify how many mons we want to display.  Thank you!

**Comment by imolesi** [comment]
Set DumpStats = true

**Comment by MaartenDeen** [comment]
Where do you put that? I tried setting "DumpStats": true in the config file, but that did nothing and got deleted from it.

**Comment by imolesi** [comment]
Create the "Dumps" folder (may the bot doesn't) and restart the bot after setting DumpStats true, the CSV file is created eveytime the bot starts
