### ISSUE TITLE
IDEA of start and stop

### ISSUE THREAD

**Issue by andreacasato** [NoxxDev/NecroBot#408]
Hi! I have got an idea!
I'm not good with coding and i'm not good with english, sorry.
Why you guys do not insert a start and stop thing?
3 variables:
1 to enable/disable the start and stop
1 to set the minutes of working
1 to set the minutes of pause

Now i explain myself
This start and stop that I have in my head it's only a thing that after 60 minutes of botting, the bot logs out from the google account and after 10 minutes (from the log out) the bots logs in and continue botting.
I think it's a googd idea so you can let the bot running day and night with a risk of getting banned (i think) reduced.
I'm not good with coding, this is only an idea for you guys :)

**Comment by imolesi** [comment]
You can do something similar with Windows Scheduler, this way I make the bot walk 2.5 hours in the morning and 3.5 hours in the afternoon.
To start the bot just launch the executable (remember to set the starting folder inside scheduler property), to stop the bot just kill the process:

`taskkill -im Necrobot.exe -f`

In italian it is called "Pianifica attività", mail me if you need more info (I'm from Bologna).

**Comment by ThatAce** [comment]
well i tried using task scheduler but it fail on the bot

**Comment by andreacasato** [comment]
I tried this method but after the running of the .exe file, the programm will stop functioning, I don't know why

**Comment by imolesi** [comment]
It work flawlessly in my pc, start and stop twice a day... did you set the starting folder in the textbox below the excecutable file name box?
