### ISSUE TITLE
Sniping

### ISSUE THREAD

**Issue by lanadelrey92** [NoxxDev/NecroBot#410]
Sniping is really dangerous? my friend have 2 botted accounts.. 1 with snipe on and one without. Niantics banned the one without snipe on and not the other one!

**Comment by imolesi** [comment]
Who knows? Maybe Niantic does not check the sniping location but it seems unlikely. I think they just assign "cheating points" to each behavior and when the sum reach a certain amount then they ban the account... like a mail spam filter. My 3 previous account were banned but they sniped A LOT, now I don't snipe at all and stopped botting a week ago as I reached level 21, no ban this week

**Comment by clash-votter** [comment]
No sniping is not dangerous. This account botted since release of v0.9.0 (6 days ago). Currently on v0.9.4.
https://cloud.githubusercontent.com/assets/21138034/17836937/dc44ccc6-67e7-11e6-990c-2e369b67329a.png

**Comment by clash-votter** [comment]
Seems the limit is 40 snipes per 10 minutes. See
https://github.com/NoxxDev/NecroBot/pull/337#issuecomment-241240393

**Comment by antibiotic1** [comment]
@clash-votter  friend can we have your config file? thanks you will help me alot

**Comment by VBQL** [comment]
@clash-votter Yeah, whatever that config did it is crazy
