### ISSUE TITLE
Thailand language Error?

### ISSUE THREAD

**Issue by 0801101009** [NoxxDev/NecroBot#413]
I can not change the language of Thailand.
![1234](https://cloud.githubusercontent.com/assets/12894301/17853330/0284390e-6896-11e6-9099-8b431cb58dde.PNG)

**Comment by VBQL** [comment]
Languages are broken at the moment I guess, same thing happened to someone else #414

**Comment by ktpspgame** [comment]
problems with

**Comment by NoxxDev** [comment]
Fix .0.9.5 or upper
