### ISSUE TITLE
Log file records are incomplete

### ISSUE THREAD

**Issue by MaartenDeen** [NoxxDev/NecroBot#415]
The log records in the console show what kind of event happened: (INFO), (POKESTOP), (PKMN), (TRANSFERRED). The logfiles written to disk do not show this. Is this a setting I can make, is it a bug or is this intentional?

### Expected Behavior
Console shows:
`[14:12:59] (PKMN) (CatchSuccess) | (Normal) Rattata Lvl: 3 CP: (35/43) IV: 36.00% | Chance: 92.71% | 54.72m dist | with a PokeBall (36 left). | 160 EXP earned | Candies: 314 | lat: 52.107143 long: 4.281342`

Log file should show:
`[14:12:59] (PKMN) (CatchSuccess) | (Normal) Rattata Lvl: 3 CP: (35/43) IV: 36.00% | Chance: 92.71% | 54.72m dist | with a PokeBall (36 left). | 160 EXP earned | Candies: 314 | lat: 52.107143 long: 4.281342`

### Actual Behavior
Log file actually shows:
`[14:12:59] (CatchSuccess) | (Normal) Rattata Lvl: 3 CP: (35/43) IV: 36.00% | Chance: 92.71% | 54.72m dist | with a PokeBall (36 left). | 160 EXP earned | Candies: 314 | lat: 52.107143 long: 4.281342`

### Other Information
Version: release (0.9.4)
Windows Version: 7

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
