### ISSUE TITLE
Feature Request - Sleep Time

### ISSUE THREAD

**Issue by masterpowers** [NoxxDev/NecroBot#416]
Just Like Kill Switch I Think We Should Also have a Sleep Time.

Let Say you Set your Sleep Time for 8 hrs...
and the Time you want to Sleep let say at your localtime 22:00
then the bot will resume after 8 hrs....

This is better than Turning Off the CLI everynow and then coz the Location resets Backs to the Original Location if you Shuf down the Windows...

**Comment by clash-votter** [comment]
Oh Shit Not This Again.

**Comment by uncannierelf** [comment]
FYTFY:

Just like the KillSwitch, we should have a Sleep Time function. For example, if we set a sleep time of 8 hours to occur at 10PM local time, the bot will turn off from 10PM to 6AM and resume automatically. This way, we don't have to physically turn the bot on and off and the bot can resume where it last was (or at the starting location) automatically.

**Comment by clash-votter** [comment]
You can do these 'Sleep' functions via batch file programming in Windows, if you looked around Google hard enough.
...
Alright I'll be nice and show my batch file here for 'Sleeping,' from 10pm to 06am. This batch file is ran via [MinGW64 terminal](https://git-scm.com/downloads), in the root folder of Necrobot (hence why the 'sleep' function works).
```
@echo off
    setlocal enableextensions disabledelayedexpansion

:loop
    call :getTime now

    set "task=day"
    if "%now%" lss "06:00:00,00" ( set "task=night" ) 
    if "%now%" geq "22:00:00,00" ( set "task=night" )

    call :task_%task%

    echo %now%

    endlocal
::goto loop here makes this batch file run continuously.
    goto :loop

:task_day
:: Here we start the bot 2 times for 30 minutes each. 5 minute delay after first session, 2 hour delay the next.
    START necrobot.exe
        echo Starting the bot for 30 minutes.
        echo %time%
        sleep 30m
    taskkill /f /im NecroBot.exe > nul
       echo Stopping the bot for 5 minutes.
       echo %time%
       sleep 5m

	START necrobot.exe
        echo Starting the bot for 30 minutes.
        echo %time%
        sleep 30m	
    taskkill /f /im NecroBot.exe > nul
	    echo Stopping the bot for 2 hours.
        echo %time%
        sleep 2h
    goto :eof

:task_night
:: Between 10pm to 6am the bot will do the tasks here.
    echo Sleeping 15 minutes.
    sleep 15m
    goto :eof

:: getTime
::    This routine returns the current (or passed as argument) time
::    in the form hh:mm:ss,cc in 24h format, with two digits in each
::    of the segments, 0 prefixed where needed.
:getTime returnVar [time]
    setlocal enableextensions disabledelayedexpansion

    :: Retrieve parameters if present. Else take current time
    if "%~2"=="" ( set "t=%time%" ) else ( set "t=%~2" )

    :: Test if time contains "correct" (usual) data. Else try something else
    echo(%t%|findstr /i /r /x /c:"[0-9:,.apm -]*" >nul || ( 
        set "t="
        for /f "tokens=2" %%a in ('2^>nul robocopy "|" . /njh') do (
            if not defined t set "t=%%a,00"
        )
        rem If we do not have a valid time string, leave
        if not defined t exit /b
    )

    :: Check if 24h time adjust is needed
    if not "%t:pm=%"=="%t%" (set "p=12" ) else (set "p=0")

    :: Separate the elements of the time string
    for /f "tokens=1-5 delims=:.,-PpAaMm " %%a in ("%t%") do (
        set "h=%%a" & set "m=00%%b" & set "s=00%%c" & set "c=00%%d" 
    )

    :: Adjust the hour part of the time string
    set /a "h=100%h%+%p%"

    :: Clean up and return the new time string
    endlocal & if not "%~1"=="" set "%~1=%h:~-2%:%m:~-2%:%s:~-2%,%c:~-2%" & exit /b
```

**Comment by FallenDev** [comment]
You can create this in a simple bash script. For Example... 
1. Create Notepad.exe on Desktop
2. Rename it to Run.bat
3. Edit Run.bat in Notepade.exe
4.  Type in --
```
@echo off
:loop
cd C:\  ((Enter path of NecroBot.exe Here and delete (()) ))
start NecroBot.exe
timeout /t 21600
taskkill /f /im NecroBot.exe
timeout /t 10800
goto loop
``` 
This does as the code above says... It will play it for 21600 seconds then time out for 10800 seconds.

**Comment by FallenDev** [comment]
You do not need the KillSwitch, in fact if @NoxxDev wants he can incorporate what I just wrote above.

**Comment by FallenDev** [comment]
Just need to have a dynamic variable that can locate NecroBot.exe

**Comment by FallenDev** [comment]
Oh... if you setup what I wrote above correctly. It will auto play NecroBot for 6 hours then rest for 3 hours and loop it.

**Comment by NoxxDev** [comment]
Not at the moment
