### ISSUE TITLE
softban necrobot

### ISSUE THREAD

**Issue by keeskwakman** [NoxxDev/NecroBot#42]
i keep getting softbanned while i believe my settings arent extreme. Im using necro bot 0.8.8, here are my configs. i hope you guys can help
[config.zip](https://github.com/NoxxDev/NecroBot/files/417986/config.zip)

**Comment by AndikaTanpaH** [comment]
plis paste at http://pastebin.com/

**Comment by keeskwakman** [comment]
never used it before but if everything is alright it is there under the name of "softban pokemon go"

**Comment by keeskwakman** [comment]
here is the link http://pastebin.com/Y5GZ0HWn

**Comment by eicool** [comment]
changeing ip wont help you anyway

**Comment by keeskwakman** [comment]
yeah i dont know waht it is because it worked fine for a day or something

**Comment by Pepperolls** [comment]
Same for me. It worked today for about 45 minutes, then I opened 2 more bots and aftter 5 minutes they all started getting softbans, and if restarted, the error with "There are no pokestops in your area. Is your maximum distance too small ?" would pop up. Usually after waiting a few hours and then starting the bot, it works, but for that limited amount of time. It`s been so for the last 3 days.

**Comment by keeskwakman** [comment]
i have a max distance of 5000, thought that was enough

**Comment by JoNMii** [comment]
Dont use more than one account per ip or you will get softban

**Comment by keeskwakman** [comment]
thx guys
