### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#423]
Just got this exception in v0.9.4
![error](https://cloud.githubusercontent.com/assets/11824134/17860377/a1a5eb30-688d-11e6-94e5-e34a62024ae2.png)

**Comment by petpetpetvm** [comment]
maybe ur googlewalk is off, or killswitch is null
I don't use googlewalk, that's why i got it all the time, hopefully @NoxxDev  will fix it soon

**Comment by TLBM** [comment]
Sorry forgot config
`  "GPXSettings": {
    "UseGpxPathing": true,
    "GpxFile": "route.gpx"
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "...",
    "Cache": true
  },
  "KillSwitchSettings": {
    "UseKillSwitchCatch": true,
    "CatchErrorPerHours": 21,
    "CatchEscapePerHours": 42,
    "CatchFleePerHours": 12,
    "CatchMissedPerHours": 49,
    "CatchSuccessPerHours": 93,
    "UseKillSwitchPokestops": true,
    "AmountPokestops": 45
  },`

**Comment by ausscheider** [comment]
Poste mal bitte deine komplette config ohne Google key

**Comment by MaartenDeen** [comment]
Not sure if this is related, but I tried gpx walking and every time I set UseGpxPathing: true, Necrobot can't log in to my google account with the same kind of error. When I set UseGpxPathing: false Necrobot can login again.
