### ISSUE TITLE
(0.9.4) Niantic Servers unstable, throttling API Calls.

### ISSUE THREAD

**Issue by owenchai1989** [NoxxDev/NecroBot#426]
**Niantic Servers unstable, throttling API Calls.**
What is this happening? Will get ban if i continue bot?

**Comment by petpetpetvm** [comment]
i got this since 0.9.4 released (maybe cuz i don't use googlewalk) and no ban until now

**Comment by LeHartx** [comment]
Even with google walk that error still pops up, not going to bot as it feels like it releases alot of API calls.

**Comment by ausscheider** [comment]
This Message come in every version. I think it's normaly 
I have no softbans or other

**Comment by developnoop** [comment]
This problem exist since the original Necrobot 0.8.X releases, so nothing new. There is another issue here raised regarding the API Calls.

**Comment by vfuyong** [comment]
I have a theory that this message is not great. If you have seen this, try to log off for some time.

**Comment by ignorantEndUser** [comment]
@developnoop I have seen other posts stating there is no inventory management and that API calls are out of control, but I have not seen a specific issue tagged with the intent of lowering total # of API calls.  Is there one an I have missed it?

**Comment by dbw-holic** [comment]
I have bee observing this message for a quite while. It actually does the job well - when it says "throttling API calls" you will notice it actually stops catching pokemons for a certain time, only spins pokestops, which to my eye is great because it's adding more variables for Niantic to analyse botting behaviour.

**Comment by wakrad** [comment]
throttling API call is repeated every 30 min.

**Comment by owenchai1989** [comment]
too bad i get perm ban in morning, bot around 6hours =(

**Comment by owenchai1989** [comment]
😭😭😭😭😭😭

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
