### ISSUE TITLE
{Suggestion} Bot Stop Limits

### ISSUE THREAD

**Issue by JoNMii** [NoxxDev/NecroBot#43]
Like now niantic set limits to api, i suggest to add some bot killers, on reach x pokestop taken, x pokemon caught.

Regards

**Comment by AnthonyWuChen** [comment]
yeah, as i have heard from some forums, they are saying that niantic is setting the pokemon catch cap to 1000 daily, and 2000 pokestop clicks daily, so it would be awesome that the necrobot can  stop operating after certain number that we can set.

**Comment by NoxxDev** [comment]
implement the alert system in brief

**Comment by JoNMii** [comment]
I dont understand you  @NoxxDev
