### ISSUE TITLE
Walking strategy issue with 0.9.4 & google api.

### ISSUE THREAD

**Issue by mvp256** [NoxxDev/NecroBot#430]
The bot is now targeting the nearest straight distance pokestop, and ignore the other pokestops on the path. This issue will lower the exp&supply efficiency from pokestops.

![pokestop](https://cloud.githubusercontent.com/assets/21179338/17865481/58bb0390-68d5-11e6-8953-061c25811213.png)

Version: 0.9.4
Windows Version:  win10

**Comment by developnoop** [comment]
Saw this also on my trial this morning.

**Comment by TLBM** [comment]
I repeat my suggestion to give all the known pokestops to the Google Maps API and let it create a optimized route.

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
