### ISSUE TITLE
ERROR v0.94

### ISSUE THREAD

**Issue by soujirouzeta** [NoxxDev/NecroBot#433]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
![error](https://cloud.githubusercontent.com/assets/21180416/17866390/f74ab1d2-686b-11e6-8c44-a6dcee6cec2c.jpg)

**Comment by iwean** [comment]
Please update Framework & Visual C++

**Comment by developnoop** [comment]
Not much information from you, after update the Framework and Visual C++, if error still is there try [https://github.com/NoxxDev/NecroBot/issues/369](url)

**Comment by ausscheider** [comment]
Or Try this one https://github.com/NoxxDev/NecroBot/issues/358

**Comment by ciberelfo** [comment]
I have the same error, version of c++->14.0.23918

Net framework 4.6.2

**Comment by soujirouzeta** [comment]
it works!!.. thanks.. iwean

**Comment by iwean** [comment]
You're welcome @soujirouzeta

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
