### ISSUE TITLE
Error, cannot open 9.4 but 9.3 work 

### ISSUE THREAD

**Issue by whoamichal** [NoxxDev/NecroBot#436]
what must i do
![untitled](https://cloud.githubusercontent.com/assets/21185541/17876302/bb1297c0-690b-11e6-9e82-f5378f98c68e.jpg)

**Comment by iwean** [comment]
Check this out #433

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
