### ISSUE TITLE
Current Operation Was Cancelled

### ISSUE THREAD

**Issue by mikegrimmers** [NoxxDev/NecroBot#44]
After about 10-15 minutes of run-time, the bot displays a singular line of red text saying "the current operation was cancelled" and then goes onto say on the next line "logging in as ******" and then does nothing.

Any ideas?

**Comment by NoxxDev** [comment]
Please, print or logs

**Comment by mikegrimmers** [comment]
I've now been banned with failed to get data error from Niantic, is there anyway to snipe under their radar?
