### ISSUE TITLE
1week only then Ban

### ISSUE THREAD

**Issue by mhicarl** [NoxxDev/NecroBot#440]
I made and experiment my 7 accounts. I bot the 3 until it reach lvl20 in 1 day and the others are just lvl 15 and lvl 6. Ive used VPN same location where i farm. ive wait for about 4-6hrs to bot those 5 accounts again and i didnt open the other 2. After 1week (today) ive open it to check those accts all of them are now getting "failed to get data from the server" ive done all the instructions that i read here but i dont have any idea why all of the 7 accts are ban at the same time.

**Comment by khairulpetrcech** [comment]
Yeap..same here got banned after 1 week..2 account(1 snipping,1 not sniping)..

There seem niantic let u play for 1 week,after that auto banned..does anybody had the same experience ?

**Comment by ausscheider** [comment]
the same. at this morning all acc's are ban.
1 ip 1 bot
no softbans
humanwalkung etc
max 9k ep per hour
max 3-4 hours per day

**Comment by jimkaya** [comment]
same here...
save config
10k ep/h
8h/day
lvl 26 after 1 week

**Comment by vipery** [comment]
bentime

**Comment by iPollox** [comment]
Something tells me that the Rocket API isn't sending the right responses that the server wants to get.

**Comment by ausscheider** [comment]
rocket api or another api
every bots are detected and the botter will banned

**Comment by langit7** [comment]
i think this is 3rd  ban wave..  next week will 4th ,  i got 1 out 4 banned in  last ban wave

**Comment by smoothrunnings** [comment]
@mhicarl You're using the same location which is also part of the problem. Niantic have been in the game of stopping botter's before Pokemon Go was even released so botting is nothing new to them, they can see you coming a million miles away. However since there are millions of people playing Pokemon Go they may not ban you right away but will eventually when they get to you.

**Comment by jimkaya** [comment]
today i will try something new...
create account, start bot, catch 1 pokemon and then i let rest the bot.

I observe if the account is deleted after one week

**Comment by wakrad** [comment]
@jimkaya wait your report after 1 week from today

**Comment by smoothrunnings** [comment]
Check the twitter page of FastPokeMapCom. It looks like Niantic is starting to implement new security measures forcing you during game play to verify your not a bot.
