### ISSUE TITLE
New acc with google IAP and google walk

### ISSUE THREAD

**Issue by petpetpetvm** [NoxxDev/NecroBot#443]
i'm just checking if is there any brand new account that used google IAP/google walk config only (with snip) got banned ?
I'm just checking... maybe it's too early for that

**Comment by Kermel** [comment]
Checking from this morning (no snipinig) with a brand new account and google walk only.
Earlier this morning I got ban on my previous account (but this one used previously also the normal walking (maybe too fast jumping)

**Comment by petpetpetvm** [comment]
@Kermel oh thanks, still waiting for more

**Comment by Kermel** [comment]
(So far not banned) :-)
