### ISSUE TITLE
[request]transferring pokemons based on best iv outcome

### ISSUE THREAD

**Issue by popsoda27** [NoxxDev/NecroBot#447]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
Transferring pokemons based on best IV attainable rather than current iv

### Actual Behavior
Transferring pokemons based on current IV value as stated in KeepMinIVPercentage value, regardless of evolved or upgraded state. Best IV attainable value is displayed when transferring eg. [Best CP: xxx IV: 100%] while current iv of pokemon is 75%

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by Kermel** [comment]
I think you are mistaken. IV on your pokemon won't change. 
The thing that you see [Best CP:, IV...] only informs you that in your pokedesk there is another pokemon with those stats

**Comment by popsoda27** [comment]
oh really?? then im badly mistaken :P here i am thinking the bot could have retained certain ones being transferred haha...sorry for the mixup.
Moderator pls close this thanks
