### ISSUE TITLE
[Feature suggest ]safe to avoild ban , stay at a fix pokestop 

### ISSUE THREAD

**Issue by siujj** [NoxxDev/NecroBot#448]
Most account were banned today.
Is there any setting can make the bot stay at a fix pokestop, no moving , only catch the pokemon around that pokestop while auto refresh?
Although it is very slow to up LV and catch pokemon, but it seem very safe.
Is it simply to set the below parameter to fulfill? 
   "MaxTravelDistanceInMeters": 1, or "MaxTravelDistanceInMeters": 0,
 "WalkingSpeedInKilometerPerHour": 0.1, or  "WalkingSpeedInKilometerPerHour": 0,

**Comment by Kermel** [comment]
Try it and post a report here ;)

**Comment by MrPiwy** [comment]
I think about this yesterday, that i will put my char on lure and dont go anywhere. but it already banned xD
