### ISSUE TITLE
How do I get a copy of the latest version with all the commits?

### ISSUE THREAD

**Issue by smoothrunnings** [NoxxDev/NecroBot#45]
How do I get a copy of the latest version with all the commits?

**Comment by JoNMii** [comment]
Just use git clone ?¿

**Comment by smoothrunnings** [comment]
not sure what git clone is?

**Comment by butilities** [comment]
git clone --recursive https://github.com/NoxxDev/NecroBot

**Comment by smoothrunnings** [comment]
So you mean click the Clone or Download button? I don't see any option to git clone on the main page.

**Comment by butilities** [comment]
If you don't have git, use the green clone button and download the zip file, but you have to manually do the same for ForexRex and PogoProtos

**Comment by joe112** [comment]
guys this still work ?

**Comment by joe112** [comment]
i got necro bot before cant find pokestop within.....

**Comment by smoothrunnings** [comment]
I installed Git. I downloaded and added the master to Git. but I still don't see inside Git how to complete the necrobot? lol

**Comment by ANR2ME** [comment]
@butilities 
if you're new to github and git, you can try using SourceTree application to clone this repository using GUI, it makes your life easier >.<

**Comment by smoothrunnings** [comment]
@ANR2ME so all I have to do is install the GitHub application and download the repository from this fork right? Then how do I create Necrobot.exe from he GitHub app?

**Comment by ANR2ME** [comment]
You need Visual Studio 2015 to compile it to EXE, github only used to download the latest source and it's dependencies

**Comment by smoothrunnings** [comment]
@ANR2ME is it easy to compile afterwards?

**Comment by ANR2ME** [comment]
Have you checked https://github.com/NoxxDev/NecroBot/wiki/Source-Code ?

**Comment by Wcidd** [comment]
Ey bois
