### ISSUE TITLE
Farewell Necrobot. Update 0.35.0 is coming

### ISSUE THREAD

**Issue by repelsteeltjehd** [NoxxDev/NecroBot#451]
For those that did not read this thread yet! 

[https://twitter.com/FastPokeMapCom](url)

the end is nearby.

**Comment by smoothrunnings** [comment]
@repelsteeltjehd Link is broken.

**Comment by Skolzack** [comment]
It's not broken, just copy and paste it

**Comment by Skolzack** [comment]
![image](https://cloud.githubusercontent.com/assets/20953554/17899146/b2971402-6930-11e6-8dc6-74017c5ab5f2.png)

**Comment by tuxfrw** [comment]
captcha? now they fucked with bots. :(

**Comment by JoNMii** [comment]
@tuxfrw nah

**Comment by tiggerite** [comment]
By all accounts the reCaptcha won't be enabled in 0.35 anyway, the main issue is the new hashing for the Unknown6 / Unknown22.

**Comment by likeness123** [comment]
So does this mean no more bots? :(
