### ISSUE TITLE
Pattern behavior The main bann problem

### ISSUE THREAD

**Issue by REDESTOR** [NoxxDev/NecroBot#453]
i think there have to be a randomiser for each option of the bot or a better ia, if you think it, there is taking less time to niantic to ban us, we always use the same config, thus bot follows the same pattern, and it takes about a week to gather our info, analyse it and see if there is a pattern, and spot us, the more we use it more information gave to the server more patterns, more easy to spot a bot

**Comment by stevens8310** [comment]
I think it not about to have a randomiser~ before my account get ban I take snipe and very stable for more than 8hrs

than I change config.json to non-catch and take stops only. It still works perfectly for 2hrs, but when I close bot and hold for 5 mins and turn on bot again, it gets ban(I also very careful in reading logs about the last coordinate the bot in, it less than 5 mins distance by walk for my default coordinate )
SO~is there something different between bot and cellphone closing the apps or start the apps again? that what I care about~ If it real, than every time we "start" the bot is a risk

**Comment by BoydTM** [comment]
It may be because of patterns (there are lot of them in necrobot), or because of the API (order of requests send to server, their frequency etc.) or because of other things. We may also assume that perm bans are not given immediately - they probably running some scripts to flag us on copy of the database ( once for a week ? )

**Comment by smoothrunnings** [comment]
@REDESTOR Niantic is rolling out captcha in their new version of Pokemon Go, and will be using it on their servers too. So I think this whole topic is pointless. :)

**Comment by REDESTOR** [comment]
@smoothrunnings yeph cause if niantic spots repeatedly pattern in play behavior send a captcha for verifying if its a bot, if no pattern no bot, no need of captcha :)
