### ISSUE TITLE
fully utilise incubators

### ISSUE THREAD

**Issue by LobsterX** [NoxxDev/NecroBot#454]
i have 2 limited use incubators which the bot refuse to use to incubate Eggs....

how to make the bot use these limited use incubators? i remember prior to 0.9.0, it was working well...

**Comment by xhaoran06** [comment]
Set it to a minimum of 2km..

    "UseEggIncubators": true,
    "UseEggIncubatorMinKm": 2,

**Comment by LobsterX** [comment]
that;s the default settings i have.... but it isnt using the limited use incubators

**Comment by NoxxDev** [comment]
Check version 0.9.7
