### ISSUE TITLE
Can we emulate an iphone device? 

### ISSUE THREAD

**Issue by daproject85** [NoxxDev/NecroBot#458]
can we emulate an iphone device? it seems like when you from an emulate android (which is all bots) to an iPhone thats when you get banned

**Comment by Skolzack** [comment]
There's already an phone emulator on auth.json

**Comment by ajns73** [comment]
I think the question is about what emulation is being used versus what type of device you own. i.e. - emulating an android device via necrobot and then logging in and actually using Pokemon Go from an iPhone because that's what you own.

**Comment by hardknoxni69a** [comment]
Chnage your auth.json to same device details of your actual phone and should be good

**Comment by daproject85** [comment]
lol @hardknoxni69a lol really bro? lol thats your answer?? lol just change your device details? did you even read the code to see if it would accept those parameters? did you even check to see ios has the same exact paramters? LOL.

i love how some people give solutions ... like im thirsty , oh go drink water yea

**Comment by hardknoxni69a** [comment]
Isnt that what the details are to edit what info is sent to server about your device so if you change your details to details of an iphone shouldnt the server see it as an iphone details atleast i try to help sounds like u just like seeing yourself type and u bet if your thirsty ill offer some water even to you lol

**Comment by lkhgamer** [comment]
i have the same thought as @hardknoxni69a "changing the phone detail at auth.json"
i give you water plus lemonade in it LOL

**Comment by alvenyen** [comment]
I read the code, and I also curious about how iphone Pokemon Go generate the signature, since it also has some patterns in NecroBot signature generating function.

**Comment by ajns73** [comment]
I don't think the issue is with knowing what those details do. I think the issue is putting valid values in those fields for an iphone. Like AndroidBootLoader. Pretty sure that is not a characteristic of an iPhone. So, "null" or is there an iOS bootloader? What is it called? Again, just saying "do it" is not helpful, and actually might be harmful to the community if incorrect emulation settings lead to easier detect of the bot.

**Comment by hardknoxni69a** [comment]
True apples do have there deviceid but for bootloader info i am unsure about that but what is wrong with using android settings? my buddy has an iphone and he logs in my account all the time and vice versa and we never have issues the main thing is sending proper values but i do think android values will be fine to use until we here further
@NoxxDev can probably say if there can be an ios setting but i strongly believe it will not make a difference and there isnt a generator for iphones in the old gui which i miss by the way so they probably didnt code iphones into the the app for the simple fact that pokemon just cares that you use real information when you do logon with a real device which your iphone will send correct info once you logon but like i said going from an iphone to android was never an issue atleast for me and we would switch accounts to get eachother pokemon a few times a day so im sure once youve met your botting goal going from android to iphone once should be fine

**Comment by ajns73** [comment]
That's the other issue. Do the Pokemon Go servers bind your device data to the the IP your are using? Does that play a part in banning, and will that render any phone used to attempt to log in from a banned account useless? Is it just the IP? Questions it would be good to know answers to, but they may amount to "What is the meaning of life?"

**Comment by ANR2ME** [comment]
As i remember the old (original) NecroBot was emulating iOS with the API while using android device data in the auth.json, so it's kindda mixedup which could also flags as bot :D

**Comment by ajns73** [comment]
@ANR2ME This was my thinking. We may be able to find individual values that "work" in emulation, but when taken as a whole, make no sense. i.e. - Android on an iPhone with a IMEI reserved for a Windows phone and a Samsung model and brand. That's a Franken-phone. But I don't know if Niantic is sniffing stuff like that or if someone has to physically see it, perhaps as part of strange activity. So maybe that stuff doesn't cause the ban, but it confirms the illegitimacy of the account once someone is alerted to look at it.

**Comment by NoxxDev** [comment]
NecroBot not support iphone device
