### ISSUE TITLE
Can't start necrobot

### ISSUE THREAD

**Issue by albysprx** [NoxxDev/NecroBot#46]
Hi, I can't start necrobot, I got this error:
![error](https://cloud.githubusercontent.com/assets/16463429/17674126/89f75ca8-6324-11e6-8288-20d1f32f5731.png)
With my real ip too so it's not the proxy and I have .net framework 4.6.2 and C++ 2008 2010 and 2015

**Comment by JoNMii** [comment]
Are u sure that u are not banned? it happen to me with banned accounts

**Comment by albysprx** [comment]
I do not think, I always botted at 15km/h and I never did a snipe

**Comment by albysprx** [comment]
yes, it's banned, with a new account work
