### ISSUE TITLE
[INFO about bans] 3 accounts experience

### ISSUE THREAD

**Issue by zapahacks** [NoxxDev/NecroBot#463]
So I want to share some ''facts'' that I have recompiled about bots and the banning procces.

I created 3 accounts about 8 days ago. All of them were associated to a real gmail account but used as PTC acc. The account country was the same one as where the bot was supposed to play/bot.

I opened all the 3 accounts (for the first time, to see professor instructions) in 3 different rooted devices (3 samsung galaxy s6 edge) that used an exposed spoofing module (which according to the comments on XDA is 99% ''perfect'', it´s only problem is related to altitude values).

Started botting one account, each for 8 hours, one at a time, from my pc, using a public VPN program called Psiphon in Windows. The VPN countries were german (for AU acc) or from the USA (Brasil acc).

1 bot was assigned to bot in sydney (probably sea level), 2 bots were assigned to bot in Rio de Janeiro (probably see level). 

The bot in Australia didnt choose a team, both bots playing in Rio manually choose a team when they achieved level 6 using the same spoofing exposed module.

The bot configuration was not stock, all of them around 12 km/h, variable, 8 seconds delays between every action (theorically, because necro doesnt seem to respect this always), the 4 commonly found pokemons evolved when they reached enough candies (generating variable exp gain), eggs where used constantly around level 21 until they were finished, they were NOT used for evolving, just for the normal "botplay" (average 45 p/h, 20k exp/h).

The auth file of each of the accounts used a galaxy s7 edge device config info, with a different device id (by the way, does anyone knows the device config info for a galaxy s6 edge?, necro doesnt seems to have it, I created more than 150 auth files and it was not in it. Any help with this would be good for the testings.)

So here goes their behaviour and what I have learned until now:
1-
Acc from AU botting in Sydney, started on Aug 15. Reached level 26 with no problems at all. I didnt choose a team for this one, 3 lucky eggs where remaining at level 26. At level 26 I decided to stop the bot for 36 hours and change the location to Rio. It botted for 4 hours, then I used the 3 eggs remaining in a row. The bot showed a red error after 30 minutes of botting with the lucky egg and force closed. I logged into a one of the real galaxy S6 with a brasilian IP and I got an error about unable to authenticate (not the banned one, just unable to authenticate), I logged in into the other 2 RIO accounts and they all worked fine, so it was especifically related to the account. I waited 6 hours and logged through the phone, it worked normally. I run the bot again, it was functioning normally, used the lucky eggs again and I got the same red error from Necro. After that my account had the same unable to athenticate error in the phone. I stopped the bot until the morning and woke up to realize the account was banned.
Conclussions: from this acc I learned, firstly, that changing countries, even with real flights lenght of waiting, was very closely related to the ban. In less than 24 hours of botting in a country different to AU the account got banned), I advise to bot only in the country linked to your PTC account. Changing cities is being tested in the other accounts. Secondly, using the lucky eggs was related to 2 reproducable (red letter) errors in Necro that preceeded the banning of the account and that generated a message of unable to authenticate in the real app/on a real phone, which were automatically fixed after waiting some time, there was no third error as the account was banned after 2. I have the log files with the errors of necro in case someone with experience wants to give it a try. Thirdly, and the most interesting to me, I discovered that if I use the free/public VPN app on the phone to open the game I get the our servers are humbled by....bla bla bla message, I had to use the real connection with no VPN to connect, BUT Necro runs smoothly through the same VPN program!. This makes me think about how Necro logs in into the accounts, because my phone couldnt, but the bot could, using same VPN program (windows and android), same countries. Perhaps the bot logs differently bypassing the "VPN banning" the normal android app has been showing since YESTERDAY, can someone confirm this VPN ban in the real app/phone?. Anyway, Necro bypass it, which I think is not good, because it is a difference with the real app that I believe that can easily identify  you as a bot user, just saying from logic, I have no experience at all in app development, so just never mind if I am saying sth with no logic at all :)

2- 
Acc 2 botting in Rio, reached level 22. It has a team assigned since level 6, always botted in Rio, same time alive, 8 days running for 8 hours each 16 hours, eggs used in a row (not to evolve) with no red error in necro. I decided to manually open the app to play in Rio (same exposed module used), I fought in a gym, just to leave it with no team, didnt assigned one of my pokemons to avoid the probability of being reported by a normal user which can afford to lose his gym haha. Catched some pokemons, did some pokefarm, then back to bot. It is still alive, I will report later. I just wanna see if taking gyms and playing in the phone IN THE SAME LOCATION the bot is running makes any difference in respect of banning times. So I will keep doing the same until being banned, just in Rio.

3- 
Acc 3 botting in Rio, reached level 22 as well. It has a team assigned since level 6 as well, always botted in Rio, same time alive, 8 days running for 8 hours periods. I manually opened it using the exposed module mentioned in a city 6 hours away by car from rio, 1 hour by plane. I spoofed there, battled the only 3 gyms that exists there, I left them with no team holding. Then I waited 4 hours, and went back to bot in Rio close to the sea level. Until know, it is alive, I will keep exactly the same conditions to see how long it lasts. I suspect this one is the next one to be banned, as taking this one is taking gyms in a different location than the one where the bot usually plays. Lets see if my theory works hehe.

---
My next plan is to continue botting in just in the same region associated to the account, but this time opening I will ask my cousins to open the app for the first time in a real phone with no spoofing techniques (this will generate real GPS values I think), then back to botting until level 5,6 or 7, then again choosing teams in a real phone with real gps data, playing for real one hour per day, then botting 7 hours. After 9 days or level 25 I will give full acces to the account to a real person (no more botting at all) who wants to play normally on a phone just in the region where the bot was botting, and I will ask him to report when and "what did he do before being banned". For this experiment I want to use the real device config (Device ID and model) of the final user phone, and I will post a ban appeal in case they ban the account and see if they "react". Please, if anyone knows where to find device config info for samsung galaxy phones it would be appreciated.

PD: niantic seems to be winning kkk...perhaps a bot to create all the possible PTC accounts would be nice so at least we could hear from them when they completely deactivate "banned accounts" hehe... just kidding :).
 
I forgot to say that I always used the latest version of necro

**Comment by VBQL** [comment]
I feel like speed and walking is a real issue. Botters are not generally patient enough to allow their bots go slowly and grind the experience like a normal player. Since we are so used to having high speeds and sniping we make it easy for Niantic to detect and ban us. If we really wanted to not be flagged, I think setting all values and sacrificing speed and efficiency should be the best way to not trigger any flags or verifications.

**Comment by REDESTOR** [comment]
there is a big issue it will fail sooner or later cause they will spot a repeated pattern in "playing" behavior  an send captcha...http://pokemongohub.net/captcha-game-pokemon-go-bots-trackers/

**Comment by joe1chen** [comment]
I also had a level 29 running with no issues even with heavy sniping on.. then I ran into an API throttling issue, and the bot was in mid-snipe with my location set to several thousand km away from starting position.  When the bot restarted it tried to walk back to the starting location.  The next day the account was banned.  I am pretty sure that teleporting to distant location was the cause of the ban.

**Comment by REDESTOR** [comment]
no one can really know what is the real problem, at this time all is based on speculation, we all know is based on the speed, miles traveled, pokestops, pokemon captured , etc, but that were just soft measures for containing and making little bit harder to gain exp with bots but it is clearly not limited on that,  for now i stop all bots until we get a new version supporting captcha, i used to bot locally about 3 hours a day randomly on 4 different accounts with "safe" configs, some changing it every start, the ones that don't randomise configuration got banned in less than a week, other one, used to snipe got banned early in morning, there is one surviving, the one with more real playing and les bot usage, i based my pattern theory on that, i think they make an analysis of playing behavior watching for repeated patterns....we are in cleary disadvantage cause the more we use snipers, bots... more information they gather to use against us

**Comment by mo0ojava** [comment]
@zapahacks Interesting read, thanks. Which xposed-module did you use?

**Comment by smoothrunnings** [comment]
@zapahacks There is something new out called....get ready for it....here it comes....CAPTCHA. Would love to see a bot that can input the captcha code! ;)

It's time to see if Bluestacks and FakeGPS  has improve their system to bypass any of the security of Niantic.

**Comment by zapahacks** [comment]
@mo0ojava I use the xposed pokemon module, it was released 17/07, it has a forum in XDA, look for comment #1410 at the module forum. I hope that guy is right, and I hope the dev gives a new update on the module.
