### ISSUE TITLE
Possible to run this on linux?

### ISSUE THREAD

**Issue by VBQL** [NoxxDev/NecroBot#464]
As title, I might be really stupid, but I would like to see this running on a linux server, this could allow people to create Raspberry Pi Pokemon Go miners.

Not sure how would the .NET framework 4.6.2 be working though, so please give me any info you guys have.

Thanks!

**Comment by macio525** [comment]
for me max .net working version is 4.5

**Comment by VBQL** [comment]
So is 4.5 working? Or is there still any errors that would occur.

Also, how did you get the .NET 4.5 if you could please tell me.

Thanks!

**Comment by VBQL** [comment]
@macio525 So dotnet isn't running with correct files, how did you do it? I have an Ubuntu 16.04.1 server.

**Comment by melhioner** [comment]
try mono

**Comment by VBQL** [comment]
So this happened @melhioner :
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null'
andy@light:~/Release$ sudo mono NecroBot.exe

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null'
