### ISSUE TITLE
BOT NOT WORKING IN NEW UPDATE

### ISSUE THREAD

**Issue by ybanezmarjune** [NoxxDev/NecroBot#465]
NEW UPDATE HAS BEEN RELEASE. BOT IS NOT RUNNING.

PLEASE UPDATE. THNX

**Comment by Paraiso0319** [comment]
@ybanezmarjune Try Go Simulator using Nox/your Android Phone.

**Comment by LobsterX** [comment]
@ybanezmarjune weird. i'm still running the bot fine.

is the bot suppose to be not working now?

**Comment by LobsterX** [comment]
@ReZeroRem31991 cant find go similator. got to the site and there was an error

**Comment by ybanezmarjune** [comment]
@LobsterX i dont know. I think i got softban. Cant find any PokeStop and Pokemon.

**Comment by kalamera** [comment]
bot still works for me.

**Comment by mo0ojava** [comment]
Might take a while to get going - once they force 0.35:
http://pokemongohub.net/captcha-game-pokemon-go-bots-trackers/

**Comment by kalamera** [comment]
@mo0ojava depends what is the "abnormal player behaviour".
Also how the API will react if you just cancel the current session and open new one, like killing the pogo app and starting it again.

**Comment by smoothrunnings** [comment]
@mo0ojava 0.35.0 was released today. I have already been prompted with a captcha on my Pokemon Go on my device. So looks like they aren't wasting anytime.

**Comment by smoothrunnings** [comment]
@kalamera All Niantic has to do if they haven't already done so is request a captcha one when everyone logs into the system after they patched the server, this will mass ban all the farmers. :(

**Comment by MaartenDeen** [comment]
@ybanezmarjune happened to me too just a few minutes ago.

**Comment by kalamera** [comment]
@smoothrunnings i have no problem to login my bot accounts one by one on my phone ;)

**Comment by likeness123** [comment]
Release 9.0 is running okay. Not one softban here. Should I be worried?

**Comment by MaartenDeen** [comment]
Well, pokestops are back, probably just a glitch in Niantics servers

**Comment by ajns73** [comment]
iOS updated to 1.5 yestderday at 9pm (which I thought would include many of the securitiy features that have been discussed). Bot still good. No Captcha.

**Comment by SWALK25** [comment]
So what if we make the config as human like as possible, bot in the areas we actually live in (areas with most pokestops)? I realize that for some people who bot, they may live further out in rural areas, and don't really have access to many stops. I'm just curious. What exactly is happening with the captcha? Meaning if we bot in the areas we live in, and later on open the app, and get the captcha, what exactly is going on in the background?

**Comment by Skolzack** [comment]
@SWALK25 Doesn't matter where you bot, where you live, which bot you use, which configs you use. One day you will be banned until we discover which parameters they're using to ban us.

**Comment by ReZeroRem31991** [comment]
@LobsterX Try this link. http://bossapk.com/site_detail_apk.xhtml?cmid=47820163?get-title=app
Hope this helps. i have 3 account, 1 using Go Simulator, 1 Necrobot, and my Main account. Necrobot Account has been banned last Mondya. Created on Aug. 15. my Go Sim Bot is still active, Created Aug 15. guess we will have to wait for another Ban Wave just to see if my Go Sim bot will survive another week.
