### ISSUE TITLE
Error 0.9.4 crash

### ISSUE THREAD

**Issue by Lindgear** [NoxxDev/NecroBot#466]
Hi guys, 
the program has quietly worked in its previous version, but when I upgraded to the latest release It stopped working, crashes everytime

**Comment by kalamera** [comment]
@Lindgear just read the realease notes man.
you need to delete the config.json and reconfigure the bot manually.
the auto conversion seems to not work correctly

**Comment by Lindgear** [comment]
I tried but still no working...


Inviato da Libero Mail per iOS


mercoledì 24 agosto 2016, 09:56 +0200 da notifications@github.com  <notifications@github.com>:

**Comment by deframet** [comment]
Try to delete **ALL** the files in the directory and then unpack release.zip and reconfigure it

**Comment by lkhgamer** [comment]
before you make a topic, please search it here.
your problem already been discuss long time ago
https://github.com/NoxxDev/NecroBot/issues/433  << read this

**Comment by Lindgear** [comment]
Ok, later i try this solution
Just a thing you're italian?



Inviato da Libero Mail per iOS


mercoledì 24 agosto 2016, 10:37 +0200 da notifications@github.com  <notifications@github.com>:

**Comment by deframet** [comment]
yep

**Comment by Lindgear** [comment]
Ahhhh finalmente!
Questa versione mi sta dando sui nervi



Inviato da Libero Mail per iOS


mercoledì 24 agosto 2016, 11:29 +0200 da notifications@github.com  <notifications@github.com>:

**Comment by nscm123** [comment]
A me questa versione non funziona e non so nemmeno perché---

**Comment by deframet** [comment]
In English please....

**Comment by nscm123** [comment]
i have lot of problems with this version, i try so many solutions but anyone didn't work

**Comment by deframet** [comment]
Have u tried to delete config dir?
