### ISSUE TITLE
fix bot 

### ISSUE THREAD

**Issue by nlapenkopje** [NoxxDev/NecroBot#47]
Can you fix The bot give me this error. (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small? i have  no locatie chance or what ? what can i do now ?

**Comment by Vorakh** [comment]
you have a softban that disable pokestop, you only have to wait the unban

**Comment by albysprx** [comment]
or use a proxy

**Comment by nlapenkopje** [comment]
how make a proxy
