### ISSUE TITLE
Pokemon Go update... now has captcha. 

### ISSUE THREAD

**Issue by smoothrunnings** [NoxxDev/NecroBot#471]
Likely the Ninatic servers are starting to push captcha requests out now as I got prompted for a captcha when I lunched my Pokemon Go new install.

**Comment by likeness123** [comment]
Oh my so does this mean bots are useless?

**Comment by ajns73** [comment]
No captcha request at launch from iOS version updated to 1.5 at 9pm last night.

**Comment by SWALK25** [comment]
Makes me wonder if you use Hotspot Shield to mask you IP address, and make it seem like a different IP, male the config file as human like as possible, and bot in your local area where a lot of pokestops are, how that would work? What exactly is the captcha things trying to do? @smoothrunnings, did you get banned?

**Comment by MV1977** [comment]
Bot appears to be working (at least it was capturing pokemon), however I did get "softban's" on every pokestop, but could be due to using public wifi where possibly more people were using bots/PoGo
.

**Comment by SWALK25** [comment]
@MV1977, I think what I'm going to try and do is test out the bot with a new account, and if it seems to be working, use my normal account, bot as much as I possibly can, and keep updated on the issues, and stop soon, just to see if some other programmers are able to work around the captcha somehow.

**Comment by tws101** [comment]
***I cant load the bot today.

LOG
Initializing NecroBot logger at time 8/24/2016 10:02:22 AM...


The screen says you IP is XX.XX.XX.XX  and nothing happens.


I am assuming I was stalled for captcha.  Tried on new account.

**Comment by kalamera** [comment]
getting the Errors: "Current operation was canceled", but the bot reloads and continues.
still up and running...

**Comment by kalamera** [comment]
My phone is still running the old version of PoGo app without any issue btw...

**Comment by leaopedro** [comment]
I can't log in, getting the following error:

Initializing NecroBot logger at time 8/24/2016 12:13:56 PM...
[12:13:59] Downloading and apply Update...
[12:13:59] Your IP is:  ***
[12:14:00] Finished downloading newest Release...
[12:14:00] Logging in using Google
[12:14:00] You need to fill out GoogleUsername and GooglePassword in auth.json!

**Comment by kalamera** [comment]
@leaopedro I suppose you need to reconfigure your bot after the update...

**Comment by leaopedro** [comment]
@kalamera Actually i think a new version is coming.. lets wait

**Comment by febryanadip** [comment]
just edit in config.json "CheckForUpdates": false, "AutoUpdate": false,

**Comment by leaopedro** [comment]
@kalamera Nice, thx

**Comment by smoothrunnings** [comment]
@kalamera download the new version, 0.35.0 which is on the Play Store, not sure about Apples Store and give it a try. :)
