### ISSUE TITLE
Error When Log In

### ISSUE THREAD

**Issue by LeoRedin** [NoxxDev/NecroBot#475]
### Expected Behavior
Login Successful

### Actual Behavior
Says I need to put my google information on json
### Your config.json
{
  "AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": "leonardopokemonredin@gmail.com",
    "GooglePassword": "*********",
    "PtcUsername": null,
    "PtcPassword": null
  },
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePackageName": "galaxy6",
    "DeviceId": "349ece6299ef437f",
    "AndroidBoardName": "universal7420",
    "AndroidBootloader": "G920FXXU3DPEK",
    "DeviceBrand": "samsung",
    "DeviceModel": "zeroflte",
    "DeviceModelIdentifier": "SM-G920F",
    "DeviceModelBoot": "qcom",
    "HardwareManufacturer": "samsung",
    "HardwareModel": "samsungexynos7420",
    "FirmwareBrand": "zerofltexx",
    "FirmwareTags": "dev-keys",
    "FirmwareType": "user",
    "FirmwareFingerprint": "samsung/zerofltexx/zeroflte:6.0.1/MMB29K/G920FXXU3DPEK:user/release-keys"
  }
}

### Other Information
Version: tried on 0.9.4 and 0.9.3
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): can't login
I used the stock config options, and I tried downloading the bot again and starting from beggining but no success.

![sem titulo](https://cloud.githubusercontent.com/assets/20828515/17936157/40aff574-69f4-11e6-9c43-9c82eccfa9e5.png)
![sem titulo2](https://cloud.githubusercontent.com/assets/20828515/17936163/42079026-69f4-11e6-92b7-d896359b2461.png)

**Comment by Hypebeast97** [comment]
same issue help please!

**Comment by sink0005** [comment]
same issue here. i think they are updating the bot

**Comment by jcnlulu** [comment]
looks like 0.9.5 is coming :+1:

**Comment by leaopedro** [comment]
+1

**Comment by kalamera** [comment]
yeah, your bot has been updated to 0.9.5
you will need to reconfigure your bot again I suppose

**Comment by LeoRedin** [comment]
@kalamera yeah I tried that already, deleting the config and auth and doing all from beginning

**Comment by SWALK25** [comment]
I still use version 0.9.0, it still seems to be working perfectly fine. I made a new account (due to niantics newest update) to test out and see if I'll get banned or not. I use Hotspot Shield to mask my IP address (really it just uses a different IP). Try downloading 9.0 and before it updates when you type your info in for the first time, exit it, and open the config.json and edit it to not automatically update, or you'll get perma banned

**Comment by kalamera** [comment]
@LeoRedin that is sad... anyhow I do not see the release officially available, which is strange :)

**Comment by febryanadip** [comment]
@LeoRedin just edit config.json
    "CheckForUpdates": false,
    "AutoUpdate": false,

**Comment by albysprx** [comment]
I'm using 0.9.3 and it works well and @LeoRedin anyway it's better to hide your IP address

**Comment by Hypebeast97** [comment]
how to to hide IP.....do I need to download any shield protector?

**Comment by kalamera** [comment]
@LeoRedin btw is the "leonardopokemonredin@gmail.com" your real google account?
It would get probably banned soon I suppose as the Niantic ppl do watch this github for sure :)

**Comment by kalamera** [comment]
@Hypebeast97 just do not publish the screens with the IP address? :)

**Comment by Hypebeast97** [comment]
lmao

**Comment by LeoRedin** [comment]
@febryanadip That seemed to work now, I tried before bu onçy disabled check for update.

no real acc just some random one

**Comment by albysprx** [comment]
yes, I mean the IP in the screenshots, delete it and delete the email address from the first post, maybe niantic is watching this thread xD

**Comment by LeoRedin** [comment]
Thanks guys! The auto update disabled seem to resolved the issue. Will close and delete things ^^

**Comment by HarambesGhost** [comment]
its an issue with auto update, I edited the config.json 
"CheckForUpdates": true,
"AutoUpdate": false,
it will ask if you wish to update, hit "Y" and it works!

**Comment by albysprx** [comment]
anyway you can hide your ip from pokemon go too with proxies

**Comment by kalamera** [comment]
better to use some VPN service...

**Comment by Hypebeast97** [comment]
@albysprx do I need any need any apps for the proxy? or just do it at setting?

**Comment by albysprx** [comment]
@Hypebeast97 you can enable it from the auth.json but you need to found a working http proxy that is very hard (almost always already softbanned)
