### ISSUE TITLE
[Feature request] Captcha support

### ISSUE THREAD

**Issue by albysprx** [NoxxDev/NecroBot#476]
Niantic has recently added captchas,
Please add support for captchas, I mean just a popup (better with a sound) with the captcha that you can solve manually and continue botting

**Comment by tws101** [comment]
Yes, this would be great... POPUP, solve keep botting....

This way anyone can bot while on there PC doing other things, LIKE WORK.

**Comment by Hypebeast97** [comment]
Any recommend for the captcha support ...... Can send the link here please !

**Comment by ANR2ME** [comment]
i heard they're using google's reCaptcha

**Comment by Hypebeast97** [comment]
@ANR2ME I see...thanks dude !

**Comment by NoxxDev** [comment]
There is no need at the moment
