### ISSUE TITLE
"HumanWalkSnipeConfig"

### ISSUE THREAD

**Issue by karmablack** [NoxxDev/NecroBot#478]
Anyone can explane what is this string in 0.9.5 ? 
 
"HumanWalkSnipeConfig": {
    "DisplayPokemonList": false,
    "MaxDistance": 1472.5,
    "MaxEstimateTime": 864.5,
    "CatchEmAllMinBalls": 52,
    "TryCatchEmAll": false,
    "CatchPokemonWhileWalking": false,
    "SpinWhileWalking": false,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "Enable": false,
    "WalkbackDistanceLimit": 298.7,
    "IncludeDefaultLocation": false

Thanx

**Comment by sesey** [comment]
I am wondering too.

**Comment by iwean** [comment]
Check this out: https://github.com/NoxxDev/NecroBot/wiki/Human-walk-snipe-config

And this: #398

**Comment by kalamera** [comment]
Indeed... just read the release notes guys :)

**Comment by mcleodjr** [comment]
Hi, I have an issue that I can't change priority for pokemons in HumanWalkSnipeFilters. It changes back everytime, like I want to set Eevee to 2, and it changed back to 10 later even I saved.

**Comment by iwean** [comment]
@mcleodjr Same issue with me.... 

Try summon the dev @samuraitruong

**Comment by BoydTM** [comment]
Same in my case - HumanWalkSnipe values seems to be fixed so far...however - beautiful idea and implementation....every new feature need polishing...

**Comment by samuraitruong** [comment]
Dont know why. I will check it later

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Aug 25, 2016 at 3:34 AM +1000, "Iwan Novirion" <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcleodjr<https://github.com/mcleodjr> Same issue with me....

Try summon the dev @samuraitruong<https://github.com/samuraitruong>

**Comment by samuraitruong** [comment]
I open PR to fix this issue already. or you cant download my build at https://app.box.com/s/a01f30ljopaxeds77r5bp1noye6xozl1

**Comment by samuraitruong** [comment]
#501 will fix the issue

**Comment by NoxxDev** [comment]
Fix 7365d992aa8b2a81daf949684890930f96a6a33b
