### ISSUE TITLE
Adding POGO Protos, same with Rocket API as a project to the solution

### ISSUE THREAD

**Issue by Kermel** [NoxxDev/NecroBot#479]
@NoxxDev What about returning POGO Protos to the solution? THe referenced Nuget packages are not frequently updated and the original POGO Protos project is quite alive (lots of updates)
Same goes with the Rocket API - currently it is referenced here as a Subproject so we cannot see the changes made in it (or am I doing just something wrong?). The original Rocket API repository seems to be dead so we might just takeover the code and place it here normally as well

**Comment by Kermel** [comment]
(adding POGO Protos would only require to monitor their github build the c# libraries regularily and commit here)

**Comment by NoxxDev** [comment]
POGOProtos updated and in solution
36b53cd30d7c4f72ded839fa1f78b750df894158
5e240dcb239f684988902c8373ef07f99f8450ad
959b748bd51a5066b994806db992445760d12135
6c0802d66889ca270cbc27e17ec8982a42363279
9932f9334d37fbf32f53743e6d1497d89bf468f0
2d30a7fbb831079f8d5eee13d44dffc6e700ca08
