### ISSUE TITLE
Google Auth not working

### ISSUE THREAD

**Issue by thedamienmarsh** [NoxxDev/NecroBot#48]
Looks like you guys are working on something right now as my bot just tried to update to 0.8.9 but google login auth is not working, says please configure google credentials in auth.json and exits

Just an FYI, if you were unaware of the issue

**Comment by NoxxDev** [comment]
Reconfigure auth.json and config.json or delete auth.json and config.json, and rename auth.json.old and config.json.old to auth.json, config.json

**Comment by thedamienmarsh** [comment]
Nothing about these files has been changed though, do you still think this is what's going on?  The code is valid, I use sublime text for my editor as well.  It was working fine until I closed the bot and reopened about 30 minutes later, now neither account is working (4 bots, 4 seperate folders), no config changes to either folder.  Also verified accounts are still active.  I will rewrite the config file if that's the fix though.

**Comment by thedamienmarsh** [comment]
LOL, ok now when I reopen the original config (not .old) the values are all NULL and defaulted.  Weird
