### ISSUE TITLE
just a question (pokemon spawner)

### ISSUE THREAD

**Issue by zinba** [NoxxDev/NecroBot#482]
when 0.9.5 finds a pokemon spawner, any way to get him to sit there and catch the pokemon?
or is it considered snipping?

![sniper](https://cloud.githubusercontent.com/assets/21026674/17942427/4cf5a5ca-6a05-11e6-8271-0f62f80b8197.png)

**Comment by samuraitruong** [comment]
It is working mate, when you see that message, you trainer is on the way to catch him, you need to see the distance and time in that message, it walk for 669m to catch him.
