### ISSUE TITLE
Feature Request - Moves keep

### ISSUE THREAD

**Issue by f3l1p1nh07** [NoxxDev/NecroBot#483]
Could add the function to maintain the pokemon only if it has the moves and the minimum requirements?

Example:

    "Lapras": {
      "KeepMinCp": 5500,
      "KeepMinLvl" 20
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        [
          "FrostBreathFast"
          "Blizzard"
        ]
      ]
      "DeprecatedMoves": null,
      "KeepMinOperator": "or"
      "MovesOperator": "and"
    },

If my Lapras has minimum level 20 or IV higher than 80, with these movements, it is in my inventory. otherwise it transfers ... even if he has 2 moves but does not have the level or iv or CP ... not say CP because I am considering only the level and IV ... he be transferred ...
today the bot checks if they have the moves. and if it keeps even not having the IV / level / cp ... would have to create a new filter command KeepMinMoves "and" or "or"

if you set to and the pokemon have to cp / iv / level and moves the filter. if you set "or" if only moves the pokemon is in inventory, or tivers cp / iv / level also ...

**Comment by f3l1p1nh07** [comment]
up

**Comment by f3l1p1nh07** [comment]
up

**Comment by NoxxDev** [comment]
Added
