### ISSUE TITLE
sniping - no pokemon found to snipe

### ISSUE THREAD

**Issue by pokebug** [NoxxDev/NecroBot#486]
Since today morning i have the problem that 95% of sniping locations have nothing to snipe there. why ?
Even with the latest update and before with 9.0.4
Tha last days it worked fine.

**Comment by kalamera** [comment]
Well I suppose this is the problem of skiplagged not the bot itself.

**Comment by NoxxDev** [comment]
v0.9.4 is no longer supported, use version 0.9.7
