### ISSUE TITLE
Sniping problem

### ISSUE THREAD

**Issue by ZaineJJ** [NoxxDev/NecroBot#487]
i do have this problem sniping 
How do i fix this problem ? 
> 

> [03:14:00] (SNIPER) Sniper count 15
> [03:14:01] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:02] (SNIPER) (PokeSnipers.com) Sniping a Nidorina with Unknown IV at 47.621308,-122.352929...
> [03:14:03] (SNIPER) Sniper count 15
> [03:14:04] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:05] (SNIPER) (PokeSnipers.com) Sniping a Wartortle with Unknown IV at 41.374059,2.168856...
> [03:14:05] (SNIPER) Sniper count 15
> [03:14:07] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:08] (SNIPER) (PokeSnipers.com) Sniping a Wartortle with Unknown IV at 40.722925,-74.009584...
> [03:14:08] (SNIPER) Sniper count 15
> [03:14:08] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:09] (SNIPER) (PokeSnipers.com) Sniping a Golem with Unknown IV at -33.415414,-70.674144...
> [03:14:10] (SNIPER) Sniper count 15
> [03:14:11] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:12] (SNIPER) (PokeSnipers.com) Sniping a Ivysaur with Unknown IV at 28.66492,-81.382772...
> [03:14:12] (SNIPER) Sniper count 15
> [03:14:14] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:15] (SNIPER) (PokeSnipers.com) Sniping a Wartortle with Unknown IV at 59.349772,18.021928...
> [03:14:15] (SNIPER) Sniper count 15
> [03:14:16] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:17] (SNIPER) (PokeSnipers.com) Sniping a Onix with Unknown IV at 34.010309,-118.498211...
> [03:14:17] (SNIPER) Sniper count 15
> [03:14:18] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:19] (SNIPER) (PokeSnipers.com) Sniping a Kabuto with Unknown IV at 40.425785,-3.728395...
> [03:14:20] (SNIPER) Sniper count 15
> [03:14:20] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:21] (SNIPER) (PokeSnipers.com) Sniping a Tauros with Unknown IV at 40.737759,-73.975886...
> [03:14:22] (SNIPER) Sniper count 15
> [03:14:23] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:24] (SNIPER) (PokeSnipers.com) Sniping a Rhydon with Unknown IV at -33.421574,-70.611036...
> [03:14:24] (SNIPER) Sniper count 15
> [03:14:26] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:27] (SNIPER) (PokeSnipers.com) Sniping a Dratini with Unknown IV at 40.766249,-74.000403...
> [03:14:27] (SNIPER) Sniper count 15
> [03:14:28] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:29] (SNIPER) (PokeSnipers.com) Sniping a Dratini with Unknown IV at 48.85296,2.352223...
> [03:14:29] (SNIPER) Sniper count 15
> [03:14:30] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:31] (SNIPER) (PokeSnipers.com) Sniping a Magmar with Unknown IV at 18.465216,-66.093054...
> [03:14:31] (SNIPER) Sniper count 15
> [03:14:33] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:34] (SNIPER) (PokeSnipers.com) Sniping a Magmar with Unknown IV at 48.85802,2.362569...
> [03:14:34] (SNIPER) Sniper count 15
> [03:14:35] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:36] (SNIPER) (PokeSnipers.com) Sniping a Omanyte with Unknown IV at 52.195862,4.383011...
> [03:14:37] (SNIPER) Sniper count 15
> [03:14:37] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:38] (SNIPER) (PokeSnipers.com) Sniping a Onix with Unknown IV at -33.450637,-70.656858...
> [03:14:39] (SNIPER) Sniper count 15
> [03:14:40] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:41] (SNIPER) (PokeSnipers.com) Sniping a Kabuto with Unknown IV at 25.786686,-80.127461...
> [03:14:41] (SNIPER) Sniper count 15
> [03:14:42] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:43] (SNIPER) (PokeSnipers.com) Sniping a Machamp with Unknown IV at 40.737818,-73.98663...
> [03:14:43] (SNIPER) Sniper count 15
> [03:14:45] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:46] (SNIPER) (PokeSnipers.com) Sniping a Kabuto with Unknown IV at -23.534404,-46.634974...
> [03:14:46] (SNIPER) Sniper count 15
> [03:14:47] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:48] (SNIPER) (PokeSnipers.com) Sniping a Golem with Unknown IV at 48.860138,2.38964...
> [03:14:48] (SNIPER) Sniper count 15
> [03:14:50] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:51] (SNIPER) (PokeSnipers.com) Sniping a Tangela with Unknown IV at 18.450693,-66.084968...
> [03:14:51] (SNIPER) Sniper count 15
> [03:14:52] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:53] (SNIPER) (PokeSnipers.com) Sniping a Scyther with Unknown IV at -33.872467,151.225498...
> [03:14:53] (SNIPER) Sniper count 15
> [03:14:54] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:55] (SNIPER) (PokeSnipers.com) Sniping a Onix with Unknown IV at -33.468441,-70.660668...
> [03:14:56] (SNIPER) Sniper count 15
> [03:14:57] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:14:58] (SNIPER) (PokeSnipers.com) Sniping a Parasect with Unknown IV at 41.900654,12.466586...
> [03:14:58] (SNIPER) Sniper count 15
> [03:14:59] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:15:00] (SNIPER) (PokeSnipers.com) Sniping a Tauros with Unknown IV at 41.887103,-87.615359...
> [03:15:00] (SNIPER) Sniper count 15
> [03:15:01] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:15:02] (SNIPER) (PokeSnipers.com) Sniping a Omanyte with Unknown IV at -6.224966,106.797973...
> [03:15:03] (SNIPER) Sniper count 15
> [03:15:04] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:15:05] (SNIPER) (PokeSnipers.com) Sniping a Onix with Unknown IV at 40.705042,-74.018582...
> [03:15:05] (SNIPER) Sniper count 15
> [03:15:07] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:15:08] (SNIPER) (PokeSnipers.com) Sniping a Tentacruel with Unknown IV at 1.349941,103.829913...
> [03:15:08] (SNIPER) Sniper count 15
> [03:15:09] (SNIPER) Did not find a Pokemon within the Location, pokemon despawned?
> [03:15:10] (SNIPER) (PokeSnipers.com) Sniping a Dratini with Unknown IV at 37.787619,-122.387213...
> [03:15:10] (SNIPER) Sniper count 15

>

**Comment by pokebug** [comment]
same problem here
