### ISSUE TITLE
HumanWalkSnipeFilters reverting back to default

### ISSUE THREAD

**Issue by SweeperJS** [NoxxDev/NecroBot#488]
I put custom configurations here for pokemon I'm interested in and parameters I'm comfortable with however they revert back when the program is running. 

For example I'll change one to have the following settings

 "Gyarados": {
      "MaxDistance": 300.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
    }

afterwards it changes back to 

"Gyarados": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    }

I'm currently using version 0.9.5, I can upload my config upon request. 
Here is my HumanWalkSnipe config

 "HumanWalkSnipeConfig": {
    "DisplayPokemonList": true,
    "MaxDistance": 300.0,
    "MaxEstimateTime": 400.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": true,
    "SnipingScanOffset": 0.025,
    "Enable": true,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true
  },

Curious if theres something I'm doing wrong of if these parameters are just not meant to be changed.

**Comment by samuraitruong** [comment]
Sorry my mistake, i fix it already.

**Comment by SweeperJS** [comment]
awesome! does this mean I need to redownload the release or make a pull of the master for it to be working?

**Comment by NoxxDev** [comment]
Fix 0c63661077ca82707a13ae10a4d092b07ce8828c

**Comment by samuraitruong** [comment]
code was merged to master, you can pull from master @SweeperJS
