### ISSUE TITLE
Little mistype

### ISSUE THREAD

**Issue by iPollox** [NoxxDev/NecroBot#489]
(SNIPER) (HUMAN WALK) Found 2 pokemon matched with -> **you** <- filters. Human walking sniper won't catch em all. but try to maximun catch if possible.

Shouldn't it be **your** ? Sounds awkward to me.

**Comment by kalamera** [comment]
and what about the "maximun"? :)

**Comment by iPollox** [comment]
Should be: Found 2 pokemon matches with your filters. Human walking sniper won't catch em all, but try to catch as many as possible.
