### ISSUE TITLE
Catchflee

### ISSUE THREAD

**Issue by petpetpetvm** [NoxxDev/NecroBot#490]
I just want to know if you can bring back the catchflee count, (the old killswitch)
it's a lot better and safer this way too

**Comment by SmartHacker** [comment]
@petpetpetvm with the new bot settings you will never get catchflee ban. Besides, by the time you get catchflee ban, you have already been flagged and will be permanent banned soon anyway. Even killswitch will not save your account. So I don't know what you mean by "a lot better and safer"

**Comment by petpetpetvm** [comment]
i'm sorry it's depend on the way of thinking, because my bots keeps switching, and it's take about 15hrs to get back to the first account (so it's hard to track all the accounts), even that you got flagged, but it still a flag, too much flee with flagged -> it's the bot obviously, even with flagged but you stop catching on time, it's still better this  way :)
Flagged : still have a chance because it's not even banned yet, you can't think it's flagged, so it's gonna get banned -> who cares about this acc anymore lol :)
Thanks

**Comment by NoxxDev** [comment]
Added v0.9.7
