### ISSUE TITLE
Snipe Problem

### ISSUE THREAD

**Issue by mkcs121** [NoxxDev/NecroBot#491]
The version 0.9.5 still snipes the pokemon which I have already deleted in the config file. I did not intend to snipe Electabuzz.

[03:26:11] PokeSnipers.com Sniping a Electabuzz with Unknown IV at 51.048939,-114.073308...

**Comment by hardknoxni69a** [comment]
I would recommend double checking you config and turn snipe to false

**Comment by MaartenDeen** [comment]
Which setting is that?

**Comment by mkcs121** [comment]
Obviously I didn't add Electabuzz for sniping but it still snipes from somewhere far away:

  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "ninetales",
      "vileplume",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "slowbro",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ],
  "HumanWalkSnipeFilters": {
    "Magikarp": {
      "MaxDistance": 300.0,
      "Priority": 10,
      "MaxWalkTimes": 200.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
    },
    "Eevee": {
      "MaxDistance": 500.0,
      "Priority": 10,
      "MaxWalkTimes": 200.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
    },
    "Electabuzz": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 600.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
    },
    "Dragonite": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Dragonair": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Dratini": {
      "MaxDistance": 2000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Charizard": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Snorlax": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Lapras": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Exeggutor": {
      "MaxDistance": 1500.0,
      "Priority": 1,
      "MaxWalkTimes": 600.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true
    },
    "Vaporeon": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Flareon": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Scyther": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Beedrill": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Chansey": {
      "MaxDistance": 1000.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Clefable": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    },
    "Golbat": {
      "MaxDistance": 500.0,
      "Priority": 6,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
    },
    "Jynx": {
      "MaxDistance": 1200.0,
      "Priority": 4,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
    },
    "Kangaskhan": {
      "MaxDistance": 800.0,
      "Priority": 4,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
    },
    "Gyarados": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false
    }
  }
}

**Comment by kalamera** [comment]
I suppose the filter does apply when the bot is actually going to snipe the pokemon.
the message just says it got the info from PokeSnipers.com
it did not actually snipe the pokemon.

**Comment by mkcs121** [comment]
No, if it didn't snipe the pokemon, it would mention not user selected pokemon. But the status said "Snipe! Let's go!". Then it sniped at the coordinates and caught it.

[03:26:11] PokeSnipers.com Sniping a Electabuzz with Unknown IV at 51.048939,-114.073308...

**Comment by VBQL** [comment]
Um, have you tried restarting the bot...? That actually solved one of my problems.

**Comment by mkcs121** [comment]
The problem still exists in v0.9.6, restarting the bot doesn't help. It does not snipe according to what you want to snipe in the list

**Comment by iwean** [comment]
@mkcs121 Try place it on PokemonsToIgnore setting
