### ISSUE TITLE
NecroBot wanders off into the wilderness

### ISSUE THREAD

**Issue by MaartenDeen** [NoxxDev/NecroBot#492]
When I start NecroBot and use the visualiser to see what is going on, a lot of pokestops near where you start are loaded. But after a while Necrobot starts wandering off into the wilderness and does not load new pokestops where it is walking.
See image:
![nopokestops](https://cloud.githubusercontent.com/assets/1825970/17945800/aae84c7e-6a45-11e6-9982-d4ea116040d3.png)

5 minutes after I posted this, pokestops appeard. I think something goes wrong with the scheduled interval and "SNIPPING"? (I assume sniping?) These is my last log entries:
`[22:04:21] (CatchSuccess) | (Normal) Psyduck Lvl: 14 CP: (367/443) IV: 20.00% | Chance: 40.01% | 65.48m dist | with a PokeBall (0 left). | 120 EXP earned | Candies: 236 | lat: 52.362071 long: 4.904564`
`[22:04:24.135] Looking for incense Pokemon...`
`[22:04:24.410] Looking for Pokemon...`
`[22:04:24.549] Looking for incense Pokemon...`
`[22:04:26.106] Looking for Pokemon...`
`[22:04:26.279] Looking for incense Pokemon...`
`[22:04:27] Name: Koninklijk Theater CarrÃ© XP: 50, Gems: 0, Items: 1 x ItemPotion, 3 x ItemPokeBall, Lat: 52.362273, Long: 4.903828`
`[22:04:30] (HUMAN WALK) Found 42 pokemon matched with you filters. Human walking sniper won't catch em all. but try to maximun catch if possible.`
`[22:04:30]           |  Name                     |  Distance     |  Expires        |  Travel times   | Catchable`
`[22:04:30] SNIPPING  |  Magikarp              |  568.19m  	|  03 min 56 sec  |  03 min 28 sec  | Possible`
`[22:04:30] SNIPPING  |  Magikarp              |  623.62m  	|  06 min 31 sec  |  04 min 45 sec  | Possible`
`[22:04:30] SNIPPING  |  Magikarp              |  819.47m  	|  06 min 54 sec  |  05 min 47 sec  | Possible`
`[22:04:30] SNIPPING  |  Magikarp              |  1005.77m  	|  09 min 11 sec  |  06 min 45 sec  | Possible`
`[22:04:30] SNIPPING  |  Magikarp              |  1250.08m  	|  08 min 07 sec  |  07 min 01 sec  | Possible`
`[22:04:30] SNIPPING  |  Dratini               |  1929.68m  	|  10 min 57 sec  |  11 min 34 sec  | Possible`
`[22:04:30] (HUMAN WALK) Found Dratini spawning | lat: 52.3606036839453, lng: 4.875566809432, dist 1929.68m , expired in 11 min 58 sec | Walk time est : 10 min 34 sec | Spin: No | Catch : No`
`[22:04:30] Traveling to Pokestop: Koninklijk Theater CarrÃ© (2406m) (418 seconds) (route GoogleWalk)`
`[22:08:04]  ##### config.json ##### `

Why is it walking 2406 meters for the next pokestop? That's crazy.
Can I turn sniping off? I have not changed any of the sniping entries in the config file.

Next pokestop also 1537m while there are dozens of pokestops nearby.

**Comment by hardknoxni69a** [comment]
Shorten your max walking distance so it stays within your specified circle

**Comment by Kermel** [comment]
Are you using the google walk ? Check the last known location and the target location and then let maps.google.com to draw the walking path between those two locations. Isn't that too far on foot ? (it may be the source of the problem)

**Comment by NoxxDev** [comment]
By log, HumanWalkSnipeTask was capturing the Pokémon found

**Comment by MaartenDeen** [comment]
But I find it a bit odd that you go walking for 2500m, don't load pokestops and also don't stop at pokestops. That is not human behaviour.
Anyway, I have effectively turned sniping off by setting "CatchEmAllMinBalls": 250, as there does not seem to be a global off switch for sniping.

**Comment by samuraitruong** [comment]
"Enable" :false. that will completely turn that off

**Comment by masterpowers** [comment]
im using it on 1000 meter radius max distance for human sniping is 900 meters max radius...
that shoud make wandering too far away fix, also remove unnecesassry pokemon like zapdos, moltres mew etc. that is not present in the game... 
it will decrease fake feeds of pokemon to catch...

**Comment by samuraitruong** [comment]
Update your config plz

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Aug 25, 2016 at 4:48 PM +1000, "masterpowers" <notifications@github.com<mailto:notifications@github.com>> wrote:


im using it on 1000 meter radius max distance for human sniping is 900 meters max radius...
that shoud make wandering too far away fix, also remove unnecesassry pokemon like zapdos, moltres mew etc. that is not present in the game...
it will decrease fake feeds of pokemon to catch...
