### ISSUE TITLE
MinPokeballsToSnipe is not used

### ISSUE THREAD

**Issue by MaartenDeen** [NoxxDev/NecroBot#496]
You can set MinPokeballsToSnipe to any value you like (default is 20), it will always use the value of 50.
In the log files:
`[22:26:49] Not enough Pokeballs to start sniping! (38/50)`

**Comment by pokebug** [comment]
the 50 limit is set in "HumanWalkSnipeConfig" , the 20 is in the general sniping settings...

**Comment by MaartenDeen** [comment]
Is that "CatchEmAllMinBalls"?

**Comment by samuraitruong** [comment]
CatchEmAllMinBalls default is 50 , I may need change the message to separate logic with normal snipe

**Comment by NoxxDev** [comment]
Are separate configurations
please close this issues after solution
