### ISSUE TITLE
how can i change to keep the pokemon with more iv then others?

### ISSUE THREAD

**Issue by denniskoenn** [NoxxDev/NecroBot#498]
question is in the topic
i want to keep the pokemons with the more iv not cp

**Comment by kalamera** [comment]
really?
did you even went throught the wiki?

> PrioritizeIVOverCP (Value)
> 
> When PrioritizeIVOverCP is set to true, the bot will sort by IV instead of CP when deciding which Pokemon to transfer out of a group of duplicate Pokemon. By default, the bot sorts by CP.

**Comment by denniskoenn** [comment]
thx
