### ISSUE TITLE
How to avoid permaban??

### ISSUE THREAD

**Issue by mewtowman** [NoxxDev/NecroBot#500]
How to avoid permaban???

**Comment by darkuru** [comment]
for now? Play the legit way. No matter how much you try your best, atm Niantic knows.

**Comment by petpetpetvm** [comment]
bot like 100+ account with different IPs, pick craziest config => stop around 24, hopefully u got about 3/4 no ban ;)

**Comment by NoxxDev** [comment]
Please, this not a Forum
