### ISSUE TITLE
Config resetting

### ISSUE THREAD

**Issue by RainbowandProud201** [NoxxDev/NecroBot#505]
Basically every time I try to save a config I have changed it gets reset when I open necrobot. What am I doing wrong? How do I stop this from happening?

**Comment by zapahacks** [comment]
Could you please check sth? is it all the config resetting or just the part of "HumanWalkSnipeFilters"?

**Comment by RainbowandProud201** [comment]
Its just HumanWalkSnipeFilters

**Comment by zapahacks** [comment]
Thanks, it is an issue with the latest version, I suggest to turn off the feature until it is fixed, search for  "HumanWalkSnipeConfig": / "Enable": false.

**Comment by samuraitruong** [comment]
#501  fixed this issue
