### ISSUE TITLE
Zapdos!?

### ISSUE THREAD

**Issue by Jabark** [NoxxDev/NecroBot#507]
Don't know if this is an issue or not, but wtf!? I'm hoping you're going to tell me that there's no chance in hell it's a bug.

![is this possible](https://cloud.githubusercontent.com/assets/9607853/17952608/1e6d046e-6a64-11e6-8597-82b4a8a3fb31.PNG)

Tried to go there manually in game, couldn't see it :/

**Comment by RainbowandProud201** [comment]
I also saw a Moltres ealier

**Comment by iPollox** [comment]
Thats weird, I opened all my logs and searched for all legendaries names and not found at all.

**Comment by Jabark** [comment]
Out of interest, that spot is within viewing distance of the famous "6 pokestops" on memorial way, or whatever its called, in the US. Perhaps someone else was around there at that point.

**Comment by Jabark** [comment]
Perhaps the spawn was correct, and my measly level 21 was unable to see it...

**Comment by zapahacks** [comment]
Are you using a free VPN app?

**Comment by Jabark** [comment]
@Zapahacks nope, why?

**Comment by zapahacks** [comment]
@jabark because when I use free VPN services the humansnipping info/pokemons I get are fake. Bot goes there but there is nothing, the same happens id I search on o map, I will get a big Skipplaged banner made of zapdos, articunos or any rare pokemon. They do not exist though.

**Comment by masterpowers** [comment]
just remove it on the pokemon array . those pokemon to snipe, its already confirmed that those poekemon are not avaiable so why snipe? or human snipe them?

**Comment by VBQL** [comment]
Everyone disable Skippflagged, someone might be trolling, this should fix it.

**Comment by samuraitruong** [comment]
yes, will turn of skippflagged or add config to turn it off. update tonight guys

**Comment by samuraitruong** [comment]
#530 now has config to turn skipflagged

**Comment by NoxxDev** [comment]
Fix #530
