### ISSUE TITLE
[Suggest] Regenerate new device id without delete auth.json for decreasing ban risk.

### ISSUE THREAD

**Issue by null32sys** [NoxxDev/NecroBot#508]
Dear NecroBot Team,

I would like to suggest for the next release, that would great if the bot always regenerate new device id by itself, such as the concept below:

 Check Bot version --> Regenerate New Device ID --> Logging in using ptc/google --- > and etc ...

I hope this feature would be decreasing ban risk for the next release.

Thank's for your attention and support.

**Comment by zapahacks** [comment]
I think this is not human like no?. Most of the people usually play in the same device, so changing devices everytime you log in would be suspicious. Correct me if I am wrong. Actually, the most human like would be using your real device id, then using it for real (not botting) in your phone, with both devices ids (bot and phone) matching.

**Comment by helpmeplease1** [comment]
If you always change your device will lead you to the road of ban. A normal ppl how to have more then 4 device to play a same account.
