### ISSUE TITLE
[Critical and fixable bug in 0.9.5] with "HumanWalkSnipeFilters" config

### ISSUE THREAD

**Issue by zapahacks** [NoxxDev/NecroBot#509]
Basically, everytime you run the app the config info related to "HumanWalkSnipeFilters" is resetted. So you will be snipping Golbats :) :) :)

You change the config, then open again the app, and back to stock.

I do not know how to properly report the bug/fix request but I guess someone who knows will read this, reproduce it for itself and post the issue in the proper site ;)

PD: I suggest botting with "HumanWalkSnipeConfig": {
    "Enable": FALSE until it is fixed

**Comment by marcksz** [comment]
This really impossible to remove a pokemon list :fearful:

**Comment by vaca1** [comment]
seems HumanWalkSnipeConfig.Enable: True and UseGPXpathing: true
it has high probability crashing and restart necrobot
and cause a softban

**Comment by samuraitruong** [comment]
the code fix already, you need pull lastest from master

**Comment by samuraitruong** [comment]
I will also update code to not snipe if use GPX later tonight

**Comment by minitotoro** [comment]
The below code is the solution to solve this issue.

In GlobalSettings.cs
-        public Dictionary<PokemonId, HumanWalkSnipeFilter> HumanWalkSnipeFilters => HumanWalkSnipeFilter.Default();
+        public Dictionary<PokemonId, HumanWalkSnipeFilter> HumanWalkSnipeFilters = HumanWalkSnipeFilter.Default();

**Comment by samuraitruong** [comment]
the code has been fix in master already @minitotoro

**Comment by BoydTM** [comment]
Thank you samuraitruong, is there any guide regarding how to compile updated source ?

**Comment by samuraitruong** [comment]
do you have visual studio. I may write a build script at weekend for those guys doesn't has visual studio.

**Comment by BoydTM** [comment]
I would appreciate this, but it will be waste of your time for only 1 person. However sometimes there days between the new builds and there may be a lot of people who would benefit from this kind of guide and possibility to be up to date ...

**Comment by samuraitruong** [comment]
just few line of scripts :)

**Comment by BoydTM** [comment]
thanks in advance...

**Comment by samuraitruong** [comment]
#530

**Comment by NoxxDev** [comment]
Fix #530
