### ISSUE TITLE
[Issue with VPN free services] Be carefull when using free VPN services with the bot and with your real phone

### ISSUE THREAD

**Issue by zapahacks** [NoxxDev/NecroBot#510]
So basically I recently found that when using most of the free VPN services you will get any of this 2 errors:

1- On the bot version 0.9.5, if you have the new humanwalkingsnipping feature enable you will get the SKIPPLAGGED info, so you will see 80 lapras, or 80 moltres, or 80 zapdos and the bot will actually go to the location but wont find anything to catch

2- On the real app in the phone, if you are using most of the free public VNP services, you will get and error saying "Our servers are humbled bla bla try again later", this does not mean you are ban, it means you can not connect with your current free VPN IP

Both issues are fixed when using a paid (not widely used) VPN service.

If someone could replicate this and report it would be nice :+1:

**Comment by CreativiTimothy** [comment]
Yeah, if you want to use multiple accounts, you must use VPN IPs that aren't popularly used

**Comment by ANR2ME** [comment]
Because too many people might be using the same free VPN and getting the same IP to play pogo
