### ISSUE TITLE
Suggestion: Station Pokemon at gyms if slot is available

### ISSUE THREAD

**Issue by CreativiTimothy** [NoxxDev/NecroBot#511]
This is a feature in PokeRoadie that I would love to see in Necrobot. Basically, this is how the feature should work if implemented:

It won't actually fight/train the gym (of your color) but just leave a Pokemon there if there is a slot open. I think it would be difficult to code attacking/training a gym, so maybe just deploy if there is a slot open.

VisitGyms: true/false
StationPokemonAtGym: true/false
StationMaxCP: 0-5000
StationMinCP: 0-5000
GymPokemonFilter: {
  [
   Pokemon: "Dragonite"
   StationAboveCP: 10-3500
   Moves:[]
   MovesOperator: and/or
}
PokemonNotToStation: {}

I just made that up ^ but you get the point

**Comment by NoxxDev** [comment]
Will not be implemented anything related to gym
