### ISSUE TITLE
(ERROR) Niantic Servers unstable, throttling API Calls.

### ISSUE THREAD

**Issue by evetaku** [NoxxDev/NecroBot#513]
what happen with (ERROR) Niantic Servers unstable, throttling API Calls. ?
some thime shown (ERROR) Niantic Servers unstable, throttling API Calls.

**Comment by VBQL** [comment]
It's fine, please just ignore it.

**Comment by xhaoran06** [comment]
Those throttling, I think was one of the reason 1 of my accounts got banned. Multiple prompts of API calls, login/logout simultaneously.

**Comment by VBQL** [comment]
Hmm, I have gotten those and yet never got banned. Maybe I am just lucky then.

**Comment by minitotoro** [comment]
Hi VBQL, would you share your lucky script  :-)

**Comment by Usernameused** [comment]
3 days ago I had this error and I have been banned instantly...

**Comment by LarryM111** [comment]
@VBQL  what do you mean by it's fine? Because I have the same error and I am unable to bot. It just keeps repeating and does not function. Does it have something to do with the script?

**Comment by VBQL** [comment]
@LarryM111 You may have an unstable internet connection, I would also suggest you to set your bot cords close to your own IP, this could prevent possible bans when Niantic verifies your location. I have not seen any more of those in the newest version of NecroBot.
