### ISSUE TITLE
095 remove KillSwitch Function

### ISSUE THREAD

**Issue by god0911** [NoxxDev/NecroBot#514]
Can find killSwitch function.
How can I do if I want to stop after catching 50 pokemons?

**Comment by erickerich** [comment]
0.9.5 use new Setting. it counts by day not hours anymore

**Comment by god0911** [comment]
Could u explain which argument to set it? tks

**Comment by ValorRed** [comment]
"PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1998,
    "PokeStopLimitMinutes": 1470
  },
  "PokemonConfig": {
    "UseCatchLimit": true,
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,
 ....

**Comment by babros** [comment]
"PokeStopLimit": 1998, <<< **24h/1998 MAX?**
"PokeStopLimitMinutes": 1470 <<<< **This? what is this?**

**Comment by AngusGunn** [comment]
1998 per 1470 minutes.
