### ISSUE TITLE
0.9.5. Use GPX, not walking

### ISSUE THREAD

**Issue by ValorRed** [NoxxDev/NecroBot#515]
Sorry, the phenomenon is different: 
1. When using GPX + GoogleWalk + disableHumanWalk: The player follow the path of GPX, but teleport - which I think now, it is expected.
2. When using GPX + GoogleWalk + enableHumanWalk: The player do not follow the path of GPX, it is walking, but not really follow the road.
3. When using GPX + enableHumanWalk, GoogleWalk disabled, begin walking, but not following the path of GPX, go quite wild. Also, like 0.9.4, it does not seem to spin the pokestop in right place, sometime it walked pass the pokestop for a distance, then it got spinned. 
<BR>
4. When not using GPX, enableHumanWalk + GoogleWalk, walk follow the road, but:
  1) miss some pokestops
  2) walking in a quite inefficient path, back and forth, 
  3) For spining a pokestop, it still walk up to the exact point, that's unhuman.

**Comment by NoxxDev** [comment]
Check v0.9.7 to fix
