### ISSUE TITLE
PokeStop does not give the 50 exp. per use. (Don't know if i'm the only one.)

### ISSUE THREAD

**Issue by ReZeroRem31991** [NoxxDev/NecroBot#519]
Like the Title says : PokeStop does not give the 50 exp. per use. (Don't know if i'm the only one.)

**Comment by samuraitruong** [comment]
sometime is 100, 150 , depend on award you got

**Comment by tanjj92** [comment]
Did you mean you get no exp at all?

**Comment by parnpahn** [comment]
caught your screen

**Comment by ReZeroRem31991** [comment]
@tanjj92  Yep, No Exp at all. unlike when i play it using mobile, i always get 50 exp per PokeStop.
anyone encountered this?

**Comment by samuraitruong** [comment]
You are being softban

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Aug 26, 2016 at 3:58 PM +1000, "Rem" <notifications@github.com<mailto:notifications@github.com>> wrote:


@tanjj92<https://github.com/tanjj92> Yep, No Exp at all. unlike when i play it using mobile, i always get 50 exp per PokeStop.
anyone encountered this?
