### ISSUE TITLE
pokestop / pokemon

### ISSUE THREAD

**Issue by Sztynks** [NoxxDev/NecroBot#52]
My bot is catching pokemons but not using pokestops

**Comment by PoppaCoder** [comment]
I'd try with a fresh bot and a new IP. The last release is working for me. Try staying at less than 5km/h.
Question for you though. Do you HAVE to get on the App to get the bot set up with it nickname and everything before using a bot? The one time I tried an account at level 0 (never logged on the app) the bot would get stuck.
