### ISSUE TITLE
using YOURS walking only encountered softban

### ISSUE THREAD

**Issue by popsoda27** [NoxxDev/NecroBot#522]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
spinning pokestops and catching as per normal. setting the walking speed at 9km/h is more than reasonable for biking. In reality, bikes can travel thru alleyways or pedestrian walkways not shown on maps, in fact on the same elevation, any place reachable by foot you can reach by bike

### Actual Behavior
catching as per normal while travelling. skipping certain pokestops as if non-reachable (just off the main roads)? after 3mins encountered softban

### Your config.json
```
"LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 1.375019,
    "DefaultLongitude": 103.896644,
    "WalkingSpeedInKilometerPerHour": 9.0,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 2.0,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1500
  },

"YoursWalkConfig": {
    "UseYoursWalk": true,
    "YoursWalkHeuristic": "bicycle"
  },
```

### Steps to Reproduce
only use YOURS walk. Google walk disabled. set walk speed to any speed you think is reasonable for being on a bicycle

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by bbaronSVK** [comment]
i have same problem, after turn off YOURS walk is all working

**Comment by NoxxDev** [comment]
Check version v0.9.6 or upper
