### ISSUE TITLE
catch : yes

### ISSUE THREAD

**Issue by poloce** [NoxxDev/NecroBot#525]
I see wordings below during snipe, but even ehen it says catch : Yes. No Pokemon was caught.

What exactly does catch : yes and catch : no means ??!!

spawning | lat: 25.141118853701, lng: 121.505232548718, dist 211.23m , expired in 07 min 26 sec | Walk time est : 03 min 32 sec | Spin: Yes | Catch : Yes

### Other Information
Version: 0.9.5
Windows Version: 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by babros** [comment]
I think show:
    "CatchPokemonWhileWalking": false,

or, filter:
    "Gyarados": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      **"CatchPokemonWhileWalking": false,**
      "SpinPokestopWhileWalking": false
    }

**Comment by poloce** [comment]
do you mean I have to set those to true?

**Comment by babros** [comment]
I think filter bugged. I started bot, after clear my filters, make default filters... I think better 0.9.4, and wait for update.

**Comment by samuraitruong** [comment]
that been fixed #501

**Comment by poloce** [comment]
@samuraitruong  can you shine some light on what does "Spin: Yes | Catch : Yes" means?  I am seeing it all the time but but nothing was caught.

**Comment by samuraitruong** [comment]
that just the info to tell you what trainer is on the way to catch pokemon, and the config of current walking is 
spin - yes: will spin all the pokestop if it close to him on the way
catch : yes -> will catch all pokemon he encounter on the way

regardless your setup in global and filter, if there not enough time which is calculate by my generic rules in code, that both option will be set to false to make sure we don't miss the pokemon we want. (need time to make the code estimate more accuracy)  cc- @poloce 

#530  also add some fix

**Comment by poloce** [comment]
@samuraitruong I seem so if it shows I walk there, but never encounter the pokemon that was suppose to snipe, was that because just simply missed it?  Like too low of level to encounter it?

**Comment by iwean** [comment]
| Spin: Yes | Catch : Yes .....make more time to get to spawn pokemon location if the distance is far away.

Better set to false on the setting where the distance is far... like more than 1000. But if below 500, set it to true.
