### ISSUE TITLE
PokemonsTransferFilter -> KeepMinDuplicatePokemon NOT WORK with v0.9.5

### ISSUE THREAD

**Issue by tinkytonky** [NoxxDev/NecroBot#526]
"PokemonsTransferFilter": {
    "Pidgey": {
      "KeepMinCp": 10,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 1.0,
      "KeepMinDuplicatePokemon": 50, <----------- Does't work. I have over 100 Pidgey and Necrobot dose't transfer Pidgeys.
      "Moves": [],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },

(Pidgey don't set to my PokemonsNotToTransfer list.)

**Comment by babros** [comment]
"KeepMinOperator": "or" --> "KeepMinOperator": "and"

**Comment by popsoda27** [comment]
check if KeepPokemonsThatCanEvolve is set to false

**Comment by xhaoran06** [comment]
Rather, don't include the Pidgey in PokemonTransferFilter man. And putting 50 on "KeepMinDuplicatePokemon" will surely not transfer your pidgeys and will exceed 50 coz of "KeepMinCp": 10, all pidgeys with min of 10cp will be kept and not be transferred at all.

**Comment by tinkytonky** [comment]
@babros 

"KeepMinOperator": "and" don't work

**Comment by NoxxDev** [comment]
Check version 0.9.7
