### ISSUE TITLE
Recycling not working, short on pokeballs

### ISSUE THREAD

**Issue by pokebot0987** [NoxxDev/NecroBot#527]
Anyone encountering this? what config should i use to stock up on pokeballs?

  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "DelayBetweenRecycleActions": false,
    "TotalAmountOfPokeballsToKeep": 320,
    "TotalAmountOfPotionsToKeep": 10,
    "TotalAmountOfRevivesToKeep": 10,
    "TotalAmountOfBerriesToKeep": 10

it doesnt keep 10 potions/revives/berries.. i logged on to my phone and threw all away.

**Comment by deframet** [comment]
It recycles when the inventory is used at __90%__

**Comment by pokebot0987** [comment]
so what should i do to stock up on pokeballs... im always having: 
(PKMN) No Pokeballs - We missed a Tentacool with CP 406

**Comment by deframet** [comment]
Don't snipe too often. Let the bot go around spinning pokestops once a while.

**Comment by popsoda27** [comment]
@pokebot0987 set your RecycleInventoryAtUsagePercentage value lower, like 50%, so the bot starts recycling more often

**Comment by pokebot0987** [comment]
ok i set it to 10% but how do i get to spin more pokestops more often?

**Comment by popsoda27** [comment]
@pokebot0987 be in a place with more pokestops? since each pokestop has a spin timer, that is out of our control.

**Comment by pokebot0987** [comment]
hmm actually i have been using necrobot since 0.8x and i have never had this pokeballs problem. so im baffled by this.

**Comment by popsoda27** [comment]
probably run it for awhile with the amended config, u will see some improvement
