### ISSUE TITLE
What is 86araTM4z9VzLMZZ.dll?

### ISSUE THREAD

**Issue by cabrerovera** [NoxxDev/NecroBot#53]
This is extremely suspicious, NoxxDev.

**Comment by PoppaCoder** [comment]
It's suspicious, yes, I'd actually have to ask NoxxDev what it is but it's not making any connections it shouldnt't be making.
![untitled](https://cloud.githubusercontent.com/assets/21015631/17678029/14630e0c-62fb-11e6-974a-5817b23b489c.png)

**Comment by NoxxDev** [comment]
Read more

http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/572524-necrobot-fork-updated-post3555462.html#post3555462

**Comment by PoppaCoder** [comment]
They talk about you using your own encrypt but when I look at the master or the release I can't find such .dll =.='

**Comment by cabrerovera** [comment]
Fixed in 0.9.0, cheers.
