### ISSUE TITLE
Last Position (ini) missing

### ISSUE THREAD

**Issue by ihka** [NoxxDev/NecroBot#534]
### Expected Behavior
LastPosition.ini will be created and used

### Actual Behavior
LastPosition.ini is missing / not created
and not used by restarting

**Comment by NoxxDev** [comment]
LastPos.ini is created when the bot closes

**Comment by grinmind** [comment]
so it does not create the LastPos.ini when restart?

**Comment by ihka** [comment]
That is new :(
In Versions bevore the Position was updated often.

Actually i will never have one beacause 
i kill the bot out of an batch file...

Damn i was so happy to read that the last position will be used by start and now i would never get one....

**Comment by vfuyong** [comment]
LastPos.ini should be updated every time there is a change. If the program crashes, it may not get updated correctly.
