### ISSUE TITLE
Please fix Google walk related to pokestop

### ISSUE THREAD

**Issue by ValorRed** [NoxxDev/NecroBot#536]
Can the logic be:
1. fine, it selects a pokestop to walk to 
2. During the walk, for every step it moved, if it pass another pokestop that can spin, spin it
3. When getting to the target end point on the Google route closes to the target pokestop, don't start walk to the exact point of pokestop, first check if it gets close enough to spin, if yes, spin it and move to next one; if not, move closer to the pokestop straight line, but also check for every step, if it is close enough.

DO NOT walk to the exact pokestop point. That's non human, and waste of time.

Thanks

**Comment by NoxxDev** [comment]
Fixed
