### ISSUE TITLE
[HowTo] Evolve to 2nd AND 3rd level

### ISSUE THREAD

**Issue by Trickass** [NoxxDev/NecroBot#539]
Can anyone help me with settings to get all pokemon by evolving?
For example, when setting Pidgey AND Pidgeotto to evolve, you'll never get a Pidgeot.
Getting a Pidgeot could be done by removing Pidgey from the evolve list, but then you'd never get a Pidgeotto in the first place...
Really can't see how to fix it :/

Thanks!

**Comment by wilsondgonzales** [comment]
"KeepMinDuplicatePokemon": 1, should allow you to keep 1 of each. But if you have pidgey on your evolve list, most likely the bot will run out of candy to evolve pidgeotto into pigeot. I can only see a solution by manually evolving pigeot before your candy runs out from evolution

**Comment by xhaoran06** [comment]
Meh, better not evolve it into Pidgeot anyways, since it uses too much candy, although it gives same exp most of the time.

**Comment by Trickass** [comment]
The Pidgey evolution was just an example of course.
Same would apply for all other 3-level pokemon...
Fact remains that it seems impossible to automate this kind of "double" evolution.

**Comment by kirito-su** [comment]
I 'think' evolution order matters based on your list

**Comment by Trickass** [comment]
It might, but wouldnt matter in this case. You'd never get to enough candy to evolve to the third one. (Pidgeot in the example)
