### ISSUE TITLE
RenameOnlyAboveIv

### ISSUE THREAD

**Issue by mkcs121** [NoxxDev/NecroBot#547]
Rename of IV100% pokemondoesn't work even though RenameOnlyAboveIv is set to true

**Comment by petpetpetvm** [comment]
above 100 or above 99 ?

**Comment by mkcs121** [comment]
By default settings is keeping above 90% IV pokemon, but those pokemon which are >IV90% are not renamed automatically even though RenameOnlyAboveIv is set to true

**Comment by roy827** [comment]
When **RenamePokemon** and **RenameAboveIv** are set to true, any Pokemon above the value in **KeepMinIvPercentage** is renamed.

**Comment by mkcs121** [comment]
Oh, didn't realize that it was changed. In the previous versions only require set true to RenameAboveIv, then all pokemon above the KeepMinIvPercentage are renamed, while RenamePokemon is still set to false to prevent the rename of all pokemon to IV_Pokemon

**Comment by NoxxDev** [comment]
Rename is default to false

**Comment by mkcs121** [comment]
@NoxxDev Yes, rename is default to false. **RenameAboveIv** only works by setting both **RenamePokemon** and **RenameAboveIv** to true. However, in the previous versions only need to set **RenameAboveIv** to true while keeping **RenamePokemon** to false for renaming pokemon above **KeepMinIvPercentage**
