### ISSUE TITLE
Human Walk Snipe not working when using GPX Route

### ISSUE THREAD

**Issue by vitorfavila** [NoxxDev/NecroBot#556]
When I'm using a GPX Route, the Human Walk Snipe do not work, the information about snipes do not show. If I use Google Routes it work properly.

### Other Information
Version: v0.9.6
Windows Version: 8
What is affected: snipe

**Comment by samuraitruong** [comment]
Some people complaint when use it with GPX so I turn if off. I need some work on logic with GPX to get it back later.

**Comment by vitorfavila** [comment]
Nice, hope you can get it soon! Thanks
