### ISSUE TITLE
Max walk speed threshold exceeded by Variant

### ISSUE THREAD

**Issue by PoppaCoder** [NoxxDev/NecroBot#56]
### Expected Behavior
Bot not to exceed max speed.

### Actual Behavior
Bot exceeds max speed when setting WalkingSpeedVariant to _true_
### Your config.json
"UseWalkingSpeedVariant": true,
### Steps to Reproduce
Set 10km/h as max. +- 1.2 can go up to 11.2km/h, not desired

### Other Information
Version: 0.8.9
Windows Version: WINDOWS 9000
What is affected: Max walk speed

Note:
I think there was an actual variant value/config setting but was removed and set to a fixed +-1.2. You can either add a variant config value or set the random walk speed not to go lower than 1km/h lower than the max. (arbitrary 1km/h but that's fine for safe botting)
variant = random(10)/10;
if( random(1))
{
  If(not exceed maxwalkspeed)
    walkspeed += variant;
}
else
{
  If(not below maxwalkspeed - 1)
    walkspeed -= variant
}

**Comment by smoothrunnings** [comment]
No person walks at 11.2Kmph. If you start walking at those speeds you'll be banned, if not right away eventually. They game maker logs everything...

**Comment by Chaaaaaaaaarlie** [comment]
then set it to 9 and it'll go to 9.9 max ;)

close the issue if your problem is solved please.

**Comment by PoppaCoder** [comment]
It's not solved. It's a real issue. I may want to use speed variant but not go beyond a certain value

**Comment by PoppaCoder** [comment]
This seems to have been solved by re-implementing speedvariant
