### ISSUE TITLE
Error "No usable PokeStops found in your area. Is your maximum distance too small?"

### ISSUE THREAD

**Issue by RedDragonx** [NoxxDev/NecroBot#561]
My Necrobot has been in the loop with this error for 10 hours. This is the first time I use Necrobot so I don't know what this error mean. Did I get ban?

**Comment by Skolzack** [comment]
Softbanned, wait more 10~12hours and then try again.

**Comment by RedDragonx** [comment]
Oh. Thank you.

**Comment by petpetpetvm** [comment]
This error mean u got ip ban, either use new ip (vpn, socks, proxies, ssh) .... Or just wait for your ip be unban
