### ISSUE TITLE
0.9.6 When DisableHumanWalking=true, bot teleports to pokeshop?

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#562]
It should still walk in straight line right? I noticed it teleports straight to the pokeshop..this is quite dangerous.

**Comment by CreativiTimothy** [comment]
No, on one of the hastbin that documented the config, it is indeed suppose to teleport when DisableHumanWalking=True

**Comment by vfuyong** [comment]
Wow..why?

**Comment by V3LL** [comment]
Because 3 weeks ago (pre softbans) teleporting to a pokestop was much more efficient (exp/h) than "walking" there.

**Comment by vfuyong** [comment]
That is dangerous to do. I will recommend still have the default walking to be enabled and disable teleport.
