### ISSUE TITLE
[Request]Telegram restart timer function

### ISSUE THREAD

**Issue by grinmind** [NoxxDev/NecroBot#564]
First of all, THANK YOU SO MUCH for adding remote restart and remote shutdown of the bot via Telegram. Really big Thanks to that, but i have one more request if it is possible, if you could add a feature where we can set a simple timer for it to restart for example for 6mins not instantaneously closing and opening it right away. Sorry if i make it even harder for you sir, but man keep up the good work on providing us a free bot.

**Comment by NoxxDev** [comment]
I see no need to implement this
