### ISSUE TITLE
How do I increase the human walking speed?

### ISSUE THREAD

**Issue by KyDoe** [NoxxDev/NecroBot#574]

**Comment by helpmeplease1** [comment]
Please read wiki before raise question. this is the most simple setup 
    "WalkingSpeedInKilometerPerHour": 2.00,    (Moving Speed)
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,

**Comment by KyDoe** [comment]
Sorry I'm new to this website and all of this information
