### ISSUE TITLE
[suggestion] Ignore pokestops while sniping 

### ISSUE THREAD

**Issue by REDESTOR** [NoxxDev/NecroBot#575]
when the bot starts sniping it keeps farming pokestops and waste time, would be good that ignore pokestops "run" to objective, catch and continue farming

**Comment by V3LL** [comment]
Set 
"CatchPokemonWhileWalking": false,
"SpinPokestopWhileWalking": false

on the HumanWalkSnipeFilters for all the pokemons you want to human snipe

**Comment by REDESTOR** [comment]
not working...

**Comment by samuraitruong** [comment]
you got the configuration already. filter will overwrite global config
