### ISSUE TITLE
CatchPokemonLimit NOT Working

### ISSUE THREAD

**Issue by Koshyy** [NoxxDev/NecroBot#576]
Hey guys, tested CatchPokemonLimit today, set to 985... and it went to 991 without stopping (and didn't stop until I stopped it)... it was NOT 1470 minutes yet (what I have it set to).

Also why is their no min/max it randomizes between?

Anybody else have the same problem?

**Comment by Koshyy** [comment]
Bump, need others input....

**Comment by CreativiTimothy** [comment]
Doesn't work for me either. Sometimes, I put 990 as the limit and it stops catching pokemon at 400. Sometimes, I put the limit at 500 and it catches 1000 Pokemon and gets me softbanned

**Comment by Koshyy** [comment]
Glad I'm not the only one @CreativiTimothy

**Comment by NoxxDev** [comment]
With time, it will eliminating the already captured
