### ISSUE TITLE
For the priority in sniping, is 1 the highest or is 10 the highest?

### ISSUE THREAD

**Issue by KyDoe** [NoxxDev/NecroBot#579]

**Comment by babros** [comment]
1 high, 10 low

**Comment by samuraitruong** [comment]
1 is higher, you can make something like -1, -2 :)))  but I going to allow you manage from UI too. it mean you can decide which one to walk to cacth from UI :+1:

**Comment by likeness123** [comment]
My bot always catches the one with 10 haha. I think 10 is the highest?

**Comment by iwean** [comment]
If it same distance... 10 is low priority.

But if you set for 1000 distance priority 1 - and 300 distance priority 10.... bot catch the nearest

**Comment by samuraitruong** [comment]
#624 Here a support that you can change priority/remove snipes from UI
