### ISSUE TITLE
[IDEA] Necrobot send snipe info to discord channel - SOLVED

### ISSUE THREAD

**Issue by FureszOszkar** [NoxxDev/NecroBot#584]
The Necrobot users  can snipe the rare pokemon what others found, if the BOT send sniping info to the discord channel, what the Pokemon feeder use....

**Comment by babros** [comment]
Ennek alapból is így kellene lennie :D

**Comment by FureszOszkar** [comment]
Nem olvastam sehol, hogy ezt tudná a BOT...

**Comment by FureszOszkar** [comment]
Now I see, the new Pokemon feeder knows this! 
https://github.com/5andr0/PogoLocationFeeder/releases

**Comment by babros** [comment]
Nem tudja a bot. Ugy ertettem, hogy szerintem magatol ertetodo lett volna igy megcsinalni, csak ehhez kellene egy szerver, szerintem azert nem igy alakult.

**Comment by FureszOszkar** [comment]
Másnak is eszébe jutott, ahogy írtam, a mai kiadású Pokemon feeder tudja ezt! :) Így teljesüljön minden kívánságom... :)

**Comment by babros** [comment]
Majdnem teljesul. Igy csak azok toltik fel, akik hasznaljak a pokemonfeedert. ( En pl nem )

**Comment by FureszOszkar** [comment]
Miért nem? Már van benne olyan funkció, hogy megadhatod, hogy melyik területről érkező snipe infók érdekelnek csak...

**Comment by babros** [comment]
Es ez mukodik a walking snipe funkcioval is?

**Comment by FureszOszkar** [comment]
Walking snipe-al nem működik, de ez még kifejleszthető a BOT-ban!
Lehet akkor ezt kellene kitenni, hogy a PokeFeeder közeli koordinátás pokemonjai elérhetőek legyenek walking snipe-al.
