### ISSUE TITLE
NO POKEBALLS

### ISSUE THREAD

**Issue by rodney7702** [NoxxDev/NecroBot#585]
How do you solve no pokeballs problem? My stash have zero poke zero great zero ultra. Bot doesnt seem to walk to pokestops...missed out a lot of great pokemons. Help

**Comment by BoydTM** [comment]
consider usage of  PokemonsToIgnore

**Comment by jiakhang** [comment]
I have the same problem and i observed on the visualizer that the bot did not spin at stops, and eventually ran out of pokeballs after the update to 0.9.6, on newly regenerated default settings.
