### ISSUE TITLE
[Enhancement] Choose next PokéStop by minimizing the ETA

### ISSUE THREAD

**Issue by timonibus** [NoxxDev/NecroBot#589]
### Expected Behavior
The bot chooses the next PokéStop as the one which it can reach in the shortest time, given the current config of path determination (Google API, shortest distance, etc.)

### Actual Behavior
The bot always determines the next PokéStop as the one with shortest distance to the current position without taking into account the ETA. This results in ridiculously long ways to the next PokéStop and skipping any PokéStop in between.  For a nice illustration see the discussion in #570. Without any changes to the current situation, HumanSniping is also impracticable because it has the distances are far too big.

### Your config.json
```
"GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "***",
    "Cache": true
  },
```

### Steps to Reproduce
Run the bot with GoogleWalking enabled and check the distances.

### Other Information
Version: 0.9.6
Windows Version:  10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): farming PokéStops

**Comment by iwean** [comment]
Poke @samuraitruong....
Can you merge your HumanWalking code to GoogleWalk.... 
so google can have get by default to >> Spin: Yes | Catch : Yes ?
