### ISSUE TITLE
Niantic Server Unstable

### ISSUE THREAD

**Issue by Cranki** [NoxxDev/NecroBot#590]
Hi guys,

i get every 30 min the Error Niantic Server are unstable, throating API cells....
Any suggestions or fixes in progress with that problem?

**Comment by MaartenDeen** [comment]
I have that too and every pokestop I visit gives a softban first. Maybe related to Niantic Captcha?

**Comment by wakrad** [comment]
nope, i guess related to hatching egg and inventory
