### ISSUE TITLE
[Suggestion] Google heuristic or walk speed increase based on pokemon to snipe priority

### ISSUE THREAD

**Issue by wilsondgonzales** [NoxxDev/NecroBot#593]
With the pokemon filters already doing such a good job, How about adding a heuristic switcher to the filters? example as follows

"HumanWalkSnipeFilters": {
    "Magikarp": {
      "MaxDistance": 300.0,
      "Priority": 10,
      "MaxWalkTimes": 200.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      `"Addheuristic/speedincreasehere": biking/+2`
    },

So if it's an all important magikarp, better run than walk or get on your bike or something coz you don't want to miss out.

**Comment by samuraitruong** [comment]
I added increase speed already. Wait for upgrade
