### ISSUE TITLE
information about ban

### ISSUE THREAD

**Issue by macabrone** [NoxxDev/NecroBot#595]
hi man, sorry for my english, I'm from Italy.
like most of you I got banned (permaban)
for now i didn't found any possibility to have back my account. BUT
there is a remote possibility that some one hack the niantic website? deleating the name from the ban list?
is this the only possibility to restore banned account or someone knows some another possibility? (excepted the useless mail to niantic)
sorry for my english again
bellaaaaaaaaaaaaaaaa

**Comment by NoxxDev** [comment]
This not a forum

**Comment by Raverbunny** [comment]
Kinda unrelated ban info, even though she never did anything wrong with her account, my partner had her account banned to day, along with one of mine( only one, not all 3, great banning system, works as intended...).
Had her ban over turned pretty much as soon as I sent email to Niantic, but still....
Also tried to email about my account too, but that was met with stony silence, what a surprise
