### ISSUE TITLE
Spin No Catch NO

### ISSUE THREAD

**Issue by likeness123** [NoxxDev/NecroBot#598]
Why does it say No on catch and spin??
![no](https://cloud.githubusercontent.com/assets/21067083/18007709/c776898a-6bd7-11e6-800c-890f2a5cc430.png)

**Comment by iwean** [comment]
It's ability of new sniping mode: "Human Walk Snipe"
When it spawn pokemon, it can still spin Pokestop (Yes/No) and keep catch another pokemon (Yes/No) on the go to spawn location.

Please read the wiki: https://github.com/NoxxDev/NecroBot/wiki/Human-walk-snipe-config

**Comment by samuraitruong** [comment]
catch pokemon will take long time than spin, so to make sure we don't miss target, catch will be turn off depend on how much time remaining there.

**Comment by pedromig123** [comment]
@likeness123 i have the same problem #577
