### ISSUE TITLE
9.0 for leveling. 9.6 for catching useful pokemon.

### ISSUE THREAD

**Issue by likeness123** [NoxxDev/NecroBot#601]
I just noticed when I am using different versions.
9.0 is better for gaining experience, it is faster compared on the later versions.
9.6 is good for catching or sniping for useful pokemon.

**Comment by NoxxDev** [comment]
This is because v 0.9.6 uses human routes to get to pokestop, thus taking longer, 0.9.0 version goes from point A to B in a straight line passing over the buildings.
You can turn off `UseGoogleWalk` setting human routes to false

**Comment by samuraitruong** [comment]
why there still have people just need to level up asap?

**Comment by xhaoran06** [comment]
^Well, the higher the level, the higher the CP of pokemons you could snipe and catch perhaps.

**Comment by BoydTM** [comment]
likeness123 - in the new version guys tried to remove patterns - which are ones of the main possible reasons for bans. If you wish to have a chance to stick with your account without getting banned - try to use new version ... better slower than never ;). ETA for crush-test -> nearest monday/tuesday
