### ISSUE TITLE
New feature - need tester : Humal walk snipes with speed up option & controller from visualizer

### ISSUE THREAD

**Issue by samuraitruong** [NoxxDev/NecroBot#602]
yes, guys guess what going next. 

I was initial code to allow you have option speed up (change base speed ) base on the pokemon filters to allow you have more control in snipes pokemon.

config will change to something like this 
`
  "Magikarp": {
      "MaxDistance": 300.0,
      "Priority": 10,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 80.4,
      "AllowSpeedUp": true
    },

`
I also add support allow you made you decision which pokemon you want to catch next from the UI of visualizer.
for example. my config for Jynx is only 1000 m, but from UI I will let the bot for immediately to Jynx 2000m

![image](https://cloud.githubusercontent.com/assets/1183138/18011928/88178e9c-6bfa-11e6-88ad-d712f8371bed.png)

![image](https://cloud.githubusercontent.com/assets/1183138/18012043/06fb284a-6bfb-11e6-8ffa-b5ed5c1fcf3f.png)

For those people who want to test this feature please download code from
necrobot : https://github.com/samuraitruong/NecroBot/tree/hwn-speed-change
visualizer : https://github.com/samuraitruong/necrobotvisualizer

I would ask you guys to test bug & contribute the idea. I already has few idea to make this feature more fun. hope that we can have stable version and open PR over weekend.

Note: use dump account for test

**Comment by samuraitruong** [comment]
@NoxxDev  :could you please pin this post at top for few days.

**Comment by masterpowers** [comment]
lets do this ! :D

**Comment by zsatanxz** [comment]
i can,t use in 0.9.6 open NecroBot.exe it foreclose
"MaxSpeedUpSpeed": 80.4,
"AllowSpeedUp": true


  "HumanWalkSnipeFilters": {
    "Magikarp": {
      "MaxDistance": 300.0,
      "Priority": 10,
      "MaxWalkTimes": 200.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true
      "MaxSpeedUpSpeed": 80.4,
      "AllowSpeedUp": true
    },

**Comment by rflpsz** [comment]
How can i test this update?
Can show me steps

**Comment by samuraitruong** [comment]
#624 I open PR already, hope @NoxxDev  will release it soon

**Comment by iwean** [comment]
@samuraitruong Can you give link for a compiled version? Thx...

**Comment by samuraitruong** [comment]
you can get 0.9.7.zip in this folder - https://app.box.com/s/a01f30ljopaxeds77r5bp1noye6xozl1

**Comment by ntatoo** [comment]
@samuraitruong how to compile the visual ?
can you show me ?

**Comment by samuraitruong** [comment]
get source from github then you can run
npm install
npm start, dont need to compile it.

you need install nodejs on your machine

**Comment by ntatoo** [comment]
@samuraitruong if you want to build it to exe 
how ?

**Comment by samuraitruong** [comment]
"scripts": {
    "start": "electron ./app --enable-logging",
    "postinstall": "install-app-deps",
    "pack": "build --dir",
    "dist": "build --win --x64",
    "dist32": "build --win --ia32",
    "zip": "build --win zip --x64",
    "zip32": "build --win zip --ia32"
  },

**Comment by samuraitruong** [comment]
you need run npm install
npm pack
npm dist32
npm zip32

**Comment by ntatoo** [comment]
@samuraitruong just paste it on command window ?
or there are other ?

i am newbie in this , step by step please 
now i am installing the npm

**Comment by samuraitruong** [comment]
install nodejs then above command will work

**Comment by ntatoo** [comment]
@samuraitruong 
![1](https://cloud.githubusercontent.com/assets/20683618/18027434/8a6e2dac-6c8d-11e6-9a39-5b29cd3a334a.png)
i got this eror

**Comment by samuraitruong** [comment]
what is your os?

**Comment by ntatoo** [comment]
os ?
i am using windows 7 x64

**Comment by ntatoo** [comment]
@samuraitruong where the link to download the build pack ??

**Comment by zsatanxz** [comment]
@samuraitruong i,m download 0.9.7 and config 
softban..........

**Comment by samuraitruong** [comment]
that another bug, fake softban, because we spin poekstop twice. there is a pull request to fix already

**Comment by zsatanxz** [comment]
I'm open bot and strat
Scan HumanWalkSnipe list and softban
Please help me

**Comment by zsatanxz** [comment]
@samuraitruong 
  "HumanWalkSnipeConfig": {
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 20,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": false,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "Enable": true,
    "WalkbackDistanceLimit": 350.0,
    "IncludeDefaultLocation": false,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": false
  },
