### ISSUE TITLE
0.9.6 Eggs - priority

### ISSUE THREAD

**Issue by BoydTM** [NoxxDev/NecroBot#603]
Is there a way to force necrobot to choose 2 km egg first (if present) instead of taking the highest one ?

**Comment by mo0ojava** [comment]
Change the default "UseEggIncubatorMinKm": 2 to 10 in config.json.

**Comment by mo0ojava** [comment]
#Suggestion --- The default-setting should actually be changed to 10, I'm always switching that one before starting a newly built version.

**Comment by BoydTM** [comment]
will try, however from logical point of view "UseEggIncubatorMinKm": 10 should mean that only 10km will be taken into consideration ....
