### ISSUE TITLE
Bug: Incubator not working when CatchPokemon set to false

### ISSUE THREAD

**Issue by zhihao4456** [NoxxDev/NecroBot#615]
I just realized when you set catchpokemon to false and let the bot to go around pokestops collect pokeball only, the incubator is not working as in the number of meters you walked is not counted~ When i first open the incubator shows 3km left but after 1 hour when it goes all the pokestop and collect the pokeballs, i saw the latest info on incubator still shows the remain of 3km~ No changes at all~ No issue with incubator when I set catchpokemon to true

**Comment by CreativiTimothy** [comment]
Can confirm. Incubators do not work when CatchPokemon is set to false. Put it at 10km/h for 2 hours without catching Pokemone and it still showed up 2km

**Comment by NoxxDev** [comment]
https://github.com/NoxxDev/NecroBot/commit/6a9dcb1cbd71b2b54e5c3a2f7808d644baa464dc
