### ISSUE TITLE
i can,t use necrobot

### ISSUE THREAD

**Issue by zsatanxz** [NoxxDev/NecroBot#617]
i download Source code (zip) i can,t use necrobot 0.9.6 ....?
i can use Source code (zip) ....?
please help

**Comment by wilsondgonzales** [comment]
https://github.com/NoxxDev/NecroBot/wiki

**Comment by zsatanxz** [comment]
i can open file ...?

**Comment by zsatanxz** [comment]
u help 
teach me teamview

**Comment by deframet** [comment]
If u use windows u can download release.zip directly from https://github.com/NoxxDev/NecroBot/releases
