### ISSUE TITLE
[Googlewalk] suggestiosn for improvement

### ISSUE THREAD

**Issue by jiakhang** [NoxxDev/NecroBot#618]
With the introduction of googlewalk, I tried it and it started running out of pokeballs. Curious to know what happened, I turned on the Visualizer and discovers this.

**Google walk on** 
1. Bot sticks to roads to reach target pokestop, likely sorted by distance on google api, not actual distance to pokestop.
2. Bot walks to target pokestop (usually a long winded way and disregard all spinable pokestops along the way to reach the target pokestop. Meanwhile it catches everything along the way. Because of this, the number of pokeballs starts to drop and eventually runs out.
3. Bot has to be on top of target pokestop before it actually spins.

**Suggestion for more human-like behavior**
This is likely to be correctable in the googlewalk logic.
1. Check for nearby pokestops while walking on path to target pokestop
2. Spin pokestops when in range, not when on top of pokestop. 
3. Stop googlewalking mode and switch to pokestop sniping mode when near target pokestop, this will emulate the human behavior of taking shortcuts when near pokestops.

### Your config.json
```
Default (except for turning on and off googlewalk for testing)
```

**Comment by jarodz** [comment]
Hi jiakhang,

Could you tell me how to turned on the Visualizer?
Thx.

**Comment by jiakhang** [comment]
https://github.com/nicoschmitt/necrobotvisualizer
