### ISSUE TITLE
Kaspersky Internet Security shows NecroBot.exe as UDS:DangerousObject.Multi.Generic

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#619]
[http://whitelisting.kaspersky.com/advisor?lang=EN#search/b34a9f0757952faf5cecded8b25f9ad1](http://whitelisting.kaspersky.com/advisor?lang=EN#search/b34a9f0757952faf5cecded8b25f9ad1)

**Comment by Ev0luti0n2016** [comment]
I did not have any issue before, but now my Kaspersky identifies this as trojan...bazon.a

**Comment by CreativiTimothy** [comment]
For some reason, my updated Kaspersky 2016 doesn't have any problems. However, my Kaspersky on my other laptop says it's dangerous object for some reason. It's really annoying

**Comment by REDESTOR** [comment]
due to heuristic analysis it detects suspicious behavior, it connects to a server and send data like a trojan...or niantic report it to scam like many other piracy or cracking programs that big corporation does't like

**Comment by madara134** [comment]
me too
