### ISSUE TITLE
Got 3 incubators but only the unlimited one is used

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#621]
### Expected Behavior
Check inventory for available incubators and put eggs in it.

### Actual Behavior
Only the unlimited incubator is used.

### Other Information
Version: 0.9.6
Windows Version: 8.1

**Comment by CreativiTimothy** [comment]
your config? eggkmmin should be between 2-10km

**Comment by TLBM** [comment]
```
    "UseEggIncubators": true,
    "UseEggIncubatorMinKm": 2,

```
[07:29:03] (EGG) Incubator status update: 4.73km left
[07:29:03] (EGG) Player below level 20, saving this 10 km Egg for later
```

![eggs](https://cloud.githubusercontent.com/assets/11824134/18025363/06434bd0-6c28-11e6-84fd-93f7fb3bda0e.png)

```

**Comment by helpmeplease1** [comment]
"UseEggIncubators": true,
    "UseEggIncubatorMinKm": 2,   (Change to 5)

You don't have 2KM egg. You set to 5.0km should work

**Comment by NoxxDev** [comment]
https://github.com/NoxxDev/NecroBot/commit/6a9dcb1cbd71b2b54e5c3a2f7808d644baa464dc
