### ISSUE TITLE
[Request] Killswitch Monitor

### ISSUE THREAD

**Issue by hardknoxni69a** [NoxxDev/NecroBot#628]
@NoxxDev 
Could we have current status of killswitch in titlebar such as Pokestops 1999/2000 Pokemon 999/1000?
think it would be good to have a monitor

**Comment by naymore** [comment]
How's that related to killswitch? KillSwitch is a check on bot startup to see if the bot should be started. I'm not sure if it is being checked while running.

**Comment by hardknoxni69a** [comment]
Thanks noxx. @naymore the killswitch is always checking if u reached your limit so say today i want to close it at 1500 instead of 1999 there will b a display for that so i know where it stand it used to show how many of our goal was reached but he just reimplemented for us thanks
