### ISSUE TITLE
Walking Speed Variance Changes too Frequently

### ISSUE THREAD

**Issue by Aurilius** [NoxxDev/NecroBot#63]
Am I missing the option that changes the interval at which you change walking speeds?  Normal people do not change their pace every 5-10 seconds.  This is almost too odd.

**Comment by Nick2400** [comment]
+1

**Comment by NoxxDev** [comment]
randomic seconds in 5 ~ 15 seconds

@ff178bee70976cf092d582e2810f747b7dd0ca8e

**Comment by Tokariew** [comment]
it's not 5 to 15, it can be change in instant ;D
https://i.imgur.com/XLHLGjO.png

**Comment by NoxxDev** [comment]
> it's not 5 to 15, it can be change in instant ;D
https://i.imgur.com/XLHLGjO.png

minimum value not be less than 5 seconds

`SpeedVariantSec += rw.Next(5000, 15000);`

**Comment by lordofthereef** [comment]
Depending on where you are walking I can absolutely see pace changes that frequently. I run Boston Common and, with the amount of foot traffic that pace gets you can very rapidly and frequently be forced to change pace.

Not saying you are not right to bring this up, but its believable where I run, and I wouldn't think pace changes, unless they are drastically changing every second by very large variations, would ever get noticed by niantic.
