### ISSUE TITLE
why i got error like this

### ISSUE THREAD

**Issue by parnpahn** [NoxxDev/NecroBot#630]
[18:12:49] 可進化的神奇寶貝：0		
[18:12:49] 更新孵化器狀態：剩餘9.59公里		
[18:12:51] 遇過的神奇寶貝：94/151，捕捉過的神奇寶貝：94/151				
[18:12:53] 前往補給站：Taipei Public Library (距離86公尺，需要30秒) (route GoogleWalk)				
[18:13:21] Pokemon Servers might be offline / unstable. Trying again...
[18:13:22] Error: System.Net.Http.HttpRequestException: 傳送要求時發生錯誤。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 嘗試存取通訊端被拒絕，因為存取權限不足。 130.211.14.80:443
   於 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   於 System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs: 行 27
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs: 行 41
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs: 行 97
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs: 行 65
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs: 行 0
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PokemonGo.RocketAPI.Rpc.Player.<UpdatePlayerLocation>d__1.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs: 行 35
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   於 PoGo.NecroBot.Logic.Strategies.Walk.BaseWalkStrategy.<DoWalk>d__14.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\BaseWalkStrategy.cs: 行 166
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__2.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs: 行 39
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PoGo.NecroBot.Logic.Navigation.<Move>d__8.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs: 行 90
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<FortPokestop>d__8.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs: 行 198
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   於 PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__7.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs: 行 86
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__0.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs: 行 57
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   於 PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs: 行 68
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 於 E:\Projetos\CSharp\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs: 行 57

**Comment by BlueVeeVee** [comment]
Get banned.

**Comment by parnpahn** [comment]
but still can caught pokemon
can use main app login
can use other botting

**Comment by parnpahn** [comment]
it's OK after i change to default language(en
and reboot my pc

**Comment by parnpahn** [comment]
i think the issue happen because
norton security ban some connection
