### ISSUE TITLE
Log file timestamp is in different formats

### ISSUE THREAD

**Issue by MaartenDeen** [NoxxDev/NecroBot#633]
### Expected Behavior
All time stamps in the log file should be in the same format. This makes analyzing easier

### Actual Behavior
Some timestamps are in hh:mm:ss.sss format, others in hh:mm:ss
Example:
`[14:12:03.137] Looking for Pokemon...	`
`[14:12:05.015] (Threw ball) Nice hit. Curve-ball...	`
`[14:12:05] (CatchMissed) | (Normal) Weedle Lvl: 7 CP: (71/87) IV: 44.00% IV: 44.00% | Chance: 57.27% | 69.10m dist | with a PokeBall (1 left). | lat: 51.930241 long: 4.483658 | Move1: PoisonStingFast Move2: Struggle	`
`[14:12:07.792] (Threw ball) Nice hit. Curve-ball...	`
`[14:12:08] (CatchSuccess Attempt #2) | (Normal) Weedle Lvl: 7 CP: (71/87) IV: 44.00% | Chance: 57.27% | 69.10m dist | with a PokeBall (0 left). | 120 EXP earned | Candies: 401 | lat: 51.930241 long: 4.483658 | Move1: PoisonStingFast Move2: Struggle	`
`[14:12:10.533] Looking for incense Pokemon...	`
`[14:12:10.790] Looking for Pokemon...	 `

### Other Information
Version: 0.9.6
Windows Version: 7.1

**Comment by Kermel** [comment]
I made that on purpose, for "DEBUG" level only (made things easier when I was tuning the google walking).
But I think for now it can be only with seconds precision
