### ISSUE TITLE
(ERROR) Current Operation was canceled.

### ISSUE THREAD

**Issue by BoydTM** [NoxxDev/NecroBot#635]
After this error bots restarts immediately. What would be the pokemon go app behaviour in that case - also reinitiaton ?

**Comment by TLBM** [comment]
Have seen it too occasionally.

**Comment by BoydTM** [comment]
Like everyone... . I wandering if it can be one of the ways to identify us. App needs about 8 seconds to reboot, bot not, so game over ...

But it could also be some necro internal error - transparent for them, so this is why the question ...

**Comment by BoydTM** [comment]
Similar pattern with Niantic Servers unstable, throttling API Calls -> necro always passing to evolutions:

[17:13:49] (ERROR) Niantic Servers unstable, throttling API Calls.
[17:13:49] (EVOLVED) Potential Evolutions: 1
[17:13:49] (EVOLVED) Weedle successfully for 500xp
