### ISSUE TITLE
[bug] Sniper HumanWalk interfering with Pokestop looking and triggering softbans

### ISSUE THREAD

**Issue by mo0ojava** [NoxxDev/NecroBot#636]
### Expected Behavior
Assuming that using GoogleWalk and HumanWalkSnipe together means that we are looting Pokestops and catching local Pokemons as usual. This is interrupted when a Snipetarget appears and we set a new route target to the Snipetarget. Commencing regular operation after the snipe is complete.

### Actual Behavior
GoogleWalk does its thing. When a snipetarget appears *something* happens and any looting of Pokestops triggers a softbanned-message. See the attached screenshots.

If you wait for the softbanned-spinning to happen, you end up *both* spinning the Pokestop and move for the target simultaneously. The latter isn't obvious though, since the vizualiser isn't catching this movement until after the spinning is done. In my case I popped up rather far from the Pokestop the instant the Pokestop-spinning was finished.

### Your config.json
Attached.

### Steps to Reproduce
+ Start GoogleWalking with the attached config. HumanWalkSniping on.
+ When (SNIPER) (HUMAN WALK) appears and a Pokestop-looting happens the bug appears.

### Other Information
Version: Dev build per d89130f7d793dc94d31b5a55e1e490f22ca517e5
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): GoogleWalk, HumanWalkSnipe

![humansniper_trigger_softban](https://cloud.githubusercontent.com/assets/20909700/18028039/07aaafd0-6c74-11e6-98fb-77f255b41311.PNG)
![humansniper_trigger_softban_2](https://cloud.githubusercontent.com/assets/20909700/18028042/0a78d340-6c74-11e6-9475-3194c2fd023f.PNG)
[config.json.txt](https://github.com/NoxxDev/NecroBot/files/440695/config.json.txt)

**Comment by BoydTM** [comment]
I do not know if it helps, but according to my observations it started to happen much more frequently (maybe coincidence) somewhere between 0.9.6.40 and 0.9.6.55 (40 & 55 are the number of commits when i took the source via git). After that i get back to 0.9.6.40 and since yesterday had only one occurence ( soft ban and after restarting necrobot -> ip ban )

**Comment by mo0ojava** [comment]
I've mainly been running on home made gpx-tracks (wtracks.appspot.com) and have *never* seen a softban before. It happened for the first time now that I was trying out the HumanWalkSniper. Haven't looked into that particular code at all though, so perhaps I'm misunderstanding something regarding how it's supposed to work. Like it being incompatible with GoogleWalk...?

**Comment by mo0ojava** [comment]
Just tested with the switch SpinWhileWalking to false and the bug don't seem to appear anymore. A hint on what's dysfunctional atm.
