### ISSUE TITLE
"Your IP is:" in RED - makes me jump every start

### ISSUE THREAD

**Issue by TLBM** [NoxxDev/NecroBot#639]
### Expected Behavior
Print it in the color of the other INFO messages.

### Actual Behavior
Is printed in red like really important messages.

### Other Information
Version: 0.9.6
Windows Version: 8.1.
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
onsole output

**Comment by REDESTOR** [comment]
it's warns you are susceptible to a ip ban, better to use a proxy, especially if you put a location different than the real or multiple accounts or bots , but if you use it locally there is no problem

**Comment by iwean** [comment]
:lol: .....please do not jump too high :dancer:

**Comment by samuraitruong** [comment]
well, not a big deal. that a good attention for user

**Comment by tanjj92** [comment]
insert kid_jump_scared_and_started_cry.gif
