### ISSUE TITLE
How to set the new configuration !

### ISSUE THREAD

**Issue by Sayton** [NoxxDev/NecroBot#64]
So no there is no Configuration UI
How am I supposed to set things up !!

**Comment by Orenthion** [comment]
Open the Config folder, and modify the values in config.json using Notepad, or Notepad++

**Comment by Sayton** [comment]
Oh
This is gonna take a while :/

**Comment by NoxxDev** [comment]
ConfigGUI is out of update for this was removed

**Comment by Sayton** [comment]
@NoxxDev So are we getting it back soon ?
Or are we having a UI for the bot !
Because it was much more user friendly than editing values.
At any case thx for the great work ^_^

**Comment by Chaaaaaaaaarlie** [comment]
"user friendly" is not always better than efficient. 
You'd have to change the gui everytime you put in a new setting.

**Comment by Sayton** [comment]
Yea but sometimes i have to reset my settings which takes a bit of time without a quick UI.
So I'm hopping to have that soon :/

**Comment by Chaaaaaaaaarlie** [comment]
Just copy and paste the stuff you want in your new config ^^
Can't be that hard.

**Comment by dayshake** [comment]
There is no device Info in the config ver 9.0.

should I just copy paste it from the previous ver?
