### ISSUE TITLE
Changing default location

### ISSUE THREAD

**Issue by KyDoe** [NoxxDev/NecroBot#648]
I already tried changing "Default Latitude": and "Default Longitute": but it didn't work. Is there any other way I can do it?

**Comment by deframet** [comment]
Edit config.json

**Comment by jarodz** [comment]
There is an option inside config.json which is named ""StartFromLastPosition" and the default is true.
When this option turn on, if your new default location is too far from the last position in short time.
The necrobot will start from the last location to your new default location.
