### ISSUE TITLE
Feature Request, Pokestop Ordered by distance to default point.

### ISSUE THREAD

**Issue by Gobu70** [NoxxDev/NecroBot#65]
Current behavior seems to be the following.  When using non-GPX mode:

When choosing the next Pokestop to visit, the algortihm orders them by distance from current point and ignores those which the timer has not expired (Based on my understanding of FarmPokestopsTask.cs).  This causes the path to wander sometimes aimlessly AWAY from where the good Pokemon are located, assuming you centered your default position some place good.

I can see in the FarmPokestopsTask.cs that the default position and current position are available right from the start, as it might have to move back to the default if it is too far away.

At the beginning of the while loop where it creates the ordered list, could there be an option that selects which point to use as it's basis point.  The current behavior would use the session.Client.Current(Lat/Lon), and the new option would use the session.Settings.Default(Lat/Lon) based on a true/false flag.

When enabled this should cause the wandering to stay close to the default point (which is why we are there in the first place).  It will wander away always choosing the closest point to the default point that doesn't have a timer going.  Once those timers expire it will head back to the default point and continue to hit points near the default point as their timers expire.

Gobu

**Comment by Gobu70** [comment]
![image](https://cloud.githubusercontent.com/assets/20968263/17684378/092758a8-6310-11e6-83d3-c7555274e9b7.png)

**Comment by Gobu70** [comment]
You can see it wandered away from where I started it over on the right side.

**Comment by Chaaaaaaaaarlie** [comment]
Change the "MaxTravelDistanceInMeters" to sth smaller then. I have it at 500.

**Comment by Gobu70** [comment]
That distance is how far it will travel away from the default point or the current point?

**Comment by Chaaaaaaaaarlie** [comment]
default

**Comment by Chaaaaaaaaarlie** [comment]
Just look up in which circle are the most pokestops / lures / pokemon and set the radius of that as the value for MaxTravelDistanceInMeters

**Comment by Gobu70** [comment]
OK, my bad.  I thought it was referring to the distance it would search for the next pokestop.  So it is like a leash from the default position.  Thanks, I'll close this issue.
