### ISSUE TITLE
[Feature Request]SnipePokemonNotInPokedex for HumanWalkSnipe

### ISSUE THREAD

**Issue by Whistler212** [NoxxDev/NecroBot#660]
Maybe its nice to have collection of  all pokemon minus legendary with human walk snipe
maybe feature SnipePokemonNotInPokedex and SnipePokemonNotInPokedexPriority for HumanWalkSnipe?

**Comment by samuraitruong** [comment]
do we need that? because sooner or later we fill pokedex
