### ISSUE TITLE
(SNIPER) [HUMANWALK] - What happen !!  why it don't catch pokemon when destination reached ??

### ISSUE THREAD

**Issue by vanillachoco** [NoxxDev/NecroBot#661]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
Catch pokemon when destination reached.

### Actual Behavior
It don't catch pokemon.

### Your config.json
```
your config here
```

### Steps to Reproduce
![dont-catch](https://cloud.githubusercontent.com/assets/21161074/18033313/57cdbe26-6d4b-11e6-86ec-5a371d808634.jpg)

### Other Information
Version:0.9.6
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by samuraitruong** [comment]
None issue

**Comment by popsoda27** [comment]
i see that "Allow catch : No"

**Comment by Cranki** [comment]
This is how the full command look like:
    "Exeggutor": {
      "MaxDistance": 400.0,
      "Priority": 1,
      "MaxWalkTimes": 420.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true
    },
Alow catch means is the player allowed to catch other Pokemon while he walks to the Snipeing Pokemon. 
Thats ok, if there is no. Nevertheless HumanWalkSnipping seems to be buggy atm.

**Comment by KyDoe** [comment]
This is also happening for me, when the player arrives at the "Sniped Destination" it doesn't catch the pokemon and just continues on.

**Comment by samuraitruong** [comment]
I don't see any bug here, please keep in mind that human sniper is use public data source, data source may not accuracy /troll data. 
Catch : yes. Spin: Yes : is only apply when you walking only. it always try to catch pokemon at destination. 

@KyDoe : what bug you mentioned?

**Comment by samuraitruong** [comment]
![image](https://cloud.githubusercontent.com/assets/1183138/18036919/9d5b3bac-6dba-11e6-97aa-4fe341458498.png)

**Comment by KyDoe** [comment]
@samuraitruong so you're saying that sniped locations might not be true?

**Comment by samuraitruong** [comment]
Yes. Puplic source never 100%

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Aug 29, 2016 at 8:10 AM +1000, "KyDoe" <notifications@github.com<mailto:notifications@github.com>> wrote:


@samuraitruong<https://github.com/samuraitruong> so you're saying that sniped locations might not be true?

**Comment by Brazuca87** [comment]
I believe the issue is if that pokemon we are sniping is a Lured pokemon. I don't believe it's searching for lured pokemons, so it just moves on... I could be wrong...

**Comment by samuraitruong** [comment]
you are wrong, code already there for looking lure pokemon

**Comment by vanillachoco** [comment]
Pokémon can not be found, right?

![dont-catch 2](https://cloud.githubusercontent.com/assets/21161074/18040731/5e34ac6c-6ddb-11e6-91b5-09180bc90d06.jpg)

**Comment by vanillachoco** [comment]
![dont-catch 3](https://cloud.githubusercontent.com/assets/21161074/18041487/cb20ecfc-6de3-11e6-9ca5-e80f5ac4b906.jpg)
