### ISSUE TITLE
i got this error? idk why

### ISSUE THREAD

**Issue by thegoehbandhit** [NoxxDev/NecroBot#665]
![capture8](https://cloud.githubusercontent.com/assets/21209981/18034407/72c8f536-6d66-11e6-9c33-e41df0990373.PNG)

this why?

**Comment by Roodren** [comment]
Same here

**Comment by smoothrunnings** [comment]
Could be the new catcpha

**Comment by CyberLykan** [comment]
If this could be implemented, maybe it would solve this problem. https://greasyfork.org/scripts/18449-recaptcha-helper/code/reCAPTCHA%20Helper.user.js

**Comment by thegoehbandhit** [comment]
no solve?

**Comment by VBQL** [comment]
Please delete your config and generate a new one
