### ISSUE TITLE
Can't find any pokestops

### ISSUE THREAD

**Issue by Niwid** [NoxxDev/NecroBot#666]
I get messages saying that there are no pokestops nearby, and even after trying a proxy i'm getting the same message. 

My config: https://docs.google.com/document/d/1pt_r924pMUvwP-mVPk1YccJFceasl_Rcbg_mXi13sMc/edit?usp=sharing

**Comment by Skolzack** [comment]
You're softbanned, wait ~1day

**Comment by naymore** [comment]
Can't find any pokestops anymore either ;-)
Even with a fresh account. 

Either it's a general issue - or my ip address is blocked.

**Comment by Skolzack** [comment]
If another account doesnt work, probably is your IP Address because here is working fine and I'm running about a week 24/7 without problems nor softbans.

**Comment by Niwid** [comment]
I've tried through a few different IPs, and still doesn't work, hasn't worked for the past 3 days.

**Comment by ausscheider** [comment]
And all IPs are free Proxy's?
Niantic know the free proxys and banned this

**Comment by Niwid** [comment]
No, i purchased these proxies

**Comment by naymore** [comment]
You guys are using proxies? Really?

**Comment by Skolzack** [comment]
Just don't use proxy guys lol

**Comment by hardknoxni69a** [comment]
Not only does the ip get banned but also your deviceids can get banned if you change the value you should be able to login but always best to wait it out humans do sleep sometimes i think they only want the players to play for around 8-12 hours a day
