### ISSUE TITLE
Feature Request... EvolutionDelay

### ISSUE THREAD

**Issue by masterpowers** [NoxxDev/NecroBot#673]
I got one of my account Banned Before For Evolving Too Fast...
I think we Should Follow the Same Delay Like You Play it...
having a 5 secs delay is not gonna help you get banned...
So for now im not evolving automatically coz it evolve too fast...
and transfer too fast and you get flagged by Niantic by that action...

**Comment by petpetpetvm** [comment]
how can you now that you got banned cuz of evolving too fast ?

**Comment by petpetpetvm** [comment]
know*

**Comment by Brazuca87** [comment]
It happened to my account as well. My main got banned for evolving too many pokemons too quickly (got banned a few minutes after). I believe they look for high chunk of exp too quickly (got 80k exp in like 20 mins).

I've modified the code on mine. This was already posted on issue #604

**Comment by hardknoxni69a** [comment]
I dont think its from evolutions to be honest ive evolved almost 175 at once with lucky egg multiple times on my account atleast 4 times and not banned there is a setting delay for player actions you can set to 30 secs even a minute if you would like i do think it would be nice to have the option to enable phoneanimation like you stated in 604 but the evolving is definitely not what you got banned for ive done it on my phone and through bot and never got banned for evolving to fast it was like 140000 in hour

**Comment by NoxxDev** [comment]
Fix https://github.com/NoxxDev/NecroBot/pull/777
