### ISSUE TITLE
[BUG] Distance traveled to capture not properly calculated

### ISSUE THREAD

**Issue by Brazuca87** [NoxxDev/NecroBot#676]
### Expected Behavior
Distance to pokemon calculated by path taken

### Actual Behavior
Distance to pokemon calculated via straight line
[23:31:01] (SNIPER) (HUMAN WALK) Found Jynx spawning | lat: 40.758572745664, lng: -73.967529574541, **dist 1085.38m** , expired in 08 min 11 sec | Estimate : 03 min 50 sec | Allow spin: Yes | Allow catch : Yes | Speed 18.16km/h
[23:31:02] (INFO) Traveling to Pokestop: Roosevelt Island Seawall and Pier  **(6361m)** (700 seconds) (route GoogleWalk)

**Comment by samuraitruong** [comment]
I found this issue . Will correct it tonight

**Comment by samuraitruong** [comment]
wow, that become a bigger issue, because if we use google api to calculate distance 2500 limit will be used in fews hours. also create big impact on performance. @NoxxDev any idea?

**Comment by bulubebek** [comment]
disable human sniping when non-necro route enabled.

**Comment by samuraitruong** [comment]
disable or not is user decision? I add a generic rules like google like = 1.6 *straight line in the code atm. we may back to implement the real distance later with support multiple google api key

**Comment by bulubebek** [comment]
IMO, best practices of human sniping is when necro-route is used, because it will be easier for bot to make its own calculation and making best decission to intercept pokemon or not.

this is the main reason why past necro devs pending PR for OSM implementation, because not all forts and/or pokemons can be reached using walking routes.

**Comment by Kermel** [comment]
I am afraid this has no solution. Google walk API sometimes returns weird routes even though you are staying practically next to the following pokestop
(you can try that directly in google maps - (maps.google.com) try to calculate "walking" route from your position to the pokestop mentioned and you will see what google returns.
Bot using the google walk strategy then only follows this route.
Calculating direct ("fly") distance provides different results (shortest way) but letting bot walk this shortest route can be dangerous as it then ignores anything on the path including buildings so it might be easily discoverable

**Comment by Kermel** [comment]
(As for displaying proper distance using the google walk, it is quite easy - google walking strategy calls google api only once, getting the list of "waypoints" as a response. We can then just calculate distance between those waypoints which will provide the correct result)

**Comment by jjskuld** [comment]
This is fixed now in master.  The last commit related to this is 5e29da081b7558105c551a522b38cefdee0f4bd8.  We now calculate the true walking distance for the walk method that is being used.
