### ISSUE TITLE
Softban Applies on How Many Pokestops/Hours Logged In (+Solution)?

### ISSUE THREAD

**Issue by Koshyy** [NoxxDev/NecroBot#68]
Hey guys,

So it appears to be 12 continuous hours of log in time causes a softban (can't catch pokemon, instantly running). Could also be how many Pokestops you visit (and I hear a lot of rumblings about 1000-2000 a day is the range)... but I think it has more to do with time logged, because twice now on 2 separate accounts there has been a softban at 12 hour ish' mark.

SOLUTION: 
An automated 'killswitch' to take a break at 11 hours and like 30 minutes for an hour (or however long it requires to stop the soft ban). After said time period it will AUTOMATICALLY RESTART the bot.
An automated 'killswitch' of sorts. At 1000 or 2000 or whatever pokestops visited in a 24 hour period, stop the bot until the 24 hour period ends. After said time period it will AUTOMATICALLY RESTART the bot.

**Comment by lordofthereef** [comment]
I would love a killswitch, although I have had some accounts run for 24+ hours and not have any issues whatsoever.

Would love to be able to just set random times for it to take breaks though. Play for three, break for one, play for two, break for two, play for five, break for three, etc.

**Comment by Koshyy** [comment]
lordofthereef, I could get behind that too! Have it "take a lunch break" with all that "walking around" lol
