### ISSUE TITLE
Possible avoiding ban by botting on and off

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#69]
I noticed that the red text message "server busy, throttling API call" might be signaling additional monitoring being turned on at server side. Then everything afterwards were tracked and analyzed. So I'm proposing one way to avoid being monitored.

Bot should not be always online.

Implement a feature to take a rest every hour or so. E.g. 60 mins up and 30 mins down. Make this configurable through config.json

**Comment by JoNMii** [comment]
Server busy was happeninf from the beggining. I think this is paranoid but a scheduler is a good idea,

**Comment by vfuyong** [comment]
It is hard to know whether server busy is related to turning monitoring on or off at server side. I assume server side does not want to track every user because it is too heavy. So they can use some heuristics to turn on monitoring. The easiest way may be "if a player plays for too long and received too much reward, turn on monitoring for a while".

I just started to try this on and off idea with Windows scheduler. Let me see what happens.

**Comment by ridalarry** [comment]
I like this idea
