### ISSUE TITLE
help me :)

### ISSUE THREAD

**Issue by celalibo** [NoxxDev/NecroBot#7]
i get this problem

[19:30:45] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[19:30:46] (ERROR) Error: System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
konum: PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.M oveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
konum: PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22 .MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.Valida teEnd(Task task)
konum: PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask. <Execute>d__2.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
konum: PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0. MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
konum: PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3 .MoveNext()

**Comment by 245trioxin** [comment]
what happens when you log into the app?

**Comment by celalibo** [comment]
this is new account

**Comment by DragonHeart69** [comment]
Have you accept de TUP & finisch de first mission?

**Comment by celalibo** [comment]
yes. i did 
already 2 level

**Comment by 245trioxin** [comment]
re download and try again

**Comment by celalibo** [comment]
dont work :)

**Comment by liamsi95** [comment]
celal, nasil oldu simdi ? yapabildinmi ?

**Comment by liamsi95** [comment]
bende ayni problem var

**Comment by liamsi95** [comment]
CELOO, tamam buldum. bunu indir [https://www.microsoft.com/fr-FR/download/details.aspx?id=48145](url) ve olacak normalde. iyi eglenceler

**Comment by NoxxDev** [comment]
This error occurred in lower versions for v0.8.9 and is a probably ban
