### ISSUE TITLE
Ignoring AutoUpdate

### ISSUE THREAD

**Issue by JoNMii** [NoxxDev/NecroBot#70]
Even autoupdate is off, bot tries to update.

**Comment by Chaaaaaaaaarlie** [comment]
No, that's   "CheckForUpdates": true,

**Comment by JoNMii** [comment]
I set false two options but it ignores. I have to remove the update code to prevent updating and imposibiliting testing my code.

**Comment by JoNMii** [comment]
Its working for you @Chaaaaaaaaarlie ?
