### ISSUE TITLE
[IDEA] First Catch, and automatic username for accounts.

### ISSUE THREAD

**Issue by TakRiuto** [NoxxDev/NecroBot#703]
Title

**Comment by CreativiTimothy** [comment]
Your title is really vague

**Comment by TakRiuto** [comment]
Complete Tutorial (Style, Name, First Catch) :l Title say all... Is for more secure, a account without username and first capture in lv 15 (example) is not possible, if add Auto-Complete Tutorial, is more safe, and more human, because if you dont complete tutorial, is not possible play Pokemon GO (Legal)

**Comment by willyambrito** [comment]
Why dont you just create the account, log in through your phone, do the first catch, set the name and ONLY AFTER IT ALL you use the bot?

**Comment by CreativiTimothy** [comment]
Oh. Yeah, good idea. Should be optional though of course.

AcceptTOS: True/False
CatchStarter: True/False

For the account name however, it's better and faster just to log into your phone

**Comment by kalamera** [comment]
Some ppl are just too lazy...
Maybe dev should even add the option to create email, create ptc account and verify the email address using the link in verification email :)

**Comment by TakRiuto** [comment]
Well, Noxx add function ^^ So... Nice job :D

2016-08-30 3:29 GMT-04:00 kalamera <notifications@github.com>:

**Comment by NoxxDev** [comment]
Added First tutorial...
