### ISSUE TITLE
Unable to find pokestop??

### ISSUE THREAD

**Issue by sunny18pc** [NoxxDev/NecroBot#705]
Now when I try to use bolt it says unable to find pokestop in your area why is it?

**Comment by popsoda27** [comment]
softban dude

**Comment by sunny18pc** [comment]
No when I try yo run on phone its working fine!!

**Comment by rjcute123** [comment]
ip ban

**Comment by sunny18pc** [comment]
And how can I find that

**Comment by iwean** [comment]
If your phone use same wifi with your PC.... that how IP Ban work...

**Comment by LeoRedin** [comment]
So I was using the bot fine on my PC, and then went to my notebook and I got this error, different networks btw. What should I do? While Playing on phone I was able to play wonderfully

**Comment by NoxxDev** [comment]
probably IP Ban
