### ISSUE TITLE
Bot admins Keeping Update _

### ISSUE THREAD

**Issue by mucro9** [NoxxDev/NecroBot#708]
Hey they are not keep update almost 6 days whats wrong ?

**Comment by FaruqX** [comment]
https://github.com/NoxxDev/NecroBot/commits/master

**Comment by ilihack** [comment]
hey mean realese

2016-08-30 14:26 GMT+02:00 FaruqX <notifications@github.com>:

**Comment by tws101** [comment]
Well there is a large number of changes they are working in.  Not one day has gone by where work has not been done.
