### ISSUE TITLE
0.9.6.113 HumanWalkSnipe - SpeedUp still under construccion ?

### ISSUE THREAD

**Issue by BoydTM** [NoxxDev/NecroBot#709]
### Expected Behavior
Increased walk speed, but Necro using value from WalkingSpeedInKilometerPerHour instead MaxSpeedUpSpeed

### Actual Behavior
[14:26:15] (SNIPER) (HUMAN WALK) Found Abra spawning | lat: 37.8033126033646, lng: -122.418012554491, dist 684.18m , expired in 04 min 13 sec | Estimate : 04 min 07 sec | Allow spin: Yes | Allow catch : No | Speed 10.60km/h
[14:26:16] (INFO) Traveling to Pokestop: Franklin Bowles Galleries (558m) (105 seconds) (route GoogleWalk)
[14:26:18] (INFO) Walking Speed: Has been changed, 10.53 Km/h to 10.52 Km/h
[14:26:18] (INFO) Walking Speed: Has been changed, 10.52 Km/h to 10.53 Km/h
[14:26:20] (INFO) Walking Speed: Has been changed, 10.53 Km/h to 10.52 Km/h
[14:26:23] (INFO) Walking Speed: Has been changed, 10.52 Km/h to 10.53 Km/h
[14:26:23] (INFO) Walking Speed: Has been changed, 10.53 Km/h to 10.52 Km/h
[14:26:24] (INFO) Walking Speed: Has been changed, 10.52 Km/h to 10.50 Km/h

### Your config.json
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "WalkingSpeedInKilometerPerHour": 10.6,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": true,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },

  "HumanWalkSnipeConfig": {
    "DisplayPokemonList": true,
    "MaxDistance": 150.0,
    "MaxEstimateTime": 60.0,
    "CatchEmAllMinBalls": 20,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": false,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "Enable": true,
    "WalkbackDistanceLimit": 1500.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": false,
    "MaxSpeedUpSpeed": 20.2,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 0
  },
### Other Information
Version: 0.9.6.113
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): CATCH

**Comment by iwean** [comment]
With me it's run...
..
![screenshot_154](https://cloud.githubusercontent.com/assets/4365551/18090103/6732c9c6-6eed-11e6-81b4-790f94ef72eb.jpg)

**Comment by iwean** [comment]
OMG... my Gyarados candies.... :smile_cat:

**Comment by BoydTM** [comment]
Wow ... 60 km/h ... are you trying to mimic a car ? ;). I guess i will have to wait for 0.9.7. So far i just downloaded sources (at the moment of 113 commits after 0.9.6) with git clone --recursive https://github.com/NoxxDev/NecroBot.git and compiled it with Visual Studio ....

**Comment by iwean** [comment]
:dancer:  :smile:

**Comment by tws101** [comment]
are these valid things to add to 9.6

"MaxSpeedUpSpeed": 20.2,
"AllowSpeedUp": true,

**Comment by BoydTM** [comment]
last sources ... or 9.7

**Comment by BoydTM** [comment]
It was my fault, i did not notice that there are indywidual settings ... sorry

    "Eevee": {
      "MaxDistance": 600.0,
      "Priority": 3,
      "MaxWalkTimes": 240.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 0.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 0
    },
