### ISSUE TITLE
throtting API calls

### ISSUE THREAD

**Issue by cuongomega** [NoxxDev/NecroBot#71]
I still got the error "throtting API calls" and it resets back to default location, it might cause my account to teleport

**Comment by NoxxDev** [comment]
"throtting API calls" dont restart in location default

**Comment by cuongomega** [comment]
i have downloaded the visualizer, will check when it got this error again

**Comment by zwerg137** [comment]
i only get the "throttling" when using GPX-Path after exact 30 min. and than its resets to default location. not teleporting but straight walking line throu buildings ..

**Comment by mo0ojava** [comment]
This issue is fixed in version 9. The GPX-tracker now resumes where it was before the "throttle".

**Comment by cuongomega** [comment]
confirm. i watch over the visualizer and it does not reset to default location
