### ISSUE TITLE
PokemonsToIgnore not working

### ISSUE THREAD

**Issue by zsatanxz** [NoxxDev/NecroBot#713]
"PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo",
    "jynx",
    "mrMime"
  ],

**Comment by moonpyk** [comment]
Set UsePokemonToNotCatchFilter to true in your config

**Comment by NoxxDev** [comment]
`"UsePokemonToNotCatchFilter": false,` set `true`
