### ISSUE TITLE
necrobot 0.9.7 

### ISSUE THREAD

**Issue by osmankudu** [NoxxDev/NecroBot#718]
https://github.com/NoxxDev/NecroBot/releases/download/v0.9.7/Release.zip

where is files ?

bot not working

**Comment by likeant** [comment]
I close auto update to make  bot working 

""AutoUpdate": false,"

**Comment by nixeo** [comment]
same here .. just happen to me.. disable the autoupdate & the 0.9.6 should work fine again

**Comment by shilei54220** [comment]
it can be downloaded at this moment

**Comment by MaartenDeen** [comment]
Aw, not cool! You remove every file from the config directory, even my saved config files. Now my previous config is gone.
Do not do that!

**Comment by avntty** [comment]
LOL next time u can back up ur config :)

**Comment by munframed** [comment]
Yep .9.6 was working perfectly and this one doesn't work at all. Possible softban! GPX doesn't even work. More realistic google walking, but no looting (possible softban) or catching. Hope to see a fix :) Thanks guys :+1:
