### ISSUE TITLE
cant connect to google acc

### ISSUE THREAD

**Issue by prozinho** [NoxxDev/NecroBot#719]
Im having auth error not connecting to my google acc 
 "AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": mail,
    "GooglePassword": pw,
    "PtcUsername": null,
    "PtcPassword": null
   isnt this how it is supposted to be ?

**Comment by ComputerApp1234** [comment]
"mail" & "pw"

**Comment by prozinho** [comment]
yh just figured it out thx anyway

**Comment by MrProblematic** [comment]
Fecha a issue mano.. XD
