### ISSUE TITLE
virus found

### ISSUE THREAD

**Issue by CharlesChung** [NoxxDev/NecroBot#72]
when I download the release.zip my trendmicro indicates a virus is found:
http://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/HKTL_POGOBOT

**Comment by Chaaaaaaaaarlie** [comment]
yes, that's what we call a "false warning" :p 
No for real, it's not a virus. Some AV just don't like some (or even one) of the functions.

**Comment by metalmouth** [comment]
and the descriptions says it all. not a surprise lol

**Comment by albysprx** [comment]
0/68 https://www.virustotal.com/it/url/7b68b8c9babde88f118be99bfb9bed2fde592bc2cfc22db8b77e3237db306ef6/analysis/
