### ISSUE TITLE
Thank You Guys

### ISSUE THREAD

**Issue by mucro9** [NoxxDev/NecroBot#720]
İ like use new released i really liked this.You guys doing great...Keep it continue

**Comment by pokebug** [comment]
thats true good job. Lets donate ! There are pretty much hours of work spent for us !

**Comment by mucro9** [comment]
Excatly..Lets Donate

**Comment by vfuyong** [comment]
Great effort.

**Comment by iPollox** [comment]
@NoxxDev this! I didn't change a single setting since 0.9.6, with 0.9.7 my EXP/H increased by 5-6K per hour, seems a lot more stable.
