### ISSUE TITLE
Can someone explain Telegram to me, and how to set it up? Thanks!

### ISSUE THREAD

**Issue by raymonders** [NoxxDev/NecroBot#721]
Title says it all :)

**Comment by LightDestory** [comment]
1) Install Telegram on your Phone
2) Find @BotFather
3) Create a new Bot
4) Copy the Token on Clipboard (or just write it on paper to remember it)
5) Start NecroBot 0.9.7 and when it asks you if you want enable Telegram Feature press Y and Enter
6)When the bot asks the Telegram API Key enter the Token of before.
7)As password the default is 12345
8)Finish

**Comment by iwean** [comment]
Or after you Copy the Token to Clipboard...
Just go to Upper Left Corner windows of the bot.
Right Click on the big RED letter **_N_** of NecroBot.
Paste your Token.

![screenshot_155](https://cloud.githubusercontent.com/assets/4365551/18109954/09c2aba6-6f3f-11e6-99c9-fbb18efba68b.jpg)

**Comment by raymonders** [comment]
thanks @LightDestory and @iwean
