### ISSUE TITLE
Pokestop counter (of the limit) increases dramatically after reconnection/error/exception

### ISSUE THREAD

**Issue by CreativiTimothy** [NoxxDev/NecroBot#736]
From 458 to 808

> [19:20:48] POKESTOP LIMIT **458**/1989
> [19:20:49] Name: Passage Sculpture, San Francisco XP: 50, Gems: 0, Items: 3 x ItemPokeBall, Lat: 37.802704, Long: -122.43171
> [19:20:50] Not enough Pokeballs to start sniping! (71/100)
> [19:20:50] Traveling to Pokestop: Moscone Center (44m) (8 seconds) (route NecroBot)
> [19:20:51] Looking for Pokemon...
> [19:20:52] Looking for incense Pokemon...
> [19:20:53] Looking for Pokemon...
> [19:20:54] Looking for incense Pokemon...
> [19:20:54] Looking for Pokemon...
> [19:20:55] Looking for incense Pokemon...
> [19:20:56] Looking for Pokemon...
> [19:20:57] Looking for incense Pokemon...
> [19:20:58] Looking for Pokemon...
> [19:22:43] Current Operation was canceled.
> [19:22:43] Logging in using Google
> [19:22:45] Playing as XXXXXXXXXXX
> [19:22:45] Detected realistic Traveling , using Default Settings inside config.json
> [19:22:45] Make sure Lat & Lng are right. Exit Program if not! Lat: 37.8029124921598 Lng: -122.431764820889
> [19:22:45] Potential Evolutions: 48
> [19:22:45] Waiting to evolve 48 Pokemon once 141 more are caught! (98/239 for 99% inventory)
> [19:22:46] Incubated egg has hatched: Oddish | Lvl: 20 CP: (624/656) IV: 77.16%
> [19:22:46] Putting egg in incubator: 5.00km left
> [19:22:48] Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 125/151
> [19:22:51] Traveling to Pokestop: Moscone Center (20m) (3 seconds) (route NecroBot)
> [19:22:52] Looking for Pokemon...
> [19:22:52] Looking for incense Pokemon...
> [19:22:53] Looking for Pokemon...
> [19:22:54] Looking for incense Pokemon...
> [19:22:55] Looking for Pokemon...
> [19:22:56] Looking for incense Pokemon...
> [19:22:56] Looking for Pokemon...
> [19:22:57] Looking for incense Pokemon...
> [19:22:58] POKESTOP LIMIT **808**/1989

**Comment by moo23** [comment]
Same here

**Comment by Brazuca87** [comment]
Yeah, I've already mentioned this in another thread (can't recall which). If bot throws an exception or something, the amount of stops and pokemons nearly doubles, as some (most) of the lines under PokemonTS.txt and PokestopTS.txt get duplicated, which starts causing issues.
