### ISSUE TITLE
Telegram not working

### ISSUE THREAD

**Issue by yoyo334** [NoxxDev/NecroBot#738]
### Expected Behavior
When setting up 0.9.7, it asked if I wanted Telegram enabled, I said yes and set it up, so I could check on the bot while out of the house.

### Actual Behavior
When I try to start the bot it says: (ERROR) Unkown Telegram Error occured.

### Your config.json
```

    "MaxTravelDistanceInMeters": 1000
  },
  "TelegramConfig": {
    "UseTelegramAPI": true,
    "TelegramAPIKey": "mytelegramkey",
    "TelegramPassword": "12345"
  },
  "GPXConfig": {

```

### Other Information
Version: 0.9.7
Windows Version: 10 (anniversary
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Telegram

**Comment by yoyo334** [comment]
Didn't read tutorial properly

**Comment by yoyo334** [comment]
Still not working

**Comment by iwean** [comment]
Have you restart the bot?

**Comment by NeiPCs** [comment]
Is working perfect, I've tested. 
Have you cleaned your config after upgrade to 0.9.7?

**Comment by NoxxDev** [comment]
Telegram is working, check your settings and api for telegram

**Comment by yoyo334** [comment]
100% clean install
