### ISSUE TITLE
Necrobot 9.7 doesn't recycle automatically.

### ISSUE THREAD

**Issue by jack062287** [NoxxDev/NecroBot#745]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by tanjj92** [comment]
i notice this too, not like previous version.

**Comment by NoxxDev** [comment]
`"UseNearActionRandom": true,`

https://github.com/NoxxDev/NecroBot/commit/d887d6a84a5ce82613eebbf6304a3faf7e7d4e09
https://github.com/NoxxDev/NecroBot/commit/6a675ac3ac25c6bafbcaee94c768daa9f8cadad7
https://github.com/NoxxDev/NecroBot/commit/e24efc0ee3d8cc36a83ff38485a0be3aaa777e28
