### ISSUE TITLE
0.9.7 + necrobotvisualizer 1.1.0 Favorite pokemon not work.

### ISSUE THREAD

**Issue by hefenglim** [NoxxDev/NecroBot#748]
### Expected Behavior

Necrobot 0.9.7 + necrobotvisualizer 1.1.0, Favorite pokemon not work.
but
Necrobot 0.9.6 + necrobotvisualizer 1.1.0, Favorite pokemon is ok no problem.

its is a bug come out??

### Other Information
Version: 0.9.7
Windows Version: Windows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by samuraitruong** [comment]
visualizer it not a best option. PokeEase is much nicer . I also implement human walk into it.

![image](https://cloud.githubusercontent.com/assets/1183138/18127641/067dc724-6fc5-11e6-8653-7b16095df02b.png)

**Comment by hefenglim** [comment]
where can download get this PokeEase ? i look at github not releaes yet?
