### ISSUE TITLE
Something to make it safer

### ISSUE THREAD

**Issue by whiskey2wine** [NoxxDev/NecroBot#75]
I have seen some other bot just implemented the human walk path or something like that(doesn't walk on the water or walk through the building). This is very good if combine with your varies walking speed.
I hope to see this feature in the new update. :p

Just try to make the best bot better. :)

**Comment by vfuyong** [comment]
In short term, it is easier to implement a variance of direction while walking. so it appears to be more irregular. The GPS move doesn't need to be a perfect straight line.

**Comment by NoxxDev** [comment]
Already implemented in v0.9.2 or upper
