### ISSUE TITLE
Softban issues at certain location.

### ISSUE THREAD

**Issue by Euphoniouz** [NoxxDev/NecroBot#76]
I'm getting softban whenever I configure bot in a certain location. And I'm only just a 10 minute ride from it. Here's my config.

 "DefaultLatitude": 14.5965787,
  "DefaultLongitude": 120.9446316,
  "WalkingSpeedInKilometerPerHour": 5.16,
  "UseWalkingSpeedVariant": true,
  "RandomlyPauseAtStops": true,
  "ShowVariantWalking": false,
  "MaxSpawnLocationOffset": 10,

**Comment by PoppaCoder** [comment]
go less than 5km/h

**Comment by Euphoniouz** [comment]
Just got fixed. I have to reinstall 
    Net Framework 4.6.2
    Visual C++ Redistributable for Visual Studio 2015
