### ISSUE TITLE
Recycle Item.

### ISSUE THREAD

**Issue by tansengcopao** [NoxxDev/NecroBot#760]
What does this code do? and how does it work? Thnx

"RandomizeRecycle": false,
"RandomRecycleValue": 5,

**Comment by Brazuca87** [comment]
Read the [Wiki](https://github.com/NoxxDev/NecroBot/wiki/Config#recyclingitems)

**Comment by NoxxDev** [comment]
[Wiki] (https://github.com/NoxxDev/NecroBot/wiki/Config#recyclingitems)
