### ISSUE TITLE
0.9.7 Some pokemons are not transfered according to setup: slowbro.

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#765]
Some pokemons are not transfered according to setup: slowbro.

I dont have any config set for slowbro and keep dup is 1. Anyone encountered the same problem?

**Comment by NoxxDev** [comment]
they are not transferred at a later time?

`"UseNearActionRandom": true,`

**Comment by vfuyong** [comment]
Nope, they are not. That is why I am a bit confused. Yeah, I do have UseNearActionRandom set to true. Should I turn it off?

**Comment by vfuyong** [comment]
Update: Please ignore clefable as it is due to wrong config. But slowbro is still a problem, I usually see 8 or 9 slowbros.

**Comment by NoxxDev** [comment]
Your config.json please

**Comment by vfuyong** [comment]
@NoxxDev 
http://pastebin.com/qMwigYfY

**Comment by vfuyong** [comment]
potentially a config problem
