### ISSUE TITLE
0.9.7 Suggestion to reduce softbans

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#772]
I am mostly certain that softban can be caused by frequent user actions. But some user actions do not have delay, e.g. rename.

Can we add a delay for rename and other actions with no delay at the moment? Potentially we can randomize the delay within a range e.g. 4 to 6 seconds.

**Comment by CreativiTimothy** [comment]
make it optional though

**Comment by zapahacks** [comment]
+1...autofavorite doesnt respect the delay either. It would be nice to have a delay for all the actions with real times...It wouldnt hurt anyone, at least to respect the app animation times and average times for user actions.

**Comment by NoxxDev** [comment]
Added
528b7e5367a03880dc5a1a08f702a89856e79f3e
235feb20ae76893d7d98737e559f72ad953c6088
