### ISSUE TITLE
0.9.7 Suggestion - Do not transfer during a catch

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#775]
I noticed transfer can happen any time even during a catch. Can we have this disabled? So it only transfer while not catching?

**Comment by mo0ojava** [comment]
This is the same as #644. It happens rather often as well. It's like the transfers are *triggered* alongside CatchPokemon. Tried to find a remedy but never came up with anything that worked unfortunately.

**Comment by vfuyong** [comment]
This is an internal state machine problem I guess. You can't resolve by changing config.

**Comment by petpetpetvm** [comment]
honestly, i don't think it's really a big problem, because in the game, you can click into the pokemon -> click run -> the pokemon still there as long as it didnt flee or despawned.

**Comment by langit7** [comment]
i do most of time when im in bus, i take break after some miss throw  then back

**Comment by NoxxDev** [comment]
Fix in 17d3726b4c13a59d6dfd332229c3230027c989ff
