### ISSUE TITLE
[Issue] MSniper.v1.0.3 not working at 0.9.7

### ISSUE THREAD

**Issue by Pokego0108** [NoxxDev/NecroBot#776]
I can found SnipeMS.json in 0.9.7 folder but not work
I'm using same config, working at 0.9.6

and some issue on 0.9.6 is 
[13:51:50] (MSniper) Sniping a Arcanine with Unknown IV at 22.470769,114.010007...
[13:51:52] Did not find a Pokemon within the Location, pokemon despawned?

However I can snipe it with pokesniper2 , is there have any config I can change to fix it?

**Comment by iwean** [comment]
HumanWalkSnipe must disable first

**Comment by iwean** [comment]
Work smooth with me :+1: 
...
![screenshot_163](https://cloud.githubusercontent.com/assets/4365551/18159447/f4c31d20-7052-11e6-8f3b-3a87353614b0.jpg)

**Comment by petpetpetvm** [comment]
i'm sorry but how can we use it ?

**Comment by catch-snorlax** [comment]
Begini ya om iwean? 
 },
  "LocationConfig": {
    "DisableHumanWalking": true,
    "StartFromLastPosition": true,

**Comment by iwean** [comment]
@catch-snorlax BUKAAAAAANNN !!!!
Kalo yg itu yg di non-aktifkan, bisa kelacak sama "Mbak Nia" kalo kamu pake bot.
Itu fasilitas agar bot terlihat seperti manusia berjalan (human walk)

Yg di non-aktifkan itu bagian HumanWalkSnipe Config.
"Enable": false,

**Comment by ntatoo** [comment]
@iwean lu bisa share config lu ?

**Comment by iwean** [comment]
@ntatoo Ntar ya bro. Masih di kantor ini.

**Comment by msx752** [comment]
> "Enable": false 
"UseSnipeLocationServer": false
"SnipeAtPokestops": false

must be

**Comment by iwean** [comment]
Nah... the dev of MSniper is here >>> @msx752 :+1:

**Comment by Pokego0108** [comment]
can we get both work?

**Comment by iwean** [comment]
@Pokego0108 As you see on my screenshot, both work perfectly!

**Comment by Pokego0108** [comment]
I mean HumanwalkSnipe and MSnipe work in same time. well I find the code in source and changed it, its both working now.
but How to improve "Did not find a Pokemon within the Location, pokemon despawned" for MSnipe?
I pretty sure the pokemon in that location because I can snipe it with Pokesnipe2, 
so is there hv any config( like "scanoffset"?), that I can change in config or source code?

**Comment by iwean** [comment]
Hmm... can you share that code to @msx752 ? Or can you make PR on that project? 
https://github.com/msx752/MSniper/

**Comment by msx752** [comment]
using HumanwalkSnipe  and MSnipe at the same time cause permanent ban.
I do not recommend

**Comment by Pokego0108** [comment]
Oh I see, got it! I will disable it, Thanks @msx752 
the MSniper1.0.4 is awesome btw :+1:

**Comment by Vilicat** [comment]
Same issue there

> I can found SnipeMS.json in 0.9.7 folder but not work
> I'm using same config, working at 0.9.6
> 
> and some issue on 0.9.6 is 
> 13:51:50 Sniping a Arcanine with Unknown IV at 22.470769,114.010007...
> [13:51:52] Did not find a Pokemon within the Location, pokemon despawned?
> 
> However I can snipe it with pokesniper2 , is there have any config I can change to fix it?

My config values : 

"Enable": false 
"UseSnipeLocationServer": false
"SnipeAtPokestops": false
"CatchPokemon": true

Sometimes catch it , but most do not.

Thx for you awesome work!!!

>
