### ISSUE TITLE
[Feature Request] Motion Sensor Input

### ISSUE THREAD

**Issue by gogr33n** [NoxxDev/NecroBot#78]
Okay, so, since the general trend seems to be making things as convincing as possible (because nobody seems to know, how n*antic actually bans), I'd propose simulating varying motion sensor input.
I don't really know, if the motion sensor even plays a role in the data communication to the servers (I think it does), but I can't stop think about it. Nobody can keep their phone absolutely still while moving.

You guys already have made great accomplishments with 

Humanized:
- walking/pathing
- ball-throwing (incl. misses)
- moving speed

... the last thing that comes to mind is the motion sensor. 
I hope it's worth checking out, if not, at least for future eventualities.

Greetings, gogr33n

**Comment by ridalarry** [comment]
It could help

**Comment by gogr33n** [comment]
I'm not quite sure, but I've read several times now that motion sensor data is included in the data encrypted in uk6. If that's true, we should definitely have that.
