### ISSUE TITLE
Catching Limit

### ISSUE THREAD

**Issue by iPollox** [NoxxDev/NecroBot#782]
So the catch limit and pokestop limit are default on my config.
I reached the limit for the catch limit, and I closed the bot for over 24 hours, when I run the bot it catches pokemon normally and says that the catch limit is currently 998/998.

Same thing happened with the pokestop, I reached 1998/1998 and closed it for many hours but the bot is now saying 1998/1998 and still get the pokestops and such. shouldnt the limit reset back 0? seems like the catch/pokestop limit will never reach the limit again and will never stop.

@NoxxDev

**Comment by mjusuf** [comment]
delete PokemonTS.txt and PokestopTS.txt from your Config folder

**Comment by emwedk** [comment]
Upper Mentioned Fix Confirmed

**Comment by hardknoxni69a** [comment]
this does work but then it isnt giving us accurate results must be a way to have counter reset after specified time the code in the log should represent some time scale that is always being updated so minute by minute you dont have to worry about going over your values

**Comment by NoxxDev** [comment]
Fix on 82ccd53205d2b8d094e74a21ff4932646c7873fc
