### ISSUE TITLE
Not credited code

### ISSUE THREAD

**Issue by Lunat1q** [NoxxDev/NecroBot#783]
Greetings dear dev, i hope you can give some credits to the code you tool from me with no proper credits.
[Example1](https://github.com/NoxxDev/NecroBot/blob/master/PoGo.NecroBot.Logic/State/CheckTosState.cs), taken from: [Source](https://github.com/Lunat1q/Catchem-PoGo/blob/master/PoGo.PokeMobBot.Logic/State/CheckTosState.cs)

**Comment by emwedk** [comment]
Greetings Lunat1q and welcome to Github - where you publicly announce your sourcefiles and codes.

First of all - since you haven't put a copyright on your Github page, it can't be "stolen" - as fine as you may put it.
Tho I C that it would have been nice of them to nod down a commentary inside the code which says ,,This Piece was found @ Lunat1q´´ and blablabla - Then again, you haven't written any copyrights in your code anyways ;)

Next - if Nec is stealing from you ... then what have you been doing with all of your sourcefiles? 
i mean - come on buddy - join the fight !

**Comment by Lunat1q** [comment]
What do you mean? It's my bot project.
Or i put credits inside every file? it's rediculous.

**Comment by jumitate** [comment]
the first post was not about using the code or rights on the code (copyright), but about giving credits to those that created the initial/original code or the code your work is based on. 

when you "inspire","borrow","copy","use","work on","enhance",etc. from code started or created by another you should give credits, otherwise without giving credits is considered theft.

sourcefiles are usually made public for two purposes:
-other devs/users can check the code for malicious intent
-other devs can work/collaborate to create a better product

**Comment by Skolzack** [comment]
Stop crying and do the best for all us players, thank you!

**Comment by kalamera** [comment]
men, just give him the credit ;)

**Comment by emwedk** [comment]
I am rather new to Github and I spoke from simple logic.
Also, I did regard the topic that it would be nice of the Dev's to include a "This Code was found @"

Real Question is if OP does that for the Codes he have copied from other sources.

Though, the way he presented himself could have been in a much nicer manner. E.g. NOT using the word "Stole"
IMO

**Comment by Skolzack** [comment]
Yea, he was rude.

@NoxxDev don't give any fucking credit to him, he wasnt nicer.

**Comment by Lunat1q** [comment]
@emwedk agree, i was just a bit surprised.
Text changed to be more polite.

**Comment by Skolzack** [comment]
@Lunat1q No, get the fuck out of here!

**Comment by kalamera** [comment]
:)

**Comment by NoxxDev** [comment]
@Lunat1q 

As you can see, this code was not I who did it, was requested through the PR by @LightDestory

**Comment by Skolzack** [comment]
@NoxxDev Dont worry Noxx, keep up the good work!


Maybe when he learn to be more humble they give credit to him, otherwise fuck him and his code :)

**Comment by Lunat1q** [comment]
@NoxxDev still, i just inform you, what some of your collaborators did it, and someone accepted it.

**Comment by Brazuca87** [comment]
@Lunat1q well, knowing where people are getting their stuff from, if not informed by the submitter, is a hard and time consuming task. "Ain't nobody got time for that"...

Whoever created the code should have mentioned it. It's even written as a reminder/best practices under new PR request:
`4. If the code is based off another individuals work, be sure to credit them appropriately.`

**Comment by kalamera** [comment]
give him the credit and move on :)

**Comment by emwedk** [comment]
^^

**Comment by jinyister** [comment]
@Skolzack stop been an asshole. u are destroying the open source spirit. this will make everyone go close source.
@NoxxDev will appreciate if you do credit it. otherwise it only paints a bad picture of u with the bad comments from people like @Skolzack

**Comment by emwedk** [comment]
@Skolzack is definately a League player Kappa

**Comment by NoxxDev** [comment]
I don't have time to check the origin of all PR, but to resolve this issue, although I really didn't have to do, I will credit

**Comment by LightDestory** [comment]
WAIT A MOMENT @NoxxDev I did request the code... The PR of this code was #690.
I just edited it and now the gender and starter are not random

**Comment by LightDestory** [comment]
And on #690 the source has been credited!

**Comment by NoxxDev** [comment]
@Lunat1q 
was credited even
There was a mistake on your part

**Comment by Lunat1q** [comment]
@NoxxDev 
Thanks not a mistake, when there is no links or git mention.

**Comment by jinyister** [comment]
Sorry @NoxxDev. Erm where is the credit I can't seem to find it. Thanks for the credit if I miss it :)

**Comment by Finrod87** [comment]
Yepp, this isnt a proper credit. shame on u!

**Comment by LightDestory** [comment]
@Lunat1q there is a bold section with big char "Credits", what do you want more? The man who posted used a prefab post, i think.

**Comment by jinyister** [comment]
@LightDestory I went to the "Credits" on https://github.com/NoxxDev/NecroBot and I don't see it? You know where is it?

**Comment by LightDestory** [comment]
@jinyister 
![immagine](https://cloud.githubusercontent.com/assets/5560558/18169717/b3ed7ddc-705b-11e6-8812-463df589373e.png)

**Comment by Lunat1q** [comment]
yeah, best credit ever :)
make it white text, it will be even better.
i'm done with this.

**Comment by Finrod87** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/21174891/18169890/6c06b99c-705c-11e6-93de-cbb78968d172.png)

No Credit here. There u should mention him with a link. everything else is just a farce and no credit to his work.

**Comment by NoxxDev** [comment]
@Lunat1q @Finrod87 

![](http://puu.sh/qWeOg/d2bcf9558f.png)

**Comment by LightDestory** [comment]
@Finrod87 So do you want 280+ names on the Credits tab of Main Project? "Thanks to everyone who voluntereered by contributing via Pull Requests!"....

**Comment by LightDestory** [comment]
The next time... set your project as private then. This is a dev community.

**Comment by Finrod87** [comment]
Thanks @NoxxDev

**Comment by jumitate** [comment]
seems that the way forward with this kind of attitude is to encourage every developer to keep his work private and NOT to share - everyone for himself.

what's easier, to give some credits to people that contributed (directly or indirectly) or to write/develop/do everything from scratch?

**Comment by LightDestory** [comment]
Yep, I said a very very stupid thing. Sorry about that

**Comment by jim16127** [comment]
I would have closed my source after these antics, too. All the guy wanted was proper credits. Now his source is closed! I hope everyone got what they were wanting.
@Lunat1q Thank you very much for your extremely elegant bot. I tell all my friends and family about it. By far the BEST BOT!!! Please continue the awesome work. Hope your girlfriend doesn't get fed up with your project. :)
