### ISSUE TITLE
Release 0.9.7 and 0.9.6 crashes on startup

### ISSUE THREAD

**Issue by Xander9188** [NoxxDev/NecroBot#788]
### Expected Behavior
I'd hope that the bot would ask for login info, location coords, etc.

### Actual Behavior
Bot crashes on startup

### Your config.json
```
your config here
```
?? I can't even find it...
I was told to try deleting it but all I have is NecroBot.exe.config, but no config.json
Translations is the only thing in config/ so I am quite confused as to where auth.json and config.json is.
I am pretty sure this is the problem so does anyone have a working auth.json and config.json that you can send to me?

### Steps to Reproduce
Download Release.zip
Extract
Run exe file
It crashes...

### Other Information
Version: 0.97 & 0.96 
Windows Version: Windows 8.1
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
![image](https://cloud.githubusercontent.com/assets/10556343/18171858/055c5f90-7029-11e6-9688-28969bbfd37a.png)

**Comment by Brazuca87** [comment]
You seem to only have 3 files inside the Release folder, did you put all the files from the .zip file on your bot folder location?

**Comment by Xander9188** [comment]
yep

**Comment by Xander9188** [comment]
![image](https://cloud.githubusercontent.com/assets/10556343/18172652/e1c3d61e-702b-11e6-8bf4-66d22a6f53a0.png)

**Comment by Brazuca87** [comment]
Have you installed the pre-requisites? .NET Framework and C++ Redist?

**Comment by Xander9188** [comment]
![image](https://cloud.githubusercontent.com/assets/10556343/18172706/2d3d7b68-702c-11e6-9529-fe2df23b4eee.png)
this is straight from github, unextracted. I think have all of the files in the zip.

**Comment by Xander9188** [comment]
yes i have those. I was able to run 0.8.6 bot back before they took that github page down. Now that i found this new necrobot site nothing seems to work

**Comment by NoxxDev** [comment]
You Download manually or by bot update?

**Comment by Xander9188** [comment]
manually, and right now i am trying to fix it by downloading 0.8.8 and doing a bot update; going well so far

**Comment by Xander9188** [comment]
yeah ok as soon as i said that, it crashed again. 0.8.8 starts up and runs just fine. it asks for google account and coords, etc. as soon as it updates and i reopen the updated exe file, it crashes just like shown in the picture except that there are leftover files from 0.8.8

**Comment by joe1chen** [comment]
It does not upgrade will.  Too many config changes.. just start from scratch.  Rename your config folder and have the bot generate a clean one.

**Comment by Xander9188** [comment]
Yeah, i tried that. The exe file still crashes though...

**Comment by Brazuca87** [comment]
You might want to try discord for assistance. I doubt this is a bot issue.

**Comment by Xander9188** [comment]
hmm ok. Discord isn't offering much help to me XDD ill give it a shot though. I appreciate your time.

**Comment by Brazuca87** [comment]
Have you tried removing the Config folder altogether? Let the bot recreate it from scratch.

**Comment by Xander9188** [comment]
yep. same crash error though :/

**Comment by Xander9188** [comment]
Actually here is what ill try... when i get back home today (im leaving in a sec) ill try installing everything on a virtual machine and see how that goes

**Comment by loquendomia** [comment]
Could be a problem with your config.
Just go to discord, we will solve your problem.

**Comment by ken9810** [comment]
or maybe you can try run the bot as administrator mode

**Comment by NoxxDev** [comment]
Fix

https://github.com/Prawith/NecroBot/commit/a43254c407dfe847c92ddfcbb6d54209e3144f43
https://github.com/NoxxDev/NecroBot/issues/803
