### ISSUE TITLE
[feature request] Pause boting

### ISSUE THREAD

**Issue by askovpen** [NoxxDev/NecroBot#79]
That bot like more human-like, need relogin with pause(10-15 sec every 30min-hour). i think

**Comment by Kongen8800** [comment]
You can download my application. You set the time yourself.
http://www.mediafire.com/download/glfyw91x86f2ph3/Kongen%27s_PoGo_BOT_Timer_1.0.0.9.zip

**Comment by ridalarry** [comment]
Thanks this is great to have

**Comment by Kongen8800** [comment]
Np. You are free to share it, new releases are posted here:
https://discord.gg/WsSpJab

**Comment by NoxxDev** [comment]
This is unlikely to be implemented

**Comment by Kongen8800** [comment]
NoxxDev my app got it anyways. People can just use that istead.
