### ISSUE TITLE
How are the IV calculated?

### ISSUE THREAD

**Issue by Danny-0815** [NoxxDev/NecroBot#792]
### Expected Behavior
The IV stated by NecroBot should match the ones stated by pogobag.me

### Actual Behavior
The IV stated by NecroBot differ from the ones stated by pogobag.me by a few percent (usually 1-3. In some cases, they actually match.)

I was just wondering, how NecroBot calculates the IV? Is it more precise than pogobag.me? Since this website is only adding up the three individual integers of attack, defense and stamina (each 1-15, no decimals) and divides them by 45.

**Comment by CreativiTimothy** [comment]
I use PokeNurse (https://github.com/vinnymac/PokeNurse) and it is very accurate as it takes the IVs out of the game instead of calculating them. I'm not sure how it does it, but I guess here's the source code:
https://github.com/vinnymac/PokeNurse

**Comment by Brazuca87** [comment]
Those sites usually calculate as a flat % for each point. Here, it's not calculates as a simple %. It's more like in the game, where CP is influenced more by Attack value than the other 2.

PoGoBag probably does a simple Atk+Def+Stam/45 (so basically 1 Atk = 1 Def = 1 Stam
Necro gives more weight to Atk. I believe 1 Atk > 1 Stam > 1 Def, but not completely sure, would need to look up the logic...

**Comment by petpetpetvm** [comment]
That's why i always look up A/D/S numbers, 15/15/15 so i know which one is strong for which ones.
And lower the %IV of transferring, example,i want to keep 15-15-13 which is around 95%, i put 90% in necro so it doesnt transfer wrong ones

**Comment by NoxxDev** [comment]
View logic in https://github.com/NoxxDev/NecroBot/blob/master/PoGo.NecroBot.Logic/PoGoUtils/PokemonInfo.cs#L34-L93
