### ISSUE TITLE
(Bug) Human Sniper Not Following Filter For Some

### ISSUE THREAD

**Issue by hardknoxni69a** [NoxxDev/NecroBot#794]
@NoxxDev 
I added filters for all my snipeable pokemon so problem is i have it set to loot all stops and catch pokemon for all my filters but for some reason some of the pokemon do not catch along the way such as my bulbasaur this is when i noticed it ran the snipe report and chose bulbasaur as target but in the description it said catch no. also note that it does not wait the 5 secs to allow scanning of area to update just in case speed was to fast? just think the bot is somehow bypassing it even my global human snipe settings are correct i believe

Actual 
[20:10:20] (HUMAN WALK) Found Bulbasaur spawning | lat: 37.7693389666982, lng: -122.465521229752, dist 498.99m , expired in 02 min 53 sec | Estimate : 00 min 59 sec | Allow spin: Yes | Allow catch : No | Speed 40.00km/h
[20:11:15] (HUMAN WALK) destination reached | lat: 37.7693389666982, lng: -122.465521229752 | wait :0.00 sec
    "Bulbasaur": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 40.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 5

"HumanWalkSnipeConfig": {
    "DisplayPokemonList": true,
    "MaxDistance": 3000.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": true,
    "SnipingScanOffset": 0.025,
    "Enable": true,
    "WalkbackDistanceLimit": 3000.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 40.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 5000

**Comment by Brazuca87** [comment]
`"DelayTimeAtDestination": 5` that is 0.005s, which is the time you waited. About the catch, maybe you didnt have enough balls? or maybe you have a duplicate in your filter?

**Comment by langit7** [comment]
maybe "UseNearActionRandom": false, or "SpinPokestopWhileWalking": true,

**Comment by samuraitruong** [comment]
if you don't have enought time to catch pokemon, that will turn off.

rules is base on distance. (1pokemon/100) * 3x delaybetween catch

for example . I set 3 sec for every catch action. I walk for 1000m, so  time for that feature turn on is 10 *3 *3 = 600s + time to travel 1000m. that mayneed to have config to turn that rules off. but if you turn that off, you will miss lot pokemon

**Comment by hardknoxni69a** [comment]
thank you folks total durr moment with the 5 instead of 5000. ill look into the logs to see if it is just the ones that are to far so wouldnt have time to catch along the way
