### ISSUE TITLE
Getting this exception when initializing for the first time

### ISSUE THREAD

**Issue by DavidSelem** [NoxxDev/NecroBot#795]
Bot getting an exception caught after first and fresh run.

### Expected Behavior
Bot should be initiated asking for config

### Actual Behavior
Exception caught, writing LogBuffer

### Your config.json

Bot doesn't even create config
### Steps to Reproduce
Download latest commits, compile and run

[http://i.imgur.com/CFclUk0.png](http://i.imgur.com/CFclUk0.png
)
### Other Information
Version:
Windows Version: 10 Anniversary Update
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by iwean** [comment]
Press Y for rebuild Language folder

**Comment by DavidSelem** [comment]
@iwean Won't let me, Necrobot instacrashes, can't type

http://i.imgur.com/iacbSu0.png

**Comment by iwean** [comment]
Move your Config folder & Log folder to New Folder for backup.
Than run the bot... let the bot make that folder for you.

**Comment by ntatoo** [comment]
@iwean the new one
mine too
@NoxxDev 

![untitled](https://cloud.githubusercontent.com/assets/20683618/18191125/0a7e99c4-70f2-11e6-82bf-b9fc04c8c20f.png)

**Comment by iwean** [comment]
@ntatoo Are you answer Y/N ?

**Comment by ntatoo** [comment]
@iwean i dont asnwer yet
try your self
[Release.zip](https://github.com/NoxxDev/NecroBot/files/451080/Release.zip)

**Comment by iwean** [comment]
@ntatoo Delete Config folder than try run again...
....
![screenshot_2](https://cloud.githubusercontent.com/assets/4365551/18191360/e8e16fba-70f3-11e6-81cc-0abb0252ad1f.png)

**Comment by ntatoo** [comment]
@iwean still
i delete it or move 
eror comming back
you try it

**Comment by iwean** [comment]
Hmm... Have you Install Net Framework and Visual C++ ?

**Comment by ntatoo** [comment]
i did bro, you working fine ?
try the relese file that i send

**Comment by iwean** [comment]
Work charm for me since @NoxxDev release that 2 days ago....

**Comment by ntatoo** [comment]
@iwean no 
download this 
[Release.zip](https://github.com/NoxxDev/NecroBot/files/451091/Release.zip)
that the new version i just compile 
try to use it , and did you got the same file ?

**Comment by ntatoo** [comment]
@iwean that man , the new version from the last source
did you get the same eror ?

**Comment by ntatoo** [comment]
@iwean lu coba bro download punya gue tu
lu liat , sama ngak eror yang muncul di punya lu bro ?
soalnya dari tadi muter" cari solusi ngak dapet
itu baru ane build sendiri pakai source yang terbaru dari master
gue kok eror ya

**Comment by iwean** [comment]
Oh sorry, you compiled from git? Ok, let me try it first. :+1:

**Comment by iwean** [comment]
Jyaaah.... temen sekampung rupanya elo bro... wkwkwk

**Comment by ntatoo** [comment]
wkwkw , ia bro sante aja
lu cobain dulu , ntah laptop gue yang masalah or apa ni
makanya gue nanya

**Comment by iwean** [comment]
Waduh, ini gw di kantor... komputernya ternyata ga dukung, ga bisa install framework, blm win 7 SP1.
Ntar dech di rumah gw coba bro.

**Comment by ntatoo** [comment]
wkwkw
oke deh bro
ntar kabarin aja

ane mah kalau versi yang udah keluar emang work dan aman sentosa
tapi yang ini eror mulu

**Comment by iwean** [comment]
Siyaaaap :+1:

**Comment by mjusuf** [comment]
@ntatoo coba delete NecroBot.exe.config dah

**Comment by ntatoo** [comment]
@mjusuf sama aja bro
ngak ngaruh

**Comment by iwean** [comment]
@DavidSelem @ntatoo 
Ok, I was checking it.... just paste your old auth.json & config.json files to Config folder of that compiled version. You are good to go!

Btw this compiled version, very fast movement... WOW! :+1: 

@mjusuf JANGAN bro! :smile:

**Comment by DavidSelem** [comment]
@Iwean I have Auth,  but don't have old config :(

**Comment by iwean** [comment]
Try my config.... and edit what you need :+1: 

http://pastebin.com/9rMh1MiT

**Comment by DavidSelem** [comment]
@Iwean Thanks mate 👌

**Comment by iwean** [comment]
@DavidSelem You're welcome :+1:

**Comment by DavidSelem** [comment]
Can't get this to work :(
Now it doesn't says that it's the first run, but now just shows the error
http://i.imgur.com/cnkUpWz.png

**Comment by Prawith** [comment]
I found the problem on ConsoleLogger.cs line 136-140.
It use _session that not create before.
======================
            _session.EventDispatcher.Send(new LogEvent
            {
                Message = finalMessage,
                Color = GetHexColor(Console.ForegroundColor)
            });
======================

**Comment by iwean** [comment]
@DavidSelem 
What section did you edit on my config? Especially on GoogleWalk section?

@Prawith 
Please make PR for that, mate. Thx :+1:

**Comment by youverena** [comment]
@iwean 
"WalkingSpeedInKilometerPerHour": **41.16**, itu aman bro ???

**Comment by iwean** [comment]
@youverena 
Sejauh ini aman bro, tp kalo ragu di edit aja ke setingan default. 4.16
Itu asalnya dari config waktu nge-test HumanWalkSnipe di postingan ini: #398

**Comment by youverena** [comment]
@iwean 
(Sambil jalan) Ada 0 Pokemon yang cocok dengan daftar filtermu. Tidak akan dapat semua, tapi mencoba yang terbaik!
mungkin diindo jarang ada rare pokemon ya bro, btw tq bro... :+1:

**Comment by iwean** [comment]
@youverena 
Hehehe... bisa jadi bro, lokasi seputaran Monas juga paling 4 atau 5 pokemon yg masuk filter.
Coba Hongkong atau Singapur bro. Lokasi yg baru di update Niantic.
