### ISSUE TITLE
How to increase the delay of sniping rare pokemons into once in 2 mins?

### ISSUE THREAD

**Issue by xcuts1** [NoxxDev/NecroBot#80]
my bot keeps on sniping and doesnt go to pokestop anymore. is there anyway i can delay snipes. the config /delaybetweensnipes doesnt seems to work

**Comment by samtch999** [comment]
may be you snipe too many pokemons

**Comment by xcuts1** [comment]
i am asking for the config on how to increase the delaybetweensnipes

**Comment by cuongomega** [comment]
MinDelayBetweenSnipes (ms): 200000 (=200s = 3 min)

**Comment by Sayton** [comment]
Same problem
Made the time around 200,000 and it still keeps sniping
Any solution !

**Comment by DmitrySilchenko** [comment]
i am SO fkn afraid that when bot comes to evolving all this mass i'll get my ass banned:

![image](https://cloud.githubusercontent.com/assets/20803444/17715077/4413e1ce-640b-11e6-9614-8252bc6265e8.png)



lol

**Comment by DmitrySilchenko** [comment]
its just so so so s t u p i d  seriously :D  - anyone who's using this 'sniping' trick in any way is just so frkn silly!   this is a 100% detected thing by their servers trust me, how can you even think it's in any was safe to do.... the world coordinates where you send your API calls are recorded forever of COURSE, and sooner or later the algorithms will reach the database shard where YOUR smart account is stored, and will analyse its stupid history of teleports and BAN IT... this is so freakin obvious .... gosh ......
