### ISSUE TITLE
0.9.7 - (ATTENTION) Encounter problem: EncounterClosed - what kind of circumstances generating this alert ?

### ISSUE THREAD

**Issue by BoydTM** [NoxxDev/NecroBot#814]
It not happens very frequently but still - anybody knows whats generating this ?

**Comment by samuraitruong** [comment]
when we get data for pokemon on the server, it was expired then server return EncounterClosed .

in real app. you sometime see pokemon, but click on that it disappear.

**Comment by BoydTM** [comment]
Thanks...
