### ISSUE TITLE
0.9.7 Pokemon inventory is full

### ISSUE THREAD

**Issue by vfuyong** [NoxxDev/NecroBot#815]
[08:34:35] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...

Then nothing is transfer...

**Comment by samuraitruong** [comment]
that message basically tell that you are reach to inventory limit setup. you need transfer pokemon manually.  I thought it is a minor bug for those people don't setup transfer pokemon probably .

**Comment by vfuyong** [comment]
I figured out that it is caused by global KeepMinCp set to a very low value so everything above this CP is kept.......
