### ISSUE TITLE
Permanent  ban

### ISSUE THREAD

**Issue by albysprx** [NoxxDev/NecroBot#82]
I created a new account with the default setting, I started it with a proxy and now it's permabanned, we need to know how it's possible because sniping was off and the walking speed was 4.16 with variant

**Comment by ridalarry** [comment]
I think the issues starts when you reach certain amount of pokestops or certain amount of pokemons caught

**Comment by tanjj92** [comment]
How long did your bot ran?

**Comment by albysprx** [comment]
I ran it for 5-6 hours

**Comment by generaljoke** [comment]
1000pokestop = 1hr ban
2000pokestop= perma ban

day1'' level 21, if you reach 22 up probably get permaban

**Comment by vfuyong** [comment]
Running too long can be risky even if you haven't capture that many pokemons or visited many shops.

**Comment by Kongen8800** [comment]
You can try to use my tool. Looping the bot close and open on a time you set.
http://www.mediafire.com/download/glfyw91x86f2ph3/Kongen%27s_PoGo_BOT_Timer_1.0.0.9.zip
discord: https://discord.gg/zayuXCw

**Comment by janga11** [comment]
i just created a few new accounts to push them all to around lvl 25. i think going higher than lvl 25 is a very high risk. just bot for 4-5 hours then use ur next account and only bot every second day. like this u should be fine.. i got around 20 accounts now and only my lvl 31 acc got banned all below 30 not.

**Comment by Kongen8800** [comment]
Thats also what my research tells. At level 25, something happens, both my acc. Banned on lvl 25.
