### ISSUE TITLE
 config.json [Line: 32, Position: 69]: TelegramConfig.TelegramAPIKey String exceeds maximum length of 32.

### ISSUE THREAD

**Issue by Delta1977** [NoxxDev/NecroBot#825]
config.json [Line: 32, Position: 69]: TelegramConfig.TelegramAPIKey String '266889602:AAHqdk0JSJF_Rn7C0qKM9V3GQetwOHmXXXX' exceeds maximum length of 32.

This is an working key in  0.9.5.  in actual master (0.9.7) this error occours.

**Comment by iwean** [comment]
I don't have that issue with actual master

**Comment by Delta1977** [comment]
Its a Fresh New clone from this Morning. With my old config and a new config trough firststart the error occours

**Comment by iwean** [comment]
hmm... maybe my clone not update yet. Let me check first....

**Comment by mo0ojava** [comment]
#832 fixes this.

**Comment by Delta1977** [comment]
Thx

**Comment by Delta1977** [comment]
Config Passes now but bot didnt work in this Version. Unknown error with Telegram. With 0.9.5 it Works

**Comment by iwean** [comment]
Same with me.
...
![screenshot_174](https://cloud.githubusercontent.com/assets/4365551/18226489/2f2db0cc-7235-11e6-811a-e9c85f8d1465.jpg)
