### ISSUE TITLE
Error: You are catching too fast. ???

### ISSUE THREAD

**Issue by HoanDao** [NoxxDev/NecroBot#835]
It runs for about 13 hours.  =))
Things were normal until about 1 hour before. 

my config:

  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 40.7127315,
    "DefaultLongitude": -74.0064015,
    "WalkingSpeedInKilometerPerHour": 5.16,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.1,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },

Pls help me!

**Comment by mo0ojava** [comment]
Try deleting PokemonTS.txt and PokestopTS.txt and restart.

**Comment by hardknoxni69a** [comment]
you can also disable killswitch just set to false but remember greed is the reason everyone seems to get banned

**Comment by HoanDao** [comment]
Thanks all. I fixed!
