### ISSUE TITLE
Error:  (FEHLER) Unkown Telegram Error occured.

### ISSUE THREAD

**Issue by Delta1977** [NoxxDev/NecroBot#837]
in actual Master this message occour:
 (FEHLER) Unkown Telegram Error occured.

Telegram-Bot didnt work

**Comment by mo0ojava** [comment]
Same thing happening here. The initialization in TelegramService is failing for some reason.
`_bot = new TelegramBotClient(apiKey);`
I saw that config-files changed encoding recently. Pondered whether the API key somehow was misformatted when retrieved from the config and sent to Telegram. Doesn't look that way when checking though:
![telegramerror](https://cloud.githubusercontent.com/assets/20909700/18227200/c1ec3816-721c-11e6-9e1b-490efdcdfc3b.PNG)

The token is correct as well. You can get a copy to compare from BotFather by doing /token. Not sure what's up here really...

**Comment by NoxxDev** [comment]
Fix 28b4877d2d693aaa9a272666f70ba1fadae544a3
