### ISSUE TITLE
Human walk distance bug!!

### ISSUE THREAD

**Issue by hugolas93** [NoxxDev/NecroBot#843]
HI!

I set Human walk to max distance 1000 and time 45.0 sec but in game dont work !!

my config:
"HumanWalkSnipeConfig": {
    "DisplayPokemonList": true,
    "MaxDistance": 1000.0,
    "MaxEstimateTime": 45.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "Enable": true,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000

In game :
![image](https://cloud.githubusercontent.com/assets/21977994/18228070/64b2eb7e-7233-11e6-9052-ca3635478e77.png)

**Comment by seouljah760** [comment]
Do you have something like this set up?

  "HumanWalkSnipeFilters": {
    "Dragonair": {
      "MaxDistance": 3000.0,
      "Priority": 2,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 25.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 1
    },
}

If so, then delete the entire   "HumanWalkSnipeFilters": {  stanzas with all the individual pokemon settings if you just want to use the pokemon to snipe filters.

**Comment by hugolas93** [comment]
ok i go try thanks for help
