### ISSUE TITLE
[Question] Proxy still working after "Niantic Servers unstable, throttling API Calls."?

### ISSUE THREAD

**Issue by ingokotin** [NoxxDev/NecroBot#849]
Hey there, I wonder if the bot still connects via Proxy after the famous "Niantic Servers unstable, throttling API Calls." error. Any suggestions how to find out?

**Comment by bulubebek** [comment]
I can confirm proxy is working properly. I did some realtime network traffic check on my router to ensure proxy is working.

**Comment by seouljah760** [comment]
In the future please adhere to the guidelines set forth in a GitHub repository and do not fill up the Issues Tracker with problems that are not issues with the code or unexpected bugs. This is not a website forum for discussion of various support topics. Please discuss these inquiries in the discord.
