### ISSUE TITLE
Crash because of nickname

### ISSUE THREAD

**Issue by Capusjon** [NoxxDev/NecroBot#852]
Hey guys,

I just downloaded the newest source via Github. The bot compiles smoothly but when I try to run the first time (creating auth/config) it crashes.

It has something to do with desired nickname, but I didn't choose one, choosing one doesn't seem to fix it either.
any ideas?

![necro crash](https://cloud.githubusercontent.com/assets/21157144/18230723/d9dc2598-72a4-11e6-9adb-2bbb3064f2c7.png)

**Comment by kuntau** [comment]
Delete `auth.json` and `config.json` in `config` folder and start again

**Comment by Capusjon** [comment]
auth.json and config.json never apear. Pasting in an old auth and config doesn't help either.

**Comment by iwean** [comment]
Run bot again and answer N when bot ask for the first setting.... it will turn off and make auth and config file for you by default. Edit that or change with your old auth & config.

**Comment by mo0ojava** [comment]
This has been fixed in the latest development build.

**Comment by Capusjon** [comment]
confirmed
