### ISSUE TITLE
Unkown Telegram Error occured.

### ISSUE THREAD

**Issue by Prawith** [NoxxDev/NecroBot#853]
I merge newest NoxxDev.master to my project. When I try to run the the release and want to use Telegram service.
It can't connect to Telegram API and console show message "Unkown Telegram Error occured.". 

### Expected Behavior
Telegram Service running.

### Actual Behavior
Telegram Service has error.

![telegram_error](https://cloud.githubusercontent.com/assets/21055112/18231220/fb0d3260-72dc-11e6-93ec-adb164cc6cf7.png)

**Comment by Delta1977** [comment]
Same as #837

**Comment by NoxxDev** [comment]
Fix 28b4877d2d693aaa9a272666f70ba1fadae544a3
