### ISSUE TITLE
Issues When Downloading From Master

### ISSUE THREAD

**Issue by Ev0luti0n2016** [NoxxDev/NecroBot#858]
I have been using the updates that are done daily by following the wiki:
      (https://github.com/NoxxDev/NecroBot/wiki/Source-Code) 
But am having problems and getting these errors when rebuilding in Visual Studio. When you press Control+f5, you can't build a config and if you add the old one it says it is missing info for: 

config.json [Line: 1, Position: 1]:  Required properties are missing from object: PokemonUpgradeFilters.

**From VS:**

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 2 Position 5.	PoGo.NecroBot.GUI	C:\xxxx\POGO\_Necro\NecroBot\PoGo.NecroBot.GUI\MainWindow.xaml	2	

Warning		Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. Visit http://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  Packages affected: MahApps.Metro	PoGo.NecroBot.GUI		0	

Warning		Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.	PoGo.NecroBot.CLI		
	
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	PoGo.NecroBot.CLI	C:\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.CLI\WebSocketHandler\ActionCommands\SetConfigHandler.cs	26	Active
Warning	CS0168	The variable 'ex' is declared but never used	PoGo.NecroBot.Logic	C:\xxx\POGO\_Necro\NecroBot\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.PokeWatchers.cs	60	Active

**Comment by Delta1977** [comment]
with source after commit  93dd523 its works. an other problem is with google apikey. if config is without it runs, if i paste a valid key in config bit crashes on startup. later i open a issue with more details

**Comment by mo0ojava** [comment]
PokemonUpgradeFilters is a new and required snippet. Look at the end of a newly generated config and copy to your old one. 
If you have VS installed you can do
devenv /diff config.json old-config.json

**Comment by iwean** [comment]
@Ev0luti0n2016 
From this: #812
And base from commited on: #819
Like @mo0ojava said.

**Comment by Ev0luti0n2016** [comment]
Thanks everybody for the help and for your work :)

....Everything is working nicely and I was able to compile from the master with no errors.
