### ISSUE TITLE
save speed?

### ISSUE THREAD

**Issue by kassumi** [NoxxDev/NecroBot#864]
hey guys, sooo, im farming in sydney, started bot on like 6am and it's now 11pm, and it catched only ~~660 pokemons. My default speed is 12.16 with 1.2 variable. So i wanted to ask, what is the upper limit of so called "safe speed" when botting? is it up to 20, or rather soething like 50, 'coz of cars?

**Comment by CreativiTimothy** [comment]
I think 40km is safe. 50km slightly risky but can work. I got 10 seconds softbans at 55km so 50km is probably good but a little risky

**Comment by Brazuca87** [comment]
this is not a forum, this is for reporting bot issues. Please go to the Discord channel to ask for help

**Comment by seouljah760** [comment]
Close this issue please.

**Comment by PhoenixCoyote** [comment]
Depending on how fast I feel like going at the time, I went for several days teleporting to stops until one of my accounts got banned. Now I average between 20 - 100, depending on how dense the area is and how fast I want to hit my daily limit. I like to stay near street car speed, I get eggs hatched at an ok rate and get more stops and mons exposure.
