### ISSUE TITLE
Renaming necrobot.exe

### ISSUE THREAD

**Issue by Byte-M3** [NoxxDev/NecroBot#87]
After version 0.8.5 it's not possible anymore to rename necrobot.exe.  It results in the following error:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'PoGo.NecroBot.Logic, Version=0.9.0.0, Culture=neutral, PublicKeyToken=nul
l' or one of its dependencies. The system cannot find the file specified.
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

This was a useful feature to run multiple accounts on multiple proxies. Would it be possible to restore this?

**Comment by vipery** [comment]
Confirmed.
Also cant use proxy with settings. My proxy cant complete latency test, but working 100%

**Comment by Byte-M3** [comment]
I never got the proxy settings in auth.json working with torguard (my vpn/proxy service). If i get that working I dont need to rename tnecrobot.exe, because I don't need proxifier anymore.

**Comment by prostoman** [comment]
rename config file and run - profit
NecroBot1.exe
NecroBot1.exe.config
