### ISSUE TITLE
[Feature Request] Start with a prompt to enter start location

### ISSUE THREAD

**Issue by wilsondgonzales** [NoxxDev/NecroBot#875]
I would start at the same default location as in the config. At the same time, I usually don't want to start at my last position from lastpos.ini

I do more often than not, select a location via maps and paste those coords in the lastpos.ini before running necro. Hoping someone would be nice enough to code something for necro to give a prompt where we can enter a new loc (49.xxx, -132.xxx format) before defaulting to either last pos or config default

**Comment by thinhphamp** [comment]
They're in the config file already.

In the Location config, you will find:

> "StartFromLastPosition": false,
> "DefaultLatitude":  ,
> "DefaultLongitude":  ,

**Comment by kalamera** [comment]
command line parameters would be more scipting friendly ;)
like:

`Necrobot.exe /Lat:<Latitude> /Long:<Longitude>`

same goes for other parameters like AutoCompleteTutorial, Nickname...

but I am just an old fashion guy who likes the command line more than gui or config files :)

**Comment by wilsondgonzales** [comment]
@kalamera either is cool as long as there's the option :)
@thinhphamp sorry but you misunderstood the post :)

ill close this issue in a few hrs. giving it a little more exposure
