### ISSUE TITLE
How long have you boted? and what lvl should you stop?

### ISSUE THREAD

**Issue by perpysling2** [NoxxDev/NecroBot#882]
Wonder when i should turn the bot of? when do people get banned?

**Comment by perpysling2** [comment]
i am 27 now

**Comment by DavideRaggi** [comment]
i'm 32 now.
1-30 in 5/6 days

**Comment by perpysling2** [comment]
beleave last time i tried i got banned on almost lvl32 or 33

**Comment by perpysling2** [comment]
but then everyone got banned and necrobot shut down their site.

**Comment by langit7** [comment]
everlasting bot till  not work

**Comment by avaloncoding** [comment]
Just ask this question under the discord chat and not here. :/

**Comment by seouljah760** [comment]
@perpysling2 	close this issue.

**Comment by t0rzz** [comment]
This is not an issue, please use the discord chat for questions.
