### ISSUE TITLE
Google maps API mabey issue I don't know

### ISSUE THREAD

**Issue by Capusjon** [NoxxDev/NecroBot#889]
I'm having a lot of errors on my google maps api, also the bot seems to take long before selecting 
a new destination.
![errors google](https://cloud.githubusercontent.com/assets/21157144/18255672/1b1e807a-73ac-11e6-92d0-1ec12464daf9.png)

Is this normal?

**Comment by erickerich** [comment]
did you pay fot it? or you only have 2500 request per day.

**Comment by jjskuld** [comment]
This Google API is becoming a limitation in my opinion.  2500 is not very high.

I have been working on an alternate routing implementation with MapQuest API.  Still needs more testing but it will handle more than 2500 and is still human-like routing.  Also should be more scalable than Yours service. Stay tuned eta for release is tomorrow afternoon

**Comment by jjskuld** [comment]
But to answer the question. Yes what you see is normal.  You made 15000 requests. The first 2500 for the day succeeded. The next 12500 requests failed because you exceeded the quota for that day.

**Comment by Capusjon** [comment]
Thanks for looking @jjskuld
