### ISSUE TITLE
Sniping Leads to Permanent Ban

### ISSUE THREAD

**Issue by mikegrimmers** [NoxxDev/NecroBot#89]
Hi guys,

It's been made very clear that the use of our beloved 'snipe' functionality sets off bells throughout Niantics office, meaning that for those of us who love to snipe now can't due to a very high chance of a permanent suspension (to which I got yesterday and am now appealing).

Is there any way, ANY way at all we can use snipe without it falling into their detection zone? Maybe setting tweaks or something that will not smoke us out. 

Cheers,

**Comment by kerim55** [comment]
I am not sure, but you could try manual sniping with Sniper2, and take some delay between snipes.

**Comment by vfuyong** [comment]
No way. Just don't snipe. They sooner or later will ban snipers

**Comment by DmitrySilchenko** [comment]
Sniping is such an obvious cheat people.... this is not worth it.
better invest more time in your account, let it change countries once in a 24-48 hours or so (with a big delay between "flights").
btw join discord to chat if you want   https://discord.gg/DtjaB

**Comment by midascodebreaker** [comment]
Niantic has now tie up the location where you caught you pokemon.
and having so many different coordinates or country code...
you know your ban already

**Comment by lordofthereef** [comment]
Why even appeal a ban when you know you got busted for going outside the TOS. It's one thing to bot, it's another thing to appeal when you get caught botting. Just start a new account. No big deal.
