### ISSUE TITLE
Can't open Necrobot

### ISSUE THREAD

**Issue by junsified** [NoxxDev/NecroBot#9]
### Expected Behavior
Bot normally opens and starts

### Actual Behavior
I'm receiving this error everytime I opens it 
![untitled](https://cloud.githubusercontent.com/assets/21025341/17650837/6503e58c-628a-11e6-99ce-1499e13f88c3.png)

### Your config.json
I'm using the default config with only my account edited on it.

### Other Information
Version: Latest
Windows Version: Windows 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by junsified** [comment]
Fixed

**Comment by liamsi95** [comment]
hey junsified, I have the same problem as you, i'd like to know how did you do to fix the problem ? thank you very much !

**Comment by 212vix** [comment]
Same here!

**Comment by Ghaanou** [comment]
" junsified commented:
Got mine fixed, download this http://filehippo.com/download_dotnet_framework_4/ "

**Comment by liamsi95** [comment]
what is this for ?

**Comment by Ghaanou** [comment]
I don't know lol but I had the same problem
Download and install it, after lanch Necrobot and normally the software works

**Comment by liamsi95** [comment]
yeah it works now but i have an other problem now. It says that it is impossible to load something

**Comment by liamsi95** [comment]
This is what i've got in my console:

> [21:21:46] Perfect! You already have the newest Version 0.8.8
> [21:21:46] Logging in using Ptc
> [21:21:46] System.DllNotFoundException: Impossible de charger la DLL 'api-ms-win-core-localization-l1-2-0.dll': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)
>    à Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
>    à Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, StringBuilder sb, String& errorMsg)
>    à Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
>    à System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
>    à System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWinHttpHandle requestHandle)
>    à System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
>    à System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()

**Comment by liamsi95** [comment]
anyone there that could help me ?

**Comment by Ghaanou** [comment]
https://github.com/NoxxDev/NecroBot/issues/6


I think it's the same problem here, try this solution

**Comment by NoxxDev** [comment]
Download and install
[Net Framework 4.6.2] (https://www.microsoft.com/en-us/download/details.aspx?id=53345)
[Visual C++ Redistributable for Visual Studio 2015] (https://www.microsoft.com/en-US/download/details.aspx?id=48145)
