### ISSUE TITLE
0.9.0 missing necroconfig

### ISSUE THREAD

**Issue by zinba** [NoxxDev/NecroBot#90]
i used 0.8.8 and 0.8.9  
when i download 0.9.0 its missing necro config.

**Comment by mitchelp** [comment]
Just open the bot and enter the setup. Put in the asked variables. And poof there is the config file.
And after you did the config with the necrobot.exe you can change the .json

**Comment by zinba** [comment]
necrobot.exe never showed up

**Comment by zinba** [comment]
necroconfig.exe never appeared

**Comment by mitchelp** [comment]
You should download the compiled version:
https://github.com/NoxxDev/NecroBot/releases/download/v0.9.0/Release.zip
from:
https://github.com/NoxxDev/NecroBot/releases

And read the **wiki**: https://github.com/NoxxDev/NecroBot/wiki

**Comment by kevinsteger** [comment]
this 0.9 update overwrote my existing auth and config files.

**Comment by zinba** [comment]
Worked.thanks
