### ISSUE TITLE
[Request] set wait time when you start. 

### ISSUE THREAD

**Issue by smoothrunnings** [NoxxDev/NecroBot#91]
There is a good place in Toronto, ON, Canada called Jack Layton Ferry, it has 4 pokestops bunched up with have lures on them 24/7. When I use bluestacks as soon as I start 4 to 5 pokemon appear, and after catching a few more appear. With Necrobot I catch 3 then my bot walks over to another spoke, sometimes it may only catch one. But there is no wait time from when you enter the game and there needs to be when you start, as we don't all start walking to the closest stop.

**Comment by dayshake** [comment]
Yup lured pokemons dont seem to be appearing, I guess you would have to pause near pokestops for atleast 5 secs

**Comment by Euphoniouz** [comment]
5 minutes in pokestop with lures is decent . I guess ^^ .
