### ISSUE TITLE
Add Features: Randomization of sensor data accelerometer,etc | Automated adjusting of walking speed 

### ISSUE THREAD

**Issue by athanatos1** [NoxxDev/NecroBot#95]
Add Features: Randomization of sensor data accelerometer,etc | Automated adjusting of walking speed

All socks 5 / http proxy support please!
Also a randomized device setting so it appears as a new device each time like necrobot

Not sure if they are added already.

**Comment by DmitrySilchenko** [comment]
a great feature request :) .
guys, everyone lets gather here in the channel   https://discord.gg/DtjaB

**Comment by NoxxDev** [comment]
> Add Features: Randomization of sensor data accelerometer,etc | Automated adjusting of walking speed
All features on bot
