### ISSUE TITLE
Speed variant improve

### ISSUE THREAD

**Issue by andy505050** [NoxxDev/NecroBot#98]
1. I feel the walking speed variant changed too high frequency. 
Suggest adjust the frequency lower.

2. It's strange for speed too unsteadiness. It's need interval smaller for speed variant.
maybe +-0.5

3.Then maybe some situations for improve as follow:
rule1: 0(starting or pokemonstop)->3->4.5~5(max speed)->3->0(pokemonstop)
rule2: 4.5~5(max speed)->encounter->catch->0->3->4.5~5(max speed)

It's maybe look more humanized

**Comment by ausscheider** [comment]
I think this is a very good idea

**Comment by gysi** [comment]
I really don't see any problem with it
