### ISSUE TITLE
URGENT: Create your own Discord chat channel/server

### ISSUE THREAD

**Issue by nfettinger** [NoxxDev/NecroBot#99]
The Necrobot Discord chat has mostly shut down. Please create your own server.

**Comment by nfettinger** [comment]
...and good luck with all the people who don't read the manual.

**Comment by athanatos1** [comment]
@Nfettinger, is the old necro discord channel still up? I posted a picture and got kicked, is it possible to get reinvited, thanks sir

**Comment by PoppaCoder** [comment]
I called Grimm on his unwillingness to help in the help channel, lol, and he banned me.

**Comment by nfettinger** [comment]
The Necrobot channel is no longer supported. NoxxDev will have to create his own channel to help you users.

**Comment by DmitrySilchenko** [comment]
I don't get this guys, why nobody opens a channel to discuss development and stuff?
I opened a channel for now that we can join, if anyone interested to discuss stuff, you're all invited:

https://discord.gg/DtjaB
